module

public import Mathlib

@[expose] public section

/-!
# Brill--Noether existence for graphs of genus six

This is the Mathlib-only Challenge surface for Brill--Noether existence through
genus six (extending the Atanasov--Ranganathan theorem through genus five), the
expected Brill--Noether rank through genus six, and once-marked Brill--Noether
existence through genus five.  The file contains the advertised theorem
statements and the complete local vocabulary needed to read them.  The
advertised declarations deliberately end in `sorry`.
-/

namespace GenusSix

universe u

open Multiset Finset

/-! ## Self-contained statement vocabulary -/

/-- A finite, nonempty, loopless undirected multigraph.  An undirected edge is
stored by either ordering of its endpoints; `num_edges` below forgets that
ordering. -/
structure CFGraph where
  /-- The finite, nonempty type of vertices. -/
  V : Type u
  [instDecidableEq : DecidableEq V]
  [instFintype : Fintype V]
  [instNonempty : Nonempty V]
  /-- Edge occurrences, each stored once using either endpoint ordering. -/
  edges : Multiset (V × V)
  /-- No edge occurrence has equal endpoints. -/
  loopless : ∀ v, (v, v) ∉ edges

attribute [instance] CFGraph.instDecidableEq CFGraph.instFintype CFGraph.instNonempty

/-- The number of edges between two vertices, counted with multiplicity. -/
def num_edges (G : CFGraph) (v w : G.V) : ℕ :=
  Multiset.card (G.edges.filter (fun e => e = (v, w) ∨ e = (w, v)))

/-- A graph is connected when every nontrivial vertex cut has a crossing
edge. -/
def graph_connected (G : CFGraph) : Prop :=
  ∀ S : Finset G.V, (∃ v w : G.V, v ∈ S ∧ w ∉ S) →
    ∃ v ∈ S, ∃ w ∉ S, num_edges G v w > 0

/-- The genus (cyclomatic number) `|E| - |V| + 1`. -/
def genus (G : CFGraph) : ℤ :=
  Multiset.card G.edges - Fintype.card G.V + 1

/-- The degree (valence) of a vertex. -/
def vertex_degree (G : CFGraph) (v : G.V) : ℤ :=
  ∑ u : G.V, (num_edges G v u : ℤ)

/-- A divisor is an integer-valued function on the vertices. -/
abbrev CFDiv (G : CFGraph) := G.V → ℤ

/-- The principal divisor obtained by firing one vertex once. -/
def firing_vector (G : CFGraph) (v : G.V) : CFDiv G :=
  fun w => if w = v then -vertex_degree G v else num_edges G v w

/-- The subgroup generated by all vertex firings. -/
def principal_divisors (G : CFGraph) : AddSubgroup (CFDiv G) :=
  AddSubgroup.closure (Set.range (firing_vector G))

/-- Two divisors are linearly equivalent when their difference is principal. -/
def linear_equiv (G : CFGraph) (D D' : CFDiv G) : Prop :=
  D' - D ∈ principal_divisors G

/-- A divisor is effective when it has no negative coefficient. -/
def effective {G : CFGraph} (D : CFDiv G) : Prop :=
  ∀ v : G.V, D v ≥ 0

/-- The additive monoid of effective divisors. -/
def Eff (G : CFGraph) : AddSubmonoid (CFDiv G) :=
  { carrier := {D : CFDiv G | effective D}
    zero_mem' := fun _ => le_refl 0
    add_mem' := fun {_D₁ _D₂} h₁ h₂ v => add_nonneg (h₁ v) (h₂ v) }

/-- A divisor is winnable when it is linearly equivalent to an effective
divisor. -/
def winnable (G : CFGraph) (D : CFDiv G) : Prop :=
  ∃ D' ∈ Eff G, linear_equiv G D D'

/-- The degree of a divisor, i.e. its total number of chips. -/
def deg {G : CFGraph} : CFDiv G →+ ℤ :=
  { toFun := fun D => ∑ v, D v
    map_zero' := by simp only [Pi.zero_apply, sum_const_zero]
    map_add' := by
      intro D₁ D₂
      simp only [Pi.add_apply, sum_add_distrib] }

/-- The effective divisors of a prescribed degree. -/
def eff_of_degree (G : CFGraph) (k : ℤ) : Set (CFDiv G) :=
  {E | effective E ∧ deg E = k}

/-- `rank_geq G D k` means that removing any effective divisor of degree `k`
from `D` leaves a winnable divisor. -/
def rank_geq (G : CFGraph) (D : CFDiv G) (k : ℤ) : Prop :=
  ∀ E ∈ eff_of_degree G k, winnable G (D - E)

/-- The divisor consisting of one chip at `v`. -/
def one_chip {G : CFGraph} (v : G.V) : CFDiv G :=
  fun w => if w = v then 1 else 0

/-! ## Brill--Noether existence through genus six -/

/-- **Brill--Noether existence through genus six.**  Every connected finite
graph of genus `g ≤ 6` satisfies Brill--Noether existence: for all integers `r`
and `d` with `ρ(g, r, d) = g - (r + 1) * (g - d + r) ≥ 0` it has a divisor of
degree `d` and rank at least `r`.  This is Baker's Brill--Noether existence
conjecture for graphs through genus six.

For `g ≤ 5` this is the theorem of Atanasov--Ranganathan, and the statement is
their theorem in the same form with five replaced by six.  The new case is
`g = 6`, where the essential case is `(r, d) = (1, 4)`: every connected
genus-six graph has a divisor of degree four and rank at least one.  The other
genus-six cases follow from it and Riemann--Roch.

No hypothesis `0 ≤ r` is needed: for `r < 0` the rank condition is vacuous. -/
theorem brill_noether_existence_through_six
    (G : CFGraph.{0}) (h_connected : graph_connected G)
    (g r d : ℤ) (h_genus : genus G = g) (h_genus_le_six : g ≤ 6)
    (h_brill_noether : (r + 1) * (g - d + r) ≤ g) :
    ∃ D : CFDiv G, deg D = d ∧ rank_geq G D r := by
  sorry

/-! ## The Brill--Noether rank through genus six

The **Brill--Noether rank** `w^r_d(G)` of Lim--Payne--Potashnik and Len is the
largest `k ≥ 0` such that every effective divisor `E` of degree `r + k` is
contained, up to linear equivalence, in a divisor of degree `d` and rank at
least `r`, with value `-1` when no such linear system exists.  Here
"contained up to linear equivalence" means that `D - E` is winnable for some
such `D`.  The two theorems below state lower bounds on
`w^r_d(G)`, unfolded into the vocabulary above.  Since `w^r_d ≤ d - r` holds
whenever the linear system exists, the bound `ρ` cannot hold in every degree;
the first theorem caps it at
`d - r`, and the second states the bound `ρ` in the range `d ≤ g + r`, where the
cap does not bind. -/

/-- **The expected Brill--Noether rank through genus six.**  Let `G` be a
connected finite graph of genus `g ≤ 6`, and let `r ≥ 0` and `d` be integers
with `ρ(g, r, d) = g - (r + 1) * (g - d + r) ≥ 0`.  Then every effective
divisor `E` of degree `r + min(ρ, d - r)` is contained, up to linear
equivalence, in a divisor `D` of degree `d` and rank at least `r`.  In other
words `w^r_d(G) ≥ min(ρ, d - r)`.

Apart from Brill--Noether existence itself, the non-elementary cases are
`(g, r, d) = (5, 1, 4)` and `(6, 1, 5)`: every pair of vertices of a genus-five
graph lies in a divisor of degree four and rank at least one, and every triple
of vertices of a genus-six graph lies in a divisor of degree five and rank at
least one.  The other cases follow from existence, from Riemann--Roch, or from
adding chips. -/
theorem brill_noether_rank_through_six
    (G : CFGraph.{0}) (h_connected : graph_connected G)
    (g r d : ℤ) (h_genus : genus G = g) (h_genus_le_six : g ≤ 6)
    (h_rank_nonneg : 0 ≤ r) (h_brill_noether : (r + 1) * (g - d + r) ≤ g)
    (E : CFDiv G) (h_effective : effective E)
    (h_degree : deg E = r + min (g - (r + 1) * (g - d + r)) (d - r)) :
    ∃ D : CFDiv G, deg D = d ∧ rank_geq G D r ∧ winnable G (D - E) := by
  sorry

/-- **`w^r_d ≥ ρ` through genus six.**  Let `G` be a connected finite graph of
genus `g ≤ 6`, and let `r ≥ 0` and `d ≤ g + r` be integers with
`ρ(g, r, d) = g - (r + 1) * (g - d + r) ≥ 0`.  Then every effective divisor `E`
of degree `r + ρ` is contained, up to linear equivalence, in a divisor `D` of
degree `d` and rank at least `r`.  That is, the Brill--Noether rank satisfies
`ρ ≤ w^r_d(G)`, as for a general curve of genus `g`. -/
theorem brill_noether_rank_ge_rho_through_six
    (G : CFGraph.{0}) (h_connected : graph_connected G)
    (g r d : ℤ) (h_genus : genus G = g) (h_genus_le_six : g ≤ 6)
    (h_rank_nonneg : 0 ≤ r) (h_brill_noether : (r + 1) * (g - d + r) ≤ g)
    (h_degree_le : d ≤ g + r)
    (E : CFDiv G) (h_effective : effective E)
    (h_degree : deg E = r + (g - (r + 1) * (g - d + r))) :
    ∃ D : CFDiv G, deg D = d ∧ rank_geq G D r ∧ winnable G (D - E) := by
  sorry

/-! ## Once-marked Brill--Noether existence through genus five -/

/-- **Once-marked Brill--Noether existence through genus five.**  Let `G` be
a connected finite graph of genus `g ≤ 5` with a marked vertex `u`, and let
`μ` be a Young diagram with at most `g` boxes, whose row lengths are
`μ_0 ≥ μ_1 ≥ ⋯ > 0` (the list `μ.rowLens`).  Then some divisor `D` of degree
`g` satisfies `rank (D + (i - μ_i) u) ≥ i` for every row `i`.  Equivalently,
the Weierstrass partition of `D` at `u` contains `μ`.

The case of rectangular diagrams is precisely the theorem of
Atanasov--Ranganathan.  If `μ` has `r + 1` rows of length `g - d + r`, then it
has at most `g` boxes exactly when `ρ(g, r, d) ≥ 0`.  The conclusion then says
that `D - (g - d) u` has degree `d` and rank at least `r`: the last row gives
this, and it implies the others.  The pairs `(r, d)` with no such rectangle
(`r < 0`, or `d ≥ g + r`) are trivial.

For example, the diagram with rows `(3, 2)` in genus five asks for a
degree-four divisor of rank at least one containing `2u`. -/
theorem once_marked_brill_noether_existence_through_five
    (G : CFGraph.{0}) (h_connected : graph_connected G)
    (h_genus_le_five : genus G ≤ 5) (u : G.V)
    (μ : YoungDiagram) (h_size : (μ.card : ℤ) ≤ genus G) :
    ∃ D : CFDiv G, deg D = genus G ∧
      ∀ (i : ℕ) (hi : i < μ.rowLens.length),
        rank_geq G (D + ((i : ℤ) - (μ.rowLens[i] : ℤ)) • one_chip u) (i : ℤ) := by
  sorry

end GenusSix
