import Mathlib

/-!
# Brill--Noether existence for graphs of genus six

This is the Mathlib-only Challenge surface for Brill--Noether existence in
genus six and two of its consequences: existence through genus six (extending
the Atanasov--Ranganathan theorem through genus five), and once-marked
Brill--Noether existence through genus five.  The file contains the advertised
theorem statements and the complete local vocabulary needed to read them.  The
advertised declarations deliberately end in `sorry`.
-/

namespace GenusSixChallenge

universe u

open Multiset Finset

/-! ## Self-contained statement vocabulary -/

/-- A finite, nonempty, loopless undirected multigraph.  An undirected edge is
stored by either ordering of its endpoints; `num_edges` below forgets that
ordering. -/
structure CFGraph where
  /-- The finite, nonempty type of vertices. -/
  V : Type u
  [instDecidableEq : DecidableEq V]
  [instFintype : Fintype V]
  [instNonempty : Nonempty V]
  /-- Edge occurrences, each stored once using either endpoint ordering. -/
  edges : Multiset (V × V)
  /-- No edge occurrence has equal endpoints. -/
  loopless : ∀ v, (v, v) ∉ edges

attribute [instance] CFGraph.instDecidableEq CFGraph.instFintype CFGraph.instNonempty

/-- The number of edges between two vertices, counted with multiplicity. -/
def num_edges (G : CFGraph) (v w : G.V) : ℕ :=
  Multiset.card (G.edges.filter (fun e => e = (v, w) ∨ e = (w, v)))

/-- A graph is connected when every nontrivial vertex cut has a crossing
edge. -/
def graph_connected (G : CFGraph) : Prop :=
  ∀ S : Finset G.V, (∃ v w : G.V, v ∈ S ∧ w ∉ S) →
    ∃ v ∈ S, ∃ w ∉ S, num_edges G v w > 0

/-- The genus (cyclomatic number) `|E| - |V| + 1`. -/
def genus (G : CFGraph) : ℤ :=
  Multiset.card G.edges - Fintype.card G.V + 1

/-- The degree (valence) of a vertex. -/
def vertex_degree (G : CFGraph) (v : G.V) : ℤ :=
  ∑ u : G.V, (num_edges G v u : ℤ)

/-- A divisor is an integer-valued function on the vertices. -/
abbrev CFDiv (G : CFGraph) := G.V → ℤ

/-- The principal divisor obtained by firing one vertex once. -/
def firing_vector (G : CFGraph) (v : G.V) : CFDiv G :=
  fun w => if w = v then -vertex_degree G v else num_edges G v w

/-- The subgroup generated by all vertex firings. -/
def principal_divisors (G : CFGraph) : AddSubgroup (CFDiv G) :=
  AddSubgroup.closure (Set.range (firing_vector G))

/-- Two divisors are linearly equivalent when their difference is principal. -/
def linear_equiv (G : CFGraph) (D D' : CFDiv G) : Prop :=
  D' - D ∈ principal_divisors G

/-- A divisor is effective when it has no negative coefficient. -/
def effective {G : CFGraph} (D : CFDiv G) : Prop :=
  ∀ v : G.V, D v ≥ 0

/-- The additive monoid of effective divisors. -/
def Eff (G : CFGraph) : AddSubmonoid (CFDiv G) :=
  { carrier := {D : CFDiv G | effective D}
    zero_mem' := by
      simp only [effective, ge_iff_le, Set.mem_ofPred_eq, Pi.zero_apply,
        Std.le_refl, implies_true]
    add_mem' := by
      intro D₁ D₂ h₁ h₂ v
      exact add_nonneg (h₁ v) (h₂ v) }

/-- A divisor is winnable when it is linearly equivalent to an effective
divisor. -/
def winnable (G : CFGraph) (D : CFDiv G) : Prop :=
  ∃ D' ∈ Eff G, linear_equiv G D D'

/-- The degree of a divisor, i.e. its total number of chips. -/
def deg {G : CFGraph} : CFDiv G →+ ℤ :=
  { toFun := fun D => ∑ v, D v
    map_zero' := by simp only [Pi.zero_apply, sum_const_zero]
    map_add' := by
      intro D₁ D₂
      simp only [Pi.add_apply, sum_add_distrib] }

/-- The effective divisors of a prescribed degree. -/
def eff_of_degree (G : CFGraph) (k : ℤ) : Set (CFDiv G) :=
  {E | effective E ∧ deg E = k}

/-- `rank_geq G D k` means that removing any effective divisor of degree `k`
from `D` leaves a winnable divisor. -/
def rank_geq (G : CFGraph) (D : CFDiv G) (k : ℤ) : Prop :=
  ∀ E ∈ eff_of_degree G k, winnable G (D - E)

/-- The divisor consisting of one chip at `v`. -/
def one_chip {G : CFGraph} (v : G.V) : CFDiv G :=
  fun w => if w = v then 1 else 0

/-! ## Brill--Noether existence in genus six -/

/-- **Brill--Noether existence in genus six.**  Every connected finite graph
of genus six satisfies Brill--Noether existence: for all integers `r ≥ 0` and
`d` with `ρ(6, r, d) = 6 - (r + 1) * (6 - d + r) ≥ 0` it has a divisor of
degree `d` and rank at least `r`. -/
theorem brill_noether_existence_genus_six
    (G : CFGraph.{u}) (h_connected : graph_connected G) (h_genus : genus G = 6)
    (r d : ℤ) (h_rank_nonnegative : 0 ≤ r)
    (h_brill_noether : (r + 1) * (6 - d + r) ≤ 6) :
    ∃ D : CFDiv G, deg D = d ∧ rank_geq G D r := by
  sorry

/-- **Brill--Noether existence through genus six.**  Every connected finite
graph of genus at most six satisfies Brill--Noether existence.  This is the
genus-five statement of Atanasov--Ranganathan, in the same form, extended by
one genus.  No hypothesis `0 ≤ r` is needed: for `r < 0` the rank condition is
vacuous. -/
theorem brill_noether_existence_through_six
    (G : CFGraph.{0}) (h_connected : graph_connected G)
    (g r d : ℤ) (h_genus : genus G = g) (h_genus_le_six : g ≤ 6)
    (h_brill_noether : (r + 1) * (g - d + r) ≤ g) :
    ∃ D : CFDiv G, deg D = d ∧ rank_geq G D r := by
  sorry

/-! ## Once-marked Brill--Noether existence through genus five -/

/-- **Once-marked Brill--Noether existence through genus five.**  Let `G` be
a connected finite graph of genus `g ≤ 5` with a marked vertex `u`, and let
`μ` be a Young diagram with at most `g` boxes, whose row lengths are
`μ_0 ≥ μ_1 ≥ ⋯ > 0` (the list `μ.rowLens`).  Then some divisor `D` of degree
`g` satisfies `rank (D + (i - μ_i) u) ≥ i` for every row `i`.  Equivalently,
the Weierstrass partition of `D` at `u` contains `μ`.

For example, the diagram with rows `(3, 2)` in genus five asks for a
degree-four divisor of rank at least one containing `2u`. -/
theorem once_marked_brill_noether_existence_through_five
    (G : CFGraph.{0}) (h_connected : graph_connected G)
    (h_genus_le_five : genus G ≤ 5) (u : G.V)
    (μ : YoungDiagram) (h_size : (μ.card : ℤ) ≤ genus G) :
    ∃ D : CFDiv G, deg D = genus G ∧
      ∀ (i : ℕ) (hi : i < μ.rowLens.length),
        rank_geq G (D + ((i : ℤ) - (μ.rowLens[i] : ℤ)) • one_chip u) (i : ℤ) := by
  sorry

end GenusSixChallenge
