import Bananas.Jacobian.BananaJacobianProposition214
import Bananas.Theta.ThetaLattice

/-!
# The two-coordinate theta Jacobian presentation

The general banana presentation has three coordinates in genus two.  This
file formalizes the paper's further quotient by the diagonal coordinate via
the projection `(x, y, z) ↦ (x - z, y - z)`.  Its image relation lattice is
generated by `(a + c, c)` and `(-a, b)`, exactly as in the paper.
-/

namespace Bananas

open Utilities

/-- The projection from the three banana coordinates to the paper's two
theta coordinates. -/
def thetaCoordinateProjection : (Fin 3 → ℤ) →+ ℤ × ℤ where
  toFun x := (x 0 - x 2, x 1 - x 2)
  map_zero' := by simp
  map_add' x y := by
    ext <;> simp <;> ring

/-- The section of `thetaCoordinateProjection` obtained by setting the last
coordinate to zero. -/
def thetaCoordinateSection : (ℤ × ℤ) →+ (Fin 3 → ℤ) where
  toFun x i := if i = 0 then x.1 else if i = 1 then x.2 else 0
  map_zero' := by
    funext i
    simp
  map_add' x y := by
    funext i
    fin_cases i <;> simp

@[simp] theorem thetaCoordinateProjection_section (x : ℤ × ℤ) :
    thetaCoordinateProjection (thetaCoordinateSection x) = x := by
  rcases x with ⟨x, y⟩
  simp [thetaCoordinateProjection, thetaCoordinateSection]

/-- Every displayed three-coordinate relation projects into the paper's
two-dimensional theta lattice. -/
theorem thetaCoordinateProjection_mem_thetaLattice_of_mem_displayedRelations
    (B : Banana 2) (x : Fin 3 → ℤ)
    (hx : x ∈ bananaDisplayedRelations B) :
    thetaCoordinateProjection x ∈
      thetaLattice (B.length 0) (B.length 1) (B.length 2) := by
  unfold bananaDisplayedRelations at hx
  let P : (Fin 3 → ℤ) → Prop := fun y =>
    thetaCoordinateProjection y ∈
      thetaLattice (B.length 0) (B.length 1) (B.length 2)
  apply AddSubgroup.closure_induction (p := fun y _ => P y) (mem := ?_)
      (zero := by exact (thetaLattice _ _ _).zero_mem)
      (add := by
        intro u v _ _ hu hv
        simpa [P] using (thetaLattice _ _ _).add_mem hu hv)
      (neg := by
        intro u _ hu
        simpa [P] using (thetaLattice _ _ _).neg_mem hu) hx
  intro y hy
  rcases hy with hy | hy
  · subst y
    change thetaCoordinateProjection bananaDiagonalRelation ∈ _
    have hProjection : thetaCoordinateProjection
        (bananaDiagonalRelation (g := 2)) = 0 := by
      ext <;> simp [thetaCoordinateProjection, bananaDiagonalRelation]
    rw [hProjection]
    exact (thetaLattice _ _ _).zero_mem
  · obtain ⟨beta, rfl⟩ := hy
    fin_cases beta
    · change thetaCoordinateProjection
          (bananaStrandLengthRelation B (0 : Fin 3)) ∈ _
      have hProjection : thetaCoordinateProjection
          (bananaStrandLengthRelation B 0) = 0 := by
        ext <;> simp [thetaCoordinateProjection, bananaStrandLengthRelation]
      rw [hProjection]
      exact (thetaLattice _ _ _).zero_mem
    · apply (thetaLattice_mem_iff
        (B.length 0) (B.length 1) (B.length 2) _ _).2
      refine ⟨0, -1, ?_, ?_⟩
      · simp [bananaStrandLengthRelation,
          bananaCoordinateBasis]
      · simp [bananaStrandLengthRelation,
          bananaCoordinateBasis]
    · apply (thetaLattice_mem_iff
        (B.length 0) (B.length 1) (B.length 2) _ _).2
      refine ⟨1, 0, ?_, ?_⟩
      · simp [bananaStrandLengthRelation, bananaCoordinateBasis]
      · simp [bananaStrandLengthRelation,
          bananaCoordinateBasis]

/-- Conversely, the full preimage of the theta lattice is the displayed
three-coordinate relation lattice.  This is the kernel calculation in the
paper's passage from three coordinates to two. -/
theorem mem_bananaDisplayedRelations_of_thetaCoordinateProjection_mem
    (B : Banana 2) (x : Fin 3 → ℤ)
    (hx : thetaCoordinateProjection x ∈
      thetaLattice (B.length 0) (B.length 1) (B.length 2)) :
    x ∈ bananaDisplayedRelations B := by
  obtain ⟨r, s, hx0, hx1⟩ := (thetaLattice_mem_iff
    (B.length 0) (B.length 1) (B.length 2)
    (thetaCoordinateProjection x).1
    (thetaCoordinateProjection x).2).1 hx
  let combination : Fin 3 → ℤ :=
    r • bananaStrandLengthRelation B 2 -
      s • bananaStrandLengthRelation B 1
  have hCombination : combination ∈ bananaDisplayedRelations B := by
    exact (bananaDisplayedRelations B).sub_mem
      ((bananaDisplayedRelations B).zsmul_mem
        (bananaStrandLengthRelation_mem_displayedRelations B 2) r)
      ((bananaDisplayedRelations B).zsmul_mem
        (bananaStrandLengthRelation_mem_displayedRelations B 1) s)
  have hDifference : x - combination =
      (x 2 + r * (B.length 2 : ℤ)) • bananaDiagonalRelation := by
    funext i
    fin_cases i
    · change x 0 - _ = _
      change x 0 - x 2 = _ at hx0
      simp [combination, bananaStrandLengthRelation, bananaCoordinateBasis,
        bananaDiagonalRelation] at hx0 ⊢
      linarith
    · change x 1 - _ = _
      change x 1 - x 2 = _ at hx1
      simp [combination, bananaStrandLengthRelation, bananaCoordinateBasis,
        bananaDiagonalRelation] at hx1 ⊢
      linarith
    · simp [combination, bananaStrandLengthRelation, bananaCoordinateBasis,
        bananaDiagonalRelation]
  have hDifferenceMem : x - combination ∈ bananaDisplayedRelations B := by
    rw [hDifference]
    exact (bananaDisplayedRelations B).zsmul_mem
      (bananaDiagonalRelation_mem_displayedRelations B)
        (x 2 + r * (B.length 2 : ℤ))
  have hSum := (bananaDisplayedRelations B).add_mem hDifferenceMem hCombination
  convert hSum using 1
  abel

/-- Exact preimage form of the theta lattice calculation. -/
theorem thetaCoordinateProjection_mem_thetaLattice_iff
    (B : Banana 2) (x : Fin 3 → ℤ) :
    thetaCoordinateProjection x ∈
        thetaLattice (B.length 0) (B.length 1) (B.length 2) ↔
      x ∈ bananaDisplayedRelations B := by
  constructor
  · exact mem_bananaDisplayedRelations_of_thetaCoordinateProjection_mem B x
  · exact thetaCoordinateProjection_mem_thetaLattice_of_mem_displayedRelations B x

/-- The quotient map induced by `(x,y,z) ↦ (x-z,y-z)`. -/
def thetaPresentedProjectionHom (B : Banana 2) :
    ((Fin 3 → ℤ) ⧸ bananaDisplayedRelations B) →+
      ((ℤ × ℤ) ⧸ thetaLattice (B.length 0) (B.length 1) (B.length 2)) :=
  QuotientAddGroup.lift (bananaDisplayedRelations B)
    ((QuotientAddGroup.mk'
      (thetaLattice (B.length 0) (B.length 1) (B.length 2))).comp
        thetaCoordinateProjection) (by
      intro x hx
      apply (QuotientAddGroup.eq_zero_iff _).2
      exact thetaCoordinateProjection_mem_thetaLattice_of_mem_displayedRelations
        B x hx)

/-- The quotient map induced by the section `(x,y) ↦ (x,y,0)`. -/
def thetaPresentedSectionHom (B : Banana 2) :
    ((ℤ × ℤ) ⧸ thetaLattice (B.length 0) (B.length 1) (B.length 2)) →+
      ((Fin 3 → ℤ) ⧸ bananaDisplayedRelations B) :=
  QuotientAddGroup.lift
    (thetaLattice (B.length 0) (B.length 1) (B.length 2))
    ((QuotientAddGroup.mk' (bananaDisplayedRelations B)).comp
      thetaCoordinateSection) (by
        intro x hx
        apply (QuotientAddGroup.eq_zero_iff _).2
        apply mem_bananaDisplayedRelations_of_thetaCoordinateProjection_mem B
        simpa using hx)

theorem thetaPresentedSectionHom_leftInverse (B : Banana 2) :
    Function.LeftInverse (thetaPresentedSectionHom B)
      (thetaPresentedProjectionHom B) := by
  intro x
  refine QuotientAddGroup.induction_on x ?_
  intro a
  apply QuotientAddGroup.eq_iff_sub_mem.mpr
  apply mem_bananaDisplayedRelations_of_thetaCoordinateProjection_mem B
  have hProjection : thetaCoordinateProjection
      (thetaCoordinateSection (thetaCoordinateProjection a) - a) = 0 := by
    rw [map_sub, thetaCoordinateProjection_section, sub_self]
  rw [hProjection]
  exact (thetaLattice _ _ _).zero_mem

theorem thetaPresentedSectionHom_rightInverse (B : Banana 2) :
    Function.RightInverse (thetaPresentedSectionHom B)
      (thetaPresentedProjectionHom B) := by
  intro x
  refine QuotientAddGroup.induction_on x ?_
  intro a
  apply QuotientAddGroup.eq_iff_sub_mem.mpr
  rw [thetaCoordinateProjection_section, sub_self]
  exact (thetaLattice _ _ _).zero_mem

/-- The exact quotient isomorphism in the theta-Jacobian paragraph of the
paper. -/
def thetaPresentedQuotientEquiv (B : Banana 2) :
    ((Fin 3 → ℤ) ⧸ bananaDisplayedRelations B) ≃+
      ((ℤ × ℤ) ⧸ thetaLattice (B.length 0) (B.length 1) (B.length 2)) where
  toFun := thetaPresentedProjectionHom B
  invFun := thetaPresentedSectionHom B
  left_inv := thetaPresentedSectionHom_leftInverse B
  right_inv := thetaPresentedSectionHom_rightInverse B
  map_add' := map_add (thetaPresentedProjectionHom B)

/-- **Theta Jacobian presentation.**  The paper's two-coordinate quotient is
additively isomorphic to the degree-zero divisor-class range of the theta
graph. -/
noncomputable def thetaLatticeQuotientEquivClassRange (B : Banana 2) :
    ((ℤ × ℤ) ⧸ thetaLattice (B.length 0) (B.length 1) (B.length 2)) ≃+
      bananaCoordinateClassRange B :=
  (thetaPresentedQuotientEquiv B).symm.trans
    (bananaDisplayedQuotientEquivClassRange B)

/-- Under the theta presentation, `[x,y]` is represented by the general
banana coordinate vector `(x,y,0)`, exactly as in the paper's construction. -/
@[simp] theorem thetaLatticeQuotientEquivClassRange_mk (B : Banana 2)
    (x : ℤ × ℤ) :
    thetaLatticeQuotientEquivClassRange B
        (QuotientAddGroup.mk'
          (thetaLattice (B.length 0) (B.length 1) (B.length 2)) x) =
      ⟨bananaCoordinateClassHom B (thetaCoordinateSection x),
        ⟨thetaCoordinateSection x, rfl⟩⟩ := by
  rfl

end Bananas
