import Utilities.Subdivision.CoreRelabeling
import Utilities.Subdivision.DegenerateSubdivisionIso
import LowGenus.GenusFiveConfigurations

/-!
# Occurrence relabeling on closed subdivision faces

An occurrence-sensitive relabeling of ordered cores transports the canonical
union-find face attached to any closed length vector.  Literal representatives
need not commute with the vertex equivalence, so the proof works with the
reachability relation generated by zero slots and then builds the induced
equivalence of quotient classes.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false

namespace Utilities.Certificate.ExplicitPotential.Core.Relabeling

open Utilities
open Utilities.Certificate
open Utilities.Certificate.ExplicitPotential
open Utilities.Certificate.DegenerateSpec
open Utilities.Certificate.ContractionForestCensusGeneral
open AtanasovRanganathan.Configurations

variable {n p : ℕ} {source target : Core n p}
variable (r : source.Relabeling target) (length : Fin p → ℕ)

private theorem zero_mem_map (e : Fin p) :
    r.slotEquiv e ∈ zeroSlots (r.reindexedLength length) ↔
      e ∈ zeroSlots length := by
  rw [mem_zeroSlots, mem_zeroSlots, reindexedLength_slotEquiv]

theorem adj_map {u v : Fin n} :
    AdjInList source (edgeList (zeroSlots length)) u v →
      AdjInList target (edgeList (zeroSlots (r.reindexedLength length)))
        (r.coreEquiv u) (r.coreEquiv v) := by
  rintro ⟨e, he, huv⟩
  refine ⟨r.slotEquiv e, (mem_edgeList _ _).2 ?_, ?_⟩
  · exact (zero_mem_map r length e).2 ((mem_edgeList _ _).1 he)
  · have ht := r.tail_eq e
    have hh := r.head_eq e
    by_cases hr : r.reversed e
    · simp [hr] at ht hh
      rcases huv with huv | huv
      · exact Or.inr ⟨hh.trans (congrArg r.coreEquiv huv.1),
          ht.trans (congrArg r.coreEquiv huv.2)⟩
      · exact Or.inl ⟨ht.trans (congrArg r.coreEquiv huv.1),
          hh.trans (congrArg r.coreEquiv huv.2)⟩
    · have hr' : r.reversed e = false := Bool.eq_false_of_not_eq_true hr
      simp [hr'] at ht hh
      rcases huv with huv | huv
      · exact Or.inl ⟨ht.trans (congrArg r.coreEquiv huv.1),
          hh.trans (congrArg r.coreEquiv huv.2)⟩
      · exact Or.inr ⟨hh.trans (congrArg r.coreEquiv huv.1),
          ht.trans (congrArg r.coreEquiv huv.2)⟩

theorem adj_map_iff {u v : Fin n} :
    AdjInList target (edgeList (zeroSlots (r.reindexedLength length)))
        (r.coreEquiv u) (r.coreEquiv v) ↔
      AdjInList source (edgeList (zeroSlots length)) u v := by
  constructor
  · rintro ⟨f, hf, huv⟩
    let e := r.slotEquiv.symm f
    have hfe : r.slotEquiv e = f := r.slotEquiv.apply_symm_apply f
    have he : e ∈ zeroSlots length := by
      apply (zero_mem_map r length e).1
      simpa [hfe] using (mem_edgeList _ _).1 hf
    refine ⟨e, (mem_edgeList _ _).2 he, ?_⟩
    have ht := r.tail_eq e
    have hh := r.head_eq e
    rw [hfe] at ht hh
    by_cases hr : r.reversed e
    · simp [hr] at ht hh
      rcases huv with huv | huv
      · exact Or.inr ⟨r.coreEquiv.injective (huv.1.symm.trans ht) |>.symm,
          r.coreEquiv.injective (huv.2.symm.trans hh) |>.symm⟩
      · exact Or.inl ⟨r.coreEquiv.injective (huv.1.symm.trans hh) |>.symm,
          r.coreEquiv.injective (huv.2.symm.trans ht) |>.symm⟩
    · have hr' : r.reversed e = false := Bool.eq_false_of_not_eq_true hr
      simp [hr'] at ht hh
      rcases huv with huv | huv
      · exact Or.inl ⟨r.coreEquiv.injective (huv.1.symm.trans ht) |>.symm,
          r.coreEquiv.injective (huv.2.symm.trans hh) |>.symm⟩
      · exact Or.inr ⟨r.coreEquiv.injective (huv.1.symm.trans hh) |>.symm,
          r.coreEquiv.injective (huv.2.symm.trans ht) |>.symm⟩
  · exact adj_map r length

theorem reach_map_iff (u v : Fin n) :
    ReachIn target (zeroSlots (r.reindexedLength length))
        (r.coreEquiv u) (r.coreEquiv v) ↔
      ReachIn source (zeroSlots length) u v := by
  unfold ReachIn ReachInList
  constructor
  · intro h
    simpa [Function.onFun] using Relation.ReflTransGen.lift r.coreEquiv.symm
      (fun a b hab => (adj_map_iff r length
        (u := r.coreEquiv.symm a) (v := r.coreEquiv.symm b)).1
        (by simpa using hab)) (r.coreEquiv u) (r.coreEquiv v) h
  · exact Relation.ReflTransGen.lift r.coreEquiv
      (fun _ _ h => adj_map r length h) u v

theorem rep_eq_iff (u v : Fin n) :
    compFold target (zeroSlots (r.reindexedLength length)) (r.coreEquiv u) =
        compFold target (zeroSlots (r.reindexedLength length)) (r.coreEquiv v) ↔
      compFold source (zeroSlots length) u =
        compFold source (zeroSlots length) v := by
  rw [compFold_iff, compFold_iff, reach_map_iff r length]

private noncomputable def classEquiv :
    {v : Fin n // compFold source (zeroSlots length) v = v} ≃
      {v : Fin n // compFold target (zeroSlots (r.reindexedLength length)) v = v} :=
  Equiv.ofBijective
    (fun x => ⟨compFold target (zeroSlots (r.reindexedLength length))
      (r.coreEquiv x.val), compFold_idem _ _ _⟩)
    ⟨by
      intro x y hxy
      apply Subtype.ext
      have hrep := (rep_eq_iff r length x.val y.val).1
        (congrArg Subtype.val hxy)
      simpa [x.property, y.property] using hrep,
     by
      intro y
      let z := r.coreEquiv.symm y.val
      let x : {v : Fin n // compFold source (zeroSlots length) v = v} :=
        ⟨compFold source (zeroSlots length) z, compFold_idem _ _ _⟩
      refine ⟨x, Subtype.ext ?_⟩
      change compFold target (zeroSlots (r.reindexedLength length))
        (r.coreEquiv (compFold source (zeroSlots length) z)) = y.val
      have hreach : ReachIn source (zeroSlots length)
          (compFold source (zeroSlots length) z) z :=
        (reachIn_equivalence source (zeroSlots length)).symm
          (reachIn_self_compFold source (zeroSlots length) z)
      have htarget := (reach_map_iff r length
        (compFold source (zeroSlots length) z) z).2 hreach
      have hrep := (compFold_iff target _ _ _).2 htarget
      simpa [z, y.property] using hrep⟩

private theorem card_fixed_eq_image (rep : Fin n → Fin n)
    (hidem : ∀ v, rep (rep v) = rep v) :
    Fintype.card {v : Fin n // rep v = v} =
      (Finset.image rep Finset.univ).card := by
  have himage : Finset.image rep Finset.univ =
      Finset.univ.filter (fun v : Fin n => rep v = v) := by
    ext v
    constructor
    · intro hv
      obtain ⟨u, -, hu⟩ := Finset.mem_image.mp hv
      exact Finset.mem_filter.mpr ⟨Finset.mem_univ _, by rw [← hu, hidem u]⟩
    · intro hv
      exact Finset.mem_image.mpr
        ⟨v, Finset.mem_univ _, (Finset.mem_filter.mp hv).2⟩
  rw [himage, Fintype.card_subtype]

private theorem zero_card_eq :
    (zeroSlots (r.reindexedLength length)).card = (zeroSlots length).card := by
  refine Finset.card_bij (fun e _ => r.slotEquiv.symm e) ?_ ?_ ?_
  · intro e he
    have := (zero_mem_map r length (r.slotEquiv.symm e)).1 (by simpa using he)
    simpa using this
  · intro a _ b _ hab
    exact r.slotEquiv.symm.injective hab
  · intro e he
    refine ⟨r.slotEquiv e, (zero_mem_map r length e).2 he, ?_⟩
    simp

theorem isForest_iff :
    IsForest target (zeroSlots (r.reindexedLength length)) ↔
      IsForest source (zeroSlots length) := by
  unfold IsForest
  have hclass := Fintype.card_congr (classEquiv r length)
  rw [card_fixed_eq_image _ (compFold_idem source (zeroSlots length)),
    card_fixed_eq_image _
      (compFold_idem target (zeroSlots (r.reindexedLength length)))] at hclass
  rw [zero_card_eq r length, hclass]

theorem isLoopy_iff :
    IsLoopy target (zeroSlots (r.reindexedLength length)) ↔
      IsLoopy source (zeroSlots length) := by
  unfold IsLoopy
  constructor
  · rintro ⟨f, hf, hrep⟩
    let e := r.slotEquiv.symm f
    have hfe : r.slotEquiv e = f := r.slotEquiv.apply_symm_apply f
    have he : e ∉ zeroSlots length := by
      intro he
      have himage := (zero_mem_map r length e).2 he
      rw [hfe] at himage
      exact hf himage
    refine ⟨e, he, ?_⟩
    apply (rep_eq_iff r length (source.tail e) (source.head e)).1
    have ht := r.tail_eq e
    have hh := r.head_eq e
    rw [hfe] at ht hh
    by_cases hr : r.reversed e
    · simp [hr] at ht hh
      simpa [ht, hh] using hrep.symm
    · have hr' : r.reversed e = false := Bool.eq_false_of_not_eq_true hr
      simp [hr'] at ht hh
      simpa [ht, hh] using hrep
  · rintro ⟨e, he, hrep⟩
    refine ⟨r.slotEquiv e, ?_, ?_⟩
    · exact fun h => he ((zero_mem_map r length e).1 h)
    · have htarget := (rep_eq_iff r length (source.tail e) (source.head e)).2 hrep
      have ht := r.tail_eq e
      have hh := r.head_eq e
      by_cases hr : r.reversed e
      · simp [hr] at ht hh
        simpa [ht, hh] using htarget.symm
      · have hr' : r.reversed e = false := Bool.eq_false_of_not_eq_true hr
        simp [hr'] at ht hh
        simpa [ht, hh] using htarget

private noncomputable def faceClassEquiv
    (source_nonempty : 0 < n)
    (hForest : IsForest source (zeroSlots length))
    (hNotLoopy : ¬ IsLoopy source (zeroSlots length)) :
    (faceSpec source source_nonempty length hForest hNotLoopy).Class ≃
      (faceSpec target source_nonempty (r.reindexedLength length)
        ((isForest_iff r length).2 hForest)
        (fun h => hNotLoopy ((isLoopy_iff r length).1 h))).Class := by
  exact classEquiv r length

private theorem faceClassEquiv_apply
    (source_nonempty : 0 < n)
    (hForest : IsForest source (zeroSlots length))
    (hNotLoopy : ¬ IsLoopy source (zeroSlots length)) (u : Fin n) :
    faceClassEquiv r length source_nonempty hForest hNotLoopy
        ⟨(faceSpec source source_nonempty length hForest hNotLoopy).rep u,
          (faceSpec source source_nonempty length hForest hNotLoopy).rep_idem u⟩ =
      ⟨(faceSpec target source_nonempty (r.reindexedLength length)
          ((isForest_iff r length).2 hForest)
          (fun h => hNotLoopy ((isLoopy_iff r length).1 h))).rep (r.coreEquiv u),
        (faceSpec target source_nonempty (r.reindexedLength length)
          ((isForest_iff r length).2 hForest)
          (fun h => hNotLoopy ((isLoopy_iff r length).1 h))).rep_idem _⟩ := by
  apply Subtype.ext
  exact (rep_eq_iff r length
    ((faceSpec source source_nonempty length hForest hNotLoopy).rep u) u).2
      ((faceSpec source source_nonempty length hForest hNotLoopy).rep_idem u)

/-- The closed faces attached to occurrence-relabelled cores are themselves
occurrence-relabelled. -/
noncomputable def faceRelabeling
    (source_nonempty : 0 < n)
    (hForest : IsForest source (zeroSlots length))
    (hNotLoopy : ¬ IsLoopy source (zeroSlots length)) :
    DegSpec.Relabeling
      (faceSpec source source_nonempty length hForest hNotLoopy)
      (faceSpec target source_nonempty (r.reindexedLength length)
        ((isForest_iff r length).2 hForest)
        (fun h => hNotLoopy ((isLoopy_iff r length).1 h))) where
  classEquiv := faceClassEquiv r length source_nonempty hForest hNotLoopy
  slotEquiv := r.slotEquiv
  reversed := r.reversed
  length_eq := fun e => (reindexedLength_slotEquiv r length e).symm
  tail_eq := by
    intro e
    by_cases hr : r.reversed e
    · simp only [if_pos hr]
      rw [faceClassEquiv_apply r length source_nonempty hForest hNotLoopy]
      apply Subtype.ext
      have ht := r.tail_eq e
      simp [hr] at ht
      change compFold target (zeroSlots (r.reindexedLength length))
          (r.coreEquiv (source.head e)) =
        compFold target (zeroSlots (r.reindexedLength length))
          (target.tail (r.slotEquiv e))
      rw [ht]
    · have hr' : r.reversed e = false := Bool.eq_false_of_not_eq_true hr
      simp only [if_neg hr]
      rw [faceClassEquiv_apply r length source_nonempty hForest hNotLoopy]
      apply Subtype.ext
      have ht := r.tail_eq e
      simp [hr'] at ht
      change compFold target (zeroSlots (r.reindexedLength length))
          (r.coreEquiv (source.tail e)) =
        compFold target (zeroSlots (r.reindexedLength length))
          (target.tail (r.slotEquiv e))
      rw [ht]
  head_eq := by
    intro e
    by_cases hr : r.reversed e
    · simp only [if_pos hr]
      rw [faceClassEquiv_apply r length source_nonempty hForest hNotLoopy]
      apply Subtype.ext
      have hh := r.head_eq e
      simp [hr] at hh
      change compFold target (zeroSlots (r.reindexedLength length))
          (r.coreEquiv (source.tail e)) =
        compFold target (zeroSlots (r.reindexedLength length))
          (target.head (r.slotEquiv e))
      rw [hh]
    · have hr' : r.reversed e = false := Bool.eq_false_of_not_eq_true hr
      simp only [if_neg hr]
      rw [faceClassEquiv_apply r length source_nonempty hForest hNotLoopy]
      apply Subtype.ext
      have hh := r.head_eq e
      simp [hr'] at hh
      change compFold target (zeroSlots (r.reindexedLength length))
          (r.coreEquiv (source.head e)) =
        compFold target (zeroSlots (r.reindexedLength length))
          (target.head (r.slotEquiv e))
      rw [hh]

/-- A closed-orthant Brill--Noether existence theorem transports backward
along an occurrence-sensitive core relabeling, at arbitrary rank and degree. -/
theorem closedPencil_of_target
    (relabeling : source.Relabeling target) (source_nonempty : 0 < n)
    {r degree : ℤ}
    (targetClosed : ∀ (targetLength : Fin p → ℕ)
      (targetForest : IsForest target (zeroSlots targetLength))
      (targetNotLoopy : ¬ IsLoopy target (zeroSlots targetLength)),
      BNExists
        (faceSpec target source_nonempty targetLength
          targetForest targetNotLoopy).graph r degree) :
    ∀ (sourceLength : Fin p → ℕ)
      (sourceForest : IsForest source (zeroSlots sourceLength))
      (sourceNotLoopy : ¬ IsLoopy source (zeroSlots sourceLength)),
      BNExists
        (faceSpec source source_nonempty sourceLength
          sourceForest sourceNotLoopy).graph r degree := by
  intro sourceLength sourceForest sourceNotLoopy
  let targetForest := (isForest_iff relabeling sourceLength).2 sourceForest
  let targetNotLoopy : ¬ IsLoopy target
      (zeroSlots (relabeling.reindexedLength sourceLength)) :=
    fun h => sourceNotLoopy ((isLoopy_iff relabeling sourceLength).1 h)
  have hTarget := targetClosed (relabeling.reindexedLength sourceLength)
    targetForest targetNotLoopy
  exact (DegSpec.Relabeling.bnExists_iff _ _
    (faceRelabeling relabeling sourceLength source_nonempty
      sourceForest sourceNotLoopy) r degree).mp hTarget

/-- A closed construction transports backward along an occurrence-sensitive
core relabeling. -/
theorem closedConstruction_of_target
    (relabeling : source.Relabeling target) (source_nonempty : 0 < n) :
    ClosedSubdivisionDharConstruction target source_nonempty →
      ClosedSubdivisionDharConstruction source source_nonempty := by
  intro construction length hForest hNotLoopy
  let targetForest := (isForest_iff relabeling length).2 hForest
  let targetNotLoopy : ¬ IsLoopy target
      (zeroSlots (relabeling.reindexedLength length)) :=
    fun h => hNotLoopy ((isLoopy_iff relabeling length).1 h)
  obtain ⟨pencil⟩ := construction (relabeling.reindexedLength length)
    targetForest targetNotLoopy
  apply DegreeFourDharPencil.nonempty_ofBNExists
  exact (DegSpec.Relabeling.bnExists_iff _ _
    (faceRelabeling relabeling length source_nonempty hForest hNotLoopy) 1 4).mp
      pencil.bnExists

end Utilities.Certificate.ExplicitPotential.Core.Relabeling
