-- The banana model: definitions, geometry, elementary structure
import Bananas.Basics.BananaBasics
import Bananas.Basics.BananaGeometry
import Bananas.Basics.BananaSameStrandLemma
import Bananas.Basics.Definitions
import Bananas.Basics.DegreeOneRepresentatives
import Bananas.Basics.GraphIsoCuts
import Bananas.Basics.MarkedIso
import Bananas.Basics.ReducedCutCriterion
import Bananas.Basics.SegmentScript
import Bananas.Basics.TwoEdgeCuts

-- The Jacobian presentation and torsion slopes (Prop 2.14)
import Bananas.Jacobian.BananaJacobianDiagonal
import Bananas.Jacobian.BananaJacobianLatticeReduction
import Bananas.Jacobian.BananaJacobianLeftJustification
import Bananas.Jacobian.BananaJacobianPresentation
import Bananas.Jacobian.BananaJacobianProposition214
import Bananas.Jacobian.BananaJacobianQuotientCertificate
import Bananas.Jacobian.BananaJacobianReducedBridge
import Bananas.Jacobian.BananaJacobianReducedInjectivity
import Bananas.Jacobian.BananaJacobianReducedUniqueness
import Bananas.Jacobian.BananaJacobianReductionTermination
import Bananas.Jacobian.BananaJacobianSurjectivity
import Bananas.Jacobian.BananaTorsionSlopes

-- Transmission, torsion orders, rank witnesses
import Bananas.Transmission.ChainBalanceArithmetic
import Bananas.Transmission.ChainTwoLoopsSameLeft
import Bananas.Transmission.ChainTwoLoopsSameRight
import Bananas.Transmission.CycleTorsionOrder
import Bananas.Transmission.EqualTorsionKGeneral
import Bananas.Transmission.ExactTorsionAPI
import Bananas.Transmission.FarMarkAPI
import Bananas.Transmission.FarMarkNegativeAPI
import Bananas.Transmission.GenericFarWitness
import Bananas.Transmission.GenericRankWitness
import Bananas.Transmission.KGeneralBNGeneral
import Bananas.Transmission.KGeneralGonality
import Bananas.Transmission.KGeneralSwap
import Bananas.Transmission.LengthTwoTorsion
import Bananas.Transmission.MixedTorsionChainBalance
import Bananas.Transmission.MixedTorsionChains
import Bananas.Transmission.NonrecurrenceDisjoint
import Bananas.Transmission.NonrecurrenceWitness
import Bananas.Transmission.RankDeltaDuality
import Bananas.Transmission.RankDetermining
import Bananas.Transmission.RankZeroSupport
import Bananas.Transmission.RankZeroVertexBridge
import Bananas.Transmission.RankZeroWitness
import Bananas.Transmission.TorsionIso
import Bananas.Transmission.TorsionOrderExact
import Bananas.Transmission.TorsionOrderTwoGeneral
import Bananas.Transmission.TransmissionAPI
import Bananas.Transmission.TransmissionBasics
import Bananas.Transmission.TransmissionBridge
import Bananas.Transmission.TwoVertexGenusOneTorsion

-- Same-strand marks: endpoint/interior analysis (Sections 3-4)
import Bananas.SameStrand.BananaEndpointDelta
import Bananas.SameStrand.BananaEndpointRankCriterion
import Bananas.SameStrand.EndpointBlock
import Bananas.SameStrand.EndpointCardinality
import Bananas.SameStrand.EndpointInversions
import Bananas.SameStrand.NSMClassification
import Bananas.SameStrand.NSMCrossWitness
import Bananas.SameStrand.NSMFullClassification
import Bananas.SameStrand.NSMSecondCrossWitness
import Bananas.SameStrand.SameStrand
import Bananas.SameStrand.SameStrandEndpointNegative
import Bananas.SameStrand.SameStrandInteriorNegative
import Bananas.SameStrand.Semibreak

-- Cross and one-off marks: inversion growth (Section 4)
import Bananas.CrossOneOff.AffineInversionFinite
import Bananas.CrossOneOff.AffineReduction
import Bananas.CrossOneOff.BananaCrossOneOffDeltaFamilies
import Bananas.CrossOneOff.BananaOneOffDeltaFamilies
import Bananas.CrossOneOff.CrossOneOffArithmetic
import Bananas.CrossOneOff.CrossOneOffBlock
import Bananas.CrossOneOff.CrossOneOffCorrectedInversion
import Bananas.CrossOneOff.CrossOneOffCorrectedKGeneral
import Bananas.CrossOneOff.CrossOneOffDelta
import Bananas.CrossOneOff.CrossOneOffExtendedBlock
import Bananas.CrossOneOff.CrossOneOffFiniteCountSol
import Bananas.CrossOneOff.CrossOneOffFiniteRows
import Bananas.CrossOneOff.CrossOneOffFiring
import Bananas.CrossOneOff.CrossOneOffForcedCountArithmetic
import Bananas.CrossOneOff.CrossOneOffForcedCountLengthTwo
import Bananas.CrossOneOff.CrossOneOffInversions
import Bananas.CrossOneOff.CrossOneOffKGeneral
import Bananas.CrossOneOff.CrossOneOffPeriodSeparation
import Bananas.CrossOneOff.CrossOneOffResidueDelta
import Bananas.CrossOneOff.CrossOneOffShortStrandPeriod
import Bananas.CrossOneOff.CrossOneOffTransmission
import Bananas.CrossOneOff.CrossStrandNegative
import Bananas.CrossOneOff.CrossStrandSupport
import Bananas.CrossOneOff.CrossingInversionCount
import Bananas.CrossOneOff.LengthTwoCross
import Bananas.CrossOneOff.LengthTwoCrossBasePoint
import Bananas.CrossOneOff.LengthTwoCrossMonotonicity
import Bananas.CrossOneOff.OneOffInversionLowerBound
import Bananas.CrossOneOff.OneOffKGeneral
import Bananas.CrossOneOff.OneOffMultipleRows
import Bananas.CrossOneOff.OneOffPeriodBound
import Bananas.CrossOneOff.OneOffPositiveRows
import Bananas.CrossOneOff.OneOffRefinedInversion
import Bananas.CrossOneOff.OneOffTransmission
import Bananas.CrossOneOff.QuadraticInversionGrowth
import Bananas.CrossOneOff.SignChangingInversions

-- Theta graphs: the genus-two exact theory
import Bananas.Theta.EvenlyMarkedThetaKGeneral
import Bananas.Theta.ThetaArithmetic
import Bananas.Theta.ThetaBoundarySubmodularity
import Bananas.Theta.ThetaChipEval
import Bananas.Theta.ThetaCoordinateRigidity
import Bananas.Theta.ThetaCounterexampleNormalForm
import Bananas.Theta.ThetaExactTorsion
import Bananas.Theta.ThetaExactTorsionRelabel
import Bananas.Theta.ThetaExceptionalArithmetic
import Bananas.Theta.ThetaGenusTwoCornerSum
import Bananas.Theta.ThetaGenusTwoTwistIdentities
import Bananas.Theta.ThetaInvTauCorrection
import Bananas.Theta.ThetaInversionCount
import Bananas.Theta.ThetaInversionFiniteSum
import Bananas.Theta.ThetaJacobian
import Bananas.Theta.ThetaJacobianPresentation
import Bananas.Theta.ThetaKGeneralClassification
import Bananas.Theta.ThetaKGeneralCoordinates
import Bananas.Theta.ThetaLattice
import Bananas.Theta.ThetaMoment
import Bananas.Theta.ThetaNegativeDivisorClasses
import Bananas.Theta.ThetaNegativeDivisorClassesBoundary
import Bananas.Theta.ThetaNegativeDivisorClassesTerminal
import Bananas.Theta.ThetaNonrecurrence
import Bananas.Theta.ThetaPrefix
import Bananas.Theta.ThetaPrincipal
import Bananas.Theta.ThetaReflectionRank
import Bananas.Theta.ThetaResidue
import Bananas.Theta.ThetaTorsionAPI
import Bananas.Theta.ThetaTransmissionAudit
import Bananas.Theta.ThetaTransmissionCases

-- Wedge sums and their k-general classification
import Bananas.Wedge.KGeneralWedgeGenerality
import Bananas.Wedge.OnceMarkedWedgeGenerality
import Bananas.Wedge.OppositeWedgeKGeneralClassification
import Bananas.Wedge.OppositeWedgeRigidity
import Bananas.Wedge.SameFactorWedgeKGeneral
import Bananas.Wedge.SameFactorWedgePeriod
import Bananas.Wedge.SameFactorWedgeRight
import Bananas.Wedge.SameFactorWedgeSubmodularity
import Bananas.Wedge.TwoVertexWedgeSubmodularity
import Bananas.Wedge.VertexWedgeAssociativity
import Bananas.Wedge.WedgeKGeneralClassification
import Bananas.Wedge.WedgeKGeneralConverse
import Bananas.Wedge.WedgeKGeneralSymmetric
import Bananas.Wedge.WedgePeriodRecurrence
import Bananas.Wedge.WedgeSubmodularity
import Bananas.Wedge.WedgeTorsionRestriction
import Bananas.Wedge.ZeroGenusWedge

-- Bridgeless low-genus classification and corrected theorems
import Bananas.Classification.BridgelessDegreeOneClasses
import Bananas.Classification.BridgelessGenusOneTopology
import Bananas.Classification.BridgelessGenusTwoClassification
import Bananas.Classification.BridgelessGenusTwoCornerAlgebra
import Bananas.Classification.BridgelessGenusTwoDegreeShape
import Bananas.Classification.BridgelessGenusTwoKGeneralReduction
import Bananas.Classification.BridgelessGenusTwoNonrecurrence
import Bananas.Classification.BridgelessGenusTwoPseudocore
import Bananas.Classification.BridgelessGenusTwoTopology
import Bananas.Classification.CorrectedBananaSimple
import Bananas.Classification.CorrectedBananaTheorem117
import Bananas.Classification.CorrectedBananaTorsion
import Bananas.Classification.CorrectedMidpointKGeneral
import Bananas.Classification.GenusOneKGeneral
import Bananas.Classification.GenusOneRankDelta
import Bananas.Classification.GenusTwoDegreeTwo
import Bananas.Classification.GenusTwoReduction
import Bananas.Classification.PointedGenusOneKGeneral
import Bananas.Classification.SciWeierstrass
import Bananas.Classification.WeierstrassPartition

-- Section 5 and Section 6 paper spines
import Bananas.Sections.SectionFiveDefinitions
import Bananas.Sections.SectionFiveInversionBound
import Bananas.Sections.SectionFiveStatements
import Bananas.Sections.SectionFiveSymmetries
import Bananas.Sections.SectionFiveTransports
import Bananas.Sections.SectionSixBananaCorollary
import Bananas.Sections.SectionSixChainConclusion
import Bananas.Sections.SectionSixDefinitions
import Bananas.Sections.SectionSixFoundation

-- Worked examples and audits
import Bananas.Examples.ExampleBngChain
import Bananas.Examples.MechanicalAPIAudit

-- Downstream applications to named results in the tropical Brill--Noether
-- literature.  These consume the Section 6 chain theorems as black boxes; they
-- are not part of the twice-marked banana paper, which is why they are indexed here
-- and not in `TwiceMarkedBananas.lean`.
import Bananas.ChainOfLoops.CDPR
import Bananas.ChainOfLoops.BridgeChainTransport
import Bananas.ChainOfLoops.CommonPeriodGonality
import Bananas.ChainOfLoops.Highlights
