module

public import DraismaVargasCount.Assembly
public import DraismaVargasCount.AttachmentFibre
public import DraismaVargasCount.BallotCoreIdentification
public import DraismaVargasCount.BallotDatum
public import DraismaVargasCount.BallotDiagonal
public import DraismaVargasCount.BallotEndSwapGeneral
public import DraismaVargasCount.BallotEndSwapSheetIso
public import DraismaVargasCount.BallotFarEndSwap
public import DraismaVargasCount.BallotFullDimensional
public import DraismaVargasCount.BallotGenus
public import DraismaVargasCount.BallotMultiplicity
public import DraismaVargasCount.BallotOrbitStability
public import DraismaVargasCount.BallotResidues
public import DraismaVargasCount.BallotSlopeDiagonalBridge
public import DraismaVargasCount.BallotSlopeSeparation
public import DraismaVargasCount.BallotSpineCensus
public import DraismaVargasCount.BallotSpineReversalSheetIso
public import DraismaVargasCount.BallotStabiliserReduction
public import DraismaVargasCount.BallotStemCensus
public import DraismaVargasCount.BallotValency
public import DraismaVargasCount.BaseCountParity
public import DraismaVargasCount.BlockMatching
public import DraismaVargasCount.BlockPreservingOverlap
public import DraismaVargasCount.BranchSharedDirection
public import DraismaVargasCount.CanonicalSurvivor
public import DraismaVargasCount.CatFlipRealizedAut
public import DraismaVargasCount.CaterpillarAllMembers
public import DraismaVargasCount.CaterpillarBallotCount
public import DraismaVargasCount.CensusAssembly
public import DraismaVargasCount.CensusConnected
public import DraismaVargasCount.ClosedBoundaryMember
public import DraismaVargasCount.ColumnReceiptExport
public import DraismaVargasCount.ConeSide
public import DraismaVargasCount.CoreChainSites
public import DraismaVargasCount.CorePencilCoverProducer
public import DraismaVargasCount.CoreRelabelInvariance
public import DraismaVargasCount.CoreSlotCoords
public import DraismaVargasCount.CountSchedule
public import DraismaVargasCount.CountTransportLink
public import DraismaVargasCount.CrossCoreParity
public import DraismaVargasCount.CrossCoreTransport
public import DraismaVargasCount.DegenerateBigDivisor
public import DraismaVargasCount.DegenerateFibreCover
public import DraismaVargasCount.DegeneratePlacement
public import DraismaVargasCount.DegenerateRealizationImage
public import DraismaVargasCount.DegenerateTransport
public import DraismaVargasCount.DiagonalClassification
public import DraismaVargasCount.DiagonalClassificationEndgame
public import DraismaVargasCount.DiagonalClassificationGenusSix
public import DraismaVargasCount.DiagonalExtract
public import DraismaVargasCount.DiagonalFromSeparation
public import DraismaVargasCount.DiagonalRigidityObligation
public import DraismaVargasCount.DiagonalTargetIso
public import DraismaVargasCount.DiscreteContraction
public import DraismaVargasCount.DiscreteW4Normalization
public import DraismaVargasCount.EdgeDenominator
public import DraismaVargasCount.EndSwapRealized
public import DraismaVargasCount.EvenGenusParity
public import DraismaVargasCount.ExpansionSeriesMoment
public import DraismaVargasCount.ExtractGenusTwo
public import DraismaVargasCount.FacetAdapterPilot
public import DraismaVargasCount.FacetCensus
public import DraismaVargasCount.FacetCommonMultiplicity
public import DraismaVargasCount.FacetMachine
public import DraismaVargasCount.FacetParityPilot
public import DraismaVargasCount.Fibre
public import DraismaVargasCount.FibreCaterpillar
public import DraismaVargasCount.FibreNormalForm
public import DraismaVargasCount.FrameColumnRigidity
public import DraismaVargasCount.GeneralKBackground
public import DraismaVargasCount.GeneralKExit
public import DraismaVargasCount.GeneralKExitSetup
public import DraismaVargasCount.GeneralKLink
public import DraismaVargasCount.GeneralKReceipts
public import DraismaVargasCount.GeneralKResolution
public import DraismaVargasCount.GeneralKRowCore
public import DraismaVargasCount.GeneralKRowEquiv
public import DraismaVargasCount.GeneralKRowGauge
public import DraismaVargasCount.GeneralKRowStar
public import DraismaVargasCount.GeneralKRowsK
public import DraismaVargasCount.GeneralKSourceFacts
public import DraismaVargasCount.GeneralKStarCount
public import DraismaVargasCount.GeneralKTracks
public import DraismaVargasCount.GeneralKTracksBlock
public import DraismaVargasCount.GeometricContraction
public import DraismaVargasCount.GeometricCount
public import DraismaVargasCount.GeometricCountFamily
public import DraismaVargasCount.GeometricFibre
public import DraismaVargasCount.GeometricInheritedBranches
public import DraismaVargasCount.GeometricInheritedRows
public import DraismaVargasCount.GeometricLimitTransport
public import DraismaVargasCount.GeometricMultiplicity
public import DraismaVargasCount.GeometricSegmentWalls
public import DraismaVargasCount.GeometricStableTransport
public import DraismaVargasCount.GeometricStar
public import DraismaVargasCount.GeometricTransport
public import DraismaVargasCount.GeometricUniformExpansion
public import DraismaVargasCount.GeometricValidityTransport
public import DraismaVargasCount.IncomingSimpleColumn
public import DraismaVargasCount.IndexPattern
public import DraismaVargasCount.InheritedLimitBranches
public import DraismaVargasCount.InheritedLimitIncidence
public import DraismaVargasCount.InheritedLimitRows
public import DraismaVargasCount.Integrality
public import DraismaVargasCount.LeafFibre
public import DraismaVargasCount.LinkReceiptExport
public import DraismaVargasCount.LollipopBridgeFibre
public import DraismaVargasCount.LollipopBridgeFibreWitness
public import DraismaVargasCount.LollipopDivalent
public import DraismaVargasCount.LollipopDivalentWitness
public import DraismaVargasCount.LollipopLeafRow
public import DraismaVargasCount.LoopAdjacentDiagonal
public import DraismaVargasCount.M11IncomingDenominator
public import DraismaVargasCount.M11LoopWall
public import DraismaVargasCount.M11MultiplicityBalance
public import DraismaVargasCount.M11StarCensusProof
public import DraismaVargasCount.M11StarExhaustionProof
public import DraismaVargasCount.M11StarParityFree
public import DraismaVargasCount.M11WallExhaustion
public import DraismaVargasCount.MemberCertifiedPencil
public import DraismaVargasCount.MemberColumnTwist
public import DraismaVargasCount.MemberCoreDarts
public import DraismaVargasCount.MemberSeedExists
public import DraismaVargasCount.MemberSeedTree
public import DraismaVargasCount.MergePinning
public import DraismaVargasCount.Multiplicity
public import DraismaVargasCount.NonTrivalentBalance
public import DraismaVargasCount.NonTrivalentCorner
public import DraismaVargasCount.NonTrivalentLeafNormalization
public import DraismaVargasCount.NonTrivalentNonfacetDenominator
public import DraismaVargasCount.OddDenominator
public import DraismaVargasCount.OddWitness
public import DraismaVargasCount.OpenAtPositivity
public import DraismaVargasCount.OpenOddRung
public import DraismaVargasCount.OutgoingRowCalculus
public import DraismaVargasCount.PartitionCensusProof
public import DraismaVargasCount.PassOnceLollipop
public import DraismaVargasCount.PassOnceLollipopWitness
public import DraismaVargasCount.PencilTransportProducer
public import DraismaVargasCount.PendantBranch
public import DraismaVargasCount.PendantDivisorTransport
public import DraismaVargasCount.PendantFibre
public import DraismaVargasCount.PendantRetraction
public import DraismaVargasCount.PositiveOrthantWall
public import DraismaVargasCount.RegrowthBalances
public import DraismaVargasCount.RegrowthWallInput
public import DraismaVargasCount.ResolutionExpansion
public import DraismaVargasCount.ResolutionExpansionFree
public import DraismaVargasCount.RigidityBasepoint
public import DraismaVargasCount.RowChipCoefficient
public import DraismaVargasCount.RowGeodesic
public import DraismaVargasCount.RowHairpinPosition
public import DraismaVargasCount.RowLeafAvoidingPosition
public import DraismaVargasCount.RowPosition
public import DraismaVargasCount.RowRealizedPosition
public import DraismaVargasCount.RowRegrowth
public import DraismaVargasCount.RowSingleColumnProof
public import DraismaVargasCount.RowSingleColumnWitness
public import DraismaVargasCount.RowSlotMap
public import DraismaVargasCount.RowSlotOrientation
public import DraismaVargasCount.RowTransitionPosition
public import DraismaVargasCount.RowVertexEnumeration
public import DraismaVargasCount.RowWalk
public import DraismaVargasCount.SegmentWalls
public import DraismaVargasCount.SharpRowDenominator
public import DraismaVargasCount.SheetLayerCensus
public import DraismaVargasCount.SheetLayerMatching
public import DraismaVargasCount.SimpleWallSupply
public import DraismaVargasCount.SlopeRigidity
public import DraismaVargasCount.SlopeStack
public import DraismaVargasCount.SlopesGeometric
public import DraismaVargasCount.SpineOffDiagonal
public import DraismaVargasCount.SpinePath
public import DraismaVargasCount.SpineReversal
public import DraismaVargasCount.SpineRowLength
public import DraismaVargasCount.SpineRowLengthWitness
public import DraismaVargasCount.SpineSingleColumn
public import DraismaVargasCount.Star
public import DraismaVargasCount.StarCensusEngine
public import DraismaVargasCount.StarFrameIso
public import DraismaVargasCount.StarMetricCompatibility
public import DraismaVargasCount.StarParityFromBalance
public import DraismaVargasCount.StarPartition
public import DraismaVargasCount.StarPilot
public import DraismaVargasCount.StarSupplyAssembly
public import DraismaVargasCount.StepSupplyGenusSix
public import DraismaVargasCount.StepSupplyReduction
public import DraismaVargasCount.SurvivingSlotMap
public import DraismaVargasCount.SwitchingParity
public import DraismaVargasCount.TargetGeodesic
public import DraismaVargasCount.TargetNormalForm
public import DraismaVargasCount.Transport
public import DraismaVargasCount.TransportMultiplicity
public import DraismaVargasCount.TransportedChipEndgame
public import DraismaVargasCount.TreeMetricPotential
public import DraismaVargasCount.TrivalentFibreUnique
public import DraismaVargasCount.TrivalentWeight
public import DraismaVargasCount.TypeChangePositiveProbe
public import DraismaVargasCount.UniformExpansionRecognition
public import DraismaVargasCount.UnitWeightBalance
public import DraismaVargasCount.ValencyFourRealisation
public import DraismaVargasCount.ValencyFourRigidity
public import DraismaVargasCount.ValencyFourSplit
public import DraismaVargasCount.ValencyThreeCensus
public import DraismaVargasCount.ValencyThreeCoreSlots
public import DraismaVargasCount.ValencyThreeDigon
public import DraismaVargasCount.ValencyThreeGeneral
public import DraismaVargasCount.ValencyThreeLoopMerge
public import DraismaVargasCount.ValencyThreeResolutionMatch
public import DraismaVargasCount.ValencyThreeRigidity
public import DraismaVargasCount.ValencyThreeSplit
public import DraismaVargasCount.ValencyThreeTypeMatch
public import DraismaVargasCount.ValencyTwoCensus
public import DraismaVargasCount.ValencyTwoPairing
public import DraismaVargasCount.ValencyTwoResolutionMatch
public import DraismaVargasCount.ValencyTwoSplit
public import DraismaVargasCount.W2M1kCountBalance
public import DraismaVargasCount.W2M1kIncomingTame
public import DraismaVargasCount.W2M1kMemberBalance
public import DraismaVargasCount.W2M1kRowTransport
public import DraismaVargasCount.W2M1kStarCensusProof
public import DraismaVargasCount.W2M1kStarExhaustionProof
public import DraismaVargasCount.W2M1kTransitionSiting
public import DraismaVargasCount.W2MkkClosure
public import DraismaVargasCount.W2MkkIncomingDenominator
public import DraismaVargasCount.W2MkkMultiplicityBalance
public import DraismaVargasCount.W2MkkStarCensusProof
public import DraismaVargasCount.W2MkkStarExhaustionProof
public import DraismaVargasCount.W2PIncomingDenominator
public import DraismaVargasCount.W2PMultiplicityBalance
public import DraismaVargasCount.W2PStarCensusProof
public import DraismaVargasCount.W2PStarExhaustionProof
public import DraismaVargasCount.W2R1StarCensusProof
public import DraismaVargasCount.W2R1StarExhaustionProof
public import DraismaVargasCount.W2R1UnitBalance
public import DraismaVargasCount.W3FourCountBalance
public import DraismaVargasCount.W3FourIncomingDenominator
public import DraismaVargasCount.W3FourMultiplicityBalance
public import DraismaVargasCount.W3FourReversedDenominator
public import DraismaVargasCount.W3FourStarCensusProof
public import DraismaVargasCount.W3FourStarExhaustionProof
public import DraismaVargasCount.W3Nd2StarCensusProof
public import DraismaVargasCount.W3Nd2StarExhaustionProof
public import DraismaVargasCount.W3Nd2UnitBalance
public import DraismaVargasCount.W3Nd3StarCensusProof
public import DraismaVargasCount.W3Nd3StarExhaustionProof
public import DraismaVargasCount.W3Nd3UnitBalance
public import DraismaVargasCount.W3ShiftIncomingDenominator
public import DraismaVargasCount.W3ShiftMultiplicityBalance
public import DraismaVargasCount.W3ShiftSixMemberBalance
public import DraismaVargasCount.W3ShiftSixMemberMatrices
public import DraismaVargasCount.W3ShiftSixMemberMultiplicity
public import DraismaVargasCount.W3ShiftStarCensusProof
public import DraismaVargasCount.W3ShiftStarExhaustionProof
public import DraismaVargasCount.W4FullDimensionalBalance
public import DraismaVargasCount.W4IncomingIndex
public import DraismaVargasCount.W4IncomingNormalizedPartitions
public import DraismaVargasCount.W4LimitContraction
public import DraismaVargasCount.W4NonDiscreteStarCensus
public import DraismaVargasCount.W4NonDiscreteStarExhaustionProof
public import DraismaVargasCount.W4PairingRigidity
public import DraismaVargasCount.W4StarParity
public import DraismaVargasCount.W4UnitBalance
public import DraismaVargasCount.W4WallExhaustion
public import DraismaVargasCount.WallSwitchingBridge
public import DraismaVargasCount.WitnessAssembly
public import DraismaVargasCount.Highlights

@[expose] public section

/-!
# The genus-six odd-subdivision witness: the Draisma--Vargas count

Every connected finite graph of genus six has a regular subdivision of odd order carrying a
divisor of degree four and rank at least one (`DraismaVargas.Count.genusSix_witness`). The proof is
a mod-2 form of the count of tropical morphisms to trees of J. Draisma and A. Vargas,
*Catalan-many tropical morphisms to trees; Part I: Constructions*, arXiv:1909.12924, and
A. Vargas, *Catalan-many tropical morphisms to trees; Part II: A space and a count*,
arXiv:2609.09109. `DraismaVargasCount.Assembly` states its five steps: the base count over the
caterpillar of loops, the crossing of trivalent walls, the type changes across Whitehead moves,
the propagation of the parity to every cubic core, and the endgame that turns an odd class into a
pencil on an odd regular subdivision.

Much of the machinery (fibres and their multiplicities, wall crossings, star censuses, and the
type-change correspondences) is stated for general degree and core size. The base count over the
caterpillar of loops and the propagation of its parity hold in every even genus at least six
(`BallotEndSwapGeneral`, `EvenGenusParity`): over every connected cubic core of genus `2k + 2`,
`k ≥ 2`, the open odd count in degree `k + 2` has the parity of `catalan (k + 1)`. The endgame is
specific to genus six.

The witness is exactly the hypothesis of `GenusSixOddDescent.bnExists_genus_six_of_oddWitness`;
together they give Brill--Noether existence in genus six. Declarations live in the namespace
`DraismaVargas.Count`.

Add an import line above whenever a module is added under `DraismaVargasCount/`, or
`lake build DraismaVargasCount` will silently skip it.
-/
