import Mathlib

/-!
# Highlights (statement-only audit copy)

This is a statement-only audit copy of the repository's auditable,
reader-facing statement layer. The definitions used in theorem statements are
repeated here in full: they do not alias or invoke the implementation library.
Only the nine advertised headline theorems are left unproved. Short proofs
which certify concrete definitions--for example, the additive laws of the
divisor degree homomorphism--remain part of the statement vocabulary.

The current installments record Brill--Noether existence through genus five,
CDPR and its sharp mixed-chain extensions, the tricycle counterexample to
invariance of divisorial gonality under regular subdivision, and the treewidth
lower bound on divisorial gonality.  Further headline theorems can be added one
at a time in the same style.
-/

namespace Highlights

universe u

open Multiset Finset

/-! ## Self-contained statement vocabulary -/

/-- A finite, nonempty, loopless undirected multigraph.  An undirected edge is
stored by either ordering of its endpoints; `num_edges` below forgets that
ordering. -/
structure CFGraph where
  /-- The finite, nonempty type of vertices. -/
  V : Type u
  [instDecidableEq : DecidableEq V]
  [instFintype : Fintype V]
  [instNonempty : Nonempty V]
  /-- Edge occurrences, each stored once using either endpoint ordering. -/
  edges : Multiset (V × V)
  /-- No edge occurrence has equal endpoints. -/
  loopless : ∀ v, (v, v) ∉ edges

attribute [instance] CFGraph.instDecidableEq CFGraph.instFintype CFGraph.instNonempty

/-- The number of edges between two vertices, counted with multiplicity. -/
def num_edges (G : CFGraph) (v w : G.V) : ℕ :=
  Multiset.card (G.edges.filter (fun e => e = (v, w) ∨ e = (w, v)))

/-- A graph is connected when every nontrivial vertex cut has a crossing
edge. -/
def graph_connected (G : CFGraph) : Prop :=
  ∀ S : Finset G.V, (∃ v w : G.V, v ∈ S ∧ w ∉ S) →
    ∃ v ∈ S, ∃ w ∉ S, num_edges G v w > 0

/-- The genus (cyclomatic number) `|E| - |V| + 1`. -/
def genus (G : CFGraph) : ℤ :=
  Multiset.card G.edges - Fintype.card G.V + 1

/-- The degree (valence) of a vertex. -/
def vertex_degree (G : CFGraph) (v : G.V) : ℤ :=
  ∑ u : G.V, (num_edges G v u : ℤ)

/-- A divisor is an integer-valued function on the vertices. -/
abbrev CFDiv (G : CFGraph) := G.V → ℤ

/-- The principal divisor obtained by firing one vertex once. -/
def firing_vector (G : CFGraph) (v : G.V) : CFDiv G :=
  fun w => if w = v then -vertex_degree G v else num_edges G v w

/-- The subgroup generated by all vertex firings. -/
def principal_divisors (G : CFGraph) : AddSubgroup (CFDiv G) :=
  AddSubgroup.closure (Set.range (firing_vector G))

/-- Two divisors are linearly equivalent when their difference is principal. -/
def linear_equiv (G : CFGraph) (D D' : CFDiv G) : Prop :=
  D' - D ∈ principal_divisors G

/-- A divisor is effective when it has no negative coefficient. -/
def effective {G : CFGraph} (D : CFDiv G) : Prop :=
  ∀ v : G.V, D v ≥ 0

/-- The additive monoid of effective divisors. -/
def Eff (G : CFGraph) : AddSubmonoid (CFDiv G) :=
  { carrier := {D : CFDiv G | effective D}
    zero_mem' := by
      simp only [effective, ge_iff_le, Set.mem_ofPred_eq, Pi.zero_apply,
        Std.le_refl, implies_true]
    add_mem' := by
      intro D₁ D₂ h₁ h₂ v
      exact add_nonneg (h₁ v) (h₂ v) }

/-- A divisor is winnable when it is linearly equivalent to an effective
divisor. -/
def winnable (G : CFGraph) (D : CFDiv G) : Prop :=
  ∃ D' ∈ Eff G, linear_equiv G D D'

/-- The degree of a divisor, i.e. its total number of chips. -/
def deg {G : CFGraph} : CFDiv G →+ ℤ :=
  { toFun := fun D => ∑ v, D v
    map_zero' := by simp only [Pi.zero_apply, sum_const_zero]
    map_add' := by
      intro D₁ D₂
      simp only [Pi.add_apply, sum_add_distrib] }

/-- The effective divisors of a prescribed degree. -/
def eff_of_degree (G : CFGraph) (k : ℤ) : Set (CFDiv G) :=
  {E | effective E ∧ deg E = k}

/-- `rank_geq G D k` means that removing any effective divisor of degree `k`
from `D` leaves a winnable divisor. -/
def rank_geq (G : CFGraph) (D : CFDiv G) (k : ℤ) : Prop :=
  ∀ E ∈ eff_of_degree G k, winnable G (D - E)

/-- `rank_eq G D r` means that the Baker--Norine rank of `D` is exactly `r`. -/
def rank_eq (G : CFGraph) (D : CFDiv G) (r : ℤ) : Prop :=
  rank_geq G D r ∧ ¬rank_geq G D (r + 1)

/-- `gonality_leq G k` means that `G` has a degree-`k` divisor of rank at
least one.  This deliberately states the witness property directly, without
introducing a minimum or an infimum. -/
def gonality_leq (G : CFGraph) (k : ℤ) : Prop :=
  ∃ D : CFDiv G, deg D = k ∧ rank_geq G D 1

/-- `gonality_eq G k` means that degree `k` supports a rank-one divisor and
no smaller degree does.  This witness formulation avoids hiding the statement
behind an infimum. -/
def gonality_eq (G : CFGraph) (k : ℤ) : Prop :=
  gonality_leq G k ∧ ∀ d : ℤ, d < k → ¬ gonality_leq G d

/-! ### Brill--Noether generality and twice-marked graphs -/

/-- The divisor consisting of one chip at `v`. -/
def one_chip {G : CFGraph} (v : G.V) : CFDiv G :=
  fun w => if w = v then 1 else 0

/-- The Brill--Noether number `rho(g,r,d)`. -/
def brill_noether_number (G : CFGraph) (r d : ℤ) : ℤ :=
  genus G - (r + 1) * (genus G - d + r)

/-- Existence of a degree-`d` divisor of rank at least `r`. -/
def brill_noether_exists (G : CFGraph) (r d : ℤ) : Prop :=
  ∃ D : CFDiv G, deg D = d ∧ rank_geq G D r

/-- The nonexistence half of Brill--Noether generality: every divisor that
exists lies in the range predicted by the Brill--Noether number. -/
def brill_noether_general (G : CFGraph) : Prop :=
  ∀ r d : ℤ, 0 ≤ r → brill_noether_exists G r d →
    0 ≤ brill_noether_number G r d

/-- A graph with an ordered left and right marked vertex.  The graph is
packaged existentially so twice-marked graphs with different vertex types can
occur in one list. -/
structure TwiceMarkedGraph where
  /-- The underlying finite multigraph. -/
  graph : CFGraph.{0}
  /-- The left marked vertex. -/
  u : graph.V
  /-- The right marked vertex. -/
  v : graph.V

/-- A harmless one-vertex value, used for an empty chain and for malformed
path-length data. -/
def trivial_twice_marked_graph : TwiceMarkedGraph where
  graph :=
    { V := Fin 1
      edges := 0
      loopless := by simp }
  u := 0
  v := 0

/-- Join two twice-marked graphs by taking their disjoint union and adding one
bridge from the right mark of the first to the left mark of the second.  The
new marks are the two outside marks.

This deliberately uses a bridge rather than identifying the two vertices;
it is the most literal finite-graph presentation of a chain. -/
def bridge_glue (G₁ G₂ : TwiceMarkedGraph) : TwiceMarkedGraph where
  graph :=
    { V := G₁.graph.V ⊕ G₂.graph.V
      edges :=
        (Sum.inl G₁.v, Sum.inr G₂.u) ::ₘ
          (G₁.graph.edges.map (fun e : G₁.graph.V × G₁.graph.V =>
            (Sum.inl e.1, Sum.inl e.2)) +
          G₂.graph.edges.map (fun e : G₂.graph.V × G₂.graph.V =>
            (Sum.inr e.1, Sum.inr e.2)))
      loopless := by
        intro z hz
        simp only [Multiset.mem_cons, Multiset.mem_add] at hz
        rcases hz with hBridge | hFactor
        · cases z <;> simp at hBridge
        · rcases hFactor with hLeft | hRight
          · rw [Multiset.mem_map] at hLeft
            obtain ⟨e, he, hEq⟩ := hLeft
            rcases e with ⟨a, b⟩
            cases z with
            | inl z =>
                simp only [Prod.mk.injEq, Sum.inl.injEq] at hEq
                rcases hEq with ⟨rfl, rfl⟩
                exact G₁.graph.loopless _ he
            | inr z => simp at hEq
          · rw [Multiset.mem_map] at hRight
            obtain ⟨e, he, hEq⟩ := hRight
            rcases e with ⟨a, b⟩
            cases z with
            | inl z => simp at hEq
            | inr z =>
                simp only [Prod.mk.injEq, Sum.inr.injEq] at hEq
                rcases hEq with ⟨rfl, rfl⟩
                exact G₂.graph.loopless _ he }
  u := Sum.inl G₁.u
  v := Sum.inr G₂.v

/-- Glue a list from left to right.  The empty list has the harmless
one-vertex value above. -/
def glue_chain : List TwiceMarkedGraph → TwiceMarkedGraph
  | [] => trivial_twice_marked_graph
  | G :: rest => rest.foldl bridge_glue G

/-- The two complementary arc lengths of a twice-marked cycle. -/
def twiceMarkedCycleLength (m n : ℕ) : Fin 2 → ℕ := ![m, n]

/-- Vertices of the cycle: the two marked endpoints and the disjoint interior
vertices of its top and bottom arcs. -/
abbrev TwiceMarkedCycleVertex (m n : ℕ) :=
  Fin 2 ⊕ (Σ arc : Fin 2, Fin (twiceMarkedCycleLength m n arc - 1))

/-- Unit steps along the two arcs. -/
abbrev TwiceMarkedCycleStep (m n : ℕ) :=
  Σ arc : Fin 2, Fin (twiceMarkedCycleLength m n arc)

/-- Left endpoint of a unit step along a cycle arc. -/
def twiceMarkedCycleStepLeft (m n : ℕ) (step : TwiceMarkedCycleStep m n) :
    TwiceMarkedCycleVertex m n :=
  if hzero : step.2.val = 0 then
    Sum.inl 0
  else
    Sum.inr ⟨step.1, ⟨step.2.val - 1, by
      have hlt := step.2.isLt
      omega⟩⟩

/-- Right endpoint of a unit step along a cycle arc. -/
def twiceMarkedCycleStepRight (m n : ℕ) (step : TwiceMarkedCycleStep m n) :
    TwiceMarkedCycleVertex m n :=
  if hlast : step.2.val + 1 = twiceMarkedCycleLength m n step.1 then
    Sum.inl 1
  else
    Sum.inr ⟨step.1, ⟨step.2.val, by
      have hlt := step.2.isLt
      omega⟩⟩

/-- A cycle marked at the endpoints of two complementary arcs of lengths
`m` and `n`.  If either length is zero, the value is the documented junk
graph `trivial_twice_marked_graph`. -/
def twice_marked_cycle (m n : ℕ) : TwiceMarkedGraph :=
  if hpos : 0 < m ∧ 0 < n then
    { graph :=
        { V := TwiceMarkedCycleVertex m n
          edges := (Finset.univ : Finset (TwiceMarkedCycleStep m n)).val.map
            (fun step =>
              (twiceMarkedCycleStepLeft m n step,
                twiceMarkedCycleStepRight m n step))
          loopless := by
            intro vertex hmem
            simp only [Multiset.mem_map, Finset.mem_val, Finset.mem_univ,
              true_and] at hmem
            obtain ⟨step, hpair⟩ := hmem
            have hne : twiceMarkedCycleStepLeft m n step ≠
                twiceMarkedCycleStepRight m n step := by
              unfold twiceMarkedCycleStepLeft twiceMarkedCycleStepRight
              split_ifs with hzero hlast
              · simp
              · simp
              · simp
              · intro heq
                have hpositions : step.2.val - 1 = step.2.val := by
                  exact congrArg (fun x => x.2.val) (Sum.inr.inj heq)
                omega
            exact hne ((Prod.mk.inj hpair).1.trans (Prod.mk.inj hpair).2.symm) }
      u := Sum.inl 0
      v := Sum.inl 1 }
  else
    trivial_twice_marked_graph

/-- `torsion_gt M n` says that no positive multiple `k ≤ n` of the two
marked points is linearly equivalent.  Equivalently, the order of `[u-v]` in
the Jacobian is greater than `n` (including the infinite-order convention). -/
def torsion_gt (M : TwiceMarkedGraph) (n : ℕ) : Prop :=
  ∀ k : ℕ, 1 ≤ k → k ≤ n →
    ¬linear_equiv M.graph
      ((k : ℤ) • one_chip M.u) ((k : ℤ) • one_chip M.v)

/-- CDPR genericity for integer cycle lengths.  There are at least two loops;
all arc lengths are positive, ruling out the junk branch of
`twice_marked_cycle`; and no two arc lengths have a ratio of positive
numerator-plus-denominator at most `2g-2`, where `g` is the number of cycles. -/
def cdpr_general (lengths : List (ℕ × ℕ)) : Prop :=
  2 ≤ lengths.length ∧
  (∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2) ∧
  ∀ mn ∈ lengths, ∀ p q : ℕ,
    0 < p → 0 < q → p + q ≤ 2 * lengths.length - 2 →
      mn.1 * q ≠ mn.2 * p

/-- The bridge-chain built from a list of pairs of cycle arc lengths. -/
def chain_of_cycles (lengths : List (ℕ × ℕ)) : TwiceMarkedGraph :=
  glue_chain (lengths.map fun mn => twice_marked_cycle mn.1 mn.2)

/-- The three strand lengths, in order. -/
def thetaLength (a b c : ℕ) : Fin 3 → ℕ := ![a, b, c]

/-- Vertices of `Theta a b c`: the top and bottom vertices, together with
three disjoint sets of `a - 1`, `b - 1`, and `c - 1` interior vertices. -/
abbrev ThetaVertex (a b c : ℕ) :=
  Fin 2 ⊕ (Σ strand : Fin 3, Fin (thetaLength a b c strand - 1))

/-- Unit steps along the three strands of `Theta a b c`. -/
abbrev ThetaStep (a b c : ℕ) :=
  Σ strand : Fin 3, Fin (thetaLength a b c strand)

/-- Left endpoint of one unit step along a theta strand. -/
def thetaStepLeft (a b c : ℕ) (step : ThetaStep a b c) :
    ThetaVertex a b c :=
  if hzero : step.2.val = 0 then
    Sum.inl 0
  else
    Sum.inr ⟨step.1, ⟨step.2.val - 1, by
      have hlt := step.2.isLt
      omega⟩⟩

/-- Right endpoint of one unit step along a theta strand. -/
def thetaStepRight (a b c : ℕ) (step : ThetaStep a b c) :
    ThetaVertex a b c :=
  if hlast : step.2.val + 1 = thetaLength a b c step.1 then
    Sum.inl 1
  else
    Sum.inr ⟨step.1, ⟨step.2.val, by
      have hlt := step.2.isLt
      omega⟩⟩

/-- `Theta a b c` is the graph made from three internally disjoint paths of
lengths `a`, `b`, and `c` joining a common top vertex to a common bottom
vertex. -/
def Theta (a b c : ℕ) : CFGraph.{0} where
  V := ThetaVertex a b c
  edges := (Finset.univ : Finset (ThetaStep a b c)).val.map fun step =>
    (thetaStepLeft a b c step, thetaStepRight a b c step)
  loopless := by
    intro vertex hmem
    simp only [Multiset.mem_map, Finset.mem_val, Finset.mem_univ, true_and]
      at hmem
    obtain ⟨step, hpair⟩ := hmem
    have hne : thetaStepLeft a b c step ≠ thetaStepRight a b c step := by
      unfold thetaStepLeft thetaStepRight
      split_ifs with hzero hlast
      · simp
      · simp
      · simp
      · intro heq
        have hpositions : step.2.val - 1 = step.2.val := by
          exact congrArg (fun x => x.2.val) (Sum.inr.inj heq)
        omega
    exact hne ((Prod.mk.inj hpair).1.trans (Prod.mk.inj hpair).2.symm)

/-- `TMTheta a b c u v` marks position `u` on the first (`a`-) strand and
position `v` on the third (`c`-) strand.  Invalid positions receive the same
documented junk value used by `twice_marked_cycle`; `evenlyMarkedK` below
contains the guards used by every theorem. -/
def TMTheta (a b c u v : ℕ) : TwiceMarkedGraph :=
  if hpos : 1 ≤ u ∧ u < a ∧ 1 ≤ v ∧ v < c then
    { graph := Theta a b c
      u := Sum.inr ⟨0, ⟨u - 1, by
        change u - 1 < a - 1
        omega⟩⟩
      v := Sum.inr ⟨2, ⟨v - 1, by
        change v - 1 < c - 1
        omega⟩⟩ }
  else
    trivial_twice_marked_graph

/-- The numerical condition that `TMTheta a b c u v` is evenly marked and
has torsion order exactly `k`.  The equal-ratio condition
`u / a = v / c` is written without division as `u * c = v * a`; exactness of
the order is recorded on both marked strands. -/
def evenlyMarkedK (a b c u v k : ℕ) : Prop :=
  0 < a ∧ 0 < b ∧ 0 < c ∧
  1 ≤ u ∧ u < a ∧ 1 ≤ v ∧ v < c ∧
  u * c = v * a ∧
  a / Nat.gcd u a = k ∧ c / Nat.gcd v c = k

/-- The two kinds of factor admitted in the mixed-chain highlight. -/
inductive CycleThetaFactor where
  | cycle (m n : ℕ)
  | theta (a b c u v k : ℕ)

/-- Forget the readable factor tag and retain its twice-marked graph. -/
def CycleThetaFactor.markedGraph : CycleThetaFactor → TwiceMarkedGraph
  | .cycle m n => twice_marked_cycle m n
  | .theta a b c u v _k => TMTheta a b c u v

/-- The genus contribution of a factor: one for a cycle and two for a theta
graph. -/
def CycleThetaFactor.factorGenus : CycleThetaFactor → ℕ
  | .cycle _ _ => 1
  | .theta _ _ _ _ _ _ => 2

/-- The exact torsion period supplied by the numerical factor data. -/
def CycleThetaFactor.period : CycleThetaFactor → ℕ
  | .cycle m n => (m + n) / Nat.gcd m n
  | .theta _a _b _c _u _v k => k

/-- The total genus contributed by a list of cycle/theta factors. -/
def CycleThetaFactor.totalGenus (factors : List CycleThetaFactor) : ℕ :=
  (factors.map CycleThetaFactor.factorGenus).sum

/-- Corollary 6.16's sharp torsion budget for a mixed chain: the exact period
of a factor exceeds the smaller of the genera accumulated on its two sides,
counting the factor on both sides. -/
def mixed_chain_torsion_budget (factors : List CycleThetaFactor) : Prop :=
  ∀ i : ℕ, ∀ hi : i < factors.length,
    min
        (CycleThetaFactor.totalGenus (factors.take (i + 1)))
        (CycleThetaFactor.totalGenus (factors.drop i)) <
      (factors.get ⟨i, hi⟩).period

/-- The twice-marked bridge-chain represented by mixed readable factors. -/
def chain_of_cycles_and_thetas
    (factors : List CycleThetaFactor) : TwiceMarkedGraph :=
  glue_chain (factors.map CycleThetaFactor.markedGraph)

/-! ### A canonical, reader-facing regular subdivision

Every occurrence of an edge gets its own slot, so parallel edges remain
distinct. In the `n`th regular subdivision that slot is replaced by a path of
`n` unit edges. Its `n - 1` new vertices remember the edge occurrence and
their position along that path. The expressions `n * 1` in the implementation
reduce definitionally to `n`; they make the unit-edge scaling explicit.
-/

/-- A canonical enumeration of the occurrences in the edge multiset.  The
subtype `G.edges` distinguishes repeated copies of the same endpoint pair. -/
noncomputable def subdivisionEdgeEquiv (G : CFGraph) :
    G.edges ≃ Fin G.edges.card := by
  simpa using Fintype.equivFin G.edges

/-- The endpoint pair occupying a canonical edge-occurrence slot. -/
noncomputable def subdivisionEdgeAt (G : CFGraph)
    (edge : Fin G.edges.card) : G.V × G.V :=
  (((subdivisionEdgeEquiv G).symm edge : G.edges) : G.V × G.V)

/-- Vertices in the `n`th regular subdivision: relabelled original vertices,
together with an edge occurrence and an interior position `0, ..., n - 2`.
The harmless relabelling by `Fin` makes the construction canonical. -/
abbrev SubdivisionVertex (G : CFGraph) (n : ℕ) :=
  Fin (Fintype.card G.V) ⊕ (Σ _edge : Fin G.edges.card, Fin (n * 1 - 1))

/-- Unit steps in the subdivided paths. -/
abbrev SubdivisionStep (G : CFGraph) (n : ℕ) :=
  Σ _edge : Fin G.edges.card, Fin (n * 1)

/-- The left endpoint of one unit step in a subdivided edge. -/
noncomputable def subdivisionStepLeft (G : CFGraph) (n : ℕ)
    (edge : Fin G.edges.card) (offset : Fin (n * 1)) : SubdivisionVertex G n :=
  if hzero : offset.val = 0 then
    Sum.inl (Fintype.equivFin G.V (subdivisionEdgeAt G edge).1)
  else
    Sum.inr ⟨edge, ⟨offset.val - 1, by
      have hoffset := offset.isLt
      omega⟩⟩

/-- The right endpoint of one unit step in a subdivided edge. -/
noncomputable def subdivisionStepRight (G : CFGraph) (n : ℕ)
    (edge : Fin G.edges.card) (offset : Fin (n * 1)) : SubdivisionVertex G n :=
  if hlast : offset.val + 1 = n * 1 then
    Sum.inl (Fintype.equivFin G.V (subdivisionEdgeAt G edge).2)
  else
    Sum.inr ⟨edge, ⟨offset.val, by
      have hoffset := offset.isLt
      omega⟩⟩

/-- The `n`th regular subdivision of `G`: every edge occurrence is replaced
by a path of exactly `n` edges. -/
noncomputable def regularSubdivision (G : CFGraph) (n : ℕ) (_hn : 0 < n) :
    CFGraph where
  V := SubdivisionVertex G n
  instNonempty := ⟨Sum.inl ⟨0, Fintype.card_pos⟩⟩
  edges := (Finset.univ : Finset (SubdivisionStep G n)).val.map fun step =>
    (subdivisionStepLeft G n step.1 step.2,
      subdivisionStepRight G n step.1 step.2)
  loopless := by
    intro vertex hmem
    simp only [Multiset.mem_map, Finset.mem_val, Finset.mem_univ, true_and]
      at hmem
    obtain ⟨⟨edge, offset⟩, hstep⟩ := hmem
    simp only [Prod.mk.injEq] at hstep
    have hne : subdivisionStepLeft G n edge offset ≠
        subdivisionStepRight G n edge offset := by
      unfold subdivisionStepLeft subdivisionStepRight
      split_ifs with hzero hlast
      · intro heq
        have hEnds : (subdivisionEdgeAt G edge).1 =
            (subdivisionEdgeAt G edge).2 :=
          (Fintype.equivFin G.V).injective (Sum.inl.inj heq)
        have hMember : subdivisionEdgeAt G edge ∈ G.edges := Multiset.coe_mem
        rcases hEdge : subdivisionEdgeAt G edge with ⟨tail, head⟩
        simp only [hEdge] at hEnds hMember
        subst head
        exact G.loopless tail hMember
      · simp
      · simp
      · intro heq
        have hSigma := Sum.inr.inj heq
        have hOffsets : offset.val - 1 = offset.val := by
          exact congrArg (fun x => x.2.val) hSigma
        omega
    exact hne (hstep.1.trans hstep.2.symm)

/-! ### The minimal tricycle

Number the centre `0`, the three minus vertices `1, 3, 5`, and the three plus
vertices `2, 4, 6`.  There are six centre spokes; two parallel edges join each
minus/plus pair; and three transition edges join each plus vertex to the next
minus vertex around the ring.
-/

/-- The minimal tricycle, displayed directly as its seven vertices and fifteen
edges.  The repeated pairs are the three doubled minus/plus edges. -/
def tricycle : CFGraph where
  V := Fin 7
  edges := Multiset.ofList [
    ((0 : Fin 7), (1 : Fin 7)), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6),
    (1, 2), (1, 2), (3, 4), (3, 4), (5, 6), (5, 6),
    (2, 3), (4, 5), (6, 1)]
  loopless := by decide

/-! ### Tree decompositions and treewidth -/

/-- The simple graph underlying a multigraph: two vertices are adjacent when
at least one edge occurrence joins them.  Parallel edges therefore do not
affect treewidth. -/
def underlyingSimpleGraph (G : CFGraph) : SimpleGraph G.V where
  Adj v w := num_edges G v w > 0
  symm := ⟨fun v w h => by
    change num_edges G v w > 0 at h
    simpa [num_edges, or_comm] using h⟩
  loopless := ⟨fun v h => by
    change num_edges G v v > 0 at h
    unfold num_edges at h
    change (G.edges.filter fun e => e = (v, v) ∨ e = (v, v)).card > 0 at h
    have hempty : G.edges.filter (fun e => e = (v, v) ∨ e = (v, v)) = 0 := by
      apply Multiset.filter_eq_nil.mpr
      intro e he hdiag
      rcases hdiag with hdiag | hdiag <;> subst e <;> exact G.loopless v he
    rw [hempty] at h
    simp at h⟩

/-- A tree decomposition of a simple graph consists of a finite tree and a bag
of graph vertices at each tree node.  Every vertex and edge is covered, and
the bags containing any fixed vertex form a connected subtree. -/
structure TreeDecomposition {V : Type u} (H : SimpleGraph V) where
  /-- Nodes of the decomposition tree. -/
  Node : Type
  [nodeFintype : Fintype Node]
  [nodeDecidableEq : DecidableEq Node]
  /-- The finite decomposition tree. -/
  tree : SimpleGraph Node
  /-- The decomposition graph is connected and acyclic. -/
  isTree : tree.IsTree
  /-- The bag at each tree node. -/
  bag : Node → Finset V
  /-- Every graph vertex occurs in a bag. -/
  cover_vertex : ∀ v : V, ∃ t, v ∈ bag t
  /-- The endpoints of every graph edge occur together in a bag. -/
  cover_edge : ∀ v w : V, H.Adj v w → ∃ t, v ∈ bag t ∧ w ∈ bag t
  /-- The nodes whose bags contain a fixed vertex form a connected subtree. -/
  coherent : ∀ v : V, (tree.induce {t | v ∈ bag t}).Connected

attribute [instance] TreeDecomposition.nodeFintype
  TreeDecomposition.nodeDecidableEq

namespace TreeDecomposition

/-- The width of a tree decomposition: one less than its largest bag size. -/
def width {V : Type u} {H : SimpleGraph V} (D : TreeDecomposition H) : ℕ :=
  (Finset.univ.sup fun t : D.Node => (D.bag t).card) - 1

end TreeDecomposition

/-- Widths realized by tree decompositions of `H`. -/
def treewidthSet {V : Type u} (H : SimpleGraph V) : Set ℕ :=
  {w | ∃ D : TreeDecomposition H, D.width = w}

/-- Treewidth is the least width of a tree decomposition. -/
noncomputable def treewidth {V : Type u} (H : SimpleGraph V) : ℕ :=
  sInf (treewidthSet H)

/-! ## Brill--Noether existence through genus five -/

/-- Every connected finite graph of genus at most five satisfies
Brill--Noether existence. -/
theorem brill_noether_existence_through_five
    (G : CFGraph.{0}) (h_connected : graph_connected G)
    (g r d : ℤ) (h_genus : genus G = g) (h_genus_le_five : g ≤ 5)
    (h_brill_noether : (r + 1) * (g - d + r) ≤ g) :
    ∃ D : CFDiv G, deg D = d ∧ rank_geq G D r := by
  sorry
/-! ## Chains of loops: the CDPR theorem and its sharp extensions -/

/-- **Marked CDPR theorem.**  At the left endpoint of a generic chain of
`g` loops, a degree-`d`, rank-at-least-`r` divisor cannot retain rank zero
after removing `r + rho + 1` chips. -/
theorem cdpr_marked_no_high_multiplicity
    (lengths : List (ℕ × ℕ)) (h_general : cdpr_general lengths)
    (D : CFDiv (chain_of_cycles lengths).graph) (r d : ℤ)
    (h_rank_nonnegative : 0 ≤ r)
    (h_rank_below_genus : r < genus (chain_of_cycles lengths).graph)
    (h_degree : deg D = d) (h_rank : rank_geq _ D r)
    (h_rho : 0 ≤ brill_noether_number (chain_of_cycles lengths).graph r d) :
    ¬rank_geq (chain_of_cycles lengths).graph
      (D - (r + brill_noether_number (chain_of_cycles lengths).graph r d + 1) •
        one_chip (chain_of_cycles lengths).u) 0 := by
  sorry
/-- **CDPR Theorem 1.1(1), discrete form.**  A generic chain of cycles is
Brill--Noether general in the nonexistence sense. -/
theorem cdpr_chain_brill_noether_general
    (lengths : List (ℕ × ℕ)) (h_general : cdpr_general lengths) :
    brill_noether_general (chain_of_cycles lengths).graph := by
  sorry
/-- The sharp cycle-chain form behind CDPR.  Numbering the `g` cycles from
`1` to `g`, the torsion order of cycle `i` need only exceed
`min(i, g + 1 - i)`. -/
theorem cycle_chain_brill_noether_general_of_torsion
    (lengths : List (ℕ × ℕ))
    (h_positive : ∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2)
    (h_torsion : ∀ i : ℕ, ∀ hi : i < lengths.length,
      torsion_gt
        (twice_marked_cycle
          (lengths.get ⟨i, hi⟩).1 (lengths.get ⟨i, hi⟩).2)
        (min (i + 1) (lengths.length - i))) :
    brill_noether_general (chain_of_cycles lengths).graph := by
  sorry
/-- **Mixed cycle/theta chain theorem.**  A chain whose factors are cycles or
evenly marked theta graphs is Brill--Noether general whenever every cycle is
nondegenerate and each factor satisfies the sharp minimum genus/torsion
budget.  This is the existential/unmarked conclusion of Corollary 6.16. -/
theorem cycle_theta_chain_brill_noether_general
    (factors : List CycleThetaFactor)
    (h_cycles_positive : ∀ m n : ℕ,
      CycleThetaFactor.cycle m n ∈ factors → 0 < m ∧ 0 < n)
    (h_thetas_evenly_marked : ∀ a b c u v k : ℕ,
      CycleThetaFactor.theta a b c u v k ∈ factors →
        evenlyMarkedK a b c u v k)
    (h_torsion : mixed_chain_torsion_budget factors) :
    brill_noether_general (chain_of_cycles_and_thetas factors).graph := by
  sorry
/-! ## Exact gonality of common-torsion chains -/

/-- **Exact gonality of a common-torsion cycle/theta chain.**  If every
factor has the same torsion order `k`, then the bridge-chain has gonality
exactly `k` whenever `k` is at most the generic gonality
`floor((g+3)/2)` of its total genus `g`.

The theta factors are allowed because the proof uses the common
`k`-general-transmission package, not a factorwise gonality assertion. -/
theorem cycle_theta_chain_gonality_eq_common_torsion
    (factors : List CycleThetaFactor) (k : ℕ)
    (h_nonempty : factors ≠ [])
    (h_cycles_positive : ∀ m n : ℕ,
      CycleThetaFactor.cycle m n ∈ factors → 0 < m ∧ 0 < n)
    (h_thetas_evenly_marked : ∀ a b c u v period : ℕ,
      CycleThetaFactor.theta a b c u v period ∈ factors →
        evenlyMarkedK a b c u v period)
    (h_common_torsion : ∀ F ∈ factors, F.period = k)
    (h_small : k ≤ (CycleThetaFactor.totalGenus factors + 3) / 2) :
    gonality_eq (chain_of_cycles_and_thetas factors).graph (k : ℤ) := by
  sorry
/-- Every gonality between two and the generic gonality occurs.  More
precisely, for every genus `g` and
`2 ≤ k ≤ floor((g+3)/2) = ceil(g/2)+1`, there is a connected finite graph of
genus `g` and divisorial gonality exactly `k`. -/
theorem exists_graph_of_genus_and_gonality
    (g k : ℕ) (hk : 2 ≤ k) (hkg : k ≤ (g + 3) / 2) :
    ∃ G : CFGraph.{0},
      graph_connected G ∧ genus G = (g : ℤ) ∧ gonality_eq G (k : ℤ) := by
  sorry
/-! ## Divisorial gonality can drop under regular subdivision -/

/-- There is a connected graph with no degree-`k`, rank-one divisor, although
one of its regular subdivisions does have such a divisor.  The witness is the
minimal tricycle, with `k = 5` and subdivision factor `n = 2`.

This is the direction that yields the divisorial/metric gonality gap: the
minimal tricycle has divisorial gonality six, while its second regular
subdivision has divisorial gonality five. -/
theorem gonality_drops_under_regular_subdivision :
    ∃ (G : CFGraph.{0}) (k : ℤ) (n : ℕ) (hn : 0 < n),
      graph_connected G ∧
        gonality_leq (regularSubdivision G n hn) k ∧ ¬gonality_leq G k := by
  sorry
/-! ## Treewidth is at most divisorial gonality -/

/-- **Treewidth is at most divisorial gonality**
(van Dobben de Bruyn--Gijswijt).  In witness form: on a connected graph, any
degree-`k` divisor of rank at least one bounds the treewidth by `k`. -/
theorem treewidth_le_gonality (G : CFGraph.{0})
    (h_connected : graph_connected G) (k : ℕ)
    (h_gonality : gonality_leq G (k : ℤ)) :
    treewidth (underlyingSimpleGraph G) ≤ k := by
  sorry
end Highlights
