module

public import DraismaVargas.LocalCases.W4StablePathCensus

@[expose] public section

/-!
# Finite stable-path assignments for W4

For the four-valent (`w4`) wall, this module generates the occurrence lists
consumed by
`W4StablePathCensus` from a row assignment on old quotient-source edges and a
coherent regrown occurrence choice for every wall block.
-/

namespace DraismaVargas.LocalCases.W4StablePathAssignment

open DraismaVargas.Infrastructure
open DraismaVargas.LocalCases.W4Assembly
open DraismaVargas.LocalCases.GlobalW4
open DraismaVargas.LocalCases.W4SourceClassification
open DraismaVargas.LocalCases.W4StablePathCensus

variable {target : CFGraph} {degree : ℕ} {wall : target.V}
  [DecidableEq target.edges]

/-- A finite assignment of old quotient-source edges and regrown wall-block
edges to stable rows.  Outer `none` in `oldRowOf` means that the old edge is
dangling and does not occur in the stable source. -/
structure PathAssignment (data : GluingDatum target degree) (wall : target.V) where
  oldRowOf : data.SourceEdge → Option (Option target.edges)
  regrown : Fin 3 → WallBlock data wall →
    Option (Option target.edges × Fin degree)
  regrown_block : ∀ pairing sourceBlock row sheet,
    regrown pairing sourceBlock = some (row, sheet) →
    WallBlock.ofSheet data wall sheet = sourceBlock

namespace PathAssignment

/-- Enumerate each old quotient-source edge once in its assigned stable row. -/
noncomputable def oldPath {data : GluingDatum target degree}
    (assignment : PathAssignment data wall)
    (row : Option target.edges) : List data.SourceEdge :=
  (Finset.univ : Finset data.SourceEdge).toList.filterMap fun edge ↦
    if assignment.oldRowOf edge = some row then some edge else none

/-- Enumerate the coherent sheet selected for each regrown wall block in its
assigned row.  Enumerating sheets rather than blocks retains an honest nd3
active representative. -/
noncomputable def newSheets {data : GluingDatum target degree}
    (assignment : PathAssignment data wall)
    (pairing : Fin 3) (row : Option target.edges) : List (Fin degree) :=
  (Finset.univ : Finset (Fin degree)).toList.filterMap fun sheet ↦
    if assignment.regrown pairing (WallBlock.ofSheet data wall sheet) =
        some (row, sheet) then some sheet else none

/-- The occurrence-sensitive path lists generated by the assignment. -/
noncomputable def pathCensus {data : GluingDatum target degree}
    (assignment : PathAssignment data wall) :
    PathCensus data where
  oldPath := assignment.oldPath
  newSheets := assignment.newSheets

private theorem count_filterMap_self
    {α : Type*} [DecidableEq α]
    (items : List α) (keep : α → Prop) [DecidablePred keep]
    (item : α) :
    (items.filterMap fun candidate ↦
      if keep candidate then some candidate else none).count item =
      if keep item then items.count item else 0 := by
  induction items with
  | nil => simp
  | cons head tail ih =>
      by_cases hHead : keep head
      · by_cases hEq : head = item
        · subst head
          simp [hHead, ih]
        · by_cases hItem : keep item
          · simp [hHead, hEq, hItem, ih]
          · simp [hHead, hEq, hItem, ih]
      · by_cases hEq : head = item
        · subst head
          simp only [List.filterMap_cons, ite_eq_right hHead]
          rw [ih, ite_eq_right hHead]
        · by_cases hItem : keep item
          · rw [List.count_cons_of_ne hEq]
            simp [hHead, hItem, ih]
          · simp only [List.filterMap_cons, ite_eq_right hHead]
            rw [ih, ite_eq_right hItem]
            simp [hItem]

/-- An old edge occurs once in its assigned row and nowhere else. -/
theorem oldPath_count {data : GluingDatum target degree}
    (assignment : PathAssignment data wall)
    (row : Option target.edges) (edge : data.SourceEdge) :
    (assignment.oldPath row).count edge =
      if assignment.oldRowOf edge = some row then 1 else 0 := by
  classical
  unfold oldPath
  rw [count_filterMap_self]
  have hCount :
      (Finset.univ : Finset data.SourceEdge).toList.count edge = 1 :=
    List.count_eq_one_of_mem
      (Finset.nodup_toList (Finset.univ : Finset data.SourceEdge)) (by simp)
  by_cases hAssigned : assignment.oldRowOf edge = some row
  · simp [hAssigned, hCount]
  · simp [hAssigned]

/-- A sheet occurs once in a regrown path precisely when its own wall block
selects it in that row. -/
theorem newSheets_count {data : GluingDatum target degree}
    (assignment : PathAssignment data wall)
    (pairing : Fin 3) (row : Option target.edges) (sheet : Fin degree) :
    (assignment.newSheets pairing row).count sheet =
      if assignment.regrown pairing (WallBlock.ofSheet data wall sheet) =
          some (row, sheet) then 1 else 0 := by
  classical
  unfold newSheets
  rw [count_filterMap_self]
  have hCount :
      (Finset.univ : Finset (Fin degree)).toList.count sheet = 1 :=
    List.count_eq_one_of_mem
      (Finset.nodup_toList (Finset.univ : Finset (Fin degree))) (by simp)
  by_cases hSelected :
      assignment.regrown pairing (WallBlock.ofSheet data wall sheet) =
        some (row, sheet)
  · simp [hSelected, hCount]
  · simp [hSelected]

end PathAssignment

/-- Assignment-level source statement for an entirely dangling wall block:
no candidate regrows a stable occurrence there, and every old star occurrence
is omitted from the stable source. -/
structure DanglingBlockMembership
    (data : GluingDatum target degree)
    (star : W4TargetPairings.FourStar target wall)
    (assignment : PathAssignment data wall)
    (sourceBlock : WallBlock data wall) where
  marker : Unit := ()
  regrown_none : ∀ pairing, assignment.regrown pairing sourceBlock = none
  old_none : ∀ edge,
    WallBlock.ofSheet data wall edge.1.2 = sourceBlock →
    some edge.1.1 ∈ canonicalW4OldColumns star →
    assignment.oldRowOf edge = none

namespace DanglingBlockMembership

/-- Finite enumeration turns complete dangling omission into the zero block
census. -/
noncomputable def blockCensus
    {data : GluingDatum target degree}
    {star : W4TargetPairings.FourStar target wall}
    {assignment : PathAssignment data wall}
    {sourceBlock : WallBlock data wall}
    (membership : DanglingBlockMembership data star assignment sourceBlock) :
    DanglingBlockCensus data star assignment.pathCensus sourceBlock where
  new_sheet_count := by
    intro pairing row sheet hBlock
    change (assignment.newSheets pairing row).count sheet = 0
    rw [PathAssignment.newSheets_count, hBlock]
    simp only [ite_eq_right_iff]
    intro hSome
    rw [membership.regrown_none pairing] at hSome
    simp at hSome
  old_path_count := by
    intro row edge hBlock hColumn
    change (assignment.oldPath row).count edge = 0
    rw [PathAssignment.oldPath_count]
    simp only [ite_eq_right_iff]
    intro hSome
    rw [membership.old_none edge hBlock hColumn] at hSome
    simp at hSome

end DanglingBlockMembership

/-- Expected regrown assignment for one nd2 block and pairing. -/
def nd2NewOccurrences {data : GluingDatum target degree}
    (sourceBlock : WallBlock data wall) (block : Nd2Block)
    (newRow : Fin 3 → Option target.edges) (pairing : Fin 3) :
    Multiset (Option target.edges × Fin degree) :=
  if W4TargetPairings.Pairing.labelRight pairing block.first =
      W4TargetPairings.Pairing.labelRight pairing block.second then 0
  else {(newRow pairing, sourceBlock.1)}

/-- The two active old branch occurrences of one nd2 wall block. -/
noncomputable def nd2OldOccurrences (data : GluingDatum target degree)
    (star : W4TargetPairings.FourStar target wall)
    (sourceBlock : WallBlock data wall) (block : Nd2Block)
    (oldRow : Fin 4 → Option target.edges) :
    Multiset (Option target.edges × data.SourceEdge) :=
  {(oldRow block.first,
      data.sourceEdge (star.edge block.first) sourceBlock.1),
    (oldRow block.second,
      data.sourceEdge (star.edge block.second) sourceBlock.1)}

/-- Expected singleton regrowth for one nd3 block and pairing. -/
def nd3NewOccurrences {target : CFGraph} {degree : ℕ} (block : Nd3Block)
    (activeSheet : Fin 4 → Fin degree)
    (newRow : Fin 3 → Option target.edges) (pairing : Fin 3) :
    Multiset (Option target.edges × Fin degree) :=
  {(newRow pairing, activeSheet (block.singletonLabel pairing))}

/-- The three active old branch occurrences of one nd3 wall block. -/
noncomputable def nd3OldOccurrences (data : GluingDatum target degree)
    (star : W4TargetPairings.FourStar target wall) (block : Nd3Block)
    (activeSheet : Fin 4 → Fin degree)
    (oldRow : Fin 4 → Option target.edges) :
    Multiset (Option target.edges × data.SourceEdge) :=
  {(oldRow block.first,
      data.sourceEdge (star.edge block.first) (activeSheet block.first)),
    (oldRow block.second,
      data.sourceEdge (star.edge block.second) (activeSheet block.second)),
    (oldRow block.third,
      data.sourceEdge (star.edge block.third) (activeSheet block.third))}

omit [DecidableEq target.edges] in
/-- Source edges over distinct labelled target occurrences are distinct,
regardless of which sheets select their edge blocks. -/
theorem sourceEdge_ne_of_label_ne
    (data : GluingDatum target degree)
    (star : W4TargetPairings.FourStar target wall)
    {first second : Fin 4} (hne : first ≠ second)
    (firstSheet secondSheet : Fin degree) :
    data.sourceEdge (star.edge first) firstSheet ≠
      data.sourceEdge (star.edge second) secondSheet := by
  intro hEdge
  have hTarget : star.edge first = star.edge second :=
    congrArg (fun edge : data.SourceEdge ↦ edge.1.1) hEdge
  exact hne (star.edge_injective hTarget)

omit [DecidableEq target.edges] in
theorem nd2NewOccurrences_nodup
    {data : GluingDatum target degree}
    (sourceBlock : WallBlock data wall) (block : Nd2Block)
    (newRow : Fin 3 → Option target.edges) (pairing : Fin 3) :
    (nd2NewOccurrences sourceBlock block newRow pairing).Nodup := by
  unfold nd2NewOccurrences
  split_ifs <;> simp

omit [DecidableEq target.edges] in
theorem nd2OldOccurrences_nodup
    (data : GluingDatum target degree)
    (star : W4TargetPairings.FourStar target wall)
    (sourceBlock : WallBlock data wall) (block : Nd2Block)
    (oldRow : Fin 4 → Option target.edges) :
    (nd2OldOccurrences data star sourceBlock block oldRow).Nodup := by
  have hEdge := sourceEdge_ne_of_label_ne data star block.distinct
    sourceBlock.1 sourceBlock.1
  simp [nd2OldOccurrences, hEdge]

omit [DecidableEq target.edges] in
theorem nd3NewOccurrences_nodup
    (block : Nd3Block) (activeSheet : Fin 4 → Fin degree)
    (newRow : Fin 3 → Option target.edges) (pairing : Fin 3) :
    (nd3NewOccurrences block activeSheet newRow pairing).Nodup := by
  simp [nd3NewOccurrences]

omit [DecidableEq target.edges] in
theorem nd3OldOccurrences_nodup
    (data : GluingDatum target degree)
    (star : W4TargetPairings.FourStar target wall) (block : Nd3Block)
    (activeSheet : Fin 4 → Fin degree)
    (oldRow : Fin 4 → Option target.edges) :
    (nd3OldOccurrences data star block activeSheet oldRow).Nodup := by
  have hFirstSecond := sourceEdge_ne_of_label_ne data star block.first_ne_second
    (activeSheet block.first) (activeSheet block.second)
  have hFirstThird := sourceEdge_ne_of_label_ne data star block.first_ne_third
    (activeSheet block.first) (activeSheet block.third)
  have hSecondThird := sourceEdge_ne_of_label_ne data star block.second_ne_third
    (activeSheet block.second) (activeSheet block.third)
  simp [nd3OldOccurrences, hFirstSecond, hFirstThird, hSecondThird]

theorem indicator_eq_count_of_iff
    {α : Type*} [DecidableEq α] {selected : Prop} [Decidable selected]
    {occurrence : α} {occurrences : Multiset α}
    (hNodup : occurrences.Nodup)
    (hSelected : selected ↔ occurrence ∈ occurrences) :
    (if selected then 1 else 0) = occurrences.count occurrence := by
  by_cases h : selected
  · rw [ite_eq_left h]
    exact (Multiset.count_eq_one_of_mem hNodup (hSelected.mp h)).symm
  · rw [ite_eq_right h]
    exact (Multiset.count_eq_zero.mpr fun hMem ↦
      h (hSelected.mpr hMem)).symm

theorem count_nd2NewOccurrences
    {data : GluingDatum target degree}
    (sourceBlock : WallBlock data wall) (block : Nd2Block)
    (newRow : Fin 3 → Option target.edges) (pairing : Fin 3)
    (row : Option target.edges) (sheet : Fin degree) :
    (nd2NewOccurrences sourceBlock block newRow pairing).count (row, sheet) =
      if W4TargetPairings.Pairing.labelRight pairing block.first =
          W4TargetPairings.Pairing.labelRight pairing block.second then 0
      else if row = newRow pairing ∧ sheet = sourceBlock.1 then 1 else 0 := by
  unfold nd2NewOccurrences
  by_cases hSame :
      W4TargetPairings.Pairing.labelRight pairing block.first =
        W4TargetPairings.Pairing.labelRight pairing block.second
  · simp [hSame]
  · rw [ite_eq_right hSame, Multiset.count_singleton]
    by_cases hRow : row = newRow pairing
    · by_cases hSheet : sheet = sourceBlock.1
      · simp [hRow, hSheet]
        exact hSame
      · simp [hRow, hSheet]
    · simp [hRow]

theorem count_nd3NewOccurrences
    (block : Nd3Block) (activeSheet : Fin 4 → Fin degree)
    (newRow : Fin 3 → Option target.edges) (pairing : Fin 3)
    (row : Option target.edges) (sheet : Fin degree) :
    (nd3NewOccurrences block activeSheet newRow pairing).count (row, sheet) =
      if row = newRow pairing ∧
          sheet = activeSheet (block.singletonLabel pairing) then 1 else 0 := by
  unfold nd3NewOccurrences
  rw [Multiset.count_singleton]
  by_cases hRow : row = newRow pairing
  · by_cases hSheet : sheet = activeSheet (block.singletonLabel pairing)
    · simp [hRow, hSheet]
    · simp [hRow, hSheet]
  · simp [hRow]

/-- Source membership classification for one nd2 block, before its paths are
enumerated. -/
structure Nd2BlockMembership
    (data : GluingDatum target degree)
    (star : W4TargetPairings.FourStar target wall)
    (assignment : PathAssignment data wall)
    (sourceBlock : WallBlock data wall) (block : Nd2Block) where
  newRow : Fin 3 → Option target.edges
  oldRow : Fin 4 → Option target.edges
  regrown_mem : ∀ pairing row sheet,
    assignment.regrown pairing sourceBlock = some (row, sheet) ↔
      (row, sheet) ∈ nd2NewOccurrences sourceBlock block newRow pairing
  old_mem : ∀ row edge,
    WallBlock.ofSheet data wall edge.1.2 = sourceBlock →
    some edge.1.1 ∈ canonicalW4OldColumns star →
    (assignment.oldRowOf edge = some row ↔
      (row, edge) ∈ nd2OldOccurrences data star sourceBlock block oldRow)
  new_row : ∀ pairing,
    W4TargetPairings.Pairing.labelRight pairing block.first ≠
      W4TargetPairings.Pairing.labelRight pairing block.second →
    newRow pairing = oldRow block.first
  old_row : oldRow block.first = oldRow block.second

namespace Nd2BlockMembership

/-- Finite enumeration turns nd2 source membership into the pointwise counts
consumed by `W4StablePathCensus`. -/
noncomputable def blockCensus
    {data : GluingDatum target degree}
    {star : W4TargetPairings.FourStar target wall}
    {assignment : PathAssignment data wall}
    {sourceBlock : WallBlock data wall} {block : Nd2Block}
    (membership : Nd2BlockMembership data star assignment sourceBlock block) :
    Nd2BlockCensus data star assignment.pathCensus sourceBlock block where
  newRow := membership.newRow
  oldRow := membership.oldRow
  new_sheet_count := by
    intro pairing row sheet hBlock
    change (assignment.newSheets pairing row).count sheet = _
    rw [PathAssignment.newSheets_count, hBlock]
    calc
      (if assignment.regrown pairing sourceBlock = some (row, sheet) then 1 else 0) =
          (nd2NewOccurrences sourceBlock block membership.newRow pairing).count
            (row, sheet) :=
        indicator_eq_count_of_iff
          (nd2NewOccurrences_nodup sourceBlock block membership.newRow pairing)
          (membership.regrown_mem pairing row sheet)
      _ = _ := count_nd2NewOccurrences sourceBlock block membership.newRow
        pairing row sheet
  old_path_count := by
    intro row edge hBlock hColumn
    change (assignment.oldPath row).count edge = _
    rw [PathAssignment.oldPath_count]
    change (if assignment.oldRowOf edge = some row then 1 else 0) =
      (nd2OldOccurrences data star sourceBlock block membership.oldRow).count
        (row, edge)
    exact indicator_eq_count_of_iff
      (nd2OldOccurrences_nodup data star sourceBlock block membership.oldRow)
      (membership.old_mem row edge hBlock hColumn)
  new_row := membership.new_row
  old_row := membership.old_row

end Nd2BlockMembership

/-- Source membership classification for one nd3 block.  The three active
sheets are explicit representatives of their edge blocks. -/
structure Nd3BlockMembership
    (data : GluingDatum target degree)
    (star : W4TargetPairings.FourStar target wall)
    (assignment : PathAssignment data wall)
    (sourceBlock : WallBlock data wall) (block : Nd3Block) where
  activeSheet : Fin 4 → Fin degree
  active_sheet : ∀ label, label ∈ block.activeLabels →
    (data.vertexPartition wall).Rel sourceBlock.1 (activeSheet label)
  newRow : Fin 3 → Option target.edges
  oldRow : Fin 4 → Option target.edges
  regrown_mem : ∀ pairing row sheet,
    assignment.regrown pairing sourceBlock = some (row, sheet) ↔
      (row, sheet) ∈ nd3NewOccurrences block activeSheet newRow pairing
  old_mem : ∀ row edge,
    WallBlock.ofSheet data wall edge.1.2 = sourceBlock →
    some edge.1.1 ∈ canonicalW4OldColumns star →
    (assignment.oldRowOf edge = some row ↔
      (row, edge) ∈ nd3OldOccurrences data star block activeSheet oldRow)
  new_row : ∀ pairing,
    newRow pairing = oldRow (block.singletonLabel pairing)

namespace Nd3BlockMembership

/-- Finite enumeration turns nd3 source membership into the pointwise counts
consumed by `W4StablePathCensus`. -/
noncomputable def blockCensus
    {data : GluingDatum target degree}
    {star : W4TargetPairings.FourStar target wall}
    {assignment : PathAssignment data wall}
    {sourceBlock : WallBlock data wall} {block : Nd3Block}
    (membership : Nd3BlockMembership data star assignment sourceBlock block) :
    Nd3BlockCensus data star assignment.pathCensus sourceBlock block where
  activeSheet := membership.activeSheet
  active_sheet := membership.active_sheet
  newRow := membership.newRow
  oldRow := membership.oldRow
  new_sheet_count := by
    intro pairing row sheet hBlock
    change (assignment.newSheets pairing row).count sheet = _
    rw [PathAssignment.newSheets_count, hBlock]
    calc
      (if assignment.regrown pairing sourceBlock = some (row, sheet) then 1 else 0) =
          (nd3NewOccurrences block membership.activeSheet membership.newRow pairing).count
            (row, sheet) :=
        indicator_eq_count_of_iff
          (nd3NewOccurrences_nodup block membership.activeSheet membership.newRow
            pairing)
          (membership.regrown_mem pairing row sheet)
      _ = _ := count_nd3NewOccurrences block membership.activeSheet
        membership.newRow pairing row sheet
  old_path_count := by
    intro row edge hBlock hColumn
    change (assignment.oldPath row).count edge = _
    rw [PathAssignment.oldPath_count]
    change (if assignment.oldRowOf edge = some row then 1 else 0) =
      (nd3OldOccurrences data star block membership.activeSheet
        membership.oldRow).count (row, edge)
    exact indicator_eq_count_of_iff
      (nd3OldOccurrences_nodup data star block membership.activeSheet
        membership.oldRow)
      (membership.old_mem row edge hBlock hColumn)
  new_row := membership.new_row

end Nd3BlockMembership

/-- The membership theorem required for a wall block, selected canonically by
its active-label classification. -/
def ExpectedBlockMembership
    (data : GluingDatum target degree)
    (star : W4TargetPairings.FourStar target wall)
    (assignment : PathAssignment data wall)
    (active : ActiveBranchProfile data star)
    (sourceBlock : WallBlock data wall) : Type :=
  match active.classification sourceBlock with
  | .dangling _ =>
      DanglingBlockMembership data star assignment sourceBlock
  | .nd2 block _ => Nd2BlockMembership data star assignment sourceBlock block
  | .nd3 block _ => Nd3BlockMembership data star assignment sourceBlock block

namespace ExpectedBlockMembership

/-- Lower a definitionally selected membership classification to the
definitionally selected pointwise count census. -/
noncomputable def blockCensus
    {data : GluingDatum target degree}
    {star : W4TargetPairings.FourStar target wall}
    {assignment : PathAssignment data wall}
    {active : ActiveBranchProfile data star}
    {sourceBlock : WallBlock data wall}
    (membership :
      ExpectedBlockMembership data star assignment active sourceBlock) :
    ExpectedBlockCensus data star active assignment.pathCensus sourceBlock := by
  cases hClassification : active.classification sourceBlock with
  | dangling hActive =>
      unfold ExpectedBlockMembership at membership
      rw [hClassification] at membership
      unfold ExpectedBlockCensus
      rw [hClassification]
      exact membership.blockCensus
  | nd2 block hActive =>
      unfold ExpectedBlockMembership at membership
      rw [hClassification] at membership
      unfold ExpectedBlockCensus
      rw [hClassification]
      exact membership.blockCensus
  | nd3 block hActive =>
      unfold ExpectedBlockMembership at membership
      rw [hClassification] at membership
      unfold ExpectedBlockCensus
      rw [hClassification]
      exact membership.blockCensus

end ExpectedBlockMembership

/-- A common finite path assignment and the source membership classification
of every wall block. -/
structure FamilyMembership
    (data : GluingDatum target degree)
    (star : W4TargetPairings.FourStar target wall)
    (active : ActiveBranchProfile data star) where
  assignment : PathAssignment data wall
  block : ∀ sourceBlock : WallBlock data wall,
    ExpectedBlockMembership data star assignment active sourceBlock

namespace FamilyMembership

/-- The finite assignment and block membership theorems generate the complete
pointwise count census. -/
noncomputable def familyCensus
    {data : GluingDatum target degree}
    {star : W4TargetPairings.FourStar target wall}
    {active : ActiveBranchProfile data star}
    (membership : FamilyMembership data star active) :
    FamilyCensus data star active where
  paths := membership.assignment.pathCensus
  block := fun sourceBlock ↦ (membership.block sourceBlock).blockCensus

end FamilyMembership

/-- W4 semantic family from a coherent finite stable-row assignment and
block-local source membership classification. -/
noncomputable def presentedFamilyOfStablePathAssignment
    (data : GluingDatum target degree)
    (star : W4TargetPairings.FourStar target wall)
    (hValid : data.Valid)
    (active : ActiveBranchProfile data star)
    (hChangeZero :
      ∑ sourceBlock : WallBlock data wall,
        AuxR0Profile.wallBlockRamification data star sourceBlock = 0)
    (membership : FamilyMembership data star active) :
    BalancedGlobal.PresentedFamily (coordinate := Option target.edges)
      3 data wall :=
  presentedFamilyOfStablePathCensus data star hValid active hChangeZero
    membership.familyCensus

end DraismaVargas.LocalCases.W4StablePathAssignment
