import Utilities.Gluing.SeparatingEdgeCut
import Utilities.Gluing.TwoEdgeConnectedRigidity
import Utilities.Segments.SeamCalculus
import Mathlib.Tactic

/-!
# Degree-one equivalence is generated by separating edges

On a connected graph, a firing script whose principal divisor is `(y)-(x)`
can be peeled one maximum level at a time.  Each peel exposes a unique
separating edge leaving the maximum set.  This is the graph-theoretic input
needed to show that a script normalized across every bridge is constant on
the degree-one divisor classes.
-/

namespace Utilities

open Finset
open Certificate.StrongSeparator

universe u

variable {G : CFGraph.{u}}

/-- The positive endpoint of a nontrivial principal one-chip difference is
never in the maximum level set of its witnessing script. -/
theorem target_not_mem_topSet_of_prin_eq_oneChip_sub
    {sigma : firing_script G} {x y : G.V} (hxy : x ≠ y)
    (hPrincipal : prin G sigma = one_chip y - one_chip x) :
    y ∉ topSet sigma := by
  intro hyTop
  have hAtY : prin G sigma y = 1 := by
    rw [hPrincipal]
    simp [one_chip, hxy.symm]
  have hUpper := prin_le_neg_outdeg_S (H := G) hyTop
  have hNonnegative := outdeg_S_nonneg G (topSet sigma) y
  omega

/-- In a connected graph, the negative endpoint of a principal one-chip
difference lies in the maximum level set of every witnessing script. -/
theorem source_mem_topSet_of_prin_eq_oneChip_sub
    (hConnected : graph_connected G) {sigma : firing_script G} {x y : G.V}
    (hxy : x ≠ y)
    (hPrincipal : prin G sigma = one_chip y - one_chip x) :
    x ∈ topSet sigma := by
  have hyNotTop : y ∉ topSet sigma :=
    target_not_mem_topSet_of_prin_eq_oneChip_sub hxy hPrincipal
  by_contra hxNotTop
  have hZero : ∀ v ∈ topSet sigma, outdeg_S G (topSet sigma) v = 0 := by
    intro v hvTop
    have hvx : v ≠ x := fun h => hxNotTop (h ▸ hvTop)
    have hvy : v ≠ y := fun h => hyNotTop (h ▸ hvTop)
    have hAtV : prin G sigma v = 0 := by
      rw [hPrincipal]
      simp [one_chip, hvx, hvy]
    exact outdeg_S_topSet_eq_zero_of_prin_eq_zero hvTop hAtV
  obtain ⟨v, hvTop⟩ := topSet_nonempty sigma
  obtain ⟨a, haTop, b, hbTop, hab⟩ :=
    hConnected (topSet sigma) ⟨v, y, hvTop, hyNotTop⟩
  have hEdgeLe := edge_le_outdeg_S (G := G) (A := topSet sigma)
    (v := a) (x := b) hbTop
  have hEdgePositive : 0 < (num_edges G a b : ℤ) := by
    exact_mod_cast hab
  rw [hZero a haTop] at hEdgeLe
  omega

/-- The maximum-set peel of a one-chip equivalence exposes a separating edge
at the negative endpoint. -/
theorem exists_separatingEdgeCut_of_prin_eq_oneChip_sub
    (hConnected : graph_connected G) {sigma : firing_script G} {x y : G.V}
    (hxy : x ≠ y)
    (hPrincipal : prin G sigma = one_chip y - one_chip x) :
    ∃ z : G.V, ∃ cut : SeparatingEdgeCut G x z,
      cut.side = topSet sigma := by
  let S : Finset G.V := topSet sigma
  have hxTopRaw : x ∈ topSet sigma :=
    source_mem_topSet_of_prin_eq_oneChip_sub hConnected hxy hPrincipal
  have hxTop : x ∈ S := hxTopRaw
  have hyNotTop : y ∉ S := by
    change y ∉ topSet sigma
    intro hyTop
    have hAtY : prin G sigma y = 1 := by
      rw [hPrincipal]
      simp [one_chip, hxy.symm]
    have hUpper := prin_le_neg_outdeg_S (H := G) hyTop
    have hNonnegative := outdeg_S_nonneg G (topSet sigma) y
    omega
  have hZeroAwayX : ∀ v ∈ S, v ≠ x → outdeg_S G S v = 0 := by
    intro v hvTop hvx
    have hvy : v ≠ y := fun h => hyNotTop (h ▸ hvTop)
    have hAtV : prin G sigma v = 0 := by
      rw [hPrincipal]
      simp [one_chip, hvx, hvy]
    exact outdeg_S_topSet_eq_zero_of_prin_eq_zero hvTop hAtV
  obtain ⟨a, haTop, z, hzTop, haz⟩ :=
    hConnected S ⟨x, y, hxTop, hyNotTop⟩
  have haEq : a = x := by
    by_contra hax
    have hEdgeLe := edge_le_outdeg_S (G := G) (A := S)
      (v := a) (x := z) hzTop
    have hEdgePositive : 0 < (num_edges G a z : ℤ) := by
      exact_mod_cast haz
    rw [hZeroAwayX a haTop hax] at hEdgeLe
    omega
  subst a
  have hAtX : prin G sigma x = -1 := by
    rw [hPrincipal]
    simp [one_chip, hxy]
  have hOutUpper : outdeg_S G S x ≤ 1 := by
    have hUpper := prin_le_neg_outdeg_S (H := G) hxTopRaw
    rw [hAtX] at hUpper
    change -1 ≤ -outdeg_S G S x at hUpper
    omega
  have hEdgeLeOut := edge_le_outdeg_S (G := G) (A := S)
    (v := x) (x := z) hzTop
  have hEdgePositive : 0 < (num_edges G x z : ℤ) := by
    exact_mod_cast haz
  have hOutEq : outdeg_S G S x = 1 := by
    omega
  have hxzOne : num_edges G x z = 1 := by
    exact_mod_cast (show (num_edges G x z : ℤ) = 1 by omega)
  refine ⟨z, {
    side := S
    left_mem := hxTop
    right_not_mem := hzTop
    cross_num_edges := ?_ }, rfl⟩
  intro p q hp hq
  by_cases hpx : p = x
  · subst p
    by_cases hqz : q = z
    · subst q
      simp [hxzOne]
    · have hqMem : q ∈ Finset.univ \ S := by simp [hq]
      have hzMem : z ∈ Finset.univ \ S := by simp [hzTop]
      have hqErase : q ∈ (Finset.univ \ S).erase z := by
        simp [hqMem, hqz]
      have hDecompose := (Finset.univ \ S).sum_erase_add
        (fun w => (num_edges G x w : ℤ)) hzMem
      have hRestNonnegative :
          0 ≤ ∑ w ∈ (Finset.univ \ S).erase z,
            (num_edges G x w : ℤ) :=
        Finset.sum_nonneg fun _ _ => Int.natCast_nonneg _
      have hTotal :
          (∑ w ∈ Finset.univ \ S, (num_edges G x w : ℤ)) = 1 := by
        exact hOutEq
      have hRestZero :
          (∑ w ∈ (Finset.univ \ S).erase z,
            (num_edges G x w : ℤ)) = 0 := by
        have hxzCast : (num_edges G x z : ℤ) = 1 := by exact_mod_cast hxzOne
        omega
      have hEdgeLeRest : (num_edges G x q : ℤ) ≤
          ∑ w ∈ (Finset.univ \ S).erase z,
            (num_edges G x w : ℤ) := by
        exact Finset.single_le_sum
          (fun w _ => Int.natCast_nonneg (num_edges G x w)) hqErase
      have hxqZero : num_edges G x q = 0 := by
        exact_mod_cast (show (num_edges G x q : ℤ) = 0 by omega)
      simp [hqz, hxqZero]
  · have hOutZero := hZeroAwayX p hp hpx
    have hEdgeLe := edge_le_outdeg_S (G := G) (A := S)
      (v := p) (x := q) hq
    have hpqZero : num_edges G p q = 0 := by
      exact_mod_cast (show (num_edges G p q : ℤ) = 0 by
        have hNonnegative : 0 ≤ (num_edges G p q : ℤ) := Int.natCast_nonneg _
        omega)
    simp [hpx, hpqZero]

/-- A script which is normalized across every separating edge is constant on
every degree-one divisor class of a connected graph.  The proof peels the
maximum set of a one-chip-equivalence witness and inducts on its endpoint
height difference. -/
theorem eq_of_chipEquivalent_of_separating_normalized
    (hConnected : graph_connected G) (rho : firing_script G)
    (hNormalized : ∀ {a b : G.V}, (cut : SeparatingEdgeCut G a b) →
      rho a = rho b)
    {x y : G.V} (hEquivalent : linear_equiv G (one_chip x) (one_chip y)) :
    rho x = rho y := by
  unfold linear_equiv at hEquivalent
  obtain ⟨sigma, hSigma⟩ :=
    (principal_iff_eq_prin G (one_chip y - one_chip x)).mp hEquivalent
  have hPrincipal : prin G sigma = one_chip y - one_chip x := hSigma.symm
  let P : ℕ → Prop := fun n =>
    ∀ (a b : G.V) (tau : firing_script G),
      prin G tau = one_chip b - one_chip a →
      (tau a - tau b).toNat = n → rho a = rho b
  have hP : ∀ n, P n := by
    intro n
    induction n using Nat.strong_induction_on with
    | h n ih =>
        intro a b tau hTau hMeasure
        by_cases hab : a = b
        · exact congrArg rho hab
        · have haTop : a ∈ topSet tau :=
            source_mem_topSet_of_prin_eq_oneChip_sub hConnected hab hTau
          have hbNotTop : b ∉ topSet tau :=
            target_not_mem_topSet_of_prin_eq_oneChip_sub hab hTau
          obtain ⟨z, cut, hSide⟩ :=
            exists_separatingEdgeCut_of_prin_eq_oneChip_sub
              hConnected hab hTau
          have haz : rho a = rho z := hNormalized cut
          by_cases hzb : z = b
          · exact haz.trans (congrArg rho hzb)
          · let tau' : firing_script G :=
              tau - indicator_script G cut.side
            have hTau' : prin G tau' = one_chip b - one_chip z := by
              dsimp [tau']
              rw [map_sub, cut.prin_indicator_script, hTau]
              abel
            have hzTop' : z ∈ topSet tau' :=
              source_mem_topSet_of_prin_eq_oneChip_sub hConnected hzb hTau'
            have hbNotTop' : b ∉ topSet tau' :=
              target_not_mem_topSet_of_prin_eq_oneChip_sub hzb hTau'
            have hNewPositive : 0 < tau' z - tau' b := by
              have hlt := lt_of_not_mem_topSet hzTop' hbNotTop'
              omega
            have hzNotTop : z ∉ topSet tau := by
              rw [← hSide]
              exact cut.right_not_mem
            have hOldDrop : tau z < tau a :=
              lt_of_not_mem_topSet haTop hzNotTop
            have hbOutside : b ∉ cut.side := by
              rw [hSide]
              exact hbNotTop
            have hTauZ : tau' z = tau z := by
              simp [tau', indicator_script, cut.right_not_mem]
            have hTauB : tau' b = tau b := by
              simp [tau', indicator_script, hbOutside]
            have hOldPositive : 0 < tau a - tau b := by
              have hlt := lt_of_not_mem_topSet haTop hbNotTop
              omega
            have hSmaller :
                (tau' z - tau' b).toNat < (tau a - tau b).toNat := by
              rw [hTauZ, hTauB]
              omega
            have hRecursive : rho z = rho b :=
              ih _ (by simpa [hMeasure] using hSmaller) z b tau' hTau' rfl
            exact haz.trans hRecursive
  exact hP (sigma x - sigma y).toNat x y sigma hPrincipal rfl

end Utilities
