import DraismaVargasCount.BallotSlopeSeparation
import DraismaVargasCount.SlopeRigidity

/-!
# The core symmetries `SymmetryRealized` actually quantifies over

`CoreDiagRigid` says that two open members of odd multiplicity with the same core
diagonal lie in the same geometric class: over the caterpillar of loops this is the
uniqueness half of `prop-caterpillar-ballot`(2) in Vargas, Part II (arXiv:2609.09109).
The module `SlopeRigidity` reduces it to an equivalence,
`coreDiagRigid_iff : CoreDiagRigid ↔ DatumIsoSupply ∧ SymmetryRealized`.  That module
does not compute the group the second residue quantifies over.

This file studies it.  `SymmetryRealized c y degree` ranges over the
`CoreRelabel.Relabel c c` stabilising an open odd member's core diagonal, so
its size is controlled by `Aut (catCore m)` -- the incidence-preserving
permutation pairs of the caterpillar core.  **At every even genus at least four
the group contains a symmetry that is not the reflection of the spine**, namely
the exchange of the two loops hanging at one end of the spine, and that symmetry
stabilises `BallotSlopes.ballotCoreDiag m s` for **every** slope sequence `s`.
So the residue is *not* confined to palindromic slope sequences, and it is not
vacuous at any member of the ballot family.

## The end swap, in one paragraph

Writing `g = 2m + 2`, the core `FibreCaterpillar.catCore m` is the spine path
`u₁ - p₂ - … - p_{g-1} - u_g` with a stem `p_i u_i` for `2 ≤ i ≤ g-1` and a
self-loop at every `u_i`.  For `m ≥ 1` the spine end `p₂` therefore carries
*two* loop neighbours: `u₁`, reached by the spine edge, and `u₂`, reached by the
stem.  Nothing in the core distinguishes them, so exchanging `u₁ ↔ u₂` together
with their loops and their two edges to `p₂` is an automorphism.  In the
indexing of `catCore (m+1)` that is the slot permutation `(0 3)(1 2)` and the
vertex permutation `(0 2)`, supported on four slots and two vertices.  Slots `0`
and `3` are leaf edges, so both carry the diagonal value `2`; slot `1` is the
first spine edge, carrying `1 / s₁`, and slot `2` is the first stem, carrying
`1 / 2` -- and `Slopes.slope_one` says `s₁ = 2` for *every* slope sequence.  The
two values therefore always agree and the diagonal is always stabilised.

## What is proved

* `Realizes.congr`, `symmetryRealized_of_stabiliser_trivial`,
  `vtx_eq_of_slot_eq_id` -- the generic form of the observation that a trivial
  diagonal stabiliser makes `SymmetryRealized` vacuous, **together with the
  vertex half it needs**: the stabilising condition constrains the slot
  permutation only, so `d.vtx = id` has to be deduced, and it can be deduced
  exactly when distinct core vertices have distinct incidence rows.
* `endSwap` -- **the end swap**, a `Relabel (catCore (m+1)) (catCore (m+1))`
  for every `m`, with `endSwap_slot_zero`, `endSwap_ne_refl` and
  `endSwap_slot_of_four_le` (it fixes every slot of index at least four, so it
  is supported at one end of the spine and is in particular not a reversal).
* `endSwap_stabilises`, `endSwap_stabilises_catDiag`,
  `endSwap_stabilises_ballotCoreDiag` -- it stabilises the caterpillar
  diagonal, and the ballot diagonal of **every** slope sequence.
* `caterpillarEndTwist` and its receipts -- a *second* open member of odd
  multiplicity with exactly the caterpillar's core diagonal, distinct from it
  at any request with `request 0 ≠ request 3`, in particular at a generic one
  (`generic_witness`).
* `realizes_endSwap_of_symmetryRealized`, `realizes_endSwap_of_coreDiagRigid`,
  `not_coreDiagRigid_of_not_realizes_endSwap` -- the consequence and its
  contrapositive.

## What is NOT proved (every hypothesis, explicitly)

* **No `Realizes` is established here.**  This file enlarges and pins down the
  obligation; it discharges none of it.  The end swap is realised by the
  caterpillar member in `EndSwapRealized` (`realizes_endSwap`).
* **`Aut (catCore m)` is not computed.**  For `m ≥ 1` this file
  exhibits one non-identity element (`endSwap`) and proves it stabilises every
  ballot diagonal; it does **not** prove that the automorphism group is
  generated by the end swaps and a reversal, and it does not construct the
  reversal (that is `SpineReversal.spineReversal`).  What is proved here is a
  lower bound on the obligation, not a reduction of it.
* **The second end swap is not built here.**  The same argument applies verbatim at
  the far end of the spine (slots `6m+8, 6m+7, 6m+5, 6m+6` at `catCore (m+1)`);
  that swap is `BallotFarEndSwap.farSwap`.
* `endSwap_stabilises_ballotCoreDiag` is a statement about the function
  `ballotCoreDiag (m+1) s`; it does **not** assert that a member with that core
  diagonal exists.  Existence of the ballot members (`BallotCoreIdentification`) is
  not touched here.
* Nothing here bears on `DatumIsoSupply`, on the count, or on parity.
-/

namespace DraismaVargas.Count.SlopeRigidity

open DraismaVargas.Count
open DraismaVargas.Count.CoreRelabel
open DraismaVargas.Count.FibreCaterpillar
open DraismaVargas.Infrastructure.CaterpillarTree (parentIndex)
open DraismaVargas.LocalCases
open DraismaVargas.LocalCases.CaterpillarDatum (IsPairEdge)
open DraismaVargas.LocalCases.CaterpillarPruning (IsLeafEdge)
open Utilities.Certificate.ExplicitPotential (Core)

/-! ## 1.  What a trivial diagonal stabiliser would buy, and what it needs -/

variable {n p degree : ℕ} {c : Core n p} {y : Fin p → ℚ}

/-- `Realizes` sees a relabelling only through its two components, so it
transports along a pointwise equality of them. -/
theorem Realizes.congr {d d' : Relabel c c} {m : FibreMember c y degree}
    (hslot : ∀ e, d.slot e = d'.slot e) (hvtx : ∀ v, d.vtx v = d'.vtx v)
    (h : Realizes d m) : Realizes d' m := by
  obtain ⟨a, hv, hs⟩ := h
  exact ⟨a, fun b ↦ (hvtx _).symm.trans (hv b), fun path ↦ (hslot _).symm.trans (hs path)⟩

/-- **A trivial diagonal stabiliser makes residue (B) vacuous.**  If every core
symmetry stabilising an open odd member's core diagonal is the identity on both
components, `SymmetryRealized` holds with nothing to construct. -/
theorem symmetryRealized_of_stabiliser_trivial
    (h : ∀ m : FibreMember c y degree, m.Open → m.HasOddMult →
      ∀ d : Relabel c c, (∀ slot, m.coreDiag (d.slot.symm slot) = m.coreDiag slot) →
        (∀ e, d.slot e = e) ∧ (∀ v, d.vtx v = v)) :
    SymmetryRealized c y degree := by
  intro m hOpen hOdd d hstab
  obtain ⟨hs, hv⟩ := h m hOpen hOdd d hstab
  exact realizes_of_trivial hs hv m

/-- **The vertex half of the previous lemma's hypothesis is not automatic.**
The stabilising condition in `SymmetryRealized` constrains `d.slot` only, so a
"trivial stabiliser" argument has to rule out a nontrivial `d.vtx` over the
identity slot permutation as well.  It can, exactly when distinct core vertices
have distinct incidence rows. -/
theorem vtx_eq_of_slot_eq_id {d : Relabel c c}
    (hsep : ∀ v w : Fin n, (∀ e, coreIncidence c v e = coreIncidence c w e) → v = w)
    (hslot : ∀ e, d.slot e = e) (v : Fin n) : d.vtx v = v := by
  refine hsep _ _ fun e ↦ ?_
  have hinc := d.incidence v e
  rwa [hslot e] at hinc

/-! ## 3.  The core, read through its indices -/

theorem catCore_tail_val (M : ℕ) (e : Fin (6 * M + 3)) :
    ((catCore M).tail e).val = branchIdx (catTailVal M e) := rfl

theorem catCore_head_val (M : ℕ) (e : Fin (6 * M + 3)) :
    ((catCore M).head e).val = branchIdx (catHeadVal M e) := rfl

/-- The incidence multiplicity, as arithmetic in the raw indices. -/
theorem coreIncidence_catCore_val (M : ℕ) (v : Fin (4 * M + 2)) (e : Fin (6 * M + 3)) :
    coreIncidence (catCore M) v e =
      (if branchIdx (catTailVal M e) = v.val then 1 else 0) +
        (if branchIdx (catHeadVal M e) = v.val then 1 else 0) := by
  unfold coreIncidence
  simp only [Fin.ext_iff, catCore_tail_val, catCore_head_val]

/-- **The four slots at the near end of the spine.**  Slot `0` is the loop at
`u₁`, slot `1` the spine edge `u₁ p₂`, slot `2` the stem `p₂ u₂` and slot `3`
the loop at `u₂`; the core vertices are `u₁ = 0`, `p₂ = 1`, `u₂ = 2`. -/
theorem coreIncidence_near (m : ℕ) (v : Fin (4 * (m + 1) + 2)) (e : Fin (6 * (m + 1) + 3))
    (he : e.val ≤ 3) :
    coreIncidence (catCore (m + 1)) v e =
      (if e.val = 0 then (if v.val = 0 then 2 else 0)
        else if e.val = 1 then (if v.val = 0 then 1 else 0) + (if v.val = 1 then 1 else 0)
        else if e.val = 2 then (if v.val = 1 then 1 else 0) + (if v.val = 2 then 1 else 0)
        else (if v.val = 2 then 2 else 0)) := by
  rw [coreIncidence_catCore_val]
  unfold catTailVal catHeadVal branchIdx parentIndex IsLeafEdge
  have hlt := e.isLt
  split_ifs <;> omega

/-- **The two swapped vertices meet no other slot.**  Away from the first four
slots, neither `u₁` nor `u₂` is incident. -/
theorem coreIncidence_far (m : ℕ) (v : Fin (4 * (m + 1) + 2)) (e : Fin (6 * (m + 1) + 3))
    (he : 4 ≤ e.val) (hv : v.val = 0 ∨ v.val = 2) :
    coreIncidence (catCore (m + 1)) v e = 0 := by
  rw [coreIncidence_catCore_val]
  unfold catTailVal catHeadVal branchIdx parentIndex IsLeafEdge
  have hlt := e.isLt
  split_ifs <;> omega

/-! ## 4.  The end swap -/

/-- The slot component of the end swap: `(0 3)(1 2)`. -/
def endSwapSlotFun (m : ℕ) (e : Fin (6 * (m + 1) + 3)) : Fin (6 * (m + 1) + 3) :=
  if e.val = 0 then ⟨3, by omega⟩
  else if e.val = 1 then ⟨2, by omega⟩
  else if e.val = 2 then ⟨1, by omega⟩
  else if e.val = 3 then ⟨0, by omega⟩
  else e

theorem endSwapSlotFun_val (m : ℕ) (e : Fin (6 * (m + 1) + 3)) :
    (endSwapSlotFun m e).val =
      if e.val = 0 then 3 else if e.val = 1 then 2 else if e.val = 2 then 1
        else if e.val = 3 then 0 else e.val := by
  unfold endSwapSlotFun
  split_ifs <;> rfl

theorem endSwapSlotFun_involutive (m : ℕ) : Function.Involutive (endSwapSlotFun m) := by
  intro e
  apply Fin.ext
  rw [endSwapSlotFun_val, endSwapSlotFun_val]
  split_ifs <;> first | contradiction | omega

/-- The vertex component of the end swap: `(0 2)`. -/
def endSwapVtxFun (m : ℕ) (v : Fin (4 * (m + 1) + 2)) : Fin (4 * (m + 1) + 2) :=
  if v.val = 0 then ⟨2, by omega⟩ else if v.val = 2 then ⟨0, by omega⟩ else v

theorem endSwapVtxFun_val (m : ℕ) (v : Fin (4 * (m + 1) + 2)) :
    (endSwapVtxFun m v).val = if v.val = 0 then 2 else if v.val = 2 then 0 else v.val := by
  unfold endSwapVtxFun
  split_ifs <;> rfl

theorem endSwapVtxFun_involutive (m : ℕ) : Function.Involutive (endSwapVtxFun m) := by
  intro v
  apply Fin.ext
  rw [endSwapVtxFun_val, endSwapVtxFun_val]
  split_ifs <;> first | contradiction | omega

theorem endSwap_incidence (m : ℕ) (v : Fin (4 * (m + 1) + 2)) (e : Fin (6 * (m + 1) + 3)) :
    coreIncidence (catCore (m + 1)) (endSwapVtxFun m v) (endSwapSlotFun m e) =
      coreIncidence (catCore (m + 1)) v e := by
  have hlt := e.isLt
  rcases (show e.val ≤ 3 ∨ 4 ≤ e.val by omega) with hsmall | hbig
  · have hswap : (endSwapSlotFun m e).val ≤ 3 := by
      rw [endSwapSlotFun_val]; split_ifs <;> omega
    rw [coreIncidence_near _ _ _ hswap, coreIncidence_near _ _ _ hsmall,
      endSwapSlotFun_val, endSwapVtxFun_val]
    split_ifs <;> first | contradiction | omega
  · have hfix : endSwapSlotFun m e = e := by
      apply Fin.ext
      rw [endSwapSlotFun_val]
      split_ifs <;> omega
    rw [hfix]
    rcases (show v.val = 0 ∨ v.val = 2 ∨ (v.val ≠ 0 ∧ v.val ≠ 2) by omega) with h | h | h
    · rw [coreIncidence_far _ _ _ hbig (Or.inl h),
        coreIncidence_far _ _ _ hbig (by rw [endSwapVtxFun_val, if_pos h]; exact Or.inr rfl)]
    · rw [coreIncidence_far _ _ _ hbig (Or.inr h),
        coreIncidence_far _ _ _ hbig
          (by rw [endSwapVtxFun_val, if_neg (by omega), if_pos h]; exact Or.inl rfl)]
    · have : endSwapVtxFun m v = v := by
        apply Fin.ext
        rw [endSwapVtxFun_val, if_neg h.1, if_neg h.2]
      rw [this]

/-- **The end swap of the caterpillar core**, for every even genus at least
four: the exchange of the two loops hanging at the near end of the spine,
together with their two edges to the end spine vertex `p₂`. -/
def endSwap (m : ℕ) : Relabel (catCore (m + 1)) (catCore (m + 1)) where
  slot := (endSwapSlotFun_involutive m).toPerm _
  vtx := (endSwapVtxFun_involutive m).toPerm _
  incidence := endSwap_incidence m

@[simp] theorem endSwap_slot_apply (m : ℕ) (e : Fin (6 * (m + 1) + 3)) :
    (endSwap m).slot e = endSwapSlotFun m e := rfl

@[simp] theorem endSwap_slot_symm_apply (m : ℕ) (e : Fin (6 * (m + 1) + 3)) :
    (endSwap m).slot.symm e = endSwapSlotFun m e := rfl

@[simp] theorem endSwap_vtx_apply (m : ℕ) (v : Fin (4 * (m + 1) + 2)) :
    (endSwap m).vtx v = endSwapVtxFun m v := rfl

theorem endSwap_slot_zero (m : ℕ) :
    (endSwap m).slot ⟨0, by omega⟩ = ⟨3, by omega⟩ := rfl

/-- **The end swap is not the identity relabelling.** -/
theorem endSwap_ne_refl (m : ℕ) : ¬ ∀ e, (endSwap m).slot e = e := by
  intro h
  have h0 := congrArg Fin.val (h ⟨0, by omega⟩)
  rw [endSwap_slot_apply, endSwapSlotFun_val] at h0
  simp at h0

/-- **The end swap is supported at one end of the spine**: it fixes every slot
of index at least four.  In particular it fixes the far leaf edge `6m+8` while
moving the near one, so it is not a reversal of the spine, and it is not the
genus-two reflection in any disguise. -/
theorem endSwap_slot_of_four_le (m : ℕ) (e : Fin (6 * (m + 1) + 3)) (he : 4 ≤ e.val) :
    (endSwap m).slot e = e := by
  apply Fin.ext
  rw [endSwap_slot_apply, endSwapSlotFun_val]
  split_ifs <;> omega

/-! ## 5.  What the end swap stabilises -/

/-- **The stabilisation criterion.**  A rational function of the core slots is
`endSwap`-invariant as soon as it agrees on the two loops and on the two edges
they use. -/
theorem endSwap_stabilises {m : ℕ} {d : Fin (6 * (m + 1) + 3) → ℚ}
    (h03 : d ⟨0, by omega⟩ = d ⟨3, by omega⟩)
    (h12 : d ⟨1, by omega⟩ = d ⟨2, by omega⟩) (slot : Fin (6 * (m + 1) + 3)) :
    d ((endSwap m).slot.symm slot) = d slot := by
  rw [endSwap_slot_symm_apply]
  unfold endSwapSlotFun
  split_ifs with h0 h1 h2 h3
  · rw [show slot = ⟨0, by omega⟩ from Fin.ext h0]; exact h03.symm
  · rw [show slot = ⟨1, by omega⟩ from Fin.ext h1]; exact h12.symm
  · rw [show slot = ⟨2, by omega⟩ from Fin.ext h2]; exact h12
  · rw [show slot = ⟨3, by omega⟩ from Fin.ext h3]; exact h03
  · rfl

/-- Both loops at the near end of the spine carry diagonal value `2`. -/
theorem catDiag_of_near_loop (m : ℕ) (slot : Fin (6 * (m + 1) + 3))
    (h : slot.val = 0 ∨ slot.val = 3) : catDiag (m + 1) slot = 2 := by
  rw [catDiag_eq, if_pos (show IsLeafEdge (m + 1) slot from Or.inl (by omega))]

/-- The spine edge `u₁ p₂` and the stem `p₂ u₂` are both pair edges, so both
carry diagonal value `1 / 2`. -/
theorem catDiag_of_near_pair (m : ℕ) (slot : Fin (6 * (m + 1) + 3))
    (h : slot.val = 1 ∨ slot.val = 2) : catDiag (m + 1) slot = 1 / 2 := by
  rw [catDiag_eq, if_neg (show ¬ IsLeafEdge (m + 1) slot by rintro (hx | hx) <;> omega),
    if_pos (show IsPairEdge (m + 1) slot.val by
      rcases h with hx | hx
      · exact Or.inl (by omega)
      · exact Or.inr ⟨by omega, by omega⟩)]

/-- **The end swap stabilises the caterpillar diagonal**, at every even genus at
least four. -/
theorem endSwap_stabilises_catDiag (m : ℕ) (slot : Fin (6 * (m + 1) + 3)) :
    catDiag (m + 1) ((endSwap m).slot.symm slot) = catDiag (m + 1) slot :=
  endSwap_stabilises
    (by rw [catDiag_of_near_loop m _ (Or.inl rfl), catDiag_of_near_loop m _ (Or.inr rfl)])
    (by rw [catDiag_of_near_pair m _ (Or.inl rfl), catDiag_of_near_pair m _ (Or.inr rfl)])
    slot

/-! ### The same, for the ballot diagonal of an arbitrary slope sequence -/

section Ballot

variable {m : ℕ}

theorem ballotCoreDiag_of_near_loop (s : Slopes (2 * (m + 1 + 1)))
    (slot : Fin (6 * (m + 1) + 3)) (h : slot.val = 0 ∨ slot.val = 3) :
    BallotSlopes.ballotCoreDiag (m + 1) s slot = 2 :=
  BallotSlopes.ballotCoreDiag_leaf s (Or.inl (by omega))

/-- The first spine edge reads `1 / s₁`, and `s₁ = 2` for every slope
sequence. -/
theorem ballotCoreDiag_of_spine_one (s : Slopes (2 * (m + 1 + 1)))
    (slot : Fin (6 * (m + 1) + 3)) (h : slot.val = 1) :
    BallotSlopes.ballotCoreDiag (m + 1) s slot = 1 / 2 := by
  rw [BallotSlopes.ballotCoreDiag_spine s (show slot.val % 3 = 1 by omega),
    show (slot.val + 2) / 3 = 1 by omega, Slopes.slope_one]
  norm_num

theorem ballotCoreDiag_of_stem_one (s : Slopes (2 * (m + 1 + 1)))
    (slot : Fin (6 * (m + 1) + 3)) (h : slot.val = 2) :
    BallotSlopes.ballotCoreDiag (m + 1) s slot = 1 / 2 :=
  BallotSlopes.ballotCoreDiag_stem s (by omega) (by omega)

/-- **The end swap stabilises the ballot diagonal of *every* slope sequence.**
The two loops both read `2`; the first spine edge reads `1 / s₁` and the first
stem reads `1 / 2`, and `Slopes.slope_one` makes `s₁ = 2` a field of `Slopes`.
So neither genericity of the request nor any palindromy condition on the slope
sequence removes this symmetry from the stabiliser of the core diagonal. -/
theorem endSwap_stabilises_ballotCoreDiag (s : Slopes (2 * (m + 1 + 1)))
    (slot : Fin (6 * (m + 1) + 3)) :
    BallotSlopes.ballotCoreDiag (m + 1) s ((endSwap m).slot.symm slot) =
      BallotSlopes.ballotCoreDiag (m + 1) s slot :=
  endSwap_stabilises
    (by rw [ballotCoreDiag_of_near_loop s _ (Or.inl rfl),
      ballotCoreDiag_of_near_loop s _ (Or.inr rfl)])
    (by rw [ballotCoreDiag_of_spine_one s _ rfl, ballotCoreDiag_of_stem_one s _ rfl])
    slot

end Ballot

/-! ## 6.  The genus `≥ 4` twin of the caterpillar member -/

section Twin

variable (m : ℕ) {request : Fin (6 * (m + 1) + 3) → ℚ}

theorem coreDiag_stable_under_endSwap (slot : Fin (6 * (m + 1) + 3)) :
    (caterpillarMember (m + 1) request).coreDiag ((endSwap m).slot.symm slot) =
      (caterpillarMember (m + 1) request).coreDiag slot := by
  rw [coreDiag_caterpillarMember]
  exact endSwap_stabilises_catDiag m slot

/-- **The twist of the caterpillar member along the end swap**, at every even
genus at least four. -/
noncomputable def caterpillarEndTwist (request : Fin (6 * (m + 1) + 3) → ℚ) :
    FibreMember (catCore (m + 1)) request (m + 1 + 2) :=
  twistMember (endSwap m) (caterpillarMember (m + 1) request)
    (diagonal_caterpillarMember (m + 1) request)

theorem caterpillarEndTwist_open (hRequest : ∀ slot, 0 < request slot) :
    (caterpillarEndTwist m request).Open :=
  twistMember_open (endSwap m) (caterpillarMember (m + 1) request)
    (diagonal_caterpillarMember (m + 1) request) (coreDiag_stable_under_endSwap m)
    (caterpillarMember_open hRequest)

theorem caterpillarEndTwist_hasOddMult : (caterpillarEndTwist m request).HasOddMult :=
  (twistMember_hasOddMult (endSwap m) (caterpillarMember (m + 1) request)
      (diagonal_caterpillarMember (m + 1) request)).mpr
    (caterpillarMember_hasOddMult (m + 1) request)

theorem caterpillarEndTwist_diagonal : (caterpillarEndTwist m request).Diagonal :=
  twistMember_diagonal (endSwap m) (caterpillarMember (m + 1) request)
    (diagonal_caterpillarMember (m + 1) request)

/-- **It has exactly the caterpillar's core diagonal.** -/
theorem caterpillarEndTwist_coreDiag :
    (caterpillarEndTwist m request).coreDiag = (caterpillarMember (m + 1) request).coreDiag := by
  funext slot
  rw [caterpillarEndTwist,
    twistMember_coreDiag (endSwap m) (caterpillarMember (m + 1) request)
      (diagonal_caterpillarMember (m + 1) request) slot,
    coreDiag_stable_under_endSwap]

/-- **It is a different member**, as soon as the loop at `u₁` and the loop at
`u₂` are requested different lengths -- in particular at a generic request. -/
theorem caterpillarEndTwist_coords_ne
    (hne : request ⟨0, by omega⟩ ≠ request ⟨3, by omega⟩) :
    (caterpillarEndTwist m request).coords ≠ (caterpillarMember (m + 1) request).coords := by
  intro hEq
  have h0 := congrFun hEq ⟨0, by omega⟩
  rw [caterpillarMember_coords, catCoords] at h0
  have hslot : (caterpillarEndTwist m request).coords ⟨0, by omega⟩ =
      request ⟨3, by omega⟩ / catDiag (m + 1) ⟨0, by omega⟩ := by
    show request ((endSwap m).slot ((caterpillarMember (m + 1) request).slotMap ⟨0, by omega⟩)) /
      (caterpillarMember (m + 1) request).matrix ⟨0, by omega⟩ ⟨0, by omega⟩ = _
    rw [slotMap_caterpillarMember, endSwap_slot_zero]
    rfl
  have hc : catDiag (m + 1) (⟨0, by omega⟩ : Fin (6 * (m + 1) + 3)) ≠ 0 := catDiag_ne_zero _ _
  rw [hslot, div_eq_div_iff hc hc] at h0
  exact hne (mul_right_cancel₀ hc h0).symm

theorem caterpillarEndTwist_ne (hne : request ⟨0, by omega⟩ ≠ request ⟨3, by omega⟩) :
    caterpillarEndTwist m request ≠ caterpillarMember (m + 1) request :=
  fun h ↦ caterpillarEndTwist_coords_ne m hne (by rw [h])

/-- **Two distinct open odd members with the same core diagonal, at every even
genus at least four, even at a generic request.**  This shows that residue (B)
of `coreDiagRigid_iff` is non-vacuous above genus two for a reason that has
nothing to do with the reflection of the spine. -/
theorem generic_witness (hRequest : ∀ slot, 0 < request slot)
    (hinj : Function.Injective request) :
    (caterpillarEndTwist m request).Open ∧ (caterpillarEndTwist m request).HasOddMult ∧
      (caterpillarEndTwist m request).coreDiag = (caterpillarMember (m + 1) request).coreDiag ∧
      caterpillarEndTwist m request ≠ caterpillarMember (m + 1) request :=
  ⟨caterpillarEndTwist_open m hRequest, caterpillarEndTwist_hasOddMult m,
    caterpillarEndTwist_coreDiag m,
    caterpillarEndTwist_ne m fun h ↦
      absurd (congrArg Fin.val (hinj h)) (show ¬((0 : ℕ) = 3) by omega)⟩

/-! ## 7.  What that forces -/

/-- **Residue (B) is not vacuous at any even genus at least four.**
`SymmetryRealized` over a positive request entails that the caterpillar gluing
datum admits a self-isomorphism inducing the end swap -- and the end swap is not
the identity (`endSwap_ne_refl`).  No hypothesis on the slope sequence, and no
genericity of the request, is available to avoid this. -/
theorem realizes_endSwap_of_symmetryRealized (hRequest : ∀ slot, 0 < request slot)
    (h : SymmetryRealized (catCore (m + 1)) request (m + 1 + 2)) :
    Realizes (endSwap m) (caterpillarMember (m + 1) request) :=
  h (caterpillarMember (m + 1) request) (caterpillarMember_open hRequest)
    (caterpillarMember_hasOddMult (m + 1) request) (endSwap m)
    (coreDiag_stable_under_endSwap m)

/-- The same, read off `rigid` itself. -/
theorem realizes_endSwap_of_coreDiagRigid (hRequest : ∀ slot, 0 < request slot)
    (hrigid : CoreDiagRigid (catCore (m + 1)) request (m + 1 + 2)) :
    Realizes (endSwap m) (caterpillarMember (m + 1) request) :=
  realizes_of_coreDiagRigid hrigid (caterpillarMember (m + 1) request)
    (caterpillarMember_open hRequest) (caterpillarMember_hasOddMult (m + 1) request)
    (diagonal_caterpillarMember (m + 1) request) (endSwap m)
    (coreDiag_stable_under_endSwap m)

/-- **The contrapositive**, which is the shape a refutation would take above
genus two. -/
theorem not_coreDiagRigid_of_not_realizes_endSwap (hRequest : ∀ slot, 0 < request slot)
    (hno : ¬ Realizes (endSwap m) (caterpillarMember (m + 1) request)) :
    ¬ CoreDiagRigid (catCore (m + 1)) request (m + 1 + 2) :=
  fun hrigid ↦ hno (realizes_endSwap_of_coreDiagRigid m hRequest hrigid)

end Twin

end DraismaVargas.Count.SlopeRigidity
