module

public import DraismaVargasCount.AttachmentFibre

@[expose] public section

/-!
# Actual pendant retraction and fibre aggregation

The retraction is the quotient of the actual source vertices by walks along
actual dangling occurrences. Its divisor is the literal pushforward of the
pullback fibre weights, not an assumed coefficient profile. At a surviving
vertex the contraction fibre is exactly the vertex and its pairwise-disjoint
incident pendant sides. The proved branch census therefore gives the exact
coefficient as direct local degree plus the number of root-containing branches.

This supplies the aggregation step of the chip-coefficient classification of
`RowChipCoefficient`. Local ramification classification and identification with
the divisor produced by a chosen metric realization's pendant-deletion chain are
separate statements.
-/

namespace DraismaVargas.Count.PendantRetraction

open DraismaVargas.Infrastructure GluingDatum
open DraismaVargas.LocalCases
open W4StableSource StableLocalProperties FullDimensionalSource
open DanglingSideStructure DanglingDescent

variable {target : CFGraph} {degree : ℕ} {data : GluingDatum target degree}
  {coordinate : Type*} [Fintype coordinate] [DecidableEq coordinate]

noncomputable local instance (p : Prop) : Decidable p := Classical.propDecidable p

/-- One step along an actual dangling source occurrence, in either orientation. -/
def DanglingStep (first second : data.SourceVertex) : Prop :=
  ∃ edge : data.SourceEdge, IsDangling data edge ∧
    (data.sourceEnds edge = (first, second) ∨ data.sourceEnds edge = (second, first))

theorem danglingStep_symm {first second : data.SourceVertex}
    (h : DanglingStep first second) : DanglingStep second first := by
  obtain ⟨edge, hEdge, hEnds⟩ := h
  exact ⟨edge, hEdge, hEnds.symm⟩

/-- The genuine contraction relation generated by the dangling occurrences. -/
def retractionSetoid (data : GluingDatum target degree) : Setoid data.SourceVertex where
  r := Relation.ReflTransGen DanglingStep
  iseqv := ⟨fun _ ↦ Relation.ReflTransGen.refl, by
    intro first second h
    induction h with
    | refl => exact .refl
    | tail h hStep ih =>
      exact (Relation.ReflTransGen.single (danglingStep_symm hStep)).trans ih,
    Relation.ReflTransGen.trans⟩

/-- The graph-theoretic pendant retraction, before choosing names for its vertices. -/
def retractVertex (vertex : data.SourceVertex) : Quotient (retractionSetoid data) :=
  Quotient.mk _ vertex

/-- The literal pushforward of the pullback fibre along the pendant contraction. -/
noncomputable def retractedFibre (root : target.V)
    (point : Quotient (retractionSetoid data)) : ℤ :=
  ∑ vertex : data.SourceVertex,
    if retractVertex vertex = point ∧ vertex.1.1 = root then
      ((data.vertexPartition vertex.1.1).blockCard vertex.1.2 : ℤ) else 0

/-- The actual dangling occurrences attached to a specified source vertex. -/
abbrev AttachedEdge (vertex : data.SourceVertex) :=
  {edge : data.SourceEdge // Incident data edge vertex ∧ IsDangling data edge}

/-- The actual pendant side of an attached occurrence, with the source-vertex
type kept explicit for the finite-sum API. -/
noncomputable def attachedSide {vertex : data.SourceVertex} (edge : AttachedEdge vertex) :
    Finset data.SourceVertex := (chosenDangling edge.2.2).cut.side

/-- A dangling edge incident to a surviving vertex has that vertex as its
outer endpoint; its pendant side contains no surviving vertex. -/
theorem outer_eq_of_incident {vertex : data.SourceVertex}
    (hSurvives : 0 < nonDanglingValency data vertex)
    {edge : data.SourceEdge} (item : DanglingData data edge)
    (hIncident : Incident data edge vertex) : item.outer = vertex := by
  have hEither : vertex = item.inner ∨ vertex = item.outer := by
    rcases item.ends with h | h
    · rw [Incident, h] at hIncident
      exact hIncident.symm.imp Eq.symm Eq.symm |>.symm
    · rw [Incident, h] at hIncident
      exact hIncident.symm.imp Eq.symm Eq.symm
  rcases hEither with hInner | hOuter
  · have hZero := nonDanglingValency_eq_zero_of_mem_side data item.cut item.cut.left_mem
    rw [← hInner] at hZero
    omega
  · exact hOuter.symm

/-- A side's connectedness supplies a walk to any of its vertices avoiding
the attachment. -/
theorem reachP_inside_side {inner outer : data.SourceVertex}
    (cut : DanglingSide data.sourceGraph inner outer)
    {first second : data.SourceVertex} (hFirst : first ∈ cut.side)
    (hSecond : second ∈ cut.side) :
    ReachP data.sourceGraph (fun vertex ↦ vertex ≠ outer) first second := by
  have hReach := reach_of_graph_connected cut.side_connected
    (⟨first, hFirst⟩ : (Utilities.inducedSubgraph data.sourceGraph cut.side
      ⟨inner, cut.left_mem⟩).V) ⟨second, hSecond⟩
  exact reachP_mono (fun (vertex : data.SourceVertex) (hMem : vertex ∈ cut.side)
      (hEq : vertex = outer) ↦ cut.right_not_mem (hEq ▸ hMem))
    (reachP_of_reach_induced ⟨inner, cut.left_mem⟩ hReach)

/-- Distinct dangling occurrences with the same attachment have disjoint
actual pendant sides. This prevents double counting in the pushforward. -/
theorem sides_disjoint_of_outer_eq
    {first second : data.SourceEdge} (one : DanglingData data first)
    (two : DanglingData data second) (hOuter : one.outer = two.outer)
    (hNe : first ≠ second) : Disjoint one.cut.side two.cut.side := by
  apply Finset.disjoint_left.mpr
  intro vertex hOne hTwo
  have hReach := reachP_inside_side one.cut hOne one.cut.left_mem
  rw [hOuter] at hReach
  have hInner := mem_side_of_reachP two.cut hTwo hReach
  have hBad := outer_mem_side_of_inner_mem_side data two one hNe hInner
  rw [hOuter] at hBad
  exact two.cut.right_not_mem hBad

/-- Every point of an actual pendant side retracts to its attachment. -/
theorem retractVertex_eq_of_mem_side
    {edge : data.SourceEdge} (item : DanglingData data edge)
    {vertex : data.SourceVertex} (hVertex : vertex ∈ item.cut.side) :
    retractVertex vertex = retractVertex item.outer := by
  have hStart : retractVertex item.inner = retractVertex item.outer :=
    Quotient.sound (Relation.ReflTransGen.single
      ⟨edge, isDangling_of_danglingData item, item.ends⟩)
  let sideGraph := Utilities.inducedSubgraph data.sourceGraph item.cut.side
    ⟨item.inner, item.cut.left_mem⟩
  have hReach : Reach sideGraph ⟨item.inner, item.cut.left_mem⟩ ⟨vertex, hVertex⟩ :=
    reach_of_graph_connected item.cut.side_connected _ _
  refine reach_propagate
    (motive := fun v : sideGraph.V ↦ retractVertex v.1 = retractVertex item.outer)
    hStart (fun before next hAdj ih ↦ ?_) hReach
  have hSourceAdj := lt_of_lt_of_eq hAdj
    (Utilities.num_edges_inducedSubgraph data.sourceGraph item.cut.side
      ⟨item.inner, item.cut.left_mem⟩ before next)
  obtain ⟨step, hEnds⟩ := exists_sourceEnds_of_num_edges_pos data hSourceAdj
  have hIncident : Incident data step before.1 := incident_of_sourceEnds data hEnds
  have hDangling := isDangling_of_incident_mem_side data item.cut.side.card
    item.inner item.outer item.cut rfl before.1 before.2 step hIncident
  exact (Quotient.sound (Relation.ReflTransGen.single
    (danglingStep_symm ⟨step, hDangling, hEnds⟩))).trans ih

/-- The fibre over a surviving vertex consists of that vertex and precisely
the actual pendant sides of its incident dangling occurrences. -/
theorem retractVertex_eq_iff
    {vertex point : data.SourceVertex}
    (hSurvives : 0 < nonDanglingValency data vertex) :
    retractVertex point = retractVertex vertex ↔
      point = vertex ∨ ∃ edge : AttachedEdge vertex,
        point ∈ attachedSide edge := by
  constructor
  · intro hEq
    have hReach : Relation.ReflTransGen DanglingStep vertex point :=
      Quotient.exact hEq.symm
    clear hEq
    induction hReach with
    | refl => exact Or.inl rfl
    | @tail before next _ hStep ih =>
      obtain ⟨step, hDangling, hEnds⟩ := hStep
      rcases ih with hBefore | ⟨edge, hBefore⟩
      · subst before
        have hIncident : Incident data step vertex := incident_of_sourceEnds data hEnds
        let edge : AttachedEdge vertex := ⟨step, hIncident, hDangling⟩
        have hOuter := outer_eq_of_incident hSurvives (chosenDangling edge.2.2) hIncident
        have hCutEnds := (chosenDangling edge.2.2).ends
        rw [hOuter] at hCutEnds
        have hNext := NonDanglingValency.other_end_unique data hEnds hCutEnds.symm
        exact Or.inr ⟨edge, hNext ▸ (chosenDangling edge.2.2).cut.left_mem⟩
      · let item := chosenDangling edge.2.2
        by_cases hNext : next ∈ item.cut.side
        · exact Or.inr ⟨edge, hNext⟩
        · have hOuter := outer_eq_of_incident hSurvives item edge.2.1
          have hCross := item.cut.cross_num_edges before next hBefore hNext
          have hPos := num_edges_pos_of_sourceEnds data hEnds
          have hPair : before = item.inner ∧ next = item.outer := by
            by_contra hNot
            exact (Nat.ne_of_gt hPos) (hCross.trans (ite_eq_right hNot))
          exact Or.inl (hPair.2.trans hOuter)
  · rintro (rfl | ⟨edge, hPoint⟩)
    · rfl
    · exact (retractVertex_eq_of_mem_side (chosenDangling edge.2.2) hPoint).trans
        (congrArg retractVertex
          (outer_eq_of_incident hSurvives (chosenDangling edge.2.2) edge.2.1))

/-- Each pendant contraction class has at most one surviving vertex. -/
theorem surviving_vertex_unique
    {first second : data.SourceVertex}
    (hFirst : 0 < nonDanglingValency data first)
    (hSecond : 0 < nonDanglingValency data second)
    (hEq : retractVertex first = retractVertex second) : first = second := by
  rcases (retractVertex_eq_iff hSecond).mp hEq with h | ⟨edge, hMem⟩
  · exact h
  · have hZero := nonDanglingValency_eq_zero_of_mem_side data
      (chosenDangling edge.2.2).cut hMem
    omega

/-- The concrete vertex set that is collapsed onto a surviving attachment. -/
noncomputable def attachmentSupport (vertex : data.SourceVertex) : Finset data.SourceVertex :=
  insert vertex (Finset.univ.biUnion fun edge : AttachedEdge vertex ↦
    attachedSide edge)

theorem mem_attachmentSupport_iff {vertex point : data.SourceVertex}
    (hSurvives : 0 < nonDanglingValency data vertex) :
    point ∈ attachmentSupport vertex ↔ retractVertex point = retractVertex vertex := by
  classical
  simp only [attachmentSupport, Finset.mem_insert, Finset.mem_biUnion,
    Finset.mem_univ, true_and]
  exact (retractVertex_eq_iff hSurvives).symm

/-- The pushforward coefficient is the sum of the original fibre weights
over its actual contraction fibre. -/
theorem retractedFibre_eq_sum_support (root : target.V) {vertex : data.SourceVertex}
    (hSurvives : 0 < nonDanglingValency data vertex) :
    retractedFibre root (retractVertex vertex) =
      ∑ point ∈ attachmentSupport vertex,
        if point.1.1 = root then
          ((data.vertexPartition point.1.1).blockCard point.1.2 : ℤ) else 0 := by
  classical
  have hSet : attachmentSupport vertex = Finset.univ.filter
      (fun point ↦ retractVertex point = retractVertex vertex) := by
    ext point
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    exact mem_attachmentSupport_iff hSurvives
  rw [hSet, Finset.sum_filter]
  unfold retractedFibre
  apply Finset.sum_congr rfl
  intro point _
  by_cases hClass : retractVertex point = retractVertex vertex <;> simp [hClass]

/-- The concrete contraction fibre decomposes without multiplicity into the
attachment and its distinct incident pendant sides. -/
theorem sum_attachmentSupport (vertex : data.SourceVertex)
    (hSurvives : 0 < nonDanglingValency data vertex) (weight : data.SourceVertex → ℤ) :
    (∑ point ∈ attachmentSupport vertex, weight point) =
      weight vertex + ∑ edge : AttachedEdge vertex,
        ∑ point ∈ attachedSide edge, weight point := by
  classical
  have hOutside : vertex ∉ Finset.univ.biUnion
      (fun edge : AttachedEdge vertex ↦ attachedSide edge) := by
    simp only [Finset.mem_biUnion, Finset.mem_univ, true_and, not_exists]
    intro edge hMem
    have hZero := nonDanglingValency_eq_zero_of_mem_side data
      (chosenDangling edge.2.2).cut hMem
    omega
  rw [attachmentSupport, Finset.sum_insert hOutside, Finset.sum_biUnion]
  intro first _ second _ hNe
  apply sides_disjoint_of_outer_eq
  · exact (outer_eq_of_incident hSurvives (chosenDangling first.2.2) first.2.1).trans
      (outer_eq_of_incident hSurvives (chosenDangling second.2.2) second.2.1).symm
  · intro h
    exact hNe (Subtype.ext h)

/-- Exact geometric aggregation: the actual retracted fibre coefficient is
the direct local degree plus one for each pendant branch containing the root. -/
theorem retractedFibre_eq_branch_sum
    (fd : FullDimensionalSourcePresentation data coordinate)
    (root : target.V) {vertex : data.SourceVertex}
    (hSurvives : 0 < nonDanglingValency data vertex) :
    retractedFibre root (retractVertex vertex) =
      (if vertex.1.1 = root then
        ((data.vertexPartition vertex.1.1).blockCard vertex.1.2 : ℤ) else 0) +
      ∑ edge : AttachedEdge vertex,
        if ReachP target (fun v ↦ v ≠ vertex.1.1)
          (chosenDangling edge.2.2).inner.1.1 root then (1 : ℤ) else 0 := by
  rw [retractedFibre_eq_sum_support root hSurvives,
    sum_attachmentSupport vertex hSurvives]
  congr 1
  apply Finset.sum_congr rfl
  intro edge _
  exact (PendantFibre.fibre_sum_eq_branch_indicator fd
    (chosenDangling edge.2.2).cut root).trans (by
      rw [outer_eq_of_incident hSurvives (chosenDangling edge.2.2) edge.2.1])

end DraismaVargas.Count.PendantRetraction
