import Mathlib

/-!
# Brill--Noether generality and gonality for chains

This is the Mathlib-only Challenge surface for the chain results selected from
`HighlightsStatements.lean`.  It contains the seven advertised theorem
statements and the complete local vocabulary needed to read them.  The
advertised declarations deliberately end in `sorry`; their proved counterparts
are in `Solutions.BNChains`.
-/

namespace BNChains

universe u

open Multiset Finset

/-! ## Self-contained statement vocabulary -/

/-- A finite, nonempty, loopless undirected multigraph.  An undirected edge is
stored by either ordering of its endpoints; `num_edges` below forgets that
ordering. -/
structure CFGraph where
  /-- The finite, nonempty type of vertices. -/
  V : Type u
  [instDecidableEq : DecidableEq V]
  [instFintype : Fintype V]
  [instNonempty : Nonempty V]
  /-- Edge occurrences, each stored once using either endpoint ordering. -/
  edges : Multiset (V × V)
  /-- No edge occurrence has equal endpoints. -/
  loopless : ∀ v, (v, v) ∉ edges

attribute [instance] CFGraph.instDecidableEq CFGraph.instFintype CFGraph.instNonempty

/-- The number of edges between two vertices, counted with multiplicity. -/
def num_edges (G : CFGraph) (v w : G.V) : ℕ :=
  Multiset.card (G.edges.filter (fun e => e = (v, w) ∨ e = (w, v)))

/-- A graph is connected when every nontrivial vertex cut has a crossing
edge. -/
def graph_connected (G : CFGraph) : Prop :=
  ∀ S : Finset G.V, (∃ v w : G.V, v ∈ S ∧ w ∉ S) →
    ∃ v ∈ S, ∃ w ∉ S, num_edges G v w > 0

/-- The genus (cyclomatic number) `|E| - |V| + 1`. -/
def genus (G : CFGraph) : ℤ :=
  Multiset.card G.edges - Fintype.card G.V + 1

/-- The degree (valence) of a vertex. -/
def vertex_degree (G : CFGraph) (v : G.V) : ℤ :=
  ∑ u : G.V, (num_edges G v u : ℤ)

/-- A divisor is an integer-valued function on the vertices. -/
abbrev CFDiv (G : CFGraph) := G.V → ℤ

/-- The principal divisor obtained by firing one vertex once. -/
def firing_vector (G : CFGraph) (v : G.V) : CFDiv G :=
  fun w => if w = v then -vertex_degree G v else num_edges G v w

/-- The subgroup generated by all vertex firings. -/
def principal_divisors (G : CFGraph) : AddSubgroup (CFDiv G) :=
  AddSubgroup.closure (Set.range (firing_vector G))

/-- Two divisors are linearly equivalent when their difference is principal. -/
def linear_equiv (G : CFGraph) (D D' : CFDiv G) : Prop :=
  D' - D ∈ principal_divisors G

/-- A divisor is effective when it has no negative coefficient. -/
def effective {G : CFGraph} (D : CFDiv G) : Prop :=
  ∀ v : G.V, D v ≥ 0

/-- The additive monoid of effective divisors. -/
def Eff (G : CFGraph) : AddSubmonoid (CFDiv G) :=
  { carrier := {D : CFDiv G | effective D}
    zero_mem' := by
      simp only [effective, ge_iff_le, Set.mem_ofPred_eq, Pi.zero_apply,
        Std.le_refl, implies_true]
    add_mem' := by
      intro D₁ D₂ h₁ h₂ v
      exact add_nonneg (h₁ v) (h₂ v) }

/-- A divisor is winnable when it is linearly equivalent to an effective
divisor. -/
def winnable (G : CFGraph) (D : CFDiv G) : Prop :=
  ∃ D' ∈ Eff G, linear_equiv G D D'

/-- The degree of a divisor, i.e. its total number of chips. -/
def deg {G : CFGraph} : CFDiv G →+ ℤ :=
  { toFun := fun D => ∑ v, D v
    map_zero' := by simp only [Pi.zero_apply, sum_const_zero]
    map_add' := by
      intro D₁ D₂
      simp only [Pi.add_apply, sum_add_distrib] }

/-- The effective divisors of a prescribed degree. -/
def eff_of_degree (G : CFGraph) (k : ℤ) : Set (CFDiv G) :=
  {E | effective E ∧ deg E = k}

/-- `rank_geq G D k` means that removing any effective divisor of degree `k`
from `D` leaves a winnable divisor. -/
def rank_geq (G : CFGraph) (D : CFDiv G) (k : ℤ) : Prop :=
  ∀ E ∈ eff_of_degree G k, winnable G (D - E)

/-- `rank_eq G D r` means that the Baker--Norine rank of `D` is exactly `r`. -/
def rank_eq (G : CFGraph) (D : CFDiv G) (r : ℤ) : Prop :=
  rank_geq G D r ∧ ¬rank_geq G D (r + 1)

/-- `gonality_leq G k` means that `G` has a degree-`k` divisor of rank at
least one.  This deliberately states the witness property directly, without
introducing a minimum or an infimum. -/
def gonality_leq (G : CFGraph) (k : ℤ) : Prop :=
  ∃ D : CFDiv G, deg D = k ∧ rank_geq G D 1

/-- `gonality_eq G k` means that degree `k` supports a rank-one divisor and
no smaller degree does.  This witness formulation avoids hiding the statement
behind an infimum. -/
def gonality_eq (G : CFGraph) (k : ℤ) : Prop :=
  gonality_leq G k ∧ ∀ d : ℤ, d < k → ¬ gonality_leq G d

/-! ### Brill--Noether generality and twice-marked graphs -/

/-- The divisor consisting of one chip at `v`. -/
def one_chip {G : CFGraph} (v : G.V) : CFDiv G :=
  fun w => if w = v then 1 else 0

/-- The Brill--Noether number `rho(g,r,d)`. -/
def brill_noether_number (G : CFGraph) (r d : ℤ) : ℤ :=
  genus G - (r + 1) * (genus G - d + r)

/-- Existence of a degree-`d` divisor of rank at least `r`. -/
def brill_noether_exists (G : CFGraph) (r d : ℤ) : Prop :=
  ∃ D : CFDiv G, deg D = d ∧ rank_geq G D r

/-- The nonexistence half of Brill--Noether generality: every divisor that
exists lies in the range predicted by the Brill--Noether number. -/
def brill_noether_general (G : CFGraph) : Prop :=
  ∀ r d : ℤ, 0 ≤ r → brill_noether_exists G r d →
    0 ≤ brill_noether_number G r d

/-- A graph with an ordered left and right marked vertex.  The graph is
packaged existentially so twice-marked graphs with different vertex types can
occur in one list. -/
structure TwiceMarkedGraph where
  /-- The underlying finite multigraph. -/
  graph : CFGraph.{0}
  /-- The left marked vertex. -/
  u : graph.V
  /-- The right marked vertex. -/
  v : graph.V

/-- A harmless one-vertex value, used for an empty chain and for as a junk value
returned for malformed path-length data. -/
def trivial_twice_marked_graph : TwiceMarkedGraph where
  graph :=
    { V := Fin 1
      edges := 0
      loopless := by simp }
  u := 0
  v := 0

/-- Join two twice-marked graphs by taking their disjoint union and adding one
bridge from the right mark of the first to the left mark of the second.  The
new marks are the two outside marks.

This deliberately uses a bridge rather than identifying the two vertices;
it is the most literal finite-graph presentation of a chain. -/
def bridge_glue (G₁ G₂ : TwiceMarkedGraph) : TwiceMarkedGraph where
  graph :=
    { V := G₁.graph.V ⊕ G₂.graph.V
      edges :=
        (Sum.inl G₁.v, Sum.inr G₂.u) ::ₘ
          (G₁.graph.edges.map (fun e : G₁.graph.V × G₁.graph.V =>
            (Sum.inl e.1, Sum.inl e.2)) +
          G₂.graph.edges.map (fun e : G₂.graph.V × G₂.graph.V =>
            (Sum.inr e.1, Sum.inr e.2)))
      loopless := by
        intro z hz
        simp only [Multiset.mem_cons, Multiset.mem_add] at hz
        rcases hz with hBridge | hFactor
        · cases z <;> simp at hBridge
        · rcases hFactor with hLeft | hRight
          · rw [Multiset.mem_map] at hLeft
            obtain ⟨e, he, hEq⟩ := hLeft
            rcases e with ⟨a, b⟩
            cases z with
            | inl z =>
                simp only [Prod.mk.injEq, Sum.inl.injEq] at hEq
                rcases hEq with ⟨rfl, rfl⟩
                exact G₁.graph.loopless _ he
            | inr z => simp at hEq
          · rw [Multiset.mem_map] at hRight
            obtain ⟨e, he, hEq⟩ := hRight
            rcases e with ⟨a, b⟩
            cases z with
            | inl z => simp at hEq
            | inr z =>
                simp only [Prod.mk.injEq, Sum.inr.injEq] at hEq
                rcases hEq with ⟨rfl, rfl⟩
                exact G₂.graph.loopless _ he }
  u := Sum.inl G₁.u
  v := Sum.inr G₂.v

/-- Glue a list from left to right.  The empty list has the harmless
one-vertex value above. -/
def glue_chain : List TwiceMarkedGraph → TwiceMarkedGraph
  | [] => trivial_twice_marked_graph
  | G :: rest => rest.foldl bridge_glue G

/-- The two complementary arc lengths of a twice-marked cycle. -/
def twiceMarkedCycleLength (m n : ℕ) : Fin 2 → ℕ := ![m, n]

/-- Vertices of the cycle: the two marked endpoints and the disjoint interior
vertices of its top and bottom arcs. -/
abbrev TwiceMarkedCycleVertex (m n : ℕ) :=
  Fin 2 ⊕ (Σ arc : Fin 2, Fin (twiceMarkedCycleLength m n arc - 1))

/-- Unit steps along the two arcs. -/
abbrev TwiceMarkedCycleStep (m n : ℕ) :=
  Σ arc : Fin 2, Fin (twiceMarkedCycleLength m n arc)

/-- Left endpoint of a unit step along a cycle arc. -/
def twiceMarkedCycleStepLeft (m n : ℕ) (step : TwiceMarkedCycleStep m n) :
    TwiceMarkedCycleVertex m n :=
  if hzero : step.2.val = 0 then
    Sum.inl 0
  else
    Sum.inr ⟨step.1, ⟨step.2.val - 1, by
      have hlt := step.2.isLt
      omega⟩⟩

/-- Right endpoint of a unit step along a cycle arc. -/
def twiceMarkedCycleStepRight (m n : ℕ) (step : TwiceMarkedCycleStep m n) :
    TwiceMarkedCycleVertex m n :=
  if hlast : step.2.val + 1 = twiceMarkedCycleLength m n step.1 then
    Sum.inl 1
  else
    Sum.inr ⟨step.1, ⟨step.2.val, by
      have hlt := step.2.isLt
      omega⟩⟩

/-- A cycle marked at the endpoints of two complementary arcs of lengths
`m` and `n`.  If either length is zero, the value is the documented junk
graph `trivial_twice_marked_graph`. -/
def twice_marked_cycle (m n : ℕ) : TwiceMarkedGraph :=
  if hpos : 0 < m ∧ 0 < n then
    { graph :=
        { V := TwiceMarkedCycleVertex m n
          edges := (Finset.univ : Finset (TwiceMarkedCycleStep m n)).val.map
            (fun step =>
              (twiceMarkedCycleStepLeft m n step,
                twiceMarkedCycleStepRight m n step))
          loopless := by
            intro vertex hmem
            simp only [Multiset.mem_map, Finset.mem_val, Finset.mem_univ,
              true_and] at hmem
            obtain ⟨step, hpair⟩ := hmem
            have hne : twiceMarkedCycleStepLeft m n step ≠
                twiceMarkedCycleStepRight m n step := by
              unfold twiceMarkedCycleStepLeft twiceMarkedCycleStepRight
              split_ifs with hzero hlast
              · simp
              · simp
              · simp
              · intro heq
                have hpositions : step.2.val - 1 = step.2.val := by
                  exact congrArg (fun x => x.2.val) (Sum.inr.inj heq)
                omega
            exact hne ((Prod.mk.inj hpair).1.trans (Prod.mk.inj hpair).2.symm) }
      u := Sum.inl 0
      v := Sum.inl 1 }
  else
    trivial_twice_marked_graph

/-- `torsion_gt M n` says that no positive multiple `k ≤ n` of the two
marked points is linearly equivalent.  Equivalently, the order of `[u-v]` in
the Jacobian is greater than `n` (including the infinite-order convention). -/
def torsion_gt (M : TwiceMarkedGraph) (n : ℕ) : Prop :=
  ∀ k : ℕ, 1 ≤ k → k ≤ n →
    ¬linear_equiv M.graph
      ((k : ℤ) • one_chip M.u) ((k : ℤ) • one_chip M.v)

/-- CDPR genericity for integer cycle lengths.  There are at least two loops;
all arc lengths are positive, ruling out the junk branch of
`twice_marked_cycle`; and no two arc lengths have a ratio of positive
numerator-plus-denominator at most `2g-2`, where `g` is the number of cycles. -/
def cdpr_general (lengths : List (ℕ × ℕ)) : Prop :=
  2 ≤ lengths.length ∧
  (∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2) ∧
  ∀ mn ∈ lengths, ∀ p q : ℕ,
    0 < p → 0 < q → p + q ≤ 2 * lengths.length - 2 →
      mn.1 * q ≠ mn.2 * p

/-- The bridge-chain built from a list of pairs of cycle arc lengths. -/
def chain_of_cycles (lengths : List (ℕ × ℕ)) : TwiceMarkedGraph :=
  glue_chain (lengths.map fun mn => twice_marked_cycle mn.1 mn.2)

/-- The three strand lengths, in order. -/
def thetaLength (a b c : ℕ) : Fin 3 → ℕ := ![a, b, c]

/-- Vertices of `Theta a b c`: the top and bottom vertices, together with
three disjoint sets of `a - 1`, `b - 1`, and `c - 1` interior vertices. -/
abbrev ThetaVertex (a b c : ℕ) :=
  Fin 2 ⊕ (Σ strand : Fin 3, Fin (thetaLength a b c strand - 1))

/-- Unit steps along the three strands of `Theta a b c`. -/
abbrev ThetaStep (a b c : ℕ) :=
  Σ strand : Fin 3, Fin (thetaLength a b c strand)

/-- Left endpoint of one unit step along a theta strand. -/
def thetaStepLeft (a b c : ℕ) (step : ThetaStep a b c) :
    ThetaVertex a b c :=
  if hzero : step.2.val = 0 then
    Sum.inl 0
  else
    Sum.inr ⟨step.1, ⟨step.2.val - 1, by
      have hlt := step.2.isLt
      omega⟩⟩

/-- Right endpoint of one unit step along a theta strand. -/
def thetaStepRight (a b c : ℕ) (step : ThetaStep a b c) :
    ThetaVertex a b c :=
  if hlast : step.2.val + 1 = thetaLength a b c step.1 then
    Sum.inl 1
  else
    Sum.inr ⟨step.1, ⟨step.2.val, by
      have hlt := step.2.isLt
      omega⟩⟩

/-- `Theta a b c` is the graph made from three internally disjoint paths of
lengths `a`, `b`, and `c` joining a common top vertex to a common bottom
vertex. -/
def Theta (a b c : ℕ) : CFGraph.{0} where
  V := ThetaVertex a b c
  edges := (Finset.univ : Finset (ThetaStep a b c)).val.map fun step =>
    (thetaStepLeft a b c step, thetaStepRight a b c step)
  loopless := by
    intro vertex hmem
    simp only [Multiset.mem_map, Finset.mem_val, Finset.mem_univ, true_and]
      at hmem
    obtain ⟨step, hpair⟩ := hmem
    have hne : thetaStepLeft a b c step ≠ thetaStepRight a b c step := by
      unfold thetaStepLeft thetaStepRight
      split_ifs with hzero hlast
      · simp
      · simp
      · simp
      · intro heq
        have hpositions : step.2.val - 1 = step.2.val := by
          exact congrArg (fun x => x.2.val) (Sum.inr.inj heq)
        omega
    exact hne ((Prod.mk.inj hpair).1.trans (Prod.mk.inj hpair).2.symm)

/-- `TMTheta a b c u v` marks position `u` on the first (`a`-) strand and
position `v` on the third (`c`-) strand.  Invalid positions receive the same
documented junk value used by `twice_marked_cycle`; `evenlyMarkedK` below
contains the guards used by every theorem. -/
def TMTheta (a b c u v : ℕ) : TwiceMarkedGraph :=
  if hpos : 1 ≤ u ∧ u < a ∧ 1 ≤ v ∧ v < c then
    { graph := Theta a b c
      u := Sum.inr ⟨0, ⟨u - 1, by
        change u - 1 < a - 1
        omega⟩⟩
      v := Sum.inr ⟨2, ⟨v - 1, by
        change v - 1 < c - 1
        omega⟩⟩ }
  else
    trivial_twice_marked_graph

/-- The numerical condition that `TMTheta a b c u v` is evenly marked and
has torsion order exactly `k`.  The equal-ratio condition
`u / a = v / c` is written without division as `u * c = v * a`; exactness of
the order is recorded on both marked strands. -/
def evenlyMarkedK (a b c u v k : ℕ) : Prop :=
  0 < a ∧ 0 < b ∧ 0 < c ∧
  1 ≤ u ∧ u < a ∧ 1 ≤ v ∧ v < c ∧
  u * c = v * a ∧
  a / Nat.gcd u a = k ∧ c / Nat.gcd v c = k

/-- The two kinds of factor admitted in the mixed-chain highlight. -/
inductive CycleThetaFactor where
  | cycle (m n : ℕ)
  | theta (a b c u v k : ℕ)

/-- Forget the readable factor tag and retain its twice-marked graph. -/
def CycleThetaFactor.markedGraph : CycleThetaFactor → TwiceMarkedGraph
  | .cycle m n => twice_marked_cycle m n
  | .theta a b c u v _k => TMTheta a b c u v

/-- The genus contribution of a factor: one for a cycle and two for a theta
graph. -/
def CycleThetaFactor.factorGenus : CycleThetaFactor → ℕ
  | .cycle _ _ => 1
  | .theta _ _ _ _ _ _ => 2

/-- The exact torsion period supplied by the numerical factor data. -/
def CycleThetaFactor.period : CycleThetaFactor → ℕ
  | .cycle m n => (m + n) / Nat.gcd m n
  | .theta _a _b _c _u _v k => k

/-- The total genus contributed by a list of cycle/theta factors. -/
def CycleThetaFactor.totalGenus (factors : List CycleThetaFactor) : ℕ :=
  (factors.map CycleThetaFactor.factorGenus).sum

/-- Corollary 6.16's sharp torsion budget for a mixed chain: the exact period
of a factor exceeds the smaller of the genera accumulated on its two sides,
counting the factor on both sides. -/
def mixed_chain_torsion_budget (factors : List CycleThetaFactor) : Prop :=
  ∀ i : ℕ, ∀ hi : i < factors.length,
    min
        (CycleThetaFactor.totalGenus (factors.take (i + 1)))
        (CycleThetaFactor.totalGenus (factors.drop i)) <
      (factors.get ⟨i, hi⟩).period

/-- The one-sided torsion budget for marked generality at the left endpoint
of a mixed chain.  At factor `i`, its period exceeds the total genus of the
suffix beginning there. -/
def mixed_chain_left_torsion_budget (factors : List CycleThetaFactor) : Prop :=
  ∀ i : ℕ, ∀ hi : i < factors.length,
    CycleThetaFactor.totalGenus (factors.drop i) <
      (factors.get ⟨i, hi⟩).period

/-- The twice-marked bridge-chain represented by mixed readable factors. -/
def chain_of_cycles_and_thetas
    (factors : List CycleThetaFactor) : TwiceMarkedGraph :=
  glue_chain (factors.map CycleThetaFactor.markedGraph)

/-! ## Chains of loops: the CDPR theorem and its sharp extensions -/

/-- **Marked CDPR theorem.**  At the left endpoint of a generic chain of
`g` loops, a degree-`d`, rank-at-least-`r` divisor cannot retain rank zero
after removing `r + rho + 1` chips. -/
theorem cdpr_marked_no_high_multiplicity
    (lengths : List (ℕ × ℕ)) (h_general : cdpr_general lengths)
    (D : CFDiv (chain_of_cycles lengths).graph) (r d : ℤ)
    (h_rank_nonnegative : 0 ≤ r)
    (h_rank_below_genus : r < genus (chain_of_cycles lengths).graph)
    (h_degree : deg D = d) (h_rank : rank_geq _ D r)
    (h_rho : 0 ≤ brill_noether_number (chain_of_cycles lengths).graph r d) :
    ¬rank_geq (chain_of_cycles lengths).graph
      (D - (r + brill_noether_number (chain_of_cycles lengths).graph r d + 1) •
        one_chip (chain_of_cycles lengths).u) 0 := by
  sorry
/-- **CDPR Theorem 1.1(1), discrete form.**  A generic chain of cycles is
Brill--Noether general in the nonexistence sense. -/
theorem cdpr_chain_brill_noether_general
    (lengths : List (ℕ × ℕ)) (h_general : cdpr_general lengths) :
    brill_noether_general (chain_of_cycles lengths).graph := by
  sorry
/-- The sharp cycle-chain form behind CDPR.  Numbering the `g` cycles from
`1` to `g`, the torsion order of cycle `i` need only exceed
`min(i, g + 1 - i)`. -/
theorem cycle_chain_brill_noether_general_of_torsion
    (lengths : List (ℕ × ℕ))
    (h_positive : ∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2)
    (h_torsion : ∀ i : ℕ, ∀ hi : i < lengths.length,
      torsion_gt
        (twice_marked_cycle
          (lengths.get ⟨i, hi⟩).1 (lengths.get ⟨i, hi⟩).2)
        (min (i + 1) (lengths.length - i))) :
    brill_noether_general (chain_of_cycles lengths).graph := by
  sorry

/-- **Marked mixed cycle/theta chain theorem.**  Under the sharp one-sided
torsion budget, a degree-`d`, rank-at-least-`r` divisor cannot retain rank zero
after removing `r + rho + 1` chips at the left endpoint of the chain. -/
theorem cycle_theta_chain_marked_no_high_multiplicity
    (factors : List CycleThetaFactor)
    (h_cycles_positive : ∀ m n : ℕ,
      CycleThetaFactor.cycle m n ∈ factors → 0 < m ∧ 0 < n)
    (h_thetas_evenly_marked : ∀ a b c u v k : ℕ,
      CycleThetaFactor.theta a b c u v k ∈ factors →
        evenlyMarkedK a b c u v k)
    (h_torsion : mixed_chain_left_torsion_budget factors)
    (D : CFDiv (chain_of_cycles_and_thetas factors).graph) (r d : ℤ)
    (h_rank_nonnegative : 0 ≤ r)
    (h_rank_below_genus :
      r < genus (chain_of_cycles_and_thetas factors).graph)
    (h_degree : deg D = d) (h_rank : rank_geq _ D r)
    (h_rho : 0 ≤ brill_noether_number
      (chain_of_cycles_and_thetas factors).graph r d) :
    ¬rank_geq (chain_of_cycles_and_thetas factors).graph
      (D - (r + brill_noether_number
        (chain_of_cycles_and_thetas factors).graph r d + 1) •
          one_chip (chain_of_cycles_and_thetas factors).u) 0 := by
  sorry

/-- **Mixed cycle/theta chain theorem.**  A chain whose factors are cycles or
evenly marked theta graphs is Brill--Noether general whenever every cycle is
nondegenerate and each factor satisfies the sharp minimum genus/torsion
budget.  This is the existential/unmarked conclusion of Corollary 6.16. -/
theorem cycle_theta_chain_brill_noether_general
    (factors : List CycleThetaFactor)
    (h_cycles_positive : ∀ m n : ℕ,
      CycleThetaFactor.cycle m n ∈ factors → 0 < m ∧ 0 < n)
    (h_thetas_evenly_marked : ∀ a b c u v k : ℕ,
      CycleThetaFactor.theta a b c u v k ∈ factors →
        evenlyMarkedK a b c u v k)
    (h_torsion : mixed_chain_torsion_budget factors) :
    brill_noether_general (chain_of_cycles_and_thetas factors).graph := by
  sorry
/-! ## Exact gonality of common-torsion chains -/

/-- **Exact gonality of a common-torsion cycle/theta chain.**  If every
factor has the same torsion order `k`, then the bridge-chain has gonality
exactly `k` whenever `k` is at most the generic gonality
`floor((g+3)/2)` of its total genus `g`.

The theta factors are allowed because the proof uses the common
`k`-general-transmission package, not a factorwise gonality assertion. -/
theorem cycle_theta_chain_gonality_eq_common_torsion
    (factors : List CycleThetaFactor) (k : ℕ)
    (h_nonempty : factors ≠ [])
    (h_cycles_positive : ∀ m n : ℕ,
      CycleThetaFactor.cycle m n ∈ factors → 0 < m ∧ 0 < n)
    (h_thetas_evenly_marked : ∀ a b c u v period : ℕ,
      CycleThetaFactor.theta a b c u v period ∈ factors →
        evenlyMarkedK a b c u v period)
    (h_common_torsion : ∀ F ∈ factors, F.period = k)
    (h_small : k ≤ (CycleThetaFactor.totalGenus factors + 3) / 2) :
    gonality_eq (chain_of_cycles_and_thetas factors).graph (k : ℤ) := by
  sorry
/-- Every gonality between two and the generic gonality occurs.  More
precisely, for every genus `g` and
`2 ≤ k ≤ floor((g+3)/2) = ceil(g/2)+1`, there is a connected finite graph of
genus `g` and divisorial gonality exactly `k`. -/
theorem exists_graph_of_genus_and_gonality
    (g k : ℕ) (hk : 2 ≤ k) (hkg : k ≤ (g + 3) / 2) :
    ∃ G : CFGraph.{0},
      graph_connected G ∧ genus G = (g : ℤ) ∧ gonality_eq G (k : ℤ) := by
  sorry

end BNChains
