import Bananas.ChainOfLoops.CDPR
import Bananas.ChainOfLoops.BridgeChainTransport
import Bananas.ChainOfLoops.CommonPeriodGonality
import Bananas.Theta.EvenlyMarkedThetaKGeneral

/-!
# Solutions for the chain Brill--Noether and gonality submission

This is the proved Solution surface corresponding to `BNChains.Challenge`.
Its statement vocabulary and proof bridges are copied from `Highlights.lean`
and restricted to the seven declarations selected for this submission.
-/

namespace BNChains

universe u

open Multiset Finset

/-! ## Self-contained statement vocabulary -/

/-- A finite, nonempty, loopless undirected multigraph.  An undirected edge is
stored by either ordering of its endpoints; `num_edges` below forgets that
ordering. -/
structure CFGraph where
  /-- The finite, nonempty type of vertices. -/
  V : Type u
  [instDecidableEq : DecidableEq V]
  [instFintype : Fintype V]
  [instNonempty : Nonempty V]
  /-- Edge occurrences, each stored once using either endpoint ordering. -/
  edges : Multiset (V × V)
  /-- No edge occurrence has equal endpoints. -/
  loopless : ∀ v, (v, v) ∉ edges

attribute [instance] CFGraph.instDecidableEq CFGraph.instFintype CFGraph.instNonempty

/-- The number of edges between two vertices, counted with multiplicity. -/
def num_edges (G : CFGraph) (v w : G.V) : ℕ :=
  Multiset.card (G.edges.filter (fun e => e = (v, w) ∨ e = (w, v)))

/-- A graph is connected when every nontrivial vertex cut has a crossing
edge. -/
def graph_connected (G : CFGraph) : Prop :=
  ∀ S : Finset G.V, (∃ v w : G.V, v ∈ S ∧ w ∉ S) →
    ∃ v ∈ S, ∃ w ∉ S, num_edges G v w > 0

/-- The genus (cyclomatic number) `|E| - |V| + 1`. -/
def genus (G : CFGraph) : ℤ :=
  Multiset.card G.edges - Fintype.card G.V + 1

/-- The degree (valence) of a vertex. -/
def vertex_degree (G : CFGraph) (v : G.V) : ℤ :=
  ∑ u : G.V, (num_edges G v u : ℤ)

/-- A divisor is an integer-valued function on the vertices. -/
abbrev CFDiv (G : CFGraph) := G.V → ℤ

/-- The principal divisor obtained by firing one vertex once. -/
def firing_vector (G : CFGraph) (v : G.V) : CFDiv G :=
  fun w => if w = v then -vertex_degree G v else num_edges G v w

/-- The subgroup generated by all vertex firings. -/
def principal_divisors (G : CFGraph) : AddSubgroup (CFDiv G) :=
  AddSubgroup.closure (Set.range (firing_vector G))

/-- Two divisors are linearly equivalent when their difference is principal. -/
def linear_equiv (G : CFGraph) (D D' : CFDiv G) : Prop :=
  D' - D ∈ principal_divisors G

/-- A divisor is effective when it has no negative coefficient. -/
def effective {G : CFGraph} (D : CFDiv G) : Prop :=
  ∀ v : G.V, D v ≥ 0

/-- The additive monoid of effective divisors. -/
def Eff (G : CFGraph) : AddSubmonoid (CFDiv G) :=
  { carrier := {D : CFDiv G | effective D}
    zero_mem' := by
      simp only [effective, ge_iff_le, Set.mem_ofPred_eq, Pi.zero_apply,
        Std.le_refl, implies_true]
    add_mem' := by
      intro D₁ D₂ h₁ h₂ v
      exact add_nonneg (h₁ v) (h₂ v) }

/-- A divisor is winnable when it is linearly equivalent to an effective
divisor. -/
def winnable (G : CFGraph) (D : CFDiv G) : Prop :=
  ∃ D' ∈ Eff G, linear_equiv G D D'

/-- The degree of a divisor, i.e. its total number of chips. -/
def deg {G : CFGraph} : CFDiv G →+ ℤ :=
  { toFun := fun D => ∑ v, D v
    map_zero' := by simp only [Pi.zero_apply, sum_const_zero]
    map_add' := by
      intro D₁ D₂
      simp only [Pi.add_apply, sum_add_distrib] }

/-- The effective divisors of a prescribed degree. -/
def eff_of_degree (G : CFGraph) (k : ℤ) : Set (CFDiv G) :=
  {E | effective E ∧ deg E = k}

/-- `rank_geq G D k` means that removing any effective divisor of degree `k`
from `D` leaves a winnable divisor. -/
def rank_geq (G : CFGraph) (D : CFDiv G) (k : ℤ) : Prop :=
  ∀ E ∈ eff_of_degree G k, winnable G (D - E)

/-- `rank_eq G D r` means that the Baker--Norine rank of `D` is exactly `r`. -/
def rank_eq (G : CFGraph) (D : CFDiv G) (r : ℤ) : Prop :=
  rank_geq G D r ∧ ¬rank_geq G D (r + 1)

/-- `gonality_leq G k` means that `G` has a degree-`k` divisor of rank at
least one.  This deliberately states the witness property directly, without
introducing a minimum or an infimum. -/
def gonality_leq (G : CFGraph) (k : ℤ) : Prop :=
  ∃ D : CFDiv G, deg D = k ∧ rank_geq G D 1

/-- `gonality_eq G k` means that degree `k` supports a rank-one divisor and
no smaller degree does.  This witness formulation avoids hiding the statement
behind an infimum. -/
def gonality_eq (G : CFGraph) (k : ℤ) : Prop :=
  gonality_leq G k ∧ ∀ d : ℤ, d < k → ¬ gonality_leq G d

/-! ### Brill--Noether generality and twice-marked graphs -/

/-- The divisor consisting of one chip at `v`. -/
def one_chip {G : CFGraph} (v : G.V) : CFDiv G :=
  fun w => if w = v then 1 else 0

/-- The Brill--Noether number `rho(g,r,d)`. -/
def brill_noether_number (G : CFGraph) (r d : ℤ) : ℤ :=
  genus G - (r + 1) * (genus G - d + r)

/-- Existence of a degree-`d` divisor of rank at least `r`. -/
def brill_noether_exists (G : CFGraph) (r d : ℤ) : Prop :=
  ∃ D : CFDiv G, deg D = d ∧ rank_geq G D r

/-- The nonexistence half of Brill--Noether generality: every divisor that
exists lies in the range predicted by the Brill--Noether number. -/
def brill_noether_general (G : CFGraph) : Prop :=
  ∀ r d : ℤ, 0 ≤ r → brill_noether_exists G r d →
    0 ≤ brill_noether_number G r d

/-- A graph with an ordered left and right marked vertex.  The graph is
packaged existentially so twice-marked graphs with different vertex types can
occur in one list. -/
structure TwiceMarkedGraph where
  /-- The underlying finite multigraph. -/
  graph : CFGraph.{0}
  /-- The left marked vertex. -/
  u : graph.V
  /-- The right marked vertex. -/
  v : graph.V

/-- A harmless one-vertex value, used for an empty chain and for as a junk value
returned for malformed path-length data. -/
def trivial_twice_marked_graph : TwiceMarkedGraph where
  graph :=
    { V := Fin 1
      edges := 0
      loopless := by simp }
  u := 0
  v := 0

/-- Join two twice-marked graphs by taking their disjoint union and adding one
bridge from the right mark of the first to the left mark of the second.  The
new marks are the two outside marks.

This deliberately uses a bridge rather than identifying the two vertices;
it is the most literal finite-graph presentation of a chain. -/
def bridge_glue (G₁ G₂ : TwiceMarkedGraph) : TwiceMarkedGraph where
  graph :=
    { V := G₁.graph.V ⊕ G₂.graph.V
      edges :=
        (Sum.inl G₁.v, Sum.inr G₂.u) ::ₘ
          (G₁.graph.edges.map (fun e : G₁.graph.V × G₁.graph.V =>
            (Sum.inl e.1, Sum.inl e.2)) +
          G₂.graph.edges.map (fun e : G₂.graph.V × G₂.graph.V =>
            (Sum.inr e.1, Sum.inr e.2)))
      loopless := by
        intro z hz
        simp only [Multiset.mem_cons, Multiset.mem_add] at hz
        rcases hz with hBridge | hFactor
        · cases z <;> simp at hBridge
        · rcases hFactor with hLeft | hRight
          · rw [Multiset.mem_map] at hLeft
            obtain ⟨e, he, hEq⟩ := hLeft
            rcases e with ⟨a, b⟩
            cases z with
            | inl z =>
                simp only [Prod.mk.injEq, Sum.inl.injEq] at hEq
                rcases hEq with ⟨rfl, rfl⟩
                exact G₁.graph.loopless _ he
            | inr z => simp at hEq
          · rw [Multiset.mem_map] at hRight
            obtain ⟨e, he, hEq⟩ := hRight
            rcases e with ⟨a, b⟩
            cases z with
            | inl z => simp at hEq
            | inr z =>
                simp only [Prod.mk.injEq, Sum.inr.injEq] at hEq
                rcases hEq with ⟨rfl, rfl⟩
                exact G₂.graph.loopless _ he }
  u := Sum.inl G₁.u
  v := Sum.inr G₂.v

/-- Glue a list from left to right.  The empty list has the harmless
one-vertex value above. -/
def glue_chain : List TwiceMarkedGraph → TwiceMarkedGraph
  | [] => trivial_twice_marked_graph
  | G :: rest => rest.foldl bridge_glue G

/-- The two complementary arc lengths of a twice-marked cycle. -/
def twiceMarkedCycleLength (m n : ℕ) : Fin 2 → ℕ := ![m, n]

/-- Vertices of the cycle: the two marked endpoints and the disjoint interior
vertices of its top and bottom arcs. -/
abbrev TwiceMarkedCycleVertex (m n : ℕ) :=
  Fin 2 ⊕ (Σ arc : Fin 2, Fin (twiceMarkedCycleLength m n arc - 1))

/-- Unit steps along the two arcs. -/
abbrev TwiceMarkedCycleStep (m n : ℕ) :=
  Σ arc : Fin 2, Fin (twiceMarkedCycleLength m n arc)

/-- Left endpoint of a unit step along a cycle arc. -/
def twiceMarkedCycleStepLeft (m n : ℕ) (step : TwiceMarkedCycleStep m n) :
    TwiceMarkedCycleVertex m n :=
  if hzero : step.2.val = 0 then
    Sum.inl 0
  else
    Sum.inr ⟨step.1, ⟨step.2.val - 1, by
      have hlt := step.2.isLt
      omega⟩⟩

/-- Right endpoint of a unit step along a cycle arc. -/
def twiceMarkedCycleStepRight (m n : ℕ) (step : TwiceMarkedCycleStep m n) :
    TwiceMarkedCycleVertex m n :=
  if hlast : step.2.val + 1 = twiceMarkedCycleLength m n step.1 then
    Sum.inl 1
  else
    Sum.inr ⟨step.1, ⟨step.2.val, by
      have hlt := step.2.isLt
      omega⟩⟩

/-- A cycle marked at the endpoints of two complementary arcs of lengths
`m` and `n`.  If either length is zero, the value is the documented junk
graph `trivial_twice_marked_graph`. -/
def twice_marked_cycle (m n : ℕ) : TwiceMarkedGraph :=
  if hpos : 0 < m ∧ 0 < n then
    { graph :=
        { V := TwiceMarkedCycleVertex m n
          edges := (Finset.univ : Finset (TwiceMarkedCycleStep m n)).val.map
            (fun step =>
              (twiceMarkedCycleStepLeft m n step,
                twiceMarkedCycleStepRight m n step))
          loopless := by
            intro vertex hmem
            simp only [Multiset.mem_map, Finset.mem_val, Finset.mem_univ,
              true_and] at hmem
            obtain ⟨step, hpair⟩ := hmem
            have hne : twiceMarkedCycleStepLeft m n step ≠
                twiceMarkedCycleStepRight m n step := by
              unfold twiceMarkedCycleStepLeft twiceMarkedCycleStepRight
              split_ifs with hzero hlast
              · simp
              · simp
              · simp
              · intro heq
                have hpositions : step.2.val - 1 = step.2.val := by
                  exact congrArg (fun x => x.2.val) (Sum.inr.inj heq)
                omega
            exact hne ((Prod.mk.inj hpair).1.trans (Prod.mk.inj hpair).2.symm) }
      u := Sum.inl 0
      v := Sum.inl 1 }
  else
    trivial_twice_marked_graph

/-- `torsion_gt M n` says that no positive multiple `k ≤ n` of the two
marked points is linearly equivalent.  Equivalently, the order of `[u-v]` in
the Jacobian is greater than `n` (including the infinite-order convention). -/
def torsion_gt (M : TwiceMarkedGraph) (n : ℕ) : Prop :=
  ∀ k : ℕ, 1 ≤ k → k ≤ n →
    ¬linear_equiv M.graph
      ((k : ℤ) • one_chip M.u) ((k : ℤ) • one_chip M.v)

/-- CDPR genericity for integer cycle lengths.  There are at least two loops;
all arc lengths are positive, ruling out the junk branch of
`twice_marked_cycle`; and no two arc lengths have a ratio of positive
numerator-plus-denominator at most `2g-2`, where `g` is the number of cycles. -/
def cdpr_general (lengths : List (ℕ × ℕ)) : Prop :=
  2 ≤ lengths.length ∧
  (∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2) ∧
  ∀ mn ∈ lengths, ∀ p q : ℕ,
    0 < p → 0 < q → p + q ≤ 2 * lengths.length - 2 →
      mn.1 * q ≠ mn.2 * p

/-- The bridge-chain built from a list of pairs of cycle arc lengths. -/
def chain_of_cycles (lengths : List (ℕ × ℕ)) : TwiceMarkedGraph :=
  glue_chain (lengths.map fun mn => twice_marked_cycle mn.1 mn.2)

/-- The three strand lengths, in order. -/
def thetaLength (a b c : ℕ) : Fin 3 → ℕ := ![a, b, c]

/-- Vertices of `Theta a b c`: the top and bottom vertices, together with
three disjoint sets of `a - 1`, `b - 1`, and `c - 1` interior vertices. -/
abbrev ThetaVertex (a b c : ℕ) :=
  Fin 2 ⊕ (Σ strand : Fin 3, Fin (thetaLength a b c strand - 1))

/-- Unit steps along the three strands of `Theta a b c`. -/
abbrev ThetaStep (a b c : ℕ) :=
  Σ strand : Fin 3, Fin (thetaLength a b c strand)

/-- Left endpoint of one unit step along a theta strand. -/
def thetaStepLeft (a b c : ℕ) (step : ThetaStep a b c) :
    ThetaVertex a b c :=
  if hzero : step.2.val = 0 then
    Sum.inl 0
  else
    Sum.inr ⟨step.1, ⟨step.2.val - 1, by
      have hlt := step.2.isLt
      omega⟩⟩

/-- Right endpoint of one unit step along a theta strand. -/
def thetaStepRight (a b c : ℕ) (step : ThetaStep a b c) :
    ThetaVertex a b c :=
  if hlast : step.2.val + 1 = thetaLength a b c step.1 then
    Sum.inl 1
  else
    Sum.inr ⟨step.1, ⟨step.2.val, by
      have hlt := step.2.isLt
      omega⟩⟩

/-- `Theta a b c` is the graph made from three internally disjoint paths of
lengths `a`, `b`, and `c` joining a common top vertex to a common bottom
vertex. -/
def Theta (a b c : ℕ) : CFGraph.{0} where
  V := ThetaVertex a b c
  edges := (Finset.univ : Finset (ThetaStep a b c)).val.map fun step =>
    (thetaStepLeft a b c step, thetaStepRight a b c step)
  loopless := by
    intro vertex hmem
    simp only [Multiset.mem_map, Finset.mem_val, Finset.mem_univ, true_and]
      at hmem
    obtain ⟨step, hpair⟩ := hmem
    have hne : thetaStepLeft a b c step ≠ thetaStepRight a b c step := by
      unfold thetaStepLeft thetaStepRight
      split_ifs with hzero hlast
      · simp
      · simp
      · simp
      · intro heq
        have hpositions : step.2.val - 1 = step.2.val := by
          exact congrArg (fun x => x.2.val) (Sum.inr.inj heq)
        omega
    exact hne ((Prod.mk.inj hpair).1.trans (Prod.mk.inj hpair).2.symm)

/-- `TMTheta a b c u v` marks position `u` on the first (`a`-) strand and
position `v` on the third (`c`-) strand.  Invalid positions receive the same
documented junk value used by `twice_marked_cycle`; `evenlyMarkedK` below
contains the guards used by every theorem. -/
def TMTheta (a b c u v : ℕ) : TwiceMarkedGraph :=
  if hpos : 1 ≤ u ∧ u < a ∧ 1 ≤ v ∧ v < c then
    { graph := Theta a b c
      u := Sum.inr ⟨0, ⟨u - 1, by
        change u - 1 < a - 1
        omega⟩⟩
      v := Sum.inr ⟨2, ⟨v - 1, by
        change v - 1 < c - 1
        omega⟩⟩ }
  else
    trivial_twice_marked_graph

/-- The numerical condition that `TMTheta a b c u v` is evenly marked and
has torsion order exactly `k`.  The equal-ratio condition
`u / a = v / c` is written without division as `u * c = v * a`; exactness of
the order is recorded on both marked strands. -/
def evenlyMarkedK (a b c u v k : ℕ) : Prop :=
  0 < a ∧ 0 < b ∧ 0 < c ∧
  1 ≤ u ∧ u < a ∧ 1 ≤ v ∧ v < c ∧
  u * c = v * a ∧
  a / Nat.gcd u a = k ∧ c / Nat.gcd v c = k

/-- The two kinds of factor admitted in the mixed-chain highlight. -/
inductive CycleThetaFactor where
  | cycle (m n : ℕ)
  | theta (a b c u v k : ℕ)

/-- Forget the readable factor tag and retain its twice-marked graph. -/
def CycleThetaFactor.markedGraph : CycleThetaFactor → TwiceMarkedGraph
  | .cycle m n => twice_marked_cycle m n
  | .theta a b c u v _k => TMTheta a b c u v

/-- The genus contribution of a factor: one for a cycle and two for a theta
graph. -/
def CycleThetaFactor.factorGenus : CycleThetaFactor → ℕ
  | .cycle _ _ => 1
  | .theta _ _ _ _ _ _ => 2

/-- The exact torsion period supplied by the numerical factor data. -/
def CycleThetaFactor.period : CycleThetaFactor → ℕ
  | .cycle m n => (m + n) / Nat.gcd m n
  | .theta _a _b _c _u _v k => k

/-- The total genus contributed by a list of cycle/theta factors. -/
def CycleThetaFactor.totalGenus (factors : List CycleThetaFactor) : ℕ :=
  (factors.map CycleThetaFactor.factorGenus).sum

/-- Corollary 6.16's sharp torsion budget for a mixed chain: the exact period
of a factor exceeds the smaller of the genera accumulated on its two sides,
counting the factor on both sides. -/
def mixed_chain_torsion_budget (factors : List CycleThetaFactor) : Prop :=
  ∀ i : ℕ, ∀ hi : i < factors.length,
    min
        (CycleThetaFactor.totalGenus (factors.take (i + 1)))
        (CycleThetaFactor.totalGenus (factors.drop i)) <
      (factors.get ⟨i, hi⟩).period

/-- The one-sided torsion budget for marked generality at the left endpoint
of a mixed chain.  At factor `i`, its period exceeds the total genus of the
suffix beginning there. -/
def mixed_chain_left_torsion_budget (factors : List CycleThetaFactor) : Prop :=
  ∀ i : ℕ, ∀ hi : i < factors.length,
    CycleThetaFactor.totalGenus (factors.drop i) <
      (factors.get ⟨i, hi⟩).period

/-- The twice-marked bridge-chain represented by mixed readable factors. -/
def chain_of_cycles_and_thetas
    (factors : List CycleThetaFactor) : TwiceMarkedGraph :=
  glue_chain (factors.map CycleThetaFactor.markedGraph)

/-! ## Proof bridges

Everything above this point is statement vocabulary.  The following private
conversion is where the file deliberately crosses into the implementation
library. -/

private def libraryGraph (G : CFGraph) : _root_.CFGraph :=
  { V := G.V
    instDecidableEq := G.instDecidableEq
    instFintype := G.instFintype
    instNonempty := G.instNonempty
    edges := G.edges
    loopless := G.loopless }

/-- Cross a reader-facing twice-marked graph into the library's marked-graph
bundle without changing any graph data. -/
private def libraryMarkedGraph (M : TwiceMarkedGraph) :
    _root_.Utilities.MarkedGraph where
  graph := libraryGraph M.graph
  left := M.u
  right := M.v

private theorem libraryMarkedGraph_bridge_glue (M N : TwiceMarkedGraph) :
    libraryMarkedGraph (bridge_glue M N) =
      (libraryMarkedGraph M).bridge (libraryMarkedGraph N) := rfl

private theorem libraryMarkedGraph_foldl_bridge
    (M : TwiceMarkedGraph) (rest : List TwiceMarkedGraph) :
    libraryMarkedGraph (rest.foldl bridge_glue M) =
      (rest.map libraryMarkedGraph).foldl
        _root_.Utilities.MarkedGraph.bridge (libraryMarkedGraph M) := by
  induction rest generalizing M with
  | nil => rfl
  | cons N rest ih =>
      simpa only [List.foldl_cons, List.map_cons,
        libraryMarkedGraph_bridge_glue] using ih (bridge_glue M N)

private theorem markedGraph_bridgeChain_eq_foldl
    (M : _root_.Utilities.MarkedGraph)
    (rest : List _root_.Utilities.MarkedGraph) :
    M.bridgeChain rest = rest.foldl _root_.Utilities.MarkedGraph.bridge M := by
  induction rest generalizing M with
  | nil => rfl
  | cons N rest ih =>
      simpa only [_root_.Utilities.MarkedGraph.bridgeChain, List.foldl_cons]
        using ih (M.bridge N)

private theorem libraryMarkedGraph_glue_chain_cons
    (M : TwiceMarkedGraph) (rest : List TwiceMarkedGraph) :
    libraryMarkedGraph (glue_chain (M :: rest)) =
      (libraryMarkedGraph M).bridgeChain (rest.map libraryMarkedGraph) := by
  rw [glue_chain, libraryMarkedGraph_foldl_bridge,
    markedGraph_bridgeChain_eq_foldl]

/-- The copied local definition of Brill--Noether generality agrees with the
library predicate after crossing the graph boundary. -/
private theorem brill_noether_general_library_iff (G : CFGraph) :
    brill_noether_general G ↔
      _root_.Bananas.BrillNoetherGeneral (libraryGraph G) := by
  constructor
  · intro h r d hr
    rintro ⟨D, hdegree, hrank⟩
    exact h r d hr ⟨D, hdegree,
      (_root_.rank_geq_iff (libraryGraph G) D r).mpr hrank⟩
  · intro h r d hr
    rintro ⟨D, hdegree, hrank⟩
    exact h r d hr ⟨D, hdegree,
      (_root_.rank_geq_iff (libraryGraph G) D r).mp hrank⟩

/-- Brill--Noether generality pulls back along the rank-preserving contraction
of a marked bridge chain. -/
private theorem brillNoetherGeneral_of_leftRankTransport
    {M N : _root_.Utilities.MarkedGraph}
    (transport : _root_.Bananas.LeftRankTransport M N)
    (hGeneral : _root_.Bananas.BrillNoetherGeneral N.graph) :
    _root_.Bananas.BrillNoetherGeneral M.graph := by
  intro r d hr
  rintro ⟨D, hdegree, hrank⟩
  have hTarget : _root_.Utilities.BNExists N.graph r d := by
    refine ⟨transport.mapDiv D, ?_, ?_⟩
    · rw [transport.deg_map, hdegree]
    · rw [transport.rank_map]
      exact hrank
  have hRho := hGeneral r d hr hTarget
  simpa only [_root_.Utilities.bnNumber, _root_.Utilities.rectangleWidth,
    transport.genus_eq] using hRho

/-! ### Explicit cycle factors versus the `Bananas` implementation -/

/-- Package a positive list of readable length pairs as the bundled loops
used by the formal CDPR theorem. -/
private def loopsOfPositive :
    (lengths : List (ℕ × ℕ)) →
      (∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2) →
      List _root_.ChainOfLoops.Loop
  | [], _ => []
  | mn :: rest, hpos =>
      { top := mn.1
        bot := mn.2
        top_pos := (hpos mn (by simp)).1
        bot_pos := (hpos mn (by simp)).2 } ::
      loopsOfPositive rest (fun pair hpair => hpos pair (by simp [hpair]))

@[simp] private theorem loopsOfPositive_length
    (lengths : List (ℕ × ℕ))
    (hpos : ∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2) :
    (loopsOfPositive lengths hpos).length = lengths.length := by
  induction lengths with
  | nil => rfl
  | cons mn rest ih =>
      simp only [loopsOfPositive, List.length_cons]
      rw [ih]

@[simp] private theorem loopsOfPositive_get_top
    (lengths : List (ℕ × ℕ))
    (hpos : ∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2)
    (i : ℕ) (hi : i < (loopsOfPositive lengths hpos).length)
    (hi' : i < lengths.length) :
    ((loopsOfPositive lengths hpos).get ⟨i, hi⟩).top =
      (lengths.get ⟨i, hi'⟩).1 := by
  induction lengths generalizing i with
  | nil => simp at hi'
  | cons mn rest ih =>
      cases i with
      | zero => rfl
      | succ i =>
          exact ih (fun pair hpair => hpos pair (by simp [hpair])) i
            (by simpa using hi) (by simpa using hi')

@[simp] private theorem loopsOfPositive_get_bot
    (lengths : List (ℕ × ℕ))
    (hpos : ∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2)
    (i : ℕ) (hi : i < (loopsOfPositive lengths hpos).length)
    (hi' : i < lengths.length) :
    ((loopsOfPositive lengths hpos).get ⟨i, hi⟩).bot =
      (lengths.get ⟨i, hi'⟩).2 := by
  induction lengths generalizing i with
  | nil => simp at hi'
  | cons mn rest ih =>
      cases i with
      | zero => rfl
      | succ i =>
          exact ih (fun pair hpair => hpos pair (by simp [hpair])) i
            (by simpa using hi) (by simpa using hi')

private theorem mem_loopsOfPositive
    (lengths : List (ℕ × ℕ))
    (hpos : ∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2)
    (P : _root_.ChainOfLoops.Loop)
    (hP : P ∈ loopsOfPositive lengths hpos) :
    ∃ mn ∈ lengths, P.top = mn.1 ∧ P.bot = mn.2 := by
  induction lengths with
  | nil =>
      have : P ∈ ([] : List _root_.ChainOfLoops.Loop) := by
        simpa only [loopsOfPositive] using hP
      exact (List.not_mem_nil this).elim
  | cons mn rest ih =>
      simp only [loopsOfPositive, List.mem_cons] at hP
      rcases hP with rfl | hP
      · exact ⟨mn, by simp, rfl, rfl⟩
      · obtain ⟨pair, hpair, htop, hbot⟩ :=
          ih (fun pair hpair => hpos pair (by simp [hpair])) hP
        exact ⟨pair, by simp [hpair], htop, hbot⟩

private theorem loopsOfPositive_cdprGeneric
    (lengths : List (ℕ × ℕ)) (hGeneral : cdpr_general lengths) :
    _root_.ChainOfLoops.CDPRGeneric
      (loopsOfPositive lengths hGeneral.2.1) := by
  intro P hP p q hp hq hsum
  obtain ⟨mn, hmn, htop, hbot⟩ :=
    mem_loopsOfPositive lengths hGeneral.2.1 P hP
  rw [htop, hbot]
  apply hGeneral.2.2 mn hmn p q hp hq
  simpa only [loopsOfPositive_length lengths hGeneral.2.1] using hsum

/-- With positive lengths, the readable two-arc construction is literally
the subdivision-graph cycle used by `ChainOfLoops.Loop`. -/
private theorem libraryMarkedGraph_twice_marked_cycle
    (m n : ℕ) (hm : 0 < m) (hn : 0 < n) :
    libraryMarkedGraph (twice_marked_cycle m n) =
      (_root_.ChainOfLoops.Loop.factor
        { top := m, bot := n, top_pos := hm, bot_pos := hn }).marked := by
  simp only [twice_marked_cycle, hm, hn, and_self, dite_true]
  rfl

private theorem libraryMarkedGraphs_cycles_eq
    (lengths : List (ℕ × ℕ))
    (hpos : ∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2) :
    lengths.map (fun mn => libraryMarkedGraph
        (twice_marked_cycle mn.1 mn.2)) =
      (loopsOfPositive lengths hpos).map
        (fun P => P.factor.marked) := by
  induction lengths with
  | nil => rfl
  | cons mn rest ih =>
      simp only [List.map_cons, loopsOfPositive, List.cons.injEq]
      constructor
      · exact libraryMarkedGraph_twice_marked_cycle mn.1 mn.2
          (hpos mn (by simp)).1 (hpos mn (by simp)).2
      · exact ih (fun pair hpair => hpos pair (by simp [hpair]))

private theorem trivial_library_brillNoetherGeneral :
    _root_.Bananas.BrillNoetherGeneral
      (libraryMarkedGraph trivial_twice_marked_graph).graph := by
  intro r d hr
  rintro ⟨D, hdegree, hrank⟩
  have hConnected : _root_.graph_connected
      (libraryMarkedGraph trivial_twice_marked_graph).graph := by
    intro S hcut
    obtain ⟨v, w, hv, hw⟩ := hcut
    have hvw : v = w := by
      change Fin 1 at v w
      exact Fin.ext (by omega)
    exact (hw (hvw ▸ hv)).elim
  have hGenus : _root_.genus
      (libraryMarkedGraph trivial_twice_marked_graph).graph = 0 := by rfl
  have hRankNonnegative : 0 ≤ _root_.rank _ D := le_trans hr hrank
  have hRankGeqZero : _root_.rank_geq
      (libraryMarkedGraph trivial_twice_marked_graph).graph D 0 :=
    (_root_.rank_geq_iff _ D 0).mpr hRankNonnegative
  obtain ⟨E, hEffective, hEquivalent⟩ :=
    (_root_.rank_nonneg_iff_winnable _ D).mp hRankGeqZero
  have hDegreeNonnegative : 0 ≤ _root_.deg D := by
    rw [_root_.linear_equiv_preserves_deg _ D E hEquivalent]
    change 0 ≤ ∑ v, E v
    exact Finset.sum_nonneg fun v _ => hEffective v
  have hRankEq := _root_.Bananas.rank_eq_degree_of_connected_genus_zero
    _ hConnected hGenus D hDegreeNonnegative
  rw [hRankEq, hdegree] at hrank
  simp only [_root_.Utilities.bnNumber, _root_.Utilities.rectangleWidth,
    hGenus]
  nlinarith

/-- The semantic `torsion_gt` predicate on the readable cycle forces the
corresponding strict numerical period bound. -/
private theorem cycle_period_gt_of_torsion_gt
    (m n budget : ℕ) (hm : 0 < m) (hn : 0 < n)
    (hTorsion : torsion_gt (twice_marked_cycle m n) budget) :
    budget < (m + n) / Nat.gcd m n := by
  let P : _root_.ChainOfLoops.Loop :=
    { top := m, bot := n, top_pos := hm, bot_pos := hn }
  have hPeriodPositive : 0 < P.torsionOrder := P.torsionOrder_pos
  by_contra hnot
  have hPeriodLe : P.torsionOrder ≤ budget := by
    simpa only [P, _root_.ChainOfLoops.Loop.torsionOrder, Nat.not_lt] using hnot
  apply hTorsion P.torsionOrder hPeriodPositive hPeriodLe
  have hWitness := (_root_.Bananas.cycle_isTorsionOrder P.banana).1.2
  have hEquivLibrary : _root_.linear_equiv P.banana.graph
      ((P.torsionOrder : ℤ) • _root_.one_chip
        (_root_.Bananas.leftEndpoint P.banana))
      ((P.torsionOrder : ℤ) • _root_.one_chip
        (_root_.Bananas.rightEndpoint P.banana)) := by
    change _root_.linear_equiv P.banana.graph
      ((P.torsionOrder : ℤ) •
        (_root_.one_chip (_root_.Bananas.leftEndpoint P.banana) -
          _root_.one_chip (_root_.Bananas.rightEndpoint P.banana))) 0
      at hWitness
    unfold _root_.linear_equiv at hWitness ⊢
    convert hWitness using 1
    funext z
    simp only [Pi.sub_apply, Pi.smul_apply, Pi.zero_apply, smul_eq_mul]
    ring
  change _root_.linear_equiv
    (libraryMarkedGraph (twice_marked_cycle m n)).graph
    ((P.torsionOrder : ℤ) • _root_.one_chip
      (libraryMarkedGraph (twice_marked_cycle m n)).left)
    ((P.torsionOrder : ℤ) • _root_.one_chip
      (libraryMarkedGraph (twice_marked_cycle m n)).right)
  rw [libraryMarkedGraph_twice_marked_cycle m n hm hn]
  exact hEquivLibrary

private theorem loop_minBudget_of_semantic_torsion
    (lengths : List (ℕ × ℕ))
    (hpos : ∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2)
    (hTorsion : ∀ i : ℕ, ∀ hi : i < lengths.length,
      torsion_gt
        (twice_marked_cycle
          (lengths.get ⟨i, hi⟩).1 (lengths.get ⟨i, hi⟩).2)
        (min (i + 1) (lengths.length - i))) :
    ∀ (i : ℕ) (hi : i < (loopsOfPositive lengths hpos).length),
      min ((i : ℤ) + 1)
          (((loopsOfPositive lengths hpos).length : ℤ) - (i : ℤ)) <
        (((loopsOfPositive lengths hpos).get ⟨i, hi⟩).torsionOrder : ℤ) := by
  intro i hi
  have hi' : i < lengths.length := by simpa using hi
  have hPairPos := hpos (lengths.get ⟨i, hi'⟩) (List.get_mem _ _)
  have hNat := cycle_period_gt_of_torsion_gt
    (lengths.get ⟨i, hi'⟩).1 (lengths.get ⟨i, hi'⟩).2
    (min (i + 1) (lengths.length - i)) hPairPos.1 hPairPos.2
    (hTorsion i hi')
  have hLeft :
      ((min (i + 1) (lengths.length - i) : ℕ) : ℤ) =
        min ((i : ℤ) + 1) ((lengths.length : ℤ) - (i : ℤ)) := by
    rw [Nat.cast_min, Nat.cast_add, Nat.cast_one, Nat.cast_sub hi'.le]
  have hLength : (loopsOfPositive lengths hpos).length = lengths.length :=
    loopsOfPositive_length lengths hpos
  let period : ℕ :=
    ((lengths.get ⟨i, hi'⟩).1 + (lengths.get ⟨i, hi'⟩).2) /
      Nat.gcd (lengths.get ⟨i, hi'⟩).1 (lengths.get ⟨i, hi'⟩).2
  have hPeriod :
      ((loopsOfPositive lengths hpos).get ⟨i, hi⟩).torsionOrder =
        period := by
    rw [_root_.ChainOfLoops.Loop.torsionOrder,
      loopsOfPositive_get_top lengths hpos i hi hi',
      loopsOfPositive_get_bot lengths hpos i hi hi']
  calc
    min ((i : ℤ) + 1)
        (((loopsOfPositive lengths hpos).length : ℤ) - (i : ℤ)) =
        min ((i : ℤ) + 1) ((lengths.length : ℤ) - (i : ℤ)) :=
      congrArg (fun count : ℕ =>
        min ((i : ℤ) + 1) ((count : ℤ) - (i : ℤ))) hLength
    _ = ((min (i + 1) (lengths.length - i) : ℕ) : ℤ) := hLeft.symm
    _ < (period : ℤ) := by exact_mod_cast hNat
    _ = (((loopsOfPositive lengths hpos).get ⟨i, hi⟩).torsionOrder : ℤ) := by
      exact_mod_cast hPeriod.symm

/-! ### Explicit theta factors versus the `Bananas` implementation -/

private def thetaBanana (a b c : ℕ) (ha : 0 < a) (hb : 0 < b)
    (hc : 0 < c) : _root_.Bananas.Banana 2 :=
  _root_.Bananas.bananaOfLengths 2 ![a, b, c] (by
    intro i
    fin_cases i
    · exact ha
    · exact hb
    · exact hc)

private noncomputable def thetaKGeneralFactor
    (a b c u v k : ℕ) (h : evenlyMarkedK a b c u v k) :
    _root_.Bananas.KGeneralChainFactor := by
  let B := thetaBanana a b c h.1 h.2.1 h.2.2.1
  let i : B.PathPosition (0 : Fin 3) := ⟨u, by
    change u < a + 1
    exact Nat.lt_succ_of_lt h.2.2.2.2.1⟩
  let j : B.PathPosition (2 : Fin 3) := ⟨v, by
    change v < c + 1
    exact Nat.lt_succ_of_lt h.2.2.2.2.2.2.1⟩
  have hEven : _root_.Bananas.EvenlyMarkedTheta B 0 2 i j := by
    exact ⟨by decide, h.2.2.2.1, h.2.2.2.2.1,
      h.2.2.2.2.2.1, h.2.2.2.2.2.2.1, h.2.2.2.2.2.2.2.1⟩
  refine
    { marked :=
        { graph := B.graph
          left := _root_.Bananas.strandVertex B 0 i
          right := _root_.Bananas.strandVertex B 2 j }
      period := k
      connected := _root_.Bananas.banana_graph_connected B
      kGeneral := ?_ }
  have hk : B.length 0 / Nat.gcd (B.length 0) i.val = k := by
    change a / Nat.gcd a u = k
    rw [Nat.gcd_comm]
    exact h.2.2.2.2.2.2.2.2.1
  exact hk ▸ _root_.Bananas.evenlyMarkedTheta_kGeneral B 0 2 i j hEven

private theorem libraryMarkedGraph_TMTheta_eq_thetaFactor
    (a b c u v k : ℕ) (h : evenlyMarkedK a b c u v k) :
    libraryMarkedGraph (TMTheta a b c u v) =
      (thetaKGeneralFactor a b c u v k h).marked := by
  have hGuard : 1 ≤ u ∧ u < a ∧ 1 ≤ v ∧ v < c :=
    ⟨h.2.2.2.1, h.2.2.2.2.1, h.2.2.2.2.2.1,
      h.2.2.2.2.2.2.1⟩
  rw [TMTheta, dif_pos hGuard]
  unfold thetaKGeneralFactor
  dsimp only
  rw [_root_.Utilities.MarkedGraph.mk.injEq]
  refine ⟨rfl, ?_, ?_⟩
  · apply heq_of_eq
    simp [libraryMarkedGraph, thetaBanana,
      _root_.Bananas.bananaOfLengths, _root_.Bananas.strandVertex,
      _root_.Utilities.Certificate.SubdivisionGraph.Spec.pathVertex,
      _root_.Utilities.Certificate.SubdivisionGraph.Spec.interiorVertex,
      Nat.ne_of_gt h.2.2.2.1, ne_of_lt h.2.2.2.2.1]
    apply congrArg Sum.inr
    apply Sigma.ext
    · rfl
    · exact HEq.rfl
  · apply heq_of_eq
    simp [libraryMarkedGraph, thetaBanana,
      _root_.Bananas.bananaOfLengths, _root_.Bananas.strandVertex,
      _root_.Utilities.Certificate.SubdivisionGraph.Spec.pathVertex,
      _root_.Utilities.Certificate.SubdivisionGraph.Spec.interiorVertex,
      Nat.ne_of_gt h.2.2.2.2.2.1,
      ne_of_lt h.2.2.2.2.2.2.1]
    apply congrArg Sum.inr
    apply Sigma.ext
    · rfl
    · exact HEq.rfl

private structure ReadableFactorRealization (F : CycleThetaFactor) where
  factor : _root_.Bananas.KGeneralChainFactor
  marked_eq : libraryMarkedGraph F.markedGraph = factor.marked
  genus_eq : _root_.genus factor.marked.graph = F.factorGenus
  period_eq : factor.period = F.period

private noncomputable def realizeReadableFactor
    (F : CycleThetaFactor)
    (hCycle : ∀ m n, F = .cycle m n → 0 < m ∧ 0 < n)
    (hTheta : ∀ a b c u v k, F = .theta a b c u v k →
      evenlyMarkedK a b c u v k) : ReadableFactorRealization F := by
  cases F with
  | cycle m n =>
      let hpos := hCycle m n rfl
      let P : _root_.ChainOfLoops.Loop :=
        { top := m, bot := n, top_pos := hpos.1, bot_pos := hpos.2 }
      exact
        { factor := P.factor
          marked_eq := libraryMarkedGraph_twice_marked_cycle m n hpos.1 hpos.2
          genus_eq := P.genus_factor
          period_eq := rfl }
  | theta a b c u v k =>
      let h := hTheta a b c u v k rfl
      exact
        { factor := thetaKGeneralFactor a b c u v k h
          marked_eq := libraryMarkedGraph_TMTheta_eq_thetaFactor
            a b c u v k h
          genus_eq := by
            change _root_.genus (thetaBanana a b c h.1 h.2.1 h.2.2.1).graph = 2
            exact (thetaBanana a b c h.1 h.2.1 h.2.2.1).genus_graph
          period_eq := rfl }

/-- A list-level realization records exactly the three pieces of bookkeeping
needed to apply the `Bananas` mixed-chain theorem: the displayed marked graphs,
their genera, and their periods. -/
private structure ReadableFactorsRealization
    (source : List CycleThetaFactor) where
  libraryFactors : List _root_.Bananas.KGeneralChainFactor
  length_eq : libraryFactors.length = source.length
  marked_eq :
    source.map (fun F => libraryMarkedGraph F.markedGraph) =
      libraryFactors.map _root_.Bananas.KGeneralChainFactor.marked
  genus_eq :
    libraryFactors.map (fun F => _root_.genus F.marked.graph) =
      source.map (fun F => (F.factorGenus : ℤ))
  period_at : ∀ (i : ℕ)
      (hi : i < libraryFactors.length) (hi' : i < source.length),
    (libraryFactors.get ⟨i, hi⟩).period =
      (source.get ⟨i, hi'⟩).period

private noncomputable def realizeReadableFactors
    (source : List CycleThetaFactor)
    (hCycle : ∀ m n, CycleThetaFactor.cycle m n ∈ source →
      0 < m ∧ 0 < n)
    (hTheta : ∀ a b c u v k,
      CycleThetaFactor.theta a b c u v k ∈ source →
        evenlyMarkedK a b c u v k) :
    ReadableFactorsRealization source := by
  induction source with
  | nil =>
      exact
        { libraryFactors := []
          length_eq := rfl
          marked_eq := rfl
          genus_eq := rfl
          period_at := by intro i hi; simp at hi }
  | cons F rest ih =>
      let head := realizeReadableFactor F
        (fun m n hF => hCycle m n (by simp [hF]))
        (fun a b c u v k hF => hTheta a b c u v k (by simp [hF]))
      let tail := ih
        (fun m n hmem => hCycle m n (by simp [hmem]))
        (fun a b c u v k hmem => hTheta a b c u v k (by simp [hmem]))
      exact
        { libraryFactors := head.factor :: tail.libraryFactors
          length_eq := by simp [tail.length_eq]
          marked_eq := by
            simp only [List.map_cons, List.cons.injEq]
            exact ⟨head.marked_eq, tail.marked_eq⟩
          genus_eq := by
            simp only [List.map_cons, List.cons.injEq]
            exact ⟨head.genus_eq, tail.genus_eq⟩
          period_at := by
            intro i hi hi'
            cases i with
            | zero => exact head.period_eq
            | succ i =>
                exact tail.period_at i (by simpa using hi) (by simpa using hi') }

private theorem totalGenus_cast_eq_sum (source : List CycleThetaFactor) :
    (CycleThetaFactor.totalGenus source : ℤ) =
      (source.map fun F => (F.factorGenus : ℤ)).sum := by
  unfold CycleThetaFactor.totalGenus
  induction source with
  | nil => simp
  | cons F rest ih =>
      simp [ih]

private theorem realized_chainFactorGenus_take
    {source : List CycleThetaFactor}
    (R : ReadableFactorsRealization source) (n : ℕ) :
    _root_.Bananas.chainFactorGenus (R.libraryFactors.take n) =
      (CycleThetaFactor.totalGenus (source.take n) : ℤ) := by
  have h := congrArg (fun values : List ℤ => (values.take n).sum) R.genus_eq
  rw [totalGenus_cast_eq_sum]
  simpa [_root_.Bananas.chainFactorGenus] using h

private theorem realized_chainFactorGenus_drop
    {source : List CycleThetaFactor}
    (R : ReadableFactorsRealization source) (n : ℕ) :
    _root_.Bananas.chainFactorGenus (R.libraryFactors.drop n) =
      (CycleThetaFactor.totalGenus (source.drop n) : ℤ) := by
  have h := congrArg (fun values : List ℤ => (values.drop n).sum) R.genus_eq
  rw [totalGenus_cast_eq_sum]
  simpa [_root_.Bananas.chainFactorGenus] using h

private theorem realized_chainMinBudget
    {source : List CycleThetaFactor}
    (R : ReadableFactorsRealization source)
    (hBudget : mixed_chain_torsion_budget source) :
    _root_.Bananas.ChainMinBudget R.libraryFactors := by
  intro i hi
  have hi' : i < source.length := by simpa [R.length_eq] using hi
  have h := hBudget i hi'
  rw [realized_chainFactorGenus_take R,
    realized_chainFactorGenus_drop R, R.period_at i hi hi']
  exact_mod_cast h

private theorem realized_chainSuffixBudget
    {source : List CycleThetaFactor}
    (R : ReadableFactorsRealization source)
    (hBudget : mixed_chain_left_torsion_budget source) :
    _root_.Bananas.ChainSuffixBudget R.libraryFactors := by
  apply (_root_.Bananas.chainSuffixBudget_iff_indexed _).mpr
  intro i hi
  have hi' : i < source.length := by simpa [R.length_eq] using hi
  have h := hBudget i hi'
  rw [realized_chainFactorGenus_drop R, R.period_at i hi hi']
  exact_mod_cast h

/-- The local witness-based gonality predicate is exactly the library's
predicate after crossing the graph-structure boundary. -/
private theorem gonality_leq_library_iff (G : CFGraph) (k : ℤ) :
    gonality_leq G k ↔ _root_.gonality_leq (libraryGraph G) k := by
  constructor
  · rintro ⟨D, hdegree, hrank⟩
    exact ⟨D, (_root_.rank_geq_iff (libraryGraph G) D 1).mp hrank, hdegree⟩
  · rintro ⟨D, hrank, hdegree⟩
    exact ⟨D, hdegree, (_root_.rank_geq_iff (libraryGraph G) D 1).mpr hrank⟩

/-! ## Chains of loops: the CDPR theorem and its sharp extensions -/

/-- **Marked CDPR theorem.**  At the left endpoint of a generic chain of
`g` loops, a degree-`d`, rank-at-least-`r` divisor cannot retain rank zero
after removing `r + rho + 1` chips. -/
theorem cdpr_marked_no_high_multiplicity
    (lengths : List (ℕ × ℕ)) (h_general : cdpr_general lengths)
    (D : CFDiv (chain_of_cycles lengths).graph) (r d : ℤ)
    (h_rank_nonnegative : 0 ≤ r)
    (h_rank_below_genus : r < genus (chain_of_cycles lengths).graph)
    (h_degree : deg D = d) (h_rank : rank_geq _ D r)
    (h_rho : 0 ≤ brill_noether_number (chain_of_cycles lengths).graph r d) :
    ¬rank_geq (chain_of_cycles lengths).graph
      (D - (r + brill_noether_number (chain_of_cycles lengths).graph r d + 1) •
        one_chip (chain_of_cycles lengths).u) 0 := by
  cases lengths with
  | nil => simp [cdpr_general] at h_general
  | cons mn rest =>
      let hRestPositive : ∀ pair ∈ rest, 0 < pair.1 ∧ 0 < pair.2 :=
        fun pair hpair => h_general.2.1 pair (by simp [hpair])
      let P : _root_.ChainOfLoops.Loop :=
        { top := mn.1
          bot := mn.2
          top_pos := (h_general.2.1 mn (by simp)).1
          bot_pos := (h_general.2.1 mn (by simp)).2 }
      let L : List _root_.ChainOfLoops.Loop :=
        loopsOfPositive rest hRestPositive
      have hGenericAll := loopsOfPositive_cdprGeneric (mn :: rest) h_general
      have hGeneric : _root_.ChainOfLoops.CDPRGeneric (P :: L) := by
        simpa only [P, L, loopsOfPositive] using hGenericAll
      have hg : 2 ≤ L.length + 1 := by
        dsimp only [L]
        rw [loopsOfPositive_length]
        simpa using h_general.1
      have hHead : libraryMarkedGraph (twice_marked_cycle mn.1 mn.2) =
          P.factor.marked := by
        exact libraryMarkedGraph_twice_marked_cycle mn.1 mn.2
          (h_general.2.1 mn (by simp)).1
          (h_general.2.1 mn (by simp)).2
      have hTail := libraryMarkedGraphs_cycles_eq rest hRestPositive
      have hMarked :
          libraryMarkedGraph (chain_of_cycles (mn :: rest)) =
            P.factor.marked.bridgeChain
              ((L.map _root_.ChainOfLoops.Loop.factor).map
                _root_.Bananas.KGeneralChainFactor.marked) := by
        change libraryMarkedGraph
            (glue_chain (twice_marked_cycle mn.1 mn.2 ::
              rest.map fun pair => twice_marked_cycle pair.1 pair.2)) = _
        rw [libraryMarkedGraph_glue_chain_cons, hHead]
        congr 1
        simpa only [L, List.map_map, Function.comp_def] using hTail
      let source := libraryMarkedGraph (chain_of_cycles (mn :: rest))
      let target := P.factor.marked.chain
        ((L.map _root_.ChainOfLoops.Loop.factor).map
          _root_.Bananas.KGeneralChainFactor.marked)
      let transport : _root_.Bananas.LeftRankTransport source target :=
        by
          dsimp only [source]
          rw [hMarked]
          exact _root_.Bananas.contractBridgeChain P.factor.marked
            ((L.map _root_.ChainOfLoops.Loop.factor).map
              _root_.Bananas.KGeneralChainFactor.marked)
      change _root_.CFDiv
        (libraryMarkedGraph (chain_of_cycles (mn :: rest))).graph at D
      change _root_.deg D = d at h_degree
      change _root_.rank_geq
        (libraryMarkedGraph (chain_of_cycles (mn :: rest))).graph D r at h_rank
      change r < _root_.genus
        (libraryMarkedGraph (chain_of_cycles (mn :: rest))).graph
        at h_rank_below_genus
      change 0 ≤ _root_.Utilities.bnNumber
        (libraryMarkedGraph (chain_of_cycles (mn :: rest))).graph r d at h_rho
      change ¬_root_.rank_geq
        (libraryMarkedGraph (chain_of_cycles (mn :: rest))).graph
        (D - (r + _root_.Utilities.bnNumber
          (libraryMarkedGraph (chain_of_cycles (mn :: rest))).graph r d + 1) •
            _root_.one_chip
              (libraryMarkedGraph (chain_of_cycles (mn :: rest))).left) 0
      intro hResidual
      have hRankSource : r ≤ _root_.rank source.graph D :=
        (_root_.rank_geq_iff source.graph D r).mp h_rank
      have hResidualSource : 0 ≤ _root_.rank source.graph
          (D - (r + _root_.Utilities.bnNumber source.graph r d + 1) •
            _root_.one_chip source.left) :=
        (_root_.rank_geq_iff source.graph _ 0).mp hResidual
      have hRankTarget : r ≤ _root_.rank target.graph (transport.mapDiv D) := by
        rw [transport.rank_map]
        exact hRankSource
      have hDegreeTarget : _root_.deg (transport.mapDiv D) = d := by
        rw [transport.deg_map, h_degree]
      have hBoundTarget : r < _root_.genus target.graph := by
        rw [transport.genus_eq]
        exact h_rank_below_genus
      have hRhoTarget : 0 ≤ _root_.Utilities.bnNumber target.graph r d := by
        simpa only [_root_.Utilities.bnNumber, _root_.Utilities.rectangleWidth,
          transport.genus_eq] using h_rho
      have hNegative := _root_.ChainOfLoops.cdpr_no_high_multiplicity_left
        P L hg hGeneric (transport.mapDiv D) r d h_rank_nonnegative
        hBoundTarget hDegreeTarget hRankTarget hRhoTarget
      change _root_.rank target.graph
        (transport.mapDiv D -
          (r + _root_.Utilities.bnNumber target.graph r d + 1) •
            _root_.one_chip target.left) < 0 at hNegative
      have hBn : _root_.Utilities.bnNumber target.graph r d =
          _root_.Utilities.bnNumber source.graph r d := by
        simp only [_root_.Utilities.bnNumber, _root_.Utilities.rectangleWidth,
          transport.genus_eq]
      have hMap : transport.mapDiv
          (D - (r + _root_.Utilities.bnNumber source.graph r d + 1) •
            _root_.one_chip source.left) =
          transport.mapDiv D -
            (r + _root_.Utilities.bnNumber target.graph r d + 1) •
              _root_.one_chip target.left := by
        rw [transport.map_sub, transport.map_zsmul,
          transport.map_one_chip, hBn]
      rw [← hMap, transport.rank_map] at hNegative
      exact (not_lt_of_ge hResidualSource) hNegative

/-- **CDPR Theorem 1.1(1), discrete form.**  A generic chain of cycles is
Brill--Noether general in the nonexistence sense. -/
theorem cdpr_chain_brill_noether_general
    (lengths : List (ℕ × ℕ)) (h_general : cdpr_general lengths) :
    brill_noether_general (chain_of_cycles lengths).graph := by
  cases lengths with
  | nil => simp [cdpr_general] at h_general
  | cons mn rest =>
      let hRestPositive : ∀ pair ∈ rest, 0 < pair.1 ∧ 0 < pair.2 :=
        fun pair hpair => h_general.2.1 pair (by simp [hpair])
      let P : _root_.ChainOfLoops.Loop :=
        { top := mn.1
          bot := mn.2
          top_pos := (h_general.2.1 mn (by simp)).1
          bot_pos := (h_general.2.1 mn (by simp)).2 }
      let L : List _root_.ChainOfLoops.Loop :=
        loopsOfPositive rest hRestPositive
      have hGenericAll := loopsOfPositive_cdprGeneric (mn :: rest) h_general
      have hGeneric : _root_.ChainOfLoops.CDPRGeneric (P :: L) := by
        simpa only [P, L, loopsOfPositive] using hGenericAll
      have hg : 2 ≤ L.length + 1 := by
        dsimp only [L]
        rw [loopsOfPositive_length]
        simpa using h_general.1
      have hBudget :=
        (_root_.ChainOfLoops.torsion_bounds_of_cdprGeneric
          P L hg hGeneric).1
      have hHead : libraryMarkedGraph (twice_marked_cycle mn.1 mn.2) =
          P.factor.marked := by
        exact libraryMarkedGraph_twice_marked_cycle mn.1 mn.2
          (h_general.2.1 mn (by simp)).1
          (h_general.2.1 mn (by simp)).2
      have hTail := libraryMarkedGraphs_cycles_eq rest hRestPositive
      have hMarked :
          libraryMarkedGraph (chain_of_cycles (mn :: rest)) =
            P.factor.marked.bridgeChain
              ((L.map _root_.ChainOfLoops.Loop.factor).map
                _root_.Bananas.KGeneralChainFactor.marked) := by
        change libraryMarkedGraph
            (glue_chain (twice_marked_cycle mn.1 mn.2 ::
              rest.map fun pair => twice_marked_cycle pair.1 pair.2)) = _
        rw [libraryMarkedGraph_glue_chain_cons, hHead]
        congr 1
        simpa only [L, List.map_map, Function.comp_def] using hTail
      have hWedgeGeneral :=
        _root_.ChainOfLoops.brillNoetherGeneral_chainOfLoops P L hBudget
      apply (brill_noether_general_library_iff _).mpr
      change _root_.Bananas.BrillNoetherGeneral
        (libraryMarkedGraph (chain_of_cycles (mn :: rest))).graph
      rw [hMarked]
      exact brillNoetherGeneral_of_leftRankTransport
        (_root_.Bananas.contractBridgeChain P.factor.marked
          ((L.map _root_.ChainOfLoops.Loop.factor).map
            _root_.Bananas.KGeneralChainFactor.marked)) hWedgeGeneral

/-- The sharp cycle-chain form behind CDPR.  Numbering the `g` cycles from
`1` to `g`, the torsion order of cycle `i` need only exceed
`min(i, g + 1 - i)`. -/
theorem cycle_chain_brill_noether_general_of_torsion
    (lengths : List (ℕ × ℕ))
    (h_positive : ∀ mn ∈ lengths, 0 < mn.1 ∧ 0 < mn.2)
    (h_torsion : ∀ i : ℕ, ∀ hi : i < lengths.length,
      torsion_gt
        (twice_marked_cycle
          (lengths.get ⟨i, hi⟩).1 (lengths.get ⟨i, hi⟩).2)
        (min (i + 1) (lengths.length - i))) :
    brill_noether_general (chain_of_cycles lengths).graph := by
  cases lengths with
  | nil =>
      apply (brill_noether_general_library_iff _).mpr
      change _root_.Bananas.BrillNoetherGeneral
        (libraryMarkedGraph trivial_twice_marked_graph).graph
      exact trivial_library_brillNoetherGeneral
  | cons mn rest =>
      let hRestPositive : ∀ pair ∈ rest, 0 < pair.1 ∧ 0 < pair.2 :=
        fun pair hpair => h_positive pair (by simp [hpair])
      let P : _root_.ChainOfLoops.Loop :=
        { top := mn.1
          bot := mn.2
          top_pos := (h_positive mn (by simp)).1
          bot_pos := (h_positive mn (by simp)).2 }
      let L : List _root_.ChainOfLoops.Loop :=
        loopsOfPositive rest hRestPositive
      have hHead : libraryMarkedGraph (twice_marked_cycle mn.1 mn.2) =
          P.factor.marked := by
        exact libraryMarkedGraph_twice_marked_cycle mn.1 mn.2
          (h_positive mn (by simp)).1 (h_positive mn (by simp)).2
      have hTail := libraryMarkedGraphs_cycles_eq rest hRestPositive
      have hMarked :
          libraryMarkedGraph (chain_of_cycles (mn :: rest)) =
            P.factor.marked.bridgeChain
              ((L.map _root_.ChainOfLoops.Loop.factor).map
                _root_.Bananas.KGeneralChainFactor.marked) := by
        change libraryMarkedGraph
            (glue_chain (twice_marked_cycle mn.1 mn.2 ::
              rest.map fun pair => twice_marked_cycle pair.1 pair.2)) = _
        rw [libraryMarkedGraph_glue_chain_cons, hHead]
        congr 1
        simpa only [L, List.map_map, Function.comp_def] using hTail
      have hBudgetAll := loop_minBudget_of_semantic_torsion
        (mn :: rest) h_positive h_torsion
      have hBudget : ∀ (i : ℕ) (hi : i < (P :: L).length),
          min ((i : ℤ) + 1) (((P :: L).length : ℤ) - (i : ℤ)) <
            (((P :: L).get ⟨i, hi⟩).torsionOrder : ℤ) := by
        simpa only [P, L, loopsOfPositive] using hBudgetAll
      have hWedgeGeneral :=
        _root_.ChainOfLoops.brillNoetherGeneral_chainOfLoops P L hBudget
      apply (brill_noether_general_library_iff _).mpr
      change _root_.Bananas.BrillNoetherGeneral
        (libraryMarkedGraph (chain_of_cycles (mn :: rest))).graph
      rw [hMarked]
      exact brillNoetherGeneral_of_leftRankTransport
        (_root_.Bananas.contractBridgeChain P.factor.marked
          ((L.map _root_.ChainOfLoops.Loop.factor).map
            _root_.Bananas.KGeneralChainFactor.marked)) hWedgeGeneral

set_option linter.unusedVariables false in
/-- **Marked mixed cycle/theta chain theorem.**  Under the sharp one-sided
torsion budget, a degree-`d`, rank-at-least-`r` divisor cannot retain rank zero
after removing `r + rho + 1` chips at the left endpoint of the chain. -/
theorem cycle_theta_chain_marked_no_high_multiplicity
    (factors : List CycleThetaFactor)
    (h_cycles_positive : ∀ m n : ℕ,
      CycleThetaFactor.cycle m n ∈ factors → 0 < m ∧ 0 < n)
    (h_thetas_evenly_marked : ∀ a b c u v k : ℕ,
      CycleThetaFactor.theta a b c u v k ∈ factors →
        evenlyMarkedK a b c u v k)
    (h_torsion : mixed_chain_left_torsion_budget factors)
    (D : CFDiv (chain_of_cycles_and_thetas factors).graph) (r d : ℤ)
    (h_rank_nonnegative : 0 ≤ r)
    (h_rank_below_genus :
      r < genus (chain_of_cycles_and_thetas factors).graph)
    (h_degree : deg D = d) (h_rank : rank_geq _ D r)
    (h_rho : 0 ≤ brill_noether_number
      (chain_of_cycles_and_thetas factors).graph r d) :
    ¬rank_geq (chain_of_cycles_and_thetas factors).graph
      (D - (r + brill_noether_number
        (chain_of_cycles_and_thetas factors).graph r d + 1) •
          one_chip (chain_of_cycles_and_thetas factors).u) 0 := by
  cases factors with
  | nil =>
      have hGenus : genus (chain_of_cycles_and_thetas []).graph = 0 := rfl
      rw [hGenus] at h_rank_below_genus
      omega
  | cons first rest =>
      let R := realizeReadableFactors (first :: rest)
        h_cycles_positive h_thetas_evenly_marked
      have hSuffix := realized_chainSuffixBudget R h_torsion
      cases hLibrary : R.libraryFactors with
      | nil =>
          have hLength := R.length_eq
          rw [hLibrary] at hLength
          simp at hLength
      | cons F tail =>
          have hMarked := R.marked_eq
          rw [hLibrary] at hMarked
          have hMarkedParts :
              libraryMarkedGraph first.markedGraph = F.marked ∧
              rest.map (fun Q => libraryMarkedGraph Q.markedGraph) =
                tail.map _root_.Bananas.KGeneralChainFactor.marked := by
            simpa only [List.map_cons, List.cons.injEq] using hMarked
          rw [hLibrary] at hSuffix
          have hSourceMarked :
              libraryMarkedGraph
                  (chain_of_cycles_and_thetas (first :: rest)) =
                F.marked.bridgeChain
                  (tail.map _root_.Bananas.KGeneralChainFactor.marked) := by
            change libraryMarkedGraph
                (glue_chain (first.markedGraph ::
                  rest.map CycleThetaFactor.markedGraph)) = _
            rw [libraryMarkedGraph_glue_chain_cons, hMarkedParts.1]
            simp only [List.map_map]
            have hTail :
                rest.map
                    (libraryMarkedGraph ∘ CycleThetaFactor.markedGraph) =
                  tail.map _root_.Bananas.KGeneralChainFactor.marked := by
              simpa only [Function.comp_def] using hMarkedParts.2
            rw [hTail]
          let source := libraryMarkedGraph
            (chain_of_cycles_and_thetas (first :: rest))
          let target := F.marked.chain
            (tail.map _root_.Bananas.KGeneralChainFactor.marked)
          let transport : _root_.Bananas.LeftRankTransport source target := by
            dsimp only [source]
            rw [hSourceMarked]
            exact _root_.Bananas.contractBridgeChain F.marked
              (tail.map _root_.Bananas.KGeneralChainFactor.marked)
          change _root_.CFDiv source.graph at D
          change _root_.deg D = d at h_degree
          change _root_.rank_geq source.graph D r at h_rank
          change ¬_root_.rank_geq source.graph
            (D - (r + _root_.Utilities.bnNumber source.graph r d + 1) •
              _root_.one_chip source.left) 0
          intro hResidual
          have hRankSource : r ≤ _root_.rank source.graph D :=
            (_root_.rank_geq_iff source.graph D r).mp h_rank
          have hResidualSource : 0 ≤ _root_.rank source.graph
              (D - (r + _root_.Utilities.bnNumber source.graph r d + 1) •
                _root_.one_chip source.left) :=
            (_root_.rank_geq_iff source.graph _ 0).mp hResidual
          have hRankTarget : r ≤
              _root_.rank target.graph (transport.mapDiv D) := by
            rw [transport.rank_map]
            exact hRankSource
          have hDegreeTarget : _root_.deg (transport.mapDiv D) = d := by
            rw [transport.deg_map, h_degree]
          have hOnceMarked : _root_.Bananas.OnceMarkedBrillNoetherGeneral
              (_root_.Bananas.reversedMarkedChain F tail).graph
              ((_root_.Bananas.reversedFactorChainIso F tail).vertexEquiv
                target.left) := by
            rw [_root_.Bananas.reversedFactorChainIso_apply_left]
            exact
              _root_.Bananas.onceMarkedBrillNoetherGeneral_reversedMixedTorsionChain
                F tail hSuffix
          have hNegative :=
            _root_.ChainOfLoops.rank_sub_high_multiplicity_neg_of_iso
              (_root_.Bananas.reversedFactorChainIso F tail)
              (_root_.Bananas.graph_connected_factorChain F tail)
              target.left hOnceMarked (transport.mapDiv D) r
              h_rank_nonnegative hRankTarget
          rw [hDegreeTarget] at hNegative
          have hBn : _root_.Utilities.bnNumber target.graph r d =
              _root_.Utilities.bnNumber source.graph r d := by
            simp only [_root_.Utilities.bnNumber,
              _root_.Utilities.rectangleWidth, transport.genus_eq]
          have hMap : transport.mapDiv
              (D - (r + _root_.Utilities.bnNumber source.graph r d + 1) •
                _root_.one_chip source.left) =
              transport.mapDiv D -
                (r + _root_.Utilities.bnNumber target.graph r d + 1) •
                  _root_.one_chip target.left := by
            rw [transport.map_sub, transport.map_zsmul,
              transport.map_one_chip, hBn]
          rw [← hMap, transport.rank_map] at hNegative
          exact (not_lt_of_ge hResidualSource) hNegative

/-- **Mixed cycle/theta chain theorem.**  A chain whose factors are cycles or
evenly marked theta graphs is Brill--Noether general whenever every cycle is
nondegenerate and each factor satisfies the sharp minimum genus/torsion
budget.  This is the existential/unmarked conclusion of Corollary 6.16. -/
theorem cycle_theta_chain_brill_noether_general
    (factors : List CycleThetaFactor)
    (h_cycles_positive : ∀ m n : ℕ,
      CycleThetaFactor.cycle m n ∈ factors → 0 < m ∧ 0 < n)
    (h_thetas_evenly_marked : ∀ a b c u v k : ℕ,
      CycleThetaFactor.theta a b c u v k ∈ factors →
        evenlyMarkedK a b c u v k)
    (h_torsion : mixed_chain_torsion_budget factors) :
    brill_noether_general (chain_of_cycles_and_thetas factors).graph := by
  cases factors with
  | nil =>
      apply (brill_noether_general_library_iff _).mpr
      change _root_.Bananas.BrillNoetherGeneral
        (libraryMarkedGraph trivial_twice_marked_graph).graph
      exact trivial_library_brillNoetherGeneral
  | cons first rest =>
      let R := realizeReadableFactors (first :: rest)
        h_cycles_positive h_thetas_evenly_marked
      have hMin := realized_chainMinBudget R h_torsion
      cases hLibrary : R.libraryFactors with
      | nil =>
          have hLength := R.length_eq
          rw [hLibrary] at hLength
          simp at hLength
      | cons F tail =>
          have hMarked := R.marked_eq
          rw [hLibrary] at hMarked
          have hMarkedParts :
              libraryMarkedGraph first.markedGraph = F.marked ∧
              rest.map (fun Q => libraryMarkedGraph Q.markedGraph) =
                tail.map _root_.Bananas.KGeneralChainFactor.marked := by
            simpa only [List.map_cons, List.cons.injEq] using hMarked
          rw [hLibrary] at hMin
          have hWedgeGeneral :=
            _root_.Bananas.brillNoetherGeneral_mixedTorsionChain_of_minBudget
              F tail hMin
          apply (brill_noether_general_library_iff _).mpr
          change _root_.Bananas.BrillNoetherGeneral
            (libraryMarkedGraph
              (glue_chain (first.markedGraph ::
                rest.map CycleThetaFactor.markedGraph))).graph
          rw [libraryMarkedGraph_glue_chain_cons, hMarkedParts.1]
          simp only [List.map_map]
          have hTail :
              rest.map (libraryMarkedGraph ∘ CycleThetaFactor.markedGraph) =
                tail.map _root_.Bananas.KGeneralChainFactor.marked := by
            simpa only [Function.comp_def] using hMarkedParts.2
          rw [hTail]
          exact brillNoetherGeneral_of_leftRankTransport
            (_root_.Bananas.contractBridgeChain F.marked
              (tail.map _root_.Bananas.KGeneralChainFactor.marked))
            hWedgeGeneral

/-! ## Exact gonality of common-torsion chains -/

/-- The readable bridge-chain has the sum of the displayed factor genera and
is connected as soon as it is nonempty and its factor guards hold. -/
private theorem cycle_theta_chain_connected_and_genus
    (factors : List CycleThetaFactor)
    (h_nonempty : factors ≠ [])
    (h_cycles_positive : ∀ m n : ℕ,
      CycleThetaFactor.cycle m n ∈ factors → 0 < m ∧ 0 < n)
    (h_thetas_evenly_marked : ∀ a b c u v period : ℕ,
      CycleThetaFactor.theta a b c u v period ∈ factors →
        evenlyMarkedK a b c u v period) :
    graph_connected (chain_of_cycles_and_thetas factors).graph ∧
      genus (chain_of_cycles_and_thetas factors).graph =
        (CycleThetaFactor.totalGenus factors : ℤ) := by
  cases factors with
  | nil => exact (h_nonempty rfl).elim
  | cons first rest =>
      let R := realizeReadableFactors (first :: rest)
        h_cycles_positive h_thetas_evenly_marked
      cases hLibrary : R.libraryFactors with
      | nil =>
          have hLength := R.length_eq
          rw [hLibrary] at hLength
          simp at hLength
      | cons F tail =>
          have hMarked := R.marked_eq
          rw [hLibrary] at hMarked
          have hMarkedParts :
              libraryMarkedGraph first.markedGraph = F.marked ∧
              rest.map (fun Q => libraryMarkedGraph Q.markedGraph) =
                tail.map _root_.Bananas.KGeneralChainFactor.marked := by
            simpa only [List.map_cons, List.cons.injEq] using hMarked
          have hMarkedChain :
              libraryMarkedGraph
                  (chain_of_cycles_and_thetas (first :: rest)) =
                F.marked.bridgeChain
                  (tail.map _root_.Bananas.KGeneralChainFactor.marked) := by
            change libraryMarkedGraph
              (glue_chain (first.markedGraph ::
                rest.map CycleThetaFactor.markedGraph)) = _
            rw [libraryMarkedGraph_glue_chain_cons, hMarkedParts.1]
            simp only [List.map_map]
            have hTail :
                rest.map
                    (libraryMarkedGraph ∘ CycleThetaFactor.markedGraph) =
                  tail.map _root_.Bananas.KGeneralChainFactor.marked := by
              simpa only [Function.comp_def] using hMarkedParts.2
            rw [hTail]
          have hGenusFactors := congrArg List.sum R.genus_eq
          rw [hLibrary] at hGenusFactors
          simp only [List.map_cons, List.sum_cons] at hGenusFactors
          have hFactorSum :
              _root_.genus F.marked.graph +
                  (tail.map fun Q => _root_.genus Q.marked.graph).sum =
                (CycleThetaFactor.totalGenus (first :: rest) : ℤ) := by
            calc
              _root_.genus F.marked.graph +
                    (tail.map fun Q => _root_.genus Q.marked.graph).sum =
                  ((first :: rest).map
                    fun Q => (Q.factorGenus : ℤ)).sum := hGenusFactors
              _ = (CycleThetaFactor.totalGenus (first :: rest) : ℤ) :=
                (totalGenus_cast_eq_sum (first :: rest)).symm
          have hBridgeGenus :
              _root_.genus
                  (F.marked.bridgeChain
                    (tail.map
                      _root_.Bananas.KGeneralChainFactor.marked)).graph =
                (CycleThetaFactor.totalGenus (first :: rest) : ℤ) := by
            let transport := _root_.Bananas.contractBridgeChain F.marked
              (tail.map _root_.Bananas.KGeneralChainFactor.marked)
            calc
              _root_.genus
                    (F.marked.bridgeChain
                      (tail.map
                        _root_.Bananas.KGeneralChainFactor.marked)).graph =
                  _root_.genus
                    (F.marked.chain
                      (tail.map
                        _root_.Bananas.KGeneralChainFactor.marked)).graph :=
                transport.genus_eq.symm
              _ = _root_.genus F.marked.graph +
                    (tail.map fun Q => _root_.genus Q.marked.graph).sum := by
                simpa only [List.map_map, Function.comp_def] using
                  (_root_.Utilities.MarkedGraph.genus_chain F.marked
                    (tail.map _root_.Bananas.KGeneralChainFactor.marked))
              _ = (CycleThetaFactor.totalGenus (first :: rest) : ℤ) :=
                hFactorSum
          constructor
          · change _root_.graph_connected
              (libraryMarkedGraph
                (chain_of_cycles_and_thetas (first :: rest))).graph
            rw [hMarkedChain]
            apply _root_.Bananas.graph_connected_bridgeChain
            · exact F.connected
            · intro N hN
              obtain ⟨Q, _hQ, rfl⟩ := List.mem_map.mp hN
              exact Q.connected
          · change _root_.genus
              (libraryMarkedGraph
                (chain_of_cycles_and_thetas (first :: rest))).graph = _
            rw [hMarkedChain]
            exact hBridgeGenus

/-- **Exact gonality of a common-torsion cycle/theta chain.**  If every
factor has the same torsion order `k`, then the bridge-chain has gonality
exactly `k` whenever `k` is at most the generic gonality
`floor((g+3)/2)` of its total genus `g`.

The theta factors are allowed because the proof uses the common
`k`-general-transmission package, not a factorwise gonality assertion. -/
theorem cycle_theta_chain_gonality_eq_common_torsion
    (factors : List CycleThetaFactor) (k : ℕ)
    (h_nonempty : factors ≠ [])
    (h_cycles_positive : ∀ m n : ℕ,
      CycleThetaFactor.cycle m n ∈ factors → 0 < m ∧ 0 < n)
    (h_thetas_evenly_marked : ∀ a b c u v period : ℕ,
      CycleThetaFactor.theta a b c u v period ∈ factors →
        evenlyMarkedK a b c u v period)
    (h_common_torsion : ∀ F ∈ factors, F.period = k)
    (h_small : k ≤ (CycleThetaFactor.totalGenus factors + 3) / 2) :
    gonality_eq (chain_of_cycles_and_thetas factors).graph (k : ℤ) := by
  cases factors with
  | nil => exact (h_nonempty rfl).elim
  | cons first rest =>
      let R := realizeReadableFactors (first :: rest)
        h_cycles_positive h_thetas_evenly_marked
      cases hLibrary : R.libraryFactors with
      | nil =>
          have hLength := R.length_eq
          rw [hLibrary] at hLength
          simp at hLength
      | cons F tail =>
          have hMarked := R.marked_eq
          rw [hLibrary] at hMarked
          have hMarkedParts :
              libraryMarkedGraph first.markedGraph = F.marked ∧
              rest.map (fun Q => libraryMarkedGraph Q.markedGraph) =
                tail.map _root_.Bananas.KGeneralChainFactor.marked := by
            simpa only [List.map_cons, List.cons.injEq] using hMarked
          have hMarkedChain :
              libraryMarkedGraph
                  (chain_of_cycles_and_thetas (first :: rest)) =
                F.marked.bridgeChain
                  (tail.map _root_.Bananas.KGeneralChainFactor.marked) := by
            change libraryMarkedGraph
              (glue_chain (first.markedGraph ::
                rest.map CycleThetaFactor.markedGraph)) = _
            rw [libraryMarkedGraph_glue_chain_cons, hMarkedParts.1]
            simp only [List.map_map]
            have hTail :
                rest.map
                    (libraryMarkedGraph ∘ CycleThetaFactor.markedGraph) =
                  tail.map _root_.Bananas.KGeneralChainFactor.marked := by
              simpa only [Function.comp_def] using hMarkedParts.2
            rw [hTail]
          have hAllPeriod : ∀ Q ∈ R.libraryFactors, Q.period = k := by
            intro Q hQ
            obtain ⟨i, hi, hget⟩ := List.mem_iff_getElem.mp hQ
            have hi' : i < (first :: rest).length := by
              simpa [R.length_eq] using hi
            have hPeriod := R.period_at i hi hi'
            have hSourcePeriod := h_common_torsion
              ((first :: rest).get ⟨i, hi'⟩)
              (List.get_mem (first :: rest) ⟨i, hi'⟩)
            rw [← hget]
            exact hPeriod.trans hSourcePeriod
          have hFPeriod : F.period = k :=
            hAllPeriod F (by simp [hLibrary])
          have hTailPeriod : ∀ Q ∈ tail, Q.period = k := by
            intro Q hQ
            exact hAllPeriod Q (by simp [hLibrary, hQ])
          have hFGeneral : _root_.Bananas.KGeneralTransmission
              (_root_.Bananas.mark F.marked.graph
                F.marked.left F.marked.right) k := by
            simpa [hFPeriod] using F.kGeneral
          have hTailGeneral : ∀ N ∈
              tail.map _root_.Bananas.KGeneralChainFactor.marked,
              _root_.Bananas.KGeneralTransmission
                (_root_.Bananas.mark N.graph N.left N.right) k := by
            intro N hN
            obtain ⟨Q, hQ, rfl⟩ := List.mem_map.mp hN
            simpa [hTailPeriod Q hQ] using Q.kGeneral
          have hTailConnected : ∀ N ∈
              tail.map _root_.Bananas.KGeneralChainFactor.marked,
              _root_.graph_connected N.graph := by
            intro N hN
            obtain ⟨Q, _hQ, rfl⟩ := List.mem_map.mp hN
            exact Q.connected
          have hGenusFactors := congrArg List.sum R.genus_eq
          rw [hLibrary] at hGenusFactors
          simp only [List.map_cons, List.sum_cons] at hGenusFactors
          have hFactorSum :
              _root_.genus F.marked.graph +
                  (tail.map fun Q => _root_.genus Q.marked.graph).sum =
                (CycleThetaFactor.totalGenus (first :: rest) : ℤ) := by
            calc
              _root_.genus F.marked.graph +
                    (tail.map fun Q => _root_.genus Q.marked.graph).sum =
                  ((first :: rest).map
                    fun Q => (Q.factorGenus : ℤ)).sum := hGenusFactors
              _ = (CycleThetaFactor.totalGenus (first :: rest) : ℤ) :=
                (totalGenus_cast_eq_sum (first :: rest)).symm
          have hBridgeGenus :
              _root_.genus
                  (F.marked.bridgeChain
                    (tail.map
                      _root_.Bananas.KGeneralChainFactor.marked)).graph =
                (CycleThetaFactor.totalGenus (first :: rest) : ℤ) := by
            let transport := _root_.Bananas.contractBridgeChain F.marked
              (tail.map _root_.Bananas.KGeneralChainFactor.marked)
            calc
              _root_.genus
                    (F.marked.bridgeChain
                      (tail.map
                        _root_.Bananas.KGeneralChainFactor.marked)).graph =
                  _root_.genus
                    (F.marked.chain
                      (tail.map
                        _root_.Bananas.KGeneralChainFactor.marked)).graph :=
                transport.genus_eq.symm
              _ = _root_.genus F.marked.graph +
                    (tail.map fun Q => _root_.genus Q.marked.graph).sum :=
                by
                  simpa only [List.map_map, Function.comp_def] using
                    (_root_.Utilities.MarkedGraph.genus_chain F.marked
                      (tail.map
                        _root_.Bananas.KGeneralChainFactor.marked))
              _ = (CycleThetaFactor.totalGenus (first :: rest) : ℤ) :=
                hFactorSum
          have hSmallLibrary :
              k ≤ ((_root_.genus
                (F.marked.bridgeChain
                  (tail.map
                    _root_.Bananas.KGeneralChainFactor.marked)).graph).toNat +
                    3) / 2 := by
            rw [hBridgeGenus, Int.toNat_natCast]
            exact h_small
          have hExact :=
            _root_.Bananas.exact_gonality_bridgeChain_of_commonPeriod
              F.marked
              (tail.map _root_.Bananas.KGeneralChainFactor.marked) k
              F.connected hFGeneral hTailConnected hTailGeneral hSmallLibrary
          unfold gonality_eq
          constructor
          · apply (gonality_leq_library_iff _ (k : ℤ)).mpr
            change _root_.gonality_leq
              (libraryMarkedGraph
                (chain_of_cycles_and_thetas (first :: rest))).graph k
            rw [hMarkedChain]
            obtain ⟨D, hdegree, hrank⟩ := hExact.1
            exact ⟨D, hrank, hdegree⟩
          · intro d hdk hLocal
            have hLibraryGonality :=
              (gonality_leq_library_iff _ d).mp hLocal
            change _root_.gonality_leq
              (libraryMarkedGraph
                (chain_of_cycles_and_thetas (first :: rest))).graph d at hLibraryGonality
            rw [hMarkedChain] at hLibraryGonality
            obtain ⟨D, hrank, hdegree⟩ := hLibraryGonality
            exact hExact.2 d hdk ⟨D, hdegree, hrank⟩

/-- Every gonality between two and the generic gonality occurs.  More
precisely, for every genus `g` and
`2 ≤ k ≤ floor((g+3)/2) = ceil(g/2)+1`, there is a connected finite graph of
genus `g` and divisorial gonality exactly `k`. -/
theorem exists_graph_of_genus_and_gonality
    (g k : ℕ) (hk : 2 ≤ k) (hkg : k ≤ (g + 3) / 2) :
    ∃ G : CFGraph.{0},
      graph_connected G ∧ genus G = (g : ℤ) ∧ gonality_eq G (k : ℤ) := by
  let factor : CycleThetaFactor := .cycle 1 (k - 1)
  let factors : List CycleThetaFactor := List.replicate g factor
  have hg : 0 < g := by
    have hmul : k * 2 ≤ g + 3 :=
      (Nat.le_div_iff_mul_le (by omega : 0 < 2)).mp hkg
    omega
  have hNonempty : factors ≠ [] := by simp [factors, hg.ne']
  have hCycles : ∀ m n : ℕ,
      CycleThetaFactor.cycle m n ∈ factors → 0 < m ∧ 0 < n := by
    intro m n hmem
    have hEq : CycleThetaFactor.cycle m n = factor :=
      (List.mem_replicate.mp hmem).2
    change CycleThetaFactor.cycle m n =
      CycleThetaFactor.cycle 1 (k - 1) at hEq
    injection hEq with hm hn
    subst m
    subst n
    omega
  have hThetas : ∀ a b c u v period : ℕ,
      CycleThetaFactor.theta a b c u v period ∈ factors →
        evenlyMarkedK a b c u v period := by
    intro a b c u v period hmem
    simp [factors, factor] at hmem
  have hPeriod : ∀ F ∈ factors, F.period = k := by
    intro F hF
    have hEq : F = factor := (List.mem_replicate.mp hF).2
    subst F
    simp only [factor, CycleThetaFactor.period, Nat.gcd_one_left, Nat.div_one]
    omega
  have hTotal : CycleThetaFactor.totalGenus factors = g := by
    simp [CycleThetaFactor.totalGenus, factors, factor,
      CycleThetaFactor.factorGenus]
  let G := (chain_of_cycles_and_thetas factors).graph
  have hGonality : gonality_eq G (k : ℤ) := by
    apply cycle_theta_chain_gonality_eq_common_torsion
      factors k hNonempty hCycles hThetas hPeriod
    simpa [hTotal] using hkg
  have hGeometry := cycle_theta_chain_connected_and_genus
    factors hNonempty hCycles hThetas
  refine ⟨G, ?_, ?_, hGonality⟩
  · exact hGeometry.1
  · rw [show genus G = (CycleThetaFactor.totalGenus factors : ℤ) from hGeometry.2,
      hTotal]

end BNChains
