import LowGenus.GenusFiveClosedOrbit

/-!
# The leg-reversing symmetry of the AR row-08 core

Row 08 is AR's *seventh* family: a hub `3` carrying both bananas and the stem of
a triangle `2 - 4 - 5`, whose other two vertices carry the far banana legs.

```
 e0, e1 : 0 == 1     e3 : 3 -> 0  (b)   e4 : 1 -> 4  (a)   e9 : 2 -> 3 (stem)
 e5 : 2 -> 4   e6 : 4 -> 5   e8 : 5 -> 2                   (the triangle)
 e2 : 6 -> 3  (c)   e7 : 5 -> 7  (d)    e10, e11 : 6 == 7
```

Its vertex automorphism group has order two, generated by

```
 sigma = (0 6)(1 7)(4 5)
```

which exchanges the two bananas and the two triangle vertices carrying a leg,
and therefore acts on the four leg lengths by `(a,b,c,d) ↦ (d,c,b,a)`.

AR draw three of the four sign patterns of `(|e4| - |e3|, |e7| - |e2|)`; the
fourth is the `sigma` image of the third, so the row needs **three** chambers
proved, not four.  `Chamber` below is their disjunction, and `chamber_covers`
carries every length vector into it.

Note that `sigma` does *not* reverse the stem `e9 : 2 -> 3`: both its ends are
fixed.  It reverses only the triangle edge `e6` and the four slots it swaps in
pairs; all six endpoint laws are `decide`d.
-/

namespace AtanasovRanganathan.GenusFiveRow08Symmetry

open Utilities

open Certificate
open Certificate.ExplicitPotential
open Utilities.Certificate.CoreOrbitReduction
open GenusFiveCoreAtlas ClosedOrbit

def vfun (data : List (Fin 8)) : Fin 8 → Fin 8 := fun i => data.getD i.val 0
def sfun (data : List (Fin 12)) : Fin 12 → Fin 12 := fun i => data.getD i.val 0
def bfun (data : List Bool) : Fin 12 → Bool := fun i => data.getD i.val false

/-- A `CoreSymmetry` literal carrying its own inverses, so that
`reindexLength` reduces without `Equiv.ofBijective`. -/
def mkSym (vmap vinv : Fin 8 → Fin 8) (smap sinv : Fin 12 → Fin 12)
    (rev : Fin 12 → Bool)
    (hv1 : ∀ x, vinv (vmap x) = x) (hv2 : ∀ x, vmap (vinv x) = x)
    (hs1 : ∀ x, sinv (smap x) = x) (hs2 : ∀ x, smap (sinv x) = x)
    (ht : ∀ e, row08Core.tail (smap e) =
      if rev e then vmap (row08Core.head e) else vmap (row08Core.tail e))
    (hh : ∀ e, row08Core.head (smap e) =
      if rev e then vmap (row08Core.tail e) else vmap (row08Core.head e)) :
    CoreSymmetry row08Core where
  vertexPerm := ⟨vmap, vinv, hv1, hv2⟩
  slotPerm := ⟨smap, sinv, hs1, hs2⟩
  reversed := rev
  tail_eq := ht
  head_eq := hh

/-- The identity, spelled in the same shape as `sigma`. -/
def idSym : CoreSymmetry row08Core :=
  mkSym (vfun [0, 1, 2, 3, 4, 5, 6, 7]) (vfun [0, 1, 2, 3, 4, 5, 6, 7])
    (sfun [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
    (sfun [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
    (bfun [false, false, false, false, false, false,
      false, false, false, false, false, false])
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)

/-- The leg reversal `(0 6)(1 7)(4 5)`. -/
def sigma : CoreSymmetry row08Core :=
  mkSym (vfun [6, 7, 2, 3, 5, 4, 0, 1]) (vfun [6, 7, 2, 3, 5, 4, 0, 1])
    (sfun [10, 11, 3, 2, 7, 8, 6, 4, 5, 9, 0, 1])
    (sfun [10, 11, 3, 2, 7, 8, 6, 4, 5, 9, 0, 1])
    (bfun [false, false, true, true, true, true,
      true, true, true, false, false, false])
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)

/-- AR's first scope: `a ≤ b` and `d ≤ c`. -/
def ChamberOne (length : Fin 12 → ℕ) : Prop :=
  length 4 ≤ length 3 ∧ length 7 ≤ length 2

/-- AR's second scope: `b ≤ a` and `c ≤ d`. -/
def ChamberTwo (length : Fin 12 → ℕ) : Prop :=
  length 3 ≤ length 4 ∧ length 2 ≤ length 7

/-- AR's third scope: `b ≤ a` and `d ≤ c`. Its `sigma` image gives the
remaining sign pattern. -/
def ChamberThree (length : Fin 12 → ℕ) : Prop :=
  length 3 ≤ length 4 ∧ length 7 ≤ length 2

/-- The union of the three scopes AR draw. -/
def Chamber (length : Fin 12 → ℕ) : Prop :=
  ChamberOne length ∨ ChamberTwo length ∨ ChamberThree length

/-- **Coverage.**  The four sign patterns are covered by the three drawn
scopes together with the `sigma` image of the third. -/
theorem chamber_covers (length : Fin 12 → ℕ) :
    ∃ g : CoreSymmetry row08Core, Chamber (g.reindexLength length) := by
  rcases le_total (length 4) (length 3) with h1 | h1 <;>
    rcases le_total (length 7) (length 2) with h2 | h2
  · exact ⟨idSym, Or.inl ⟨h1, h2⟩⟩
  · exact ⟨sigma, Or.inr (Or.inr ⟨h2, h1⟩)⟩
  · exact ⟨idSym, Or.inr (Or.inr ⟨h1, h2⟩)⟩
  · exact ⟨idSym, Or.inr (Or.inl ⟨h1, h2⟩)⟩

end AtanasovRanganathan.GenusFiveRow08Symmetry
