import LowGenus.GenusFiveClosedOrbit

/-!
# The order-two symmetry of the AR row-10 core

Row 10 is Atanasov--Ranganathan's *ninth* family: a triangle `{0, 1, 2}` with a
spoke from each corner, an apex `3` joining the ends of two of the spokes, and a
banana `{6, 7}` reached from the other two spoke ends.

```
 e0 : 0 -> 2   e1 : 2 -> 1   e2 : 1 -> 0            the triangle
 e10 : 0 -> 3   e4 : 1 -> 4   e3 : 2 -> 5           the three spokes  a, b, c
 e5 : 3 -> 4   e9 : 5 -> 3                          the apex
 e6 : 4 -> 6   e11 : 5 -> 7   e7, e8 : 6 == 7       the banana
```

The three spokes are **not** interchangeable -- `e10` lands on the apex while
`e4` and `e3` land on the banana side -- so the slot-level symmetry group has
order four (two vertex permutations times the banana-slot swap) and the vertex
group has order two, generated by

* `sigma = (1 2)(4 5)(6 7)`, slots `(e0 e2)(e3 e4)(e5 e9)(e6 e11)` with `e1`,
  `e7`, `e8`, `e10` fixed (`e1`, `e7`, `e8` reversed).

It acts on the three spoke lengths by `(a, b, c) ↦ (a, c, b)`.

The two displayed cases are "`a = min(a,b,c)`" and "`b = min(a,b,c)`". The
remaining case, `c = min`, is the `sigma` image of the second. Thus the three chambers

| chamber | inequalities |
|---|---|
| **1** (their first scope)  | `|e10| ≤ |e4|`, `|e10| ≤ |e3|` |
| **2** (their second scope) | `|e4| ≤ |e10|`, `|e4| ≤ |e3|` |
| **3** = `sigma`(2)         | `|e3| ≤ |e10|`, `|e3| ≤ |e4|` |

cover the closed orthant -- the minimum of three is attained -- and fall into the
**two** orbits `{1}` (chamber 1 is `sigma`-stable as a region, since `sigma`
fixes `a` and swaps `b` with `c`) and `{2, 3}`.  Exactly the two scopes AR draw
have to be proved.  All inequalities are weak, so the three regions overlap on
the walls and no strictness is ever needed.

Each permutation carries its own explicit inverse -- `sigma` is an involution --
which keeps `CoreSymmetry.reindexLength` definitionally transparent, the pattern
of `GenusFiveRow01Symmetry` and `GenusFiveRow05Symmetry`.
-/

namespace AtanasovRanganathan.GenusFiveRow10Symmetry

open Utilities

open Certificate
open Certificate.ExplicitPotential
open Utilities.Certificate.CoreOrbitReduction
open GenusFiveCoreAtlas ClosedOrbit

def vfun (data : List (Fin 8)) : Fin 8 → Fin 8 := fun i => data.getD i.val 0
def sfun (data : List (Fin 12)) : Fin 12 → Fin 12 := fun i => data.getD i.val 0
def bfun (data : List Bool) : Fin 12 → Bool := fun i => data.getD i.val false

/-- A `CoreSymmetry` literal carrying its own inverses, so that
`reindexLength` reduces without `Equiv.ofBijective`. -/
def mkSym (vmap vinv : Fin 8 → Fin 8) (smap sinv : Fin 12 → Fin 12)
    (rev : Fin 12 → Bool)
    (hv1 : ∀ x, vinv (vmap x) = x) (hv2 : ∀ x, vmap (vinv x) = x)
    (hs1 : ∀ x, sinv (smap x) = x) (hs2 : ∀ x, smap (sinv x) = x)
    (ht : ∀ e, row10Core.tail (smap e) =
      if rev e then vmap (row10Core.head e) else vmap (row10Core.tail e))
    (hh : ∀ e, row10Core.head (smap e) =
      if rev e then vmap (row10Core.tail e) else vmap (row10Core.head e)) :
    CoreSymmetry row10Core where
  vertexPerm := ⟨vmap, vinv, hv1, hv2⟩
  slotPerm := ⟨smap, sinv, hs1, hs2⟩
  reversed := rev
  tail_eq := ht
  head_eq := hh

/-- The identity, spelled in the same shape as the involution. -/
def idSym : CoreSymmetry row10Core :=
  mkSym (vfun [0, 1, 2, 3, 4, 5, 6, 7]) (vfun [0, 1, 2, 3, 4, 5, 6, 7])
    (sfun [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
    (sfun [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
    (bfun [false, false, false, false, false, false,
      false, false, false, false, false, false])
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)

/-- The reflection `sigma = (1 2)(4 5)(6 7)`, which fixes the apex spoke `e10`
and swaps the two banana-side spokes `e4` and `e3`. -/
def sigma : CoreSymmetry row10Core :=
  mkSym (vfun [0, 2, 1, 3, 5, 4, 7, 6]) (vfun [0, 2, 1, 3, 5, 4, 7, 6])
    (sfun [2, 1, 0, 4, 3, 9, 11, 7, 8, 5, 10, 6])
    (sfun [2, 1, 0, 4, 3, 9, 11, 7, 8, 5, 10, 6])
    (bfun [true, true, true, false, false, true,
      false, true, true, true, false, false])
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)

/-- Chamber 1: AR's first scope, the apex spoke `a` realizes the minimum. -/
def ChamberOne (length : Fin 12 → ℕ) : Prop :=
  length 10 ≤ length 4 ∧ length 10 ≤ length 3

/-- Chamber 2: AR's second scope, the spoke `b` realizes the minimum. -/
def ChamberTwo (length : Fin 12 → ℕ) : Prop :=
  length 4 ≤ length 10 ∧ length 4 ≤ length 3

/-- The union of the two scopes AR draw.  The third case, `c = min`, is the
`sigma` image of chamber 2 and needs no proof of its own. -/
def Chamber (length : Fin 12 → ℕ) : Prop :=
  ChamberOne length ∨ ChamberTwo length

/-- **Coverage.**  The minimum of the three spoke lengths is attained; the two
cases where it is `a` or `b` are the drawn scopes, and the third is carried onto
chamber 2 by `sigma`, which swaps `|e4|` with `|e3|` and fixes `|e10|`. -/
theorem chamber_covers (length : Fin 12 → ℕ) :
    ∃ g : CoreSymmetry row10Core, Chamber (g.reindexLength length) := by
  by_cases hA : length 10 ≤ length 4 ∧ length 10 ≤ length 3
  · exact ⟨idSym, Or.inl hA⟩
  · by_cases hB : length 4 ≤ length 10 ∧ length 4 ≤ length 3
    · exact ⟨idSym, Or.inr hB⟩
    · refine ⟨sigma, Or.inr ⟨?_, ?_⟩⟩
      · show length 3 ≤ length 10
        omega
      · show length 3 ≤ length 4
        omega

end AtanasovRanganathan.GenusFiveRow10Symmetry
