import Utilities.Subdivision.DegenerateRamp
import Utilities.Subdivision.DegenerateMultiBreakScript
import Utilities.Subdivision.DegenerateSeparator
import Utilities.Subdivision.ClosedCoreSymmetry
import Utilities.Subdivision.ClosedContraction
import Utilities.Segments.AtanasovRanganathanConfigurations
import LowGenus.GenusFourCubicAtlas

/-!
# Unconditional CLOSED-ORTHANT existence on genus-four Core 097

The pencil is expressed over
`Utilities.Certificate.DegenerateSpec.DegSpec`, whose lengths may vanish, so the
conclusion covers the whole closed orthant: every subdivision of the row-097
core *and* every equal-genus contraction of one.

The positive-length statement follows from the result here.

The face `ℓ₈ = 0` also supplies the corresponding row-068 case.

## The mathematics is the same; the bookkeeping is different

Writing the split core as

```text
e0 0-4   e1 0-5   e2 0-5   e3 1-2   e4 1-3
e5 1-5   e6 2-3   e7 2-4   e8 3-4
```

the vertices `2` and `3` are the hubs of a theta graph with arcs `e6`,
`e3 + e4` (through `1`) and `e7 + e8` (through `4`); the interior vertices `1`
and `4` of the last two arcs are joined by a handle
`1 —e5— 5 =banana(e1,e2)= 0 —e0— 4`.  Writing
`Δ = length 0 - length 5` and `d = min Δ (length 4)`, the pencil is

```text
D = 3 + 4 + (the point at distance d from 1 along e3),
```

moved onto the core by marches across the three-edge cuts `star 2`,
`{e0,e3,e4}`, `star 0` and across the two-edge cut `{e0,e5}` (used twice).
The Klein four-group `σ = (0 5)(1 4)`, `τ = (2 3)` puts an arbitrary length
vector in the chamber `length 5 ≤ length 0`, `length 4 ≤ length 3`.

Three things change on the closed orthant, and all three are handled once, in
`Certificate/DegenerateRamp.lean`, rather than per march:

* **Vertices are classes.**  `DegSpec.Vertex = Class ⊕ Interior`, and
  `coreVertex` is not injective at a face.  Every value at a class is the class
  *sum* of the uncontracted per-core-vertex value
  (`DegSpec.prin_coreVertex_eq_classSum`), so the per-vertex arithmetic of the
  open proof transfers by addition.
* **Path positions have three cases**, `k = 0`, `0 < k < length`,
  `k = length`, and the last is reachable.  `DegSpec.pathAt` is the
  *unbounded* path vertex: it clamps `k` to the slot, so no statement below
  carries a position bound at all.
* **A ramp must be constant on classes.**  That is `RampData.repInv`, and it
  is free whenever `rep` is generated by the vanishing slots
  (`RampData.of_reachIn`), which is how `RowProof.censusSpec` is built.

The four per-march divisor identities of the retired open proof — four
`set_option maxHeartbeats 1000000` declarations there — are replaced by a
*single* generic one, `DegSpec.prin_ramp_eq`, instantiated nine-slot-wise.
This file needs no heartbeat override.
-/

namespace LowGenus.GenusFourRow097Closed

open Utilities

open Utilities.Certificate.DegenerateSpec
open Utilities.Certificate
open Utilities.Certificate.ClosedFaceCensus
open Utilities.Certificate.ClosedCoreSymmetry
open Utilities.Certificate.ClosedContraction
open Utilities.Certificate.ContractionForestCensusGeneral
open AtanasovRanganathan.Configurations

/-! ## Finite-index bookkeeping -/

theorem sum_univ_nine {M : Type*} [AddCommMonoid M] (f : Fin 9 → M) :
    ∑ i : Fin 9, f i =
      f 0 + f 1 + f 2 + f 3 + f 4 + f 5 + f 6 + f 7 + f 8 := by
  rw [Fin.sum_univ_castSucc (f := f),
    Fin.sum_univ_eight (f := fun i : Fin 8 => f i.castSucc)]
  rfl

theorem forall_fin_nine {P : Fin 9 → Prop} (h0 : P 0) (h1 : P 1) (h2 : P 2)
    (h3 : P 3) (h4 : P 4) (h5 : P 5) (h6 : P 6) (h7 : P 7) (h8 : P 8) :
    ∀ e : Fin 9, P e := by
  intro e
  fin_cases e
  exacts [h0, h1, h2, h3, h4, h5, h6, h7, h8]

theorem forall_fin_six {P : Fin 6 → Prop} (h0 : P 0) (h1 : P 1) (h2 : P 2)
    (h3 : P 3) (h4 : P 4) (h5 : P 5) : ∀ v : Fin 6, P v := by
  intro v
  fin_cases v
  exacts [h0, h1, h2, h3, h4, h5]

/-! ## Rank one from reaching the core classes

The closed-orthant analogue of
`Utilities.Certificate.CoreVertexReachability.bnExists_of_reaches_coreVertices`.
Both hypotheses it needs about the ambient graph are already hypothesis-free on
a `DegSpec`: the class vertices are a strong separator
(`DegSpec.strongSeparatorCertificate`) and connectivity comes from the finite
cut certificate on the *uncontracted* core
(`DegSpec.graph_connected_of_coreConnected`). -/

section Reachability

variable {n p : ℕ}

theorem bnExists_of_reaches_coreVertices (d : DegSpec n p)
    (hCore : d.core.Connected) (D : CFDiv d.graph) (degree : ℤ)
    (hDegree : deg D = degree)
    (hReaches : ∀ v : Fin n, StrongSeparator.Reaches d.graph D (d.coreVertex v)) :
    BNExists d.graph 1 degree := by
  refine ⟨D, hDegree, ?_⟩
  apply StrongSeparator.rank_ge_one_of_strongSeparatorCertificate
    (d.graph_connected_of_coreConnected hCore)
    (ExplicitPotential.Certificate.degenerateCoreVertices_nonempty d)
    d.strongSeparatorCertificate
  intro vertex hVertex
  obtain ⟨anchor, -, rfl⟩ := Finset.mem_image.mp hVertex
  exact hReaches anchor

end Reachability

/-! ## The oriented row-097 core -/

/-- The orientation data of the row-097 split core, read on the **core** rather
than on a positive subdivision: on the closed orthant the slot lengths are not
part of this datum. -/
structure IsCore097 (core : ExplicitPotential.Core 6 9) : Prop where
  t0 : core.tail 0 = 0
  t1 : core.tail 1 = 0
  t2 : core.tail 2 = 0
  t3 : core.tail 3 = 1
  t4 : core.tail 4 = 1
  t5 : core.tail 5 = 1
  t6 : core.tail 6 = 2
  t7 : core.tail 7 = 2
  t8 : core.tail 8 = 3
  h0 : core.head 0 = 4
  h1 : core.head 1 = 5
  h2 : core.head 2 = 5
  h3 : core.head 3 = 2
  h4 : core.head 4 = 3
  h5 : core.head 5 = 5
  h6 : core.head 6 = 3
  h7 : core.head 7 = 4
  h8 : core.head 8 = 4

namespace IsCore097

variable {core : ExplicitPotential.Core 6 9}

/-- The row-097 core is connected: any nonempty proper cut of the six vertices
is crossed by some slot.  Assuming no slot crosses the cut, the nine slots link
all six vertices into a single chain `0 - 4`, `0 - 5 - 1`, `1 - 2`, `1 - 3`, so
every vertex agrees with `0`. -/
theorem core_connected (hp : IsCore097 core) : core.Connected := by
  intro S hS
  obtain ⟨v, w, hv, hw⟩ := hS
  by_contra hNoCross
  simp only [not_exists, not_or] at hNoCross
  have hIffEdge : ∀ edge : Fin 9, core.tail edge ∈ S ↔ core.head edge ∈ S := by
    intro edge
    have he := hNoCross edge
    constructor
    · intro hA
      by_contra hB
      exact he.1 ⟨hA, hB⟩
    · intro hB
      by_contra hA
      exact he.2 ⟨hB, hA⟩
  have h04 : (0 : Fin 6) ∈ S ↔ (4 : Fin 6) ∈ S := by
    have := hIffEdge 0; rwa [hp.t0, hp.h0] at this
  have h05 : (0 : Fin 6) ∈ S ↔ (5 : Fin 6) ∈ S := by
    have := hIffEdge 1; rwa [hp.t1, hp.h1] at this
  have h15 : (1 : Fin 6) ∈ S ↔ (5 : Fin 6) ∈ S := by
    have := hIffEdge 5; rwa [hp.t5, hp.h5] at this
  have h12 : (1 : Fin 6) ∈ S ↔ (2 : Fin 6) ∈ S := by
    have := hIffEdge 3; rwa [hp.t3, hp.h3] at this
  have h13 : (1 : Fin 6) ∈ S ↔ (3 : Fin 6) ∈ S := by
    have := hIffEdge 4; rwa [hp.t4, hp.h4] at this
  have h01 : (0 : Fin 6) ∈ S ↔ (1 : Fin 6) ∈ S := h05.trans h15.symm
  have h02 : (0 : Fin 6) ∈ S ↔ (2 : Fin 6) ∈ S := h01.trans h12
  have h03 : (0 : Fin 6) ∈ S ↔ (3 : Fin 6) ∈ S := h01.trans h13
  have hAll : ∀ u : Fin 6, u ∈ S ↔ (0 : Fin 6) ∈ S := by
    refine forall_fin_six ?_ ?_ ?_ ?_ ?_ ?_
    · exact Iff.rfl
    · exact h01.symm
    · exact h02.symm
    · exact h03.symm
    · exact h04.symm
    · exact h05.symm
  exact hw (((hAll v).trans (hAll w).symm).mp hv)

end IsCore097

/-! ## The pencil parameters

Every parameter is a function of the length vector alone; no positivity and no
spec is involved. -/

section Parameters

variable (L : Fin 9 → ℕ)

/-- Depth of the moving chip on slot `e3`. -/
def dpos : ℕ := min (L 0 - L 5) (L 4)

/-- Residual handle imbalance. -/
def cRest : ℕ := L 0 - L 5 - dpos L

/-- Length of the `star 2` march. -/
def uMax : ℕ := min (L 3 - dpos L) (min (L 6) (L 7))

/-- Length of the second pass of the `{e0,e5}` march. -/
def m2Max : ℕ := min (cRest L) (L 5)

/-- Length of the `star 0` march. -/
def wMax : ℕ := min (cRest L - m2Max L) (min (L 1) (L 2))

end Parameters

/-! ## The four marches -/

section Marches

variable (L : Fin 9 → ℕ)

/-- Core potential of the `star 2` march. -/
def vPot (u : ℕ) : Fin 6 → ℤ := fun v => if v = 2 then -(u : ℤ) else 0

/-- Slot signs of the `star 2` march. -/
def vSgn : Fin 9 → ℤ := fun e =>
  if e = 3 then -1 else if e = 6 then 1 else if e = 7 then 1 else 0

/-- Window starts of the `star 2` march. -/
def vLo (u : ℕ) : Fin 9 → ℕ := fun e =>
  if e = 3 then dpos L
  else if e = 6 then L 6 - u
  else if e = 7 then L 7 - u else 0

/-- Core potential of the `{e0,e3,e4}` march. -/
def pPot (s : ℕ) : Fin 6 → ℤ := fun v =>
  if v = 0 then -(s : ℤ) else if v = 1 then -(s : ℤ)
  else if v = 5 then -(s : ℤ) else 0

/-- Slot signs of the `{e0,e3,e4}` march. -/
def pSgn : Fin 9 → ℤ := fun e =>
  if e = 0 then 1 else if e = 3 then 1 else if e = 4 then 1 else 0

/-- Window starts of the `{e0,e3,e4}` march. -/
def pLo (s : ℕ) : Fin 9 → ℕ := fun e =>
  if e = 0 then L 0 - s
  else if e = 3 then dpos L - s
  else if e = 4 then L 4 - s else 0

/-- Core potential of the `{e0,e5}` march. -/
def mPot (r : ℕ) : Fin 6 → ℤ := fun v =>
  if v = 0 then -(r : ℤ) else if v = 5 then -(r : ℤ) else 0

/-- Slot signs of the `{e0,e5}` march. -/
def mSgn : Fin 9 → ℤ := fun e =>
  if e = 0 then 1 else if e = 5 then -1 else 0

/-- Window starts of the `{e0,e5}` march starting from depth `a` on `e0`. -/
def mLo (a r : ℕ) : Fin 9 → ℕ := fun e => if e = 0 then a - r else 0

/-- Core potential of the `star 0` march. -/
def wPot (w : ℕ) : Fin 6 → ℤ := fun v => if v = 0 then -(w : ℤ) else 0

/-- Slot signs of the `star 0` march. -/
def wSgn : Fin 9 → ℤ := fun e =>
  if e = 0 then 1 else if e = 1 then 1 else if e = 2 then 1 else 0

/-- Window starts of the `star 0` march. -/
def wLo (w : ℕ) : Fin 9 → ℕ := fun e =>
  if e = 0 then cRest L - m2Max L - w
  else if e = 1 then L 1 - w
  else if e = 2 then L 2 - w else 0

end Marches

section Values

variable {L : Fin 9 → ℕ} {u s r a w : ℕ}

@[simp] theorem vPot_0 : vPot u 0 = 0 := by norm_num [vPot, Fin.ext_iff]
@[simp] theorem vPot_1 : vPot u 1 = 0 := by norm_num [vPot, Fin.ext_iff]
@[simp] theorem vPot_2 : vPot u 2 = -(u : ℤ) := by norm_num [vPot, Fin.ext_iff]
@[simp] theorem vPot_3 : vPot u 3 = 0 := by norm_num [vPot, Fin.ext_iff]
@[simp] theorem vPot_4 : vPot u 4 = 0 := by norm_num [vPot, Fin.ext_iff]
@[simp] theorem vPot_5 : vPot u 5 = 0 := by norm_num [vPot, Fin.ext_iff]

@[simp] theorem vSgn_0 : vSgn 0 = 0 := by norm_num [vSgn, Fin.ext_iff]
@[simp] theorem vSgn_1 : vSgn 1 = 0 := by norm_num [vSgn, Fin.ext_iff]
@[simp] theorem vSgn_2 : vSgn 2 = 0 := by norm_num [vSgn, Fin.ext_iff]
@[simp] theorem vSgn_3 : vSgn 3 = -1 := by norm_num [vSgn, Fin.ext_iff]
@[simp] theorem vSgn_4 : vSgn 4 = 0 := by norm_num [vSgn, Fin.ext_iff]
@[simp] theorem vSgn_5 : vSgn 5 = 0 := by norm_num [vSgn, Fin.ext_iff]
@[simp] theorem vSgn_6 : vSgn 6 = 1 := by norm_num [vSgn, Fin.ext_iff]
@[simp] theorem vSgn_7 : vSgn 7 = 1 := by norm_num [vSgn, Fin.ext_iff]
@[simp] theorem vSgn_8 : vSgn 8 = 0 := by norm_num [vSgn, Fin.ext_iff]

@[simp] theorem vLo_0 : vLo L u 0 = 0 := by norm_num [vLo, Fin.ext_iff]
@[simp] theorem vLo_1 : vLo L u 1 = 0 := by norm_num [vLo, Fin.ext_iff]
@[simp] theorem vLo_2 : vLo L u 2 = 0 := by norm_num [vLo, Fin.ext_iff]
@[simp] theorem vLo_3 : vLo L u 3 = dpos L := by norm_num [vLo, Fin.ext_iff]
@[simp] theorem vLo_4 : vLo L u 4 = 0 := by norm_num [vLo, Fin.ext_iff]
@[simp] theorem vLo_5 : vLo L u 5 = 0 := by norm_num [vLo, Fin.ext_iff]
@[simp] theorem vLo_6 : vLo L u 6 = L 6 - u := by norm_num [vLo, Fin.ext_iff]
@[simp] theorem vLo_7 : vLo L u 7 = L 7 - u := by norm_num [vLo, Fin.ext_iff]
@[simp] theorem vLo_8 : vLo L u 8 = 0 := by norm_num [vLo, Fin.ext_iff]

@[simp] theorem pPot_0 : pPot s 0 = -(s : ℤ) := by norm_num [pPot, Fin.ext_iff]
@[simp] theorem pPot_1 : pPot s 1 = -(s : ℤ) := by norm_num [pPot, Fin.ext_iff]
@[simp] theorem pPot_2 : pPot s 2 = 0 := by norm_num [pPot, Fin.ext_iff]
@[simp] theorem pPot_3 : pPot s 3 = 0 := by norm_num [pPot, Fin.ext_iff]
@[simp] theorem pPot_4 : pPot s 4 = 0 := by norm_num [pPot, Fin.ext_iff]
@[simp] theorem pPot_5 : pPot s 5 = -(s : ℤ) := by norm_num [pPot, Fin.ext_iff]

@[simp] theorem pSgn_0 : pSgn 0 = 1 := by norm_num [pSgn, Fin.ext_iff]
@[simp] theorem pSgn_1 : pSgn 1 = 0 := by norm_num [pSgn, Fin.ext_iff]
@[simp] theorem pSgn_2 : pSgn 2 = 0 := by norm_num [pSgn, Fin.ext_iff]
@[simp] theorem pSgn_3 : pSgn 3 = 1 := by norm_num [pSgn, Fin.ext_iff]
@[simp] theorem pSgn_4 : pSgn 4 = 1 := by norm_num [pSgn, Fin.ext_iff]
@[simp] theorem pSgn_5 : pSgn 5 = 0 := by norm_num [pSgn, Fin.ext_iff]
@[simp] theorem pSgn_6 : pSgn 6 = 0 := by norm_num [pSgn, Fin.ext_iff]
@[simp] theorem pSgn_7 : pSgn 7 = 0 := by norm_num [pSgn, Fin.ext_iff]
@[simp] theorem pSgn_8 : pSgn 8 = 0 := by norm_num [pSgn, Fin.ext_iff]

@[simp] theorem pLo_0 : pLo L s 0 = L 0 - s := by norm_num [pLo, Fin.ext_iff]
@[simp] theorem pLo_1 : pLo L s 1 = 0 := by norm_num [pLo, Fin.ext_iff]
@[simp] theorem pLo_2 : pLo L s 2 = 0 := by norm_num [pLo, Fin.ext_iff]
@[simp] theorem pLo_3 : pLo L s 3 = dpos L - s := by norm_num [pLo, Fin.ext_iff]
@[simp] theorem pLo_4 : pLo L s 4 = L 4 - s := by norm_num [pLo, Fin.ext_iff]
@[simp] theorem pLo_5 : pLo L s 5 = 0 := by norm_num [pLo, Fin.ext_iff]
@[simp] theorem pLo_6 : pLo L s 6 = 0 := by norm_num [pLo, Fin.ext_iff]
@[simp] theorem pLo_7 : pLo L s 7 = 0 := by norm_num [pLo, Fin.ext_iff]
@[simp] theorem pLo_8 : pLo L s 8 = 0 := by norm_num [pLo, Fin.ext_iff]

@[simp] theorem mPot_0 : mPot r 0 = -(r : ℤ) := by norm_num [mPot, Fin.ext_iff]
@[simp] theorem mPot_1 : mPot r 1 = 0 := by norm_num [mPot, Fin.ext_iff]
@[simp] theorem mPot_2 : mPot r 2 = 0 := by norm_num [mPot, Fin.ext_iff]
@[simp] theorem mPot_3 : mPot r 3 = 0 := by norm_num [mPot, Fin.ext_iff]
@[simp] theorem mPot_4 : mPot r 4 = 0 := by norm_num [mPot, Fin.ext_iff]
@[simp] theorem mPot_5 : mPot r 5 = -(r : ℤ) := by norm_num [mPot, Fin.ext_iff]

@[simp] theorem mSgn_0 : mSgn 0 = 1 := by norm_num [mSgn, Fin.ext_iff]
@[simp] theorem mSgn_1 : mSgn 1 = 0 := by norm_num [mSgn, Fin.ext_iff]
@[simp] theorem mSgn_2 : mSgn 2 = 0 := by norm_num [mSgn, Fin.ext_iff]
@[simp] theorem mSgn_3 : mSgn 3 = 0 := by norm_num [mSgn, Fin.ext_iff]
@[simp] theorem mSgn_4 : mSgn 4 = 0 := by norm_num [mSgn, Fin.ext_iff]
@[simp] theorem mSgn_5 : mSgn 5 = -1 := by norm_num [mSgn, Fin.ext_iff]
@[simp] theorem mSgn_6 : mSgn 6 = 0 := by norm_num [mSgn, Fin.ext_iff]
@[simp] theorem mSgn_7 : mSgn 7 = 0 := by norm_num [mSgn, Fin.ext_iff]
@[simp] theorem mSgn_8 : mSgn 8 = 0 := by norm_num [mSgn, Fin.ext_iff]

@[simp] theorem mLo_0 : mLo a r 0 = a - r := by norm_num [mLo, Fin.ext_iff]
@[simp] theorem mLo_1 : mLo a r 1 = 0 := by norm_num [mLo, Fin.ext_iff]
@[simp] theorem mLo_2 : mLo a r 2 = 0 := by norm_num [mLo, Fin.ext_iff]
@[simp] theorem mLo_3 : mLo a r 3 = 0 := by norm_num [mLo, Fin.ext_iff]
@[simp] theorem mLo_4 : mLo a r 4 = 0 := by norm_num [mLo, Fin.ext_iff]
@[simp] theorem mLo_5 : mLo a r 5 = 0 := by norm_num [mLo, Fin.ext_iff]
@[simp] theorem mLo_6 : mLo a r 6 = 0 := by norm_num [mLo, Fin.ext_iff]
@[simp] theorem mLo_7 : mLo a r 7 = 0 := by norm_num [mLo, Fin.ext_iff]
@[simp] theorem mLo_8 : mLo a r 8 = 0 := by norm_num [mLo, Fin.ext_iff]

@[simp] theorem wPot_0 : wPot w 0 = -(w : ℤ) := by norm_num [wPot, Fin.ext_iff]
@[simp] theorem wPot_1 : wPot w 1 = 0 := by norm_num [wPot, Fin.ext_iff]
@[simp] theorem wPot_2 : wPot w 2 = 0 := by norm_num [wPot, Fin.ext_iff]
@[simp] theorem wPot_3 : wPot w 3 = 0 := by norm_num [wPot, Fin.ext_iff]
@[simp] theorem wPot_4 : wPot w 4 = 0 := by norm_num [wPot, Fin.ext_iff]
@[simp] theorem wPot_5 : wPot w 5 = 0 := by norm_num [wPot, Fin.ext_iff]

@[simp] theorem wSgn_0 : wSgn 0 = 1 := by norm_num [wSgn, Fin.ext_iff]
@[simp] theorem wSgn_1 : wSgn 1 = 1 := by norm_num [wSgn, Fin.ext_iff]
@[simp] theorem wSgn_2 : wSgn 2 = 1 := by norm_num [wSgn, Fin.ext_iff]
@[simp] theorem wSgn_3 : wSgn 3 = 0 := by norm_num [wSgn, Fin.ext_iff]
@[simp] theorem wSgn_4 : wSgn 4 = 0 := by norm_num [wSgn, Fin.ext_iff]
@[simp] theorem wSgn_5 : wSgn 5 = 0 := by norm_num [wSgn, Fin.ext_iff]
@[simp] theorem wSgn_6 : wSgn 6 = 0 := by norm_num [wSgn, Fin.ext_iff]
@[simp] theorem wSgn_7 : wSgn 7 = 0 := by norm_num [wSgn, Fin.ext_iff]
@[simp] theorem wSgn_8 : wSgn 8 = 0 := by norm_num [wSgn, Fin.ext_iff]

@[simp] theorem wLo_0 : wLo L w 0 = cRest L - m2Max L - w := by
  norm_num [wLo, Fin.ext_iff]
@[simp] theorem wLo_1 : wLo L w 1 = L 1 - w := by norm_num [wLo, Fin.ext_iff]
@[simp] theorem wLo_2 : wLo L w 2 = L 2 - w := by norm_num [wLo, Fin.ext_iff]
@[simp] theorem wLo_3 : wLo L w 3 = 0 := by norm_num [wLo, Fin.ext_iff]
@[simp] theorem wLo_4 : wLo L w 4 = 0 := by norm_num [wLo, Fin.ext_iff]
@[simp] theorem wLo_5 : wLo L w 5 = 0 := by norm_num [wLo, Fin.ext_iff]
@[simp] theorem wLo_6 : wLo L w 6 = 0 := by norm_num [wLo, Fin.ext_iff]
@[simp] theorem wLo_7 : wLo L w 7 = 0 := by norm_num [wLo, Fin.ext_iff]
@[simp] theorem wLo_8 : wLo L w 8 = 0 := by norm_num [wLo, Fin.ext_iff]

end Values

/-! ## The ramps

`RampData.repInv` — the one field the open orthant does not need — is supplied
uniformly by `RampData.of_reachIn` from `RepGen`, so each march below proves
exactly the two conditions its open counterpart proves. -/

section Ramps

/-- The census hypothesis every closed-orthant march needs: `rep`-equality is
witnessed by a chain of vanishing slots.  Free for `RowProof.censusSpec`, whose
`rep` is `compFold` of the vanishing set (`compFold_iff`). -/
def RepGen (d : DegSpec 6 9) : Prop :=
  ∀ u v : Fin 6, d.rep u = d.rep v →
    ReachIn d.core (Finset.univ.filter fun e : Fin 9 => d.length e = 0) u v

variable {d : DegSpec 6 9}

theorem vRamp (hp : IsCore097 d.core) (hrep : RepGen d) {u : ℕ}
    (hu3 : dpos d.length + u ≤ d.length 3) (hu6 : u ≤ d.length 6)
    (hu7 : u ≤ d.length 7) :
    DegSpec.RampData d (vPot u) vSgn (vLo d.length u) u := by
  refine DegSpec.RampData.of_reachIn ?_ ?_ hrep
  · refine forall_fin_nine ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ <;>
      simp [hp.t0, hp.t1, hp.t2, hp.t3, hp.t4, hp.t5, hp.t6, hp.t7, hp.t8,
        hp.h0, hp.h1, hp.h2, hp.h3, hp.h4, hp.h5, hp.h6, hp.h7, hp.h8]
  · refine forall_fin_nine ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ <;> simp <;> omega

theorem pRamp (hp : IsCore097 d.core) (hrep : RepGen d) {s : ℕ}
    (hs0 : s ≤ d.length 0) (hsd : s ≤ dpos d.length)
    (hd3 : dpos d.length ≤ d.length 3) (hs4 : s ≤ d.length 4) :
    DegSpec.RampData d (pPot s) pSgn (pLo d.length s) s := by
  refine DegSpec.RampData.of_reachIn ?_ ?_ hrep
  · refine forall_fin_nine ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ <;>
      simp [hp.t0, hp.t1, hp.t2, hp.t3, hp.t4, hp.t5, hp.t6, hp.t7, hp.t8,
        hp.h0, hp.h1, hp.h2, hp.h3, hp.h4, hp.h5, hp.h6, hp.h7, hp.h8]
  · refine forall_fin_nine ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ <;> simp <;> omega

theorem mRamp (hp : IsCore097 d.core) (hrep : RepGen d) {a r : ℕ}
    (ha : a ≤ d.length 0) (hr1 : r ≤ a) (hr2 : r ≤ d.length 5) :
    DegSpec.RampData d (mPot r) mSgn (mLo a r) r := by
  refine DegSpec.RampData.of_reachIn ?_ ?_ hrep
  · refine forall_fin_nine ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ <;>
      simp [hp.t0, hp.t1, hp.t2, hp.t3, hp.t4, hp.t5, hp.t6, hp.t7, hp.t8,
        hp.h0, hp.h1, hp.h2, hp.h3, hp.h4, hp.h5, hp.h6, hp.h7, hp.h8]
  · refine forall_fin_nine ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ <;> simp <;> omega

theorem wRamp (hp : IsCore097 d.core) (hrep : RepGen d) {w : ℕ}
    (hx : cRest d.length - m2Max d.length ≤ d.length 0)
    (hww : w ≤ cRest d.length - m2Max d.length) (hw1 : w ≤ d.length 1)
    (hw2 : w ≤ d.length 2) :
    DegSpec.RampData d (wPot w) wSgn (wLo d.length w) w := by
  refine DegSpec.RampData.of_reachIn ?_ ?_ hrep
  · refine forall_fin_nine ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ <;>
      simp [hp.t0, hp.t1, hp.t2, hp.t3, hp.t4, hp.t5, hp.t6, hp.t7, hp.t8,
        hp.h0, hp.h1, hp.h2, hp.h3, hp.h4, hp.h5, hp.h6, hp.h7, hp.h8]
  · refine forall_fin_nine ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ <;> simp <;> omega

/-- The `star 2` march. -/
def vScript (d : DegSpec 6 9) (u : ℕ) : firing_script d.graph :=
  d.rampScript (vPot u) vSgn (vLo d.length u) u

/-- The `{e0,e3,e4}` march. -/
def pScript (d : DegSpec 6 9) (s : ℕ) : firing_script d.graph :=
  d.rampScript (pPot s) pSgn (pLo d.length s) s

/-- The `{e0,e5}` march. -/
def mScript (d : DegSpec 6 9) (a r : ℕ) : firing_script d.graph :=
  d.rampScript (mPot r) mSgn (mLo a r) r

/-- The `star 0` march. -/
def wScript (d : DegSpec 6 9) (w : ℕ) : firing_script d.graph :=
  d.rampScript (wPot w) wSgn (wLo d.length w) w

end Ramps

/-! ## Divisor identities for the four marches

Each is one instantiation of the generic `DegSpec.prin_ramp_eq`, expanded over
the nine slots.  No case analysis and no heartbeat override occurs. -/

section RampEq

variable {d : DegSpec 6 9}

theorem prin_v_eq {u : ℕ} (h : DegSpec.RampData d (vPot u) vSgn (vLo d.length u) u)
    (hu6 : u ≤ d.length 6) (hu7 : u ≤ d.length 7) :
    prin d.graph (vScript d u) =
      (one_chip (G := d.graph) (d.pathAt 3 (dpos d.length + u)) -
          one_chip (d.pathAt 3 (dpos d.length))) +
        (one_chip (d.pathAt 6 (d.length 6 - u)) -
          one_chip (d.pathAt 6 (d.length 6))) +
        (one_chip (d.pathAt 7 (d.length 7 - u)) -
          one_chip (d.pathAt 7 (d.length 7))) := by
  have e6 : d.pathAt 6 (d.length 6 - u + u) = d.pathAt 6 (d.length 6) :=
    d.pathAt_of_eq 6 (by omega)
  have e7 : d.pathAt 7 (d.length 7 - u + u) = d.pathAt 7 (d.length 7) :=
    d.pathAt_of_eq 7 (by omega)
  rw [vScript, DegSpec.prin_ramp_eq h, sum_univ_nine]
  simp only [vSgn_0, vSgn_1, vSgn_2, vSgn_3, vSgn_4, vSgn_5, vSgn_6, vSgn_7,
    vSgn_8, vLo_0, vLo_1, vLo_2, vLo_3, vLo_4, vLo_5, vLo_6, vLo_7, vLo_8,
    e6, e7, zero_smul, one_smul, neg_smul]
  abel

theorem prin_p_eq {s : ℕ} (h : DegSpec.RampData d (pPot s) pSgn (pLo d.length s) s)
    (hs0 : s ≤ d.length 0) (hsd : s ≤ dpos d.length) (hs4 : s ≤ d.length 4) :
    prin d.graph (pScript d s) =
      (one_chip (G := d.graph) (d.pathAt 0 (d.length 0 - s)) -
          one_chip (d.pathAt 0 (d.length 0))) +
        (one_chip (d.pathAt 3 (dpos d.length - s)) -
          one_chip (d.pathAt 3 (dpos d.length))) +
        (one_chip (d.pathAt 4 (d.length 4 - s)) -
          one_chip (d.pathAt 4 (d.length 4))) := by
  have e0 : d.pathAt 0 (d.length 0 - s + s) = d.pathAt 0 (d.length 0) :=
    d.pathAt_of_eq 0 (by omega)
  have e3 : d.pathAt 3 (dpos d.length - s + s) = d.pathAt 3 (dpos d.length) :=
    d.pathAt_of_eq 3 (by omega)
  have e4 : d.pathAt 4 (d.length 4 - s + s) = d.pathAt 4 (d.length 4) :=
    d.pathAt_of_eq 4 (by omega)
  rw [pScript, DegSpec.prin_ramp_eq h, sum_univ_nine]
  simp only [pSgn_0, pSgn_1, pSgn_2, pSgn_3, pSgn_4, pSgn_5, pSgn_6, pSgn_7,
    pSgn_8, pLo_0, pLo_1, pLo_2, pLo_3, pLo_4, pLo_5, pLo_6, pLo_7, pLo_8,
    e0, e3, e4, zero_smul, one_smul]
  abel

theorem prin_m_eq {a r : ℕ} (h : DegSpec.RampData d (mPot r) mSgn (mLo a r) r)
    (hr1 : r ≤ a) :
    prin d.graph (mScript d a r) =
      (one_chip (G := d.graph) (d.pathAt 0 (a - r)) - one_chip (d.pathAt 0 a)) -
        (one_chip (d.pathAt 5 0) - one_chip (d.pathAt 5 r)) := by
  have e0 : d.pathAt 0 (a - r + r) = d.pathAt 0 a := d.pathAt_of_eq 0 (by omega)
  have e5 : d.pathAt 5 (0 + r) = d.pathAt 5 r := d.pathAt_of_eq 5 (by omega)
  rw [mScript, DegSpec.prin_ramp_eq h, sum_univ_nine]
  simp only [mSgn_0, mSgn_1, mSgn_2, mSgn_3, mSgn_4, mSgn_5, mSgn_6, mSgn_7,
    mSgn_8, mLo_0, mLo_1, mLo_2, mLo_3, mLo_4, mLo_5, mLo_6, mLo_7, mLo_8,
    e0, e5, zero_smul, one_smul, neg_smul]
  abel

theorem prin_w_eq {w : ℕ} (h : DegSpec.RampData d (wPot w) wSgn (wLo d.length w) w)
    (hww : w ≤ cRest d.length - m2Max d.length) (hw1 : w ≤ d.length 1)
    (hw2 : w ≤ d.length 2) :
    prin d.graph (wScript d w) =
      (one_chip (G := d.graph)
            (d.pathAt 0 (cRest d.length - m2Max d.length - w)) -
          one_chip (d.pathAt 0 (cRest d.length - m2Max d.length))) +
        (one_chip (d.pathAt 1 (d.length 1 - w)) -
          one_chip (d.pathAt 1 (d.length 1))) +
        (one_chip (d.pathAt 2 (d.length 2 - w)) -
          one_chip (d.pathAt 2 (d.length 2))) := by
  have e0 : d.pathAt 0 (cRest d.length - m2Max d.length - w + w) =
      d.pathAt 0 (cRest d.length - m2Max d.length) := d.pathAt_of_eq 0 (by omega)
  have e1 : d.pathAt 1 (d.length 1 - w + w) = d.pathAt 1 (d.length 1) :=
    d.pathAt_of_eq 1 (by omega)
  have e2 : d.pathAt 2 (d.length 2 - w + w) = d.pathAt 2 (d.length 2) :=
    d.pathAt_of_eq 2 (by omega)
  rw [wScript, DegSpec.prin_ramp_eq h, sum_univ_nine]
  simp only [wSgn_0, wSgn_1, wSgn_2, wSgn_3, wSgn_4, wSgn_5, wSgn_6, wSgn_7,
    wSgn_8, wLo_0, wLo_1, wLo_2, wLo_3, wLo_4, wLo_5, wLo_6, wLo_7, wLo_8,
    e0, e1, e2, zero_smul, one_smul]
  abel

end RampEq

/-! ## Bridging core classes and path positions

On the closed orthant these are the *only* places where a slot's two endpoints
can coincide, and `pathAt` already knows: `pathAt e k = coreVertex (head e)` for
every `k ≥ length e`, including `k = 0` on a vanishing slot. -/

section Bridge

variable {d : DegSpec 6 9}

theorem cvT0 (hp : IsCore097 d.core) : d.pathAt 0 0 = d.coreVertex 0 := by
  rw [d.pathAt_zero, hp.t0]

theorem cvT1 (hp : IsCore097 d.core) : d.pathAt 1 0 = d.coreVertex 0 := by
  rw [d.pathAt_zero, hp.t1]

theorem cvT2 (hp : IsCore097 d.core) : d.pathAt 2 0 = d.coreVertex 0 := by
  rw [d.pathAt_zero, hp.t2]

theorem cvT3 (hp : IsCore097 d.core) : d.pathAt 3 0 = d.coreVertex 1 := by
  rw [d.pathAt_zero, hp.t3]

theorem cvT4 (hp : IsCore097 d.core) : d.pathAt 4 0 = d.coreVertex 1 := by
  rw [d.pathAt_zero, hp.t4]

theorem cvT5 (hp : IsCore097 d.core) : d.pathAt 5 0 = d.coreVertex 1 := by
  rw [d.pathAt_zero, hp.t5]

theorem cvT6 (hp : IsCore097 d.core) : d.pathAt 6 0 = d.coreVertex 2 := by
  rw [d.pathAt_zero, hp.t6]

theorem cvT7 (hp : IsCore097 d.core) : d.pathAt 7 0 = d.coreVertex 2 := by
  rw [d.pathAt_zero, hp.t7]

theorem cvH0 (hp : IsCore097 d.core) :
    d.pathAt 0 (d.length 0) = d.coreVertex 4 := by
  rw [d.pathAt_length (le_refl _), hp.h0]

theorem cvH1 (hp : IsCore097 d.core) :
    d.pathAt 1 (d.length 1) = d.coreVertex 5 := by
  rw [d.pathAt_length (le_refl _), hp.h1]

theorem cvH2 (hp : IsCore097 d.core) :
    d.pathAt 2 (d.length 2) = d.coreVertex 5 := by
  rw [d.pathAt_length (le_refl _), hp.h2]

theorem cvH3 (hp : IsCore097 d.core) :
    d.pathAt 3 (d.length 3) = d.coreVertex 2 := by
  rw [d.pathAt_length (le_refl _), hp.h3]

theorem cvH4 (hp : IsCore097 d.core) :
    d.pathAt 4 (d.length 4) = d.coreVertex 3 := by
  rw [d.pathAt_length (le_refl _), hp.h4]

theorem cvH5 (hp : IsCore097 d.core) :
    d.pathAt 5 (d.length 5) = d.coreVertex 5 := by
  rw [d.pathAt_length (le_refl _), hp.h5]

theorem cvH6 (hp : IsCore097 d.core) :
    d.pathAt 6 (d.length 6) = d.coreVertex 3 := by
  rw [d.pathAt_length (le_refl _), hp.h6]

theorem cvH7 (hp : IsCore097 d.core) :
    d.pathAt 7 (d.length 7) = d.coreVertex 4 := by
  rw [d.pathAt_length (le_refl _), hp.h7]

end Bridge

/-! ## The pencil and the states it passes through -/

section States

/-- The degree-three pencil of row 097. -/
def pen (d : DegSpec 6 9) : CFDiv d.graph :=
  one_chip (d.pathAt 3 (dpos d.length)) + one_chip (d.coreVertex 3) +
    one_chip (d.coreVertex 4)

variable {d : DegSpec 6 9}

theorem deg_pen : deg (pen d) = 3 := by
  unfold pen
  rw [deg.map_add, deg.map_add, deg_one_chip, deg_one_chip, deg_one_chip]
  norm_num

theorem state_v (hp : IsCore097 d.core) (hrep : RepGen d) {u : ℕ}
    (hu3 : dpos d.length + u ≤ d.length 3) (hu6 : u ≤ d.length 6)
    (hu7 : u ≤ d.length 7) :
    pen d + prin d.graph (vScript d u) =
      one_chip (G := d.graph) (d.pathAt 3 (dpos d.length + u)) +
        one_chip (d.pathAt 6 (d.length 6 - u)) +
        one_chip (d.pathAt 7 (d.length 7 - u)) := by
  rw [pen, prin_v_eq (vRamp hp hrep hu3 hu6 hu7) hu6 hu7, cvH6 hp, cvH7 hp]
  abel

theorem state_p (hp : IsCore097 d.core) (hrep : RepGen d) {s : ℕ}
    (hs0 : s ≤ d.length 0) (hsd : s ≤ dpos d.length)
    (hd3 : dpos d.length ≤ d.length 3) (hs4 : s ≤ d.length 4) :
    pen d + prin d.graph (pScript d s) =
      one_chip (G := d.graph) (d.pathAt 0 (d.length 0 - s)) +
        one_chip (d.pathAt 3 (dpos d.length - s)) +
        one_chip (d.pathAt 4 (d.length 4 - s)) := by
  rw [pen, prin_p_eq (pRamp hp hrep hs0 hsd hd3 hs4) hs0 hsd hs4, cvH4 hp,
    cvH0 hp]
  abel

theorem state_m1 (hp : IsCore097 d.core) (hrep : RepGen d)
    (hd0 : dpos d.length ≤ d.length 0) (hd3 : dpos d.length ≤ d.length 3)
    (hd4 : dpos d.length ≤ d.length 4) {r : ℕ} (hr : r ≤ d.length 5)
    (hrle : r ≤ d.length 0 - dpos d.length) :
    pen d + prin d.graph (pScript d (dpos d.length) +
        mScript d (d.length 0 - dpos d.length) r) =
      one_chip (G := d.graph)
          (d.pathAt 0 (d.length 0 - dpos d.length - r)) +
        one_chip (d.pathAt 5 r) +
        one_chip (d.pathAt 4 (d.length 4 - dpos d.length)) := by
  have hz : d.pathAt 3 (dpos d.length - dpos d.length) = d.pathAt 5 0 := by
    rw [d.pathAt_of_eq 3 (Nat.sub_self _), cvT3 hp, cvT5 hp]
  rw [map_add, ← add_assoc, state_p hp hrep hd0 le_rfl hd3 hd4,
    prin_m_eq (a := d.length 0 - dpos d.length)
      (mRamp hp hrep (by omega) hrle hr) hrle, hz]
  abel

theorem state_m2 (hp : IsCore097 d.core) (hrep : RepGen d)
    (hd0 : dpos d.length ≤ d.length 0) (hd3 : dpos d.length ≤ d.length 3)
    (hd4 : dpos d.length ≤ d.length 4)
    (hcase : d.length 4 = dpos d.length)
    (h5 : d.length 5 ≤ d.length 0 - dpos d.length)
    {r : ℕ} (hr : r ≤ d.length 5) (hrc : r ≤ cRest d.length) :
    pen d + prin d.graph (pScript d (dpos d.length) +
        mScript d (d.length 0 - dpos d.length) (d.length 5) +
        mScript d (cRest d.length) r) =
      one_chip (G := d.graph) (d.pathAt 0 (cRest d.length - r)) +
        one_chip (d.pathAt 5 r) + one_chip (d.coreVertex 5) := by
  have hcr : cRest d.length ≤ d.length 0 := by simp only [cRest]; omega
  have heq0 : d.pathAt 0 (d.length 0 - dpos d.length - d.length 5) =
      d.pathAt 0 (cRest d.length) :=
    d.pathAt_of_eq 0 (by simp only [cRest]; omega)
  have hz4 : d.pathAt 4 (d.length 4 - dpos d.length) = d.pathAt 5 0 := by
    rw [d.pathAt_of_eq 4 (show d.length 4 - dpos d.length = 0 by omega),
      cvT4 hp, cvT5 hp]
  rw [map_add, ← add_assoc, state_m1 hp hrep hd0 hd3 hd4 le_rfl h5,
    prin_m_eq (mRamp hp hrep hcr hrc hr) hrc, hz4, heq0, cvH5 hp]
  abel

theorem state_w (hp : IsCore097 d.core) (hrep : RepGen d)
    (hd0 : dpos d.length ≤ d.length 0) (hd3 : dpos d.length ≤ d.length 3)
    (hd4 : dpos d.length ≤ d.length 4)
    (hcase : d.length 4 = dpos d.length)
    (h5 : d.length 5 ≤ d.length 0 - dpos d.length)
    (hm2 : m2Max d.length = d.length 5)
    {w : ℕ} (hww : w ≤ cRest d.length - m2Max d.length)
    (hw1 : w ≤ d.length 1) (hw2 : w ≤ d.length 2) :
    pen d + prin d.graph (pScript d (dpos d.length) +
        mScript d (d.length 0 - dpos d.length) (d.length 5) +
        mScript d (cRest d.length) (d.length 5) + wScript d w) =
      one_chip (G := d.graph)
          (d.pathAt 0 (cRest d.length - m2Max d.length - w)) +
        one_chip (d.pathAt 1 (d.length 1 - w)) +
        one_chip (d.pathAt 2 (d.length 2 - w)) := by
  have hcr : cRest d.length ≤ d.length 0 := by simp only [cRest]; omega
  have h5c : d.length 5 ≤ cRest d.length := by
    have hm := hm2; simp only [m2Max] at hm; omega
  have hx : cRest d.length - m2Max d.length ≤ d.length 0 := by omega
  have heq0 : d.pathAt 0 (cRest d.length - d.length 5) =
      d.pathAt 0 (cRest d.length - m2Max d.length) :=
    d.pathAt_of_eq 0 (by omega)
  rw [map_add, ← add_assoc,
    state_m2 hp hrep hd0 hd3 hd4 hcase h5 le_rfl h5c,
    prin_w_eq (wRamp hp hrep hx hww hw1 hw2) hww hw1 hw2, heq0, cvH1 hp,
    cvH2 hp, cvH5 hp]
  abel

end States

/-! ## Reaching every core class -/

section Assembly

variable {d : DegSpec 6 9}

theorem chip_three (A B C q : d.graph.V) (hq : q = A ∨ q = B ∨ q = C) :
    1 ≤ (one_chip A + one_chip B + one_chip C) q := by
  rcases hq with rfl | rfl | rfl
  · exact threeChipDivisor_has_chip_first _ _ _
  · exact threeChipDivisor_has_chip_second _ _ _
  · exact threeChipDivisor_has_chip_third _ _ _

theorem reaches_three (script : firing_script d.graph) (A B C : d.graph.V)
    (hst : pen d + prin d.graph script = one_chip A + one_chip B + one_chip C)
    (q : d.graph.V) (hq : q = A ∨ q = B ∨ q = C) :
    StrongSeparator.Reaches d.graph (pen d) q := by
  refine d.reaches_of_script (pen d) script q ?_ ?_
  · rw [hst]
    exact threeChipDivisor_effective A B C
  · rw [hst]
    exact chip_three A B C q hq

end Assembly

/-! ## The covering argument -/

section Cover

variable {d : DegSpec 6 9}

theorem bounds (hba : d.length 5 ≤ d.length 0) (hbc : d.length 4 ≤ d.length 3) :
    dpos d.length ≤ d.length 4 ∧ dpos d.length ≤ d.length 3 ∧
      dpos d.length ≤ d.length 0 ∧
      d.length 5 ≤ d.length 0 - dpos d.length := by
  simp only [dpos]
  omega

theorem uBounds (hbc : d.length 4 ≤ d.length 3) :
    dpos d.length + uMax d.length ≤ d.length 3 ∧
      uMax d.length ≤ d.length 6 ∧ uMax d.length ≤ d.length 7 := by
  have hd4 : dpos d.length ≤ d.length 4 := by simp only [dpos]; omega
  simp only [uMax]
  omega

theorem wLen (hba : d.length 5 ≤ d.length 0) :
    cRest d.length - m2Max d.length ≤ d.length 0 := by
  simp only [cRest, m2Max, dpos]
  omega

theorem wBounds : wMax d.length ≤ cRest d.length - m2Max d.length ∧
    wMax d.length ≤ d.length 1 ∧ wMax d.length ≤ d.length 2 := by
  simp only [wMax]
  omega

theorem mBounds : m2Max d.length ≤ cRest d.length ∧
    m2Max d.length ≤ d.length 5 := by
  simp only [m2Max]
  omega

theorem cRest_le (hba : d.length 5 ≤ d.length 0) :
    cRest d.length ≤ d.length 0 := by
  simp only [cRest]
  omega

/-- A nonzero residual imbalance forces the moving chip to sit at the far end
of slot `e4`. -/
theorem dpos_eq_of_cRest_pos (h : 0 < cRest d.length) :
    d.length 4 = dpos d.length := by
  simp only [cRest, dpos] at h ⊢
  omega

/-- If the `star 0` march is nontrivial then the second `{e0,e5}` pass ran to
the end of slot `e5`. -/
theorem m2Max_eq_of_pos (h : 0 < cRest d.length - m2Max d.length) :
    m2Max d.length = d.length 5 := by
  simp only [m2Max] at h ⊢
  omega

theorem cRest_pos_of (h : 0 < cRest d.length - m2Max d.length) :
    0 < cRest d.length := by
  have := (mBounds (d := d)).1
  omega

/-- A state with chips at both banana endpoints, available whenever the
`star 0` march is trivial. -/
theorem banana_pair (hp : IsCore097 d.core) (hrep : RepGen d)
    (hba : d.length 5 ≤ d.length 0) (hbc : d.length 4 ≤ d.length 3)
    (hx0 : cRest d.length - m2Max d.length = 0) :
    ∃ (script : firing_script d.graph) (Z : d.graph.V),
      pen d + prin d.graph script =
        one_chip (d.coreVertex 0) + one_chip (d.coreVertex 5) + one_chip Z := by
  obtain ⟨hd4, hd3, hd0, h5⟩ := bounds hba hbc
  have hcr : cRest d.length ≤ d.length 0 := cRest_le hba
  by_cases hcase : d.length 4 = dpos d.length
  · refine ⟨pScript d (dpos d.length) +
      mScript d (d.length 0 - dpos d.length) (d.length 5) +
      mScript d (cRest d.length) (m2Max d.length),
      d.pathAt 5 (m2Max d.length), ?_⟩
    rw [state_m2 hp hrep hd0 hd3 hd4 hcase h5 (mBounds (d := d)).2
      (mBounds (d := d)).1]
    have e1 : d.pathAt 0 (cRest d.length - m2Max d.length) = d.coreVertex 0 := by
      rw [d.pathAt_of_eq 0 hx0, cvT0 hp]
    rw [e1]
    abel
  · have hc0 : cRest d.length = 0 := by
      simp only [cRest, dpos] at *
      omega
    refine ⟨pScript d (dpos d.length) +
      mScript d (d.length 0 - dpos d.length) (d.length 5),
      d.pathAt 4 (d.length 4 - dpos d.length), ?_⟩
    rw [state_m1 hp hrep hd0 hd3 hd4 le_rfl h5]
    have e1 : d.pathAt 0 (d.length 0 - dpos d.length - d.length 5) =
        d.coreVertex 0 := by
      rw [d.pathAt_of_eq 0 (show d.length 0 - dpos d.length - d.length 5 = 0 by
        simp only [cRest] at hc0; omega), cvT0 hp]
    have e2 : d.pathAt 5 (d.length 5) = d.coreVertex 5 := cvH5 hp
    rw [e1, e2]

/-- At the end of the `star 2` march there is a chip at the hub `2`. -/
theorem hub_two (hp : IsCore097 d.core) (hbc : d.length 4 ≤ d.length 3) :
    d.coreVertex 2 = d.pathAt 3 (dpos d.length + uMax d.length) ∨
      d.coreVertex 2 = d.pathAt 6 (d.length 6 - uMax d.length) ∨
      d.coreVertex 2 = d.pathAt 7 (d.length 7 - uMax d.length) := by
  obtain ⟨hU3, hU6, hU7⟩ := uBounds hbc
  have hd4 : dpos d.length ≤ d.length 4 := by simp only [dpos]; omega
  have hcase : dpos d.length + uMax d.length = d.length 3 ∨
      d.length 6 - uMax d.length = 0 ∨ d.length 7 - uMax d.length = 0 := by
    simp only [uMax] at *
    omega
  rcases hcase with hc | hc | hc
  · exact Or.inl (by rw [← cvH3 hp, d.pathAt_of_eq 3 hc])
  · exact Or.inr (Or.inl (by rw [← cvT6 hp, d.pathAt_of_eq 6 hc]))
  · exact Or.inr (Or.inr (by rw [← cvT7 hp, d.pathAt_of_eq 7 hc]))

/-- At the end of the `star 0` march there is a chip at the vertex `0`. -/
theorem hub_zero (hp : IsCore097 d.core) (hba : d.length 5 ≤ d.length 0) :
    d.coreVertex 0 =
        d.pathAt 0 (cRest d.length - m2Max d.length - wMax d.length) ∨
      d.coreVertex 0 = d.pathAt 1 (d.length 1 - wMax d.length) ∨
      d.coreVertex 0 = d.pathAt 2 (d.length 2 - wMax d.length) := by
  have hw := wLen (d := d) hba
  have hcase : cRest d.length - m2Max d.length - wMax d.length = 0 ∨
      d.length 1 - wMax d.length = 0 ∨ d.length 2 - wMax d.length = 0 := by
    simp only [wMax] at *
    omega
  rcases hcase with hc | hc | hc
  · exact Or.inl (by rw [← cvT0 hp, d.pathAt_of_eq 0 hc])
  · exact Or.inr (Or.inl (by rw [← cvT1 hp, d.pathAt_of_eq 1 hc]))
  · exact Or.inr (Or.inr (by rw [← cvT2 hp, d.pathAt_of_eq 2 hc]))

/-- **Every core class is reached.** -/
theorem reaches_core (hp : IsCore097 d.core) (hrep : RepGen d)
    (hba : d.length 5 ≤ d.length 0) (hbc : d.length 4 ≤ d.length 3)
    (v : Fin 6) :
    StrongSeparator.Reaches d.graph (pen d) (d.coreVertex v) := by
  obtain ⟨hd4, hd3, hd0, h5⟩ := bounds hba hbc
  obtain ⟨hU3, hU6, hU7⟩ := uBounds hbc
  obtain ⟨hmc, hm5⟩ := mBounds (d := d)
  obtain ⟨hW0, hW1, hW2⟩ := wBounds (d := d)
  have hcr := cRest_le (d := d) hba
  revert v
  refine forall_fin_six ?_ ?_ ?_ ?_ ?_ ?_
  · -- the banana vertex `0`
    by_cases hx0 : cRest d.length - m2Max d.length = 0
    · obtain ⟨script, Z, hst⟩ := banana_pair hp hrep hba hbc hx0
      exact reaches_three script _ _ _ hst _ (Or.inl rfl)
    · have hpos : 0 < cRest d.length - m2Max d.length := by omega
      have hcase := dpos_eq_of_cRest_pos (cRest_pos_of hpos)
      have hm2 := m2Max_eq_of_pos hpos
      exact reaches_three _ _ _ _
        (state_w (w := wMax d.length) hp hrep hd0 hd3 hd4 hcase h5 hm2 hW0 hW1
          hW2) _ (hub_zero hp hba)
  · -- the theta arc vertex `1`
    refine reaches_three _ _ _ _
      (state_p (s := dpos d.length) hp hrep hd0 le_rfl hd3 hd4) _
      (Or.inr (Or.inl ?_))
    rw [d.pathAt_of_eq 3 (Nat.sub_self _), cvT3 hp]
  · -- the hub `2`
    exact reaches_three _ _ _ _
      (state_v (u := uMax d.length) hp hrep hU3 hU6 hU7) _ (hub_two hp hbc)
  · -- the hub `3`, carried by the pencil itself
    refine reaches_three 0 (d.pathAt 3 (dpos d.length)) (d.coreVertex 3)
      (d.coreVertex 4) ?_ _ (Or.inr (Or.inl rfl))
    rw [map_zero, add_zero, pen]
  · -- the handle vertex `4`, carried by the pencil itself
    refine reaches_three 0 (d.pathAt 3 (dpos d.length)) (d.coreVertex 3)
      (d.coreVertex 4) ?_ _ (Or.inr (Or.inr rfl))
    rw [map_zero, add_zero, pen]
  · -- the banana vertex `5`
    refine reaches_three _ _ _ _
      (state_m1 (r := d.length 5) hp hrep hd0 hd3 hd4 le_rfl h5) _
      (Or.inr (Or.inl ?_))
    exact (cvH5 hp).symm

/-- **Row 097 on the closed orthant, in the chamber
`length 5 ≤ length 0`, `length 4 ≤ length 3`.** -/
theorem bnExists_one_three (hp : IsCore097 d.core) (hrep : RepGen d)
    (hba : d.length 5 ≤ d.length 0) (hbc : d.length 4 ≤ d.length 3) :
    BNExists d.graph 1 3 :=
  bnExists_of_reaches_coreVertices d hp.core_connected (pen d) 3 deg_pen
    (fun v => reaches_core hp hrep hba hbc v)

end Cover

/-! ## The catalog row, on the closed orthant

An arbitrary length vector is moved into the chamber
`length 5 ≤ length 0 ∧ length 4 ≤ length 3` by the Klein four-group of
automorphisms of the row-097 core, transported with
`ClosedCoreSymmetry.bnExists_iff` — the closed-orthant counterpart of
`Certificate/SubdivisionIso.lean`'s `bnExists_of_coreAuto`.  The transport is
along the *contracted* graphs, so the chamber reduction costs nothing extra at
a face. -/

section Row

open Utilities.Certificate.CoreOrbitReduction

/-- The row-097 split core is the public cubic-atlas presentation. -/
abbrev core : ExplicitPotential.Core 6 9 :=
  AtanasovRanganathan.GenusFourCubicAtlas.row097Core

theorem isCore097_core : IsCore097 core := by constructor <;> decide

/-- `σ = (0 5)(1 4)` on core vertices. -/
def sigVertex : Equiv.Perm (Fin 6) where
  toFun := ![5, 4, 2, 3, 1, 0]
  invFun := ![5, 4, 2, 3, 1, 0]
  left_inv := by decide
  right_inv := by decide

/-- `σ` on edge slots: `e0 ↔ e5`, `e3 ↔ e7`, `e4 ↔ e8`. -/
def sigSlot : Equiv.Perm (Fin 9) where
  toFun := ![5, 1, 2, 7, 8, 0, 6, 3, 4]
  invFun := ![5, 1, 2, 7, 8, 0, 6, 3, 4]
  left_inv := by decide
  right_inv := by decide

/-- Reading directions of the `σ`-image slots. -/
def sigReversed : Fin 9 → Bool :=
  ![true, true, true, true, true, true, false, true, true]

/-- `τ = (2 3)` on core vertices. -/
def tauVertex : Equiv.Perm (Fin 6) where
  toFun := ![0, 1, 3, 2, 4, 5]
  invFun := ![0, 1, 3, 2, 4, 5]
  left_inv := by decide
  right_inv := by decide

/-- `τ` on edge slots: `e3 ↔ e4`, `e7 ↔ e8`. -/
def tauSlot : Equiv.Perm (Fin 9) where
  toFun := ![0, 1, 2, 4, 3, 5, 6, 8, 7]
  invFun := ![0, 1, 2, 4, 3, 5, 6, 8, 7]
  left_inv := by decide
  right_inv := by decide

/-- Reading directions of the `τ`-image slots. -/
def tauReversed : Fin 9 → Bool :=
  ![false, false, false, false, false, false, true, false, false]

/-- `σ`, as a core symmetry. -/
def sigma : CoreSymmetry core where
  vertexPerm := sigVertex
  slotPerm := sigSlot
  reversed := sigReversed
  tail_eq := by decide
  head_eq := by decide

/-- `τ`, as a core symmetry. -/
def tau : CoreSymmetry core where
  vertexPerm := tauVertex
  slotPerm := tauSlot
  reversed := tauReversed
  tail_eq := by decide
  head_eq := by decide

/-- `censusSpec`'s representative map is a `compFold` of the vanishing set, so
`RepGen` — the one hypothesis a closed-orthant ramp needs beyond the
open-orthant ones — is free. -/
theorem repGen_censusSpec (ℓ : Fin 9 → ℕ)
    (hForest : IsForest core (zeroSet ℓ))
    (hNotLoopy : ¬ IsLoopy core (zeroSet ℓ)) :
    RepGen (censusSpec core (by norm_num) ℓ hForest hNotLoopy) :=
  fun u v h => (compFold_iff core (zeroSet ℓ) u v).mp h

/-- **`BNExists … 1 3` for catalog row `097`, on the whole closed length
orthant.**  Quantified over every length vector whose vanishing set is a
non-loopy forest — every subdivision of the row-097 core *and* every
equal-genus contraction of one.

No Boolean check, no generated data, and no length chamber decomposition
occurs anywhere below: the four cases are the orbit of one under the core's
Klein four-group. -/
theorem bnExists_closed (ℓ : Fin 9 → ℕ)
    (hForest : IsForest core (zeroSet ℓ))
    (hNotLoopy : ¬ IsLoopy core (zeroSet ℓ)) :
    BNExists (censusSpec core (by norm_num) ℓ hForest hNotLoopy).graph 1 3 := by
  have ht0 : (tau.slotPerm.symm : Fin 9 → Fin 9) 0 = 0 := by decide
  have ht3 : (tau.slotPerm.symm : Fin 9 → Fin 9) 3 = 4 := by decide
  have ht4 : (tau.slotPerm.symm : Fin 9 → Fin 9) 4 = 3 := by decide
  have ht5 : (tau.slotPerm.symm : Fin 9 → Fin 9) 5 = 5 := by decide
  have hs0 : (sigma.slotPerm.symm : Fin 9 → Fin 9) 0 = 5 := by decide
  have hs3 : (sigma.slotPerm.symm : Fin 9 → Fin 9) 3 = 7 := by decide
  have hs4 : (sigma.slotPerm.symm : Fin 9 → Fin 9) 4 = 8 := by decide
  have hs5 : (sigma.slotPerm.symm : Fin 9 → Fin 9) 5 = 0 := by decide
  by_cases h50 : ℓ 5 ≤ ℓ 0
  · by_cases h43 : ℓ 4 ≤ ℓ 3
    · exact bnExists_one_three isCore097_core
        (repGen_censusSpec ℓ hForest hNotLoopy) h50 h43
    · refine (ClosedCoreSymmetry.bnExists_iff tau ℓ (by norm_num) hForest hNotLoopy
        1 3).mp ?_
      refine bnExists_one_three isCore097_core
        (repGen_censusSpec _ _ _) ?_ ?_
      · show ℓ ((tau.slotPerm.symm : Fin 9 → Fin 9) 5) ≤
          ℓ ((tau.slotPerm.symm : Fin 9 → Fin 9) 0)
        rw [ht5, ht0]; exact h50
      · show ℓ ((tau.slotPerm.symm : Fin 9 → Fin 9) 4) ≤
          ℓ ((tau.slotPerm.symm : Fin 9 → Fin 9) 3)
        rw [ht4, ht3]; omega
  · by_cases h87 : ℓ 8 ≤ ℓ 7
    · refine (ClosedCoreSymmetry.bnExists_iff sigma ℓ (by norm_num) hForest hNotLoopy
        1 3).mp ?_
      refine bnExists_one_three isCore097_core
        (repGen_censusSpec _ _ _) ?_ ?_
      · show ℓ ((sigma.slotPerm.symm : Fin 9 → Fin 9) 5) ≤
          ℓ ((sigma.slotPerm.symm : Fin 9 → Fin 9) 0)
        rw [hs5, hs0]; omega
      · show ℓ ((sigma.slotPerm.symm : Fin 9 → Fin 9) 4) ≤
          ℓ ((sigma.slotPerm.symm : Fin 9 → Fin 9) 3)
        rw [hs4, hs3]; exact h87
    · refine (ClosedCoreSymmetry.bnExists_iff sigma ℓ (by norm_num) hForest hNotLoopy
        1 3).mp ?_
      refine (ClosedCoreSymmetry.bnExists_iff tau
        (ClosedCoreSymmetry.targetLength sigma ℓ)
        (by norm_num) _ _ 1 3).mp ?_
      refine bnExists_one_three isCore097_core
        (repGen_censusSpec _ _ _) ?_ ?_
      · show ℓ ((sigma.slotPerm.symm : Fin 9 → Fin 9)
            ((tau.slotPerm.symm : Fin 9 → Fin 9) 5)) ≤
          ℓ ((sigma.slotPerm.symm : Fin 9 → Fin 9)
            ((tau.slotPerm.symm : Fin 9 → Fin 9) 0))
        rw [ht5, ht0, hs5, hs0]; omega
      · show ℓ ((sigma.slotPerm.symm : Fin 9 → Fin 9)
            ((tau.slotPerm.symm : Fin 9 → Fin 9) 4)) ≤
          ℓ ((sigma.slotPerm.symm : Fin 9 → Fin 9)
            ((tau.slotPerm.symm : Fin 9 → Fin 9) 3))
        rw [ht4, ht3, hs3, hs4]; omega

/-- The object the conclusion speaks about has the row's genus at every face. -/
theorem genus_eq (ℓ : Fin 9 → ℕ)
    (hForest : IsForest core (zeroSet ℓ))
    (hNotLoopy : ¬ IsLoopy core (zeroSet ℓ)) :
    genus (censusSpec core (by norm_num) ℓ hForest hNotLoopy).graph = 4 := by
  rw [DegSpec.genus_graph]
  norm_num

end Row

end LowGenus.GenusFourRow097Closed
