import DraismaVargas.Infrastructure.GluingContraction

/-!
# Fibres of the source vertex map of a contracted gluing datum

`DraismaVargas/Infrastructure/GluingContraction.lean` contracts a gluing datum
along one target occurrence and builds
`GluingContraction.sourceVertexMap : data.SourceVertex → (contractDatum …).SourceVertex`,
which it proves surjective.  This file describes its *fibres*.

The file has three parts.

## (1) The generation property of the join

`SheetPartition.join` is built in `Infrastructure/SheetJoin.lean` as the
partition whose relation is `SheetPartition.JoinRel`, the `Relation.EqvGen` of
the union of the two endpoint relations.  `EqvGen` carries explicit `symm` and
`trans` constructors, so it is not directly a *chain*.  Because both endpoint
relations are already equivalence relations, the symmetry and transitivity
constructors are redundant, and the join class of a sheet is exactly the set of
sheets reachable by a finite **alternating chain** of endpoint steps:

* `joinRel_iff_altChain` — `JoinRel left right i j ↔ AltChain left right i j`,
  where `AltChain` is `Relation.ReflTransGen (AltStep left right)` and
  `AltStep left right i j` is `left.Rel i j ∨ right.Rel i j`;
* `join_rel_iff_altChain`, `isJoin_rel_iff_altChain` — the same statement read
  through the constructed join and through an arbitrary join;
* `joinRel_iff_reflTransGen_altRound` — the genuinely *alternating* form: the
  join is the reflexive-transitive closure of "one left-step then one
  right-step";
* `joinRel_iff_exists_chain` — the `List.IsChain` form;
* `joinRel_map` — the induction principle the rest of the file runs on: any
  equivalence relation pulled back along a map that identifies both endpoint
  relations already identifies the whole join.

## (2) The fibre equation

`sourceVertexMap_eq_iff` says that two source vertices have the same image
exactly when they are joined by a chain of source occurrences lying over the
contracted target occurrence (`ReachThroughContracted`).  The easy direction is
an induction using `GluingContraction.sourceVertexMap_sourceEnds_eq_of_contracted`.
The substantive direction is (1) together with the observation that the
edge partition above the contracted occurrence refines *both* endpoint vertex
partitions, so that the two endpoint copies of every sheet are joined by an
actual source occurrence (`reach_sourceEndpoint_left_right`).

The off-merge case is separated out as `sourceVertexMap_eq_iff_of_ne`
(injectivity away from the merge) and the merge case as
`sourceVertexMap_eq_iff_joinRel` / `sourceVertexMap_eq_iff_join_rel` /
`sourceVertexMap_eq_iff_altChain`; `sourceVertexMap_eq_iff_cases` bundles the
two into one explicit case description.  `contractedStep_mem_sourceGraph_edges`
records that a `ContractedStep` is an edge of `sourceGraph`, so
`ReachThroughContracted` really is "joined by a walk".

## (3) Surviving occurrences

`sourceEdgeMap_surjective`, `sourceEdgeMap_bijective` and `sourceEdgeEquiv`
say the surviving source occurrences are exactly the source occurrences of the
contracted datum, and `sourceEdgeIndex_sourceEdgeMap` (with its
`sourceEdgeEquiv` and inverse forms) says the contraction preserves
`sourceEdgeIndex`.
-/

namespace DraismaVargas.Infrastructure

namespace ContractionFibre

/-! ## (1) The join is generated by alternating chains -/

section Join

variable {d : ℕ}

/-- One step of an alternating chain: a step inside a block of the left
endpoint partition, or a step inside a block of the right one. -/
def AltStep (left right : SheetPartition d) (i j : Fin d) : Prop :=
  left.Rel i j ∨ right.Rel i j

theorem altStep_of_left {left right : SheetPartition d} {i j : Fin d}
    (h : left.Rel i j) : AltStep left right i j := Or.inl h

theorem altStep_of_right {left right : SheetPartition d} {i j : Fin d}
    (h : right.Rel i j) : AltStep left right i j := Or.inr h

theorem AltStep.symm {left right : SheetPartition d} {i j : Fin d}
    (h : AltStep left right i j) : AltStep left right j i :=
  h.elim (fun hLeft ↦ Or.inl hLeft.symm) fun hRight ↦ Or.inr hRight.symm

theorem AltStep.joinRel {left right : SheetPartition d} {i j : Fin d}
    (h : AltStep left right i j) : SheetPartition.JoinRel left right i j :=
  h.elim SheetPartition.joinRel_of_left SheetPartition.joinRel_of_right

/-- An **alternating chain**: finitely many consecutive endpoint steps. -/
def AltChain (left right : SheetPartition d) : Fin d → Fin d → Prop :=
  Relation.ReflTransGen (AltStep left right)

theorem AltChain.refl (left right : SheetPartition d) (i : Fin d) :
    AltChain left right i i := Relation.ReflTransGen.refl

theorem AltChain.single {left right : SheetPartition d} {i j : Fin d}
    (h : AltStep left right i j) : AltChain left right i j :=
  Relation.ReflTransGen.single h

theorem AltChain.trans {left right : SheetPartition d} {i j k : Fin d}
    (hij : AltChain left right i j) (hjk : AltChain left right j k) :
    AltChain left right i k := Relation.ReflTransGen.trans hij hjk

theorem AltChain.symm {left right : SheetPartition d} {i j : Fin d}
    (h : AltChain left right i j) : AltChain left right j i := by
  induction h with
  | refl => exact AltChain.refl left right i
  | tail _ hStep ih => exact Relation.ReflTransGen.head hStep.symm ih

theorem altChain_equivalence (left right : SheetPartition d) :
    Equivalence (AltChain left right) :=
  ⟨AltChain.refl left right, AltChain.symm, AltChain.trans⟩

/-- **The generation property of the join.**  Two sheets are join-related
exactly when a finite alternating chain of left- and right-steps connects
them.  `JoinRel` is an `EqvGen`, which carries `symm` and `trans`
constructors; both are redundant here because the two endpoint relations are
themselves equivalence relations. -/
theorem joinRel_iff_altChain (left right : SheetPartition d) (i j : Fin d) :
    SheetPartition.JoinRel left right i j ↔ AltChain left right i j := by
  constructor
  · intro h
    induction h with
    | rel x y hxy => exact AltChain.single hxy
    | refl x => exact AltChain.refl left right x
    | symm x y _ ih => exact ih.symm
    | trans x y z _ _ ihFirst ihSecond => exact ihFirst.trans ihSecond
  · intro h
    induction h with
    | refl => exact SheetPartition.joinRel_refl left right i
    | tail _ hStep ih => exact ih.trans hStep.joinRel

/-- The generation property read through the constructed join. -/
theorem join_rel_iff_altChain (left right : SheetPartition d) (i j : Fin d) :
    (SheetPartition.join left right).Rel i j ↔ AltChain left right i j :=
  (SheetPartition.join_rel_iff left right i j).trans (joinRel_iff_altChain left right i j)

/-- The generation property read through an arbitrary join. -/
theorem isJoin_rel_iff_altChain {left right wall : SheetPartition d}
    (h : SheetPartition.IsJoin left right wall) (i j : Fin d) :
    wall.Rel i j ↔ AltChain left right i j :=
  (h i j).trans (joinRel_iff_altChain left right i j)

/-- One *round* of a strictly alternating chain: a left-step followed by a
right-step. -/
def AltRound (left right : SheetPartition d) (i j : Fin d) : Prop :=
  ∃ k, left.Rel i k ∧ right.Rel k j

theorem altRound_of_left {left right : SheetPartition d} {i j : Fin d}
    (h : left.Rel i j) : AltRound left right i j :=
  ⟨j, h, rfl⟩

theorem altRound_of_right {left right : SheetPartition d} {i j : Fin d}
    (h : right.Rel i j) : AltRound left right i j :=
  ⟨i, rfl, h⟩

theorem AltRound.joinRel {left right : SheetPartition d} {i j : Fin d}
    (h : AltRound left right i j) : SheetPartition.JoinRel left right i j := by
  obtain ⟨k, hLeft, hRight⟩ := h
  exact (SheetPartition.joinRel_of_left hLeft).trans (SheetPartition.joinRel_of_right hRight)

/-- The strictly alternating form of the generation property: the join is the
reflexive-transitive closure of "follow the left partition, then the right
one". -/
theorem joinRel_iff_reflTransGen_altRound (left right : SheetPartition d) (i j : Fin d) :
    SheetPartition.JoinRel left right i j ↔
      Relation.ReflTransGen (AltRound left right) i j := by
  constructor
  · intro h
    have hChain : Relation.ReflTransGen (AltStep left right) i j :=
      (joinRel_iff_altChain left right i j).mp h
    exact Relation.ReflTransGen.mono
      (fun x y hxy ↦ hxy.elim altRound_of_left altRound_of_right) _ _ hChain
  · intro h
    induction h with
    | refl => exact SheetPartition.joinRel_refl left right i
    | tail _ hRound ih => exact ih.trans hRound.joinRel

/-- The list form of the generation property. -/
theorem joinRel_iff_exists_chain (left right : SheetPartition d) (i j : Fin d) :
    SheetPartition.JoinRel left right i j ↔
      ∃ l : List (Fin d), List.IsChain (AltStep left right) (i :: l) ∧
        (i :: l).getLast (List.cons_ne_nil _ _) = j := by
  rw [joinRel_iff_altChain]
  constructor
  · exact fun h ↦ List.exists_isChain_cons_of_relationReflTransGen h
  · rintro ⟨l, hChain, hLast⟩
    exact List.relationReflTransGen_of_exists_isChain_cons l hChain hLast

/-- **The induction principle the join is used through.**  If a map identifies
every left-step and every right-step of sheets, it identifies every pair of
join-related sheets.  This is `SheetPartition.IsJoin.least` for an arbitrary
equivalence relation pulled back along an arbitrary map, and it is the form the
fibre computation below needs. -/
theorem joinRel_map {β : Sort*} {left right : SheetPartition d}
    {rel : β → β → Prop} (hEquiv : Equivalence rel) (f : Fin d → β)
    (hLeft : ∀ i j, left.Rel i j → rel (f i) (f j))
    (hRight : ∀ i j, right.Rel i j → rel (f i) (f j))
    {i j : Fin d} (h : SheetPartition.JoinRel left right i j) : rel (f i) (f j) := by
  induction h with
  | rel x y hxy => exact hxy.elim (hLeft x y) (hRight x y)
  | refl x => exact hEquiv.refl (f x)
  | symm x y _ ih => exact hEquiv.symm ih
  | trans x y z _ _ ihFirst ihSecond => exact hEquiv.trans ihFirst ihSecond

/-- `joinRel_map` for the constructed join. -/
theorem join_rel_map {β : Sort*} {left right : SheetPartition d}
    {rel : β → β → Prop} (hEquiv : Equivalence rel) (f : Fin d → β)
    (hLeft : ∀ i j, left.Rel i j → rel (f i) (f j))
    (hRight : ∀ i j, right.Rel i j → rel (f i) (f j))
    {i j : Fin d} (h : (SheetPartition.join left right).Rel i j) :
    rel (f i) (f j) :=
  joinRel_map hEquiv f hLeft hRight ((SheetPartition.join_rel_iff left right i j).mp h)

end Join

/-! ## (2) The fibre of the source vertex map -/

section Fibre

open GraphContraction GluingContraction

variable {target : CFGraph} {degree : ℕ} {a b : target.V}

/-- Every source vertex is the endpoint named by its own target vertex and
sheet. -/
theorem sourceEndpoint_self (data : GluingDatum target degree) (x : data.SourceVertex) :
    data.sourceEndpoint x.1.1 x.1.2 = x :=
  Subtype.ext (Prod.ext rfl x.2)

/-- Two source vertices are the two endpoints of one source edge occurrence
lying over the target occurrence `contracted`. -/
def ContractedStep (data : GluingDatum target degree) (contracted : target.edges)
    (x y : data.SourceVertex) : Prop :=
  ∃ e : data.SourceEdge, e.1.1 = contracted ∧
    (data.sourceEnds e).1 = x ∧ (data.sourceEnds e).2 = y

/-- Joined by a walk in the quotient source all of whose occurrences lie over
the contracted target occurrence.  This is the fibre relation of
`GluingContraction.sourceVertexMap`. -/
def ReachThroughContracted (data : GluingDatum target degree)
    (contracted : target.edges) (x y : data.SourceVertex) : Prop :=
  Relation.EqvGen (ContractedStep data contracted) x y

theorem reachThroughContracted_equivalence (data : GluingDatum target degree)
    (contracted : target.edges) :
    Equivalence (ReachThroughContracted data contracted) :=
  Relation.EqvGen.is_equivalence _

theorem ReachThroughContracted.refl (data : GluingDatum target degree)
    (contracted : target.edges) (x : data.SourceVertex) :
    ReachThroughContracted data contracted x x :=
  Relation.EqvGen.refl x

theorem ReachThroughContracted.symm {data : GluingDatum target degree}
    {contracted : target.edges} {x y : data.SourceVertex}
    (h : ReachThroughContracted data contracted x y) :
    ReachThroughContracted data contracted y x :=
  Relation.EqvGen.symm x y h

theorem ReachThroughContracted.trans {data : GluingDatum target degree}
    {contracted : target.edges} {x y z : data.SourceVertex}
    (hxy : ReachThroughContracted data contracted x y)
    (hyz : ReachThroughContracted data contracted y z) :
    ReachThroughContracted data contracted x z :=
  Relation.EqvGen.trans x y z hxy hyz

theorem ContractedStep.reach {data : GluingDatum target degree}
    {contracted : target.edges} {x y : data.SourceVertex}
    (h : ContractedStep data contracted x y) :
    ReachThroughContracted data contracted x y :=
  Relation.EqvGen.rel x y h

/-- A `ContractedStep` really is an edge of the quotient source graph, so
`ReachThroughContracted` really is "joined by a walk all of whose occurrences
lie over the contracted target occurrence". -/
theorem contractedStep_mem_sourceGraph_edges (data : GluingDatum target degree)
    {contracted : target.edges} {x y : data.SourceVertex}
    (h : ContractedStep data contracted x y) : (x, y) ∈ data.sourceGraph.edges := by
  obtain ⟨e, -, hFirst, hSecond⟩ := h
  show (x, y) ∈ (Finset.univ : Finset data.SourceEdge).val.map data.sourceEnds
  refine Multiset.mem_map.mpr ⟨e, Finset.mem_val.mpr (Finset.mem_univ e), ?_⟩
  rw [← hFirst, ← hSecond]

/-- The edge partition above a target occurrence refines the vertex partition
above its first endpoint, so passing to the edge-block representative does not
move the left source endpoint. -/
theorem sourceEndpoint_edgePartition_repr_left (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (s : Fin degree) :
    data.sourceEndpoint a ((data.edgePartition contracted).repr s)
      = data.sourceEndpoint a s := by
  have hA : (contracted : target.V × target.V).1 = a := by rw [hc]
  have hRefines := data.refines_left contracted
  rw [hA] at hRefines
  exact Subtype.ext (Prod.ext rfl
    (hRefines.rel ((data.edgePartition contracted).rel_repr_left s)))

/-- The right-endpoint form of `sourceEndpoint_edgePartition_repr_left`. -/
theorem sourceEndpoint_edgePartition_repr_right (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (s : Fin degree) :
    data.sourceEndpoint b ((data.edgePartition contracted).repr s)
      = data.sourceEndpoint b s := by
  have hB : (contracted : target.V × target.V).2 = b := by rw [hc]
  have hRefines := data.refines_right contracted
  rw [hB] at hRefines
  exact Subtype.ext (Prod.ext rfl
    (hRefines.rel ((data.edgePartition contracted).rel_repr_right s).symm))

/-- **The bridge.**  For *every* sheet the two endpoint copies above the
contracted target occurrence are joined by an actual source occurrence: the
occurrence through the edge-block representative of that sheet has exactly
those two endpoints, because the edge partition refines both endpoint vertex
partitions. -/
theorem reach_sourceEndpoint_left_right (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (s : Fin degree) :
    ReachThroughContracted data contracted
      (data.sourceEndpoint a s) (data.sourceEndpoint b s) := by
  have hA : (contracted : target.V × target.V).1 = a := by rw [hc]
  have hB : (contracted : target.V × target.V).2 = b := by rw [hc]
  refine ContractedStep.reach ⟨data.sourceEdge contracted s, rfl, ?_, ?_⟩
  · show data.sourceEndpoint (contracted : target.V × target.V).1
      ((data.edgePartition contracted).repr s) = _
    rw [hA, sourceEndpoint_edgePartition_repr_left data hc]
  · show data.sourceEndpoint (contracted : target.V × target.V).2
      ((data.edgePartition contracted).repr s) = _
    rw [hB, sourceEndpoint_edgePartition_repr_right data hc]

/-- Moving a source vertex above `a` or `b` to its copy above `a`. -/
theorem reach_sourceEndpoint_merge (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    {u : target.V} (hu : u = a ∨ u = b) (s : Fin degree) :
    ReachThroughContracted data contracted
      (data.sourceEndpoint u s) (data.sourceEndpoint a s) := by
  rcases hu with hu | hu
  · rw [hu]
    exact ReachThroughContracted.refl data contracted _
  · rw [hu]
    exact (reach_sourceEndpoint_left_right data hc s).symm

/-- **The substantive half of the fibre equation.**  Join-related sheets give
reachable source vertices.  This is `joinRel_map` applied to the equivalence
relation `ReachThroughContracted`, pulled back along `s ↦ sourceEndpoint a s`:
a left-step does not move that source vertex at all, and a right-step moves it
only after crossing the contracted occurrence and back. -/
theorem reach_of_joinRel (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    {s t : Fin degree}
    (h : SheetPartition.JoinRel (data.vertexPartition a) (data.vertexPartition b) s t) :
    ReachThroughContracted data contracted
      (data.sourceEndpoint a s) (data.sourceEndpoint a t) := by
  refine joinRel_map (reachThroughContracted_equivalence data contracted)
    (fun sheet ↦ data.sourceEndpoint a sheet) ?_ ?_ h
  · intro i j hij
    have hEq : data.sourceEndpoint a i = data.sourceEndpoint a j :=
      Subtype.ext (Prod.ext rfl hij)
    rw [hEq]
    exact ReachThroughContracted.refl data contracted _
  · intro i j hij
    have hEq : data.sourceEndpoint b i = data.sourceEndpoint b j :=
      Subtype.ext (Prod.ext rfl hij)
    refine (reach_sourceEndpoint_left_right data hc i).trans ?_
    rw [hEq]
    exact (reach_sourceEndpoint_left_right data hc j).symm

/-- The merge form of `reach_of_joinRel`: join-related sheets give reachable
source vertices above either endpoint of the contracted occurrence. -/
theorem reach_of_joinRel_merge (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    {u v : target.V} (hu : u = a ∨ u = b) (hv : v = a ∨ v = b) {s t : Fin degree}
    (h : SheetPartition.JoinRel (data.vertexPartition a) (data.vertexPartition b) s t) :
    ReachThroughContracted data contracted
      (data.sourceEndpoint u s) (data.sourceEndpoint v t) :=
  ((reach_sourceEndpoint_merge data hc hu s).trans (reach_of_joinRel data hc h)).trans
    (reach_sourceEndpoint_merge data hc hv t).symm

/-! ### Reading off the two components of the image -/

/-- Both endpoints of the contracted occurrence fold to the merged vertex. -/
theorem fold_eq_of_eq_or (hab : a ≠ b) {u : target.V} (hu : u = a ∨ u = b) :
    fold target hab u = ⟨a, hab⟩ := by
  rcases hu with hu | hu
  · rw [hu]; exact fold_a target hab
  · rw [hu]; exact fold_self target hab

/-- Above the merged vertex the contracted datum carries the join of the two
endpoint partitions. -/
theorem contractVertexPartition_fold_merge (data : GluingDatum target degree) (hab : a ≠ b)
    {u : target.V} (hu : u = a ∨ u = b) :
    contractVertexPartition data a b (fold target hab u)
      = SheetPartition.join (data.vertexPartition a) (data.vertexPartition b) := by
  rw [fold_eq_of_eq_or hab hu]
  exact contractVertexPartition_merge data a b hab

/-- Away from the merged vertex the contracted datum carries the old
partition. -/
theorem contractVertexPartition_fold_of_ne (data : GluingDatum target degree) (hab : a ≠ b)
    {u : target.V} (hua : u ≠ a) (hub : u ≠ b) :
    contractVertexPartition data a b (fold target hab u) = data.vertexPartition u := by
  rw [fold_of_ne target hab hub]
  exact contractVertexPartition_of_ne data a b (y := ⟨u, hub⟩) hua

/-- The two components of `sourceVertexMap x = sourceVertexMap y`. -/
theorem sourceVertexMap_eq_iff_parts (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1) (x y : data.SourceVertex) :
    sourceVertexMap data hc hab hOne x = sourceVertexMap data hc hab hOne y ↔
      (fold target hab x.1.1 = fold target hab y.1.1 ∧
        (contractVertexPartition data a b (fold target hab x.1.1)).repr x.1.2
          = (contractVertexPartition data a b (fold target hab y.1.1)).repr y.1.2) := by
  constructor
  · intro h
    exact ⟨congrArg
        (fun z : (contractDatum data hc hab hOne).SourceVertex ↦ z.1.1) h,
      congrArg (fun z : (contractDatum data hc hab hOne).SourceVertex ↦ z.1.2) h⟩
  · rintro ⟨hfold, hrepr⟩
    exact Subtype.ext (Prod.ext hfold hrepr)

/-- At the merge the fibre is a join class of sheets. -/
theorem reach_of_repr_eq_merge (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) {x y : data.SourceVertex}
    (hx : x.1.1 = a ∨ x.1.1 = b) (hy : y.1.1 = a ∨ y.1.1 = b)
    (hrepr : (contractVertexPartition data a b (fold target hab x.1.1)).repr x.1.2
      = (contractVertexPartition data a b (fold target hab y.1.1)).repr y.1.2) :
    ReachThroughContracted data contracted x y := by
  rw [contractVertexPartition_fold_merge data hab hx,
    contractVertexPartition_fold_merge data hab hy] at hrepr
  have hjoin : SheetPartition.JoinRel (data.vertexPartition a) (data.vertexPartition b)
      x.1.2 y.1.2 :=
    (SheetPartition.join_rel_iff (data.vertexPartition a) (data.vertexPartition b)
      x.1.2 y.1.2).mp hrepr
  have hreach := reach_of_joinRel_merge data hc hx hy hjoin
  rwa [sourceEndpoint_self, sourceEndpoint_self] at hreach

/-! ### The fibre equation -/

/-- **The fibre equation for the source vertex map.**  Two source vertices of a
gluing datum have the same image in the contracted datum exactly when they are
joined by a chain of source edge occurrences lying over the contracted target
occurrence.

The easy direction is an `EqvGen` induction whose base case is
`GluingContraction.sourceVertexMap_sourceEnds_eq_of_contracted`.  The
substantive direction is the generation property of the join
(`joinRel_map`) together with `reach_sourceEndpoint_left_right`. -/
theorem sourceVertexMap_eq_iff (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1) (x y : data.SourceVertex) :
    sourceVertexMap data hc hab hOne x = sourceVertexMap data hc hab hOne y ↔
      ReachThroughContracted data contracted x y := by
  constructor
  · intro h
    obtain ⟨hfold, hrepr⟩ := (sourceVertexMap_eq_iff_parts data hc hab hOne x y).mp h
    rcases (fold_eq_fold_iff target hab x.1.1 y.1.1).mp hfold with
      heq | ⟨hxA, hyB⟩ | ⟨hxB, hyA⟩
    · by_cases hmerge : x.1.1 = a ∨ x.1.1 = b
      · refine reach_of_repr_eq_merge data hc hab hmerge ?_ hrepr
        rw [← heq]
        exact hmerge
      · obtain ⟨hxa, hxb⟩ := not_or.mp hmerge
        have hya : y.1.1 ≠ a := by rw [← heq]; exact hxa
        have hyb : y.1.1 ≠ b := by rw [← heq]; exact hxb
        rw [contractVertexPartition_fold_of_ne data hab hxa hxb,
          contractVertexPartition_fold_of_ne data hab hya hyb, x.2, y.2] at hrepr
        have hxy : x = y := Subtype.ext (Prod.ext heq hrepr)
        rw [hxy]
        exact ReachThroughContracted.refl data contracted y
    · exact reach_of_repr_eq_merge data hc hab (Or.inl hxA) (Or.inr hyB) hrepr
    · exact reach_of_repr_eq_merge data hc hab (Or.inr hxB) (Or.inl hyA) hrepr
  · intro h
    induction h with
    | rel u v huv =>
        obtain ⟨e, he, hFirst, hSecond⟩ := huv
        rw [← hFirst, ← hSecond]
        exact sourceVertexMap_sourceEnds_eq_of_contracted data hc hab hOne e he
    | refl u => rfl
    | symm u v _ ih => exact ih.symm
    | trans u v w _ _ ihFirst ihSecond => exact ihFirst.trans ihSecond

/-- Away from the merged vertex `sourceVertexMap` is injective: the fibre
equation degenerates because no source occurrence over the contracted
occurrence touches a source vertex above another target vertex. -/
theorem sourceVertexMap_eq_iff_of_ne (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1) (x y : data.SourceVertex)
    (hxa : x.1.1 ≠ a) (hxb : x.1.1 ≠ b) :
    sourceVertexMap data hc hab hOne x = sourceVertexMap data hc hab hOne y ↔ x = y := by
  constructor
  · intro h
    obtain ⟨hfold, hrepr⟩ := (sourceVertexMap_eq_iff_parts data hc hab hOne x y).mp h
    have heq : x.1.1 = y.1.1 := by
      rcases (fold_eq_fold_iff target hab x.1.1 y.1.1).mp hfold with
        heq | ⟨hxA, -⟩ | ⟨hxB, -⟩
      · exact heq
      · exact absurd hxA hxa
      · exact absurd hxB hxb
    have hya : y.1.1 ≠ a := by rw [← heq]; exact hxa
    have hyb : y.1.1 ≠ b := by rw [← heq]; exact hxb
    rw [contractVertexPartition_fold_of_ne data hab hxa hxb,
      contractVertexPartition_fold_of_ne data hab hya hyb, x.2, y.2] at hrepr
    exact Subtype.ext (Prod.ext heq hrepr)
  · rintro rfl
    rfl

/-- At the merged vertex the fibre equation is exactly the join relation on
sheets. -/
theorem sourceVertexMap_eq_iff_joinRel (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1) (x y : data.SourceVertex)
    (hx : x.1.1 = a ∨ x.1.1 = b) (hy : y.1.1 = a ∨ y.1.1 = b) :
    sourceVertexMap data hc hab hOne x = sourceVertexMap data hc hab hOne y ↔
      SheetPartition.JoinRel (data.vertexPartition a) (data.vertexPartition b)
        x.1.2 y.1.2 := by
  rw [sourceVertexMap_eq_iff_parts data hc hab hOne x y,
    contractVertexPartition_fold_merge data hab hx,
    contractVertexPartition_fold_merge data hab hy]
  constructor
  · rintro ⟨-, hrepr⟩
    exact (SheetPartition.join_rel_iff (data.vertexPartition a) (data.vertexPartition b)
      x.1.2 y.1.2).mp hrepr
  · intro hjoin
    refine ⟨?_, (SheetPartition.join_rel_iff (data.vertexPartition a)
      (data.vertexPartition b) x.1.2 y.1.2).mpr hjoin⟩
    rw [fold_eq_of_eq_or hab hx, fold_eq_of_eq_or hab hy]

/-- The merge case of the fibre equation, read through the partition the
contracted datum actually carries above the merged vertex. -/
theorem sourceVertexMap_eq_iff_join_rel (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1) (x y : data.SourceVertex)
    (hx : x.1.1 = a ∨ x.1.1 = b) (hy : y.1.1 = a ∨ y.1.1 = b) :
    sourceVertexMap data hc hab hOne x = sourceVertexMap data hc hab hOne y ↔
      (SheetPartition.join (data.vertexPartition a) (data.vertexPartition b)).Rel
        x.1.2 y.1.2 :=
  (sourceVertexMap_eq_iff_joinRel data hc hab hOne x y hx hy).trans
    (SheetPartition.join_rel_iff (data.vertexPartition a) (data.vertexPartition b)
      x.1.2 y.1.2).symm

/-- The merge case of the fibre equation as an alternating chain of sheets:
two source vertices above the contracted occurrence have the same image
exactly when a finite alternating chain of `vertexPartition a`-steps and
`vertexPartition b`-steps joins their sheets. -/
theorem sourceVertexMap_eq_iff_altChain (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1) (x y : data.SourceVertex)
    (hx : x.1.1 = a ∨ x.1.1 = b) (hy : y.1.1 = a ∨ y.1.1 = b) :
    sourceVertexMap data hc hab hOne x = sourceVertexMap data hc hab hOne y ↔
      AltChain (data.vertexPartition a) (data.vertexPartition b) x.1.2 y.1.2 :=
  (sourceVertexMap_eq_iff_joinRel data hc hab hOne x y hx hy).trans
    (joinRel_iff_altChain (data.vertexPartition a) (data.vertexPartition b)
      x.1.2 y.1.2)

/-- The explicit case description of the fibre: away from the merge
`sourceVertexMap` is injective, and at the merge its fibres are the join
classes. -/
theorem sourceVertexMap_eq_iff_cases (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1) (x y : data.SourceVertex) :
    sourceVertexMap data hc hab hOne x = sourceVertexMap data hc hab hOne y ↔
      x = y ∨ ((x.1.1 = a ∨ x.1.1 = b) ∧ (y.1.1 = a ∨ y.1.1 = b) ∧
        SheetPartition.JoinRel (data.vertexPartition a) (data.vertexPartition b)
          x.1.2 y.1.2) := by
  constructor
  · intro h
    by_cases hmerge : x.1.1 = a ∨ x.1.1 = b
    · obtain ⟨hfold, -⟩ := (sourceVertexMap_eq_iff_parts data hc hab hOne x y).mp h
      have hy : y.1.1 = a ∨ y.1.1 = b := by
        rcases (fold_eq_fold_iff target hab x.1.1 y.1.1).mp hfold with
          heq | ⟨-, hyB⟩ | ⟨-, hyA⟩
        · rw [← heq]; exact hmerge
        · exact Or.inr hyB
        · exact Or.inl hyA
      exact Or.inr ⟨hmerge, hy,
        (sourceVertexMap_eq_iff_joinRel data hc hab hOne x y hmerge hy).mp h⟩
    · obtain ⟨hxa, hxb⟩ := not_or.mp hmerge
      exact Or.inl ((sourceVertexMap_eq_iff_of_ne data hc hab hOne x y hxa hxb).mp h)
  · rintro (rfl | ⟨hx, hy, hjoin⟩)
    · rfl
    · exact (sourceVertexMap_eq_iff_joinRel data hc hab hOne x y hx hy).mpr hjoin

end Fibre

/-! ## (3) The surviving source edge occurrences -/

section SurvivingEdges

open GraphContraction GluingContraction

variable {target : CFGraph} {degree : ℕ} {a b : target.V}

/-- Every source edge occurrence of the contracted datum comes from a source
edge occurrence of the original datum lying over a surviving target
occurrence.  Together with `GluingContraction.sourceEdgeMap_injective` this
makes the surviving source occurrences match the source occurrences
downstairs exactly. -/
theorem sourceEdgeMap_surjective (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1) :
    Function.Surjective (sourceEdgeMap data hc hab hOne) := by
  intro f
  have hne : unfoldEdge hc hab hOne f.1.1 ≠ contracted :=
    unfoldEdge_ne_contracted hc hab hOne f.1.1
  refine ⟨⟨⟨(unfoldEdge hc hab hOne f.1.1, f.1.2), f.2⟩, hne⟩, ?_⟩
  exact Subtype.ext (Prod.ext (foldEdge_unfoldEdge hc hab hOne f.1.1 hne) rfl)

theorem sourceEdgeMap_bijective (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1) :
    Function.Bijective (sourceEdgeMap data hc hab hOne) :=
  ⟨sourceEdgeMap_injective data hc hab hOne, sourceEdgeMap_surjective data hc hab hOne⟩

/-- The source edge occurrences of the contracted datum are exactly the source
edge occurrences of the original datum away from the contracted target
occurrence. -/
noncomputable def sourceEdgeEquiv (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1) :
    {e : data.SourceEdge // e.1.1 ≠ contracted} ≃
      (contractDatum data hc hab hOne).SourceEdge :=
  Equiv.ofBijective _ (sourceEdgeMap_bijective data hc hab hOne)

@[simp] theorem sourceEdgeEquiv_apply (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1)
    (e : {e : data.SourceEdge // e.1.1 ≠ contracted}) :
    sourceEdgeEquiv data hc hab hOne e = sourceEdgeMap data hc hab hOne e := rfl

/-- The contraction preserves the index of a surviving source edge occurrence:
the occurrence keeps its own edge partition, so it keeps its block. -/
theorem sourceEdgeIndex_sourceEdgeMap (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1)
    (e : {e : data.SourceEdge // e.1.1 ≠ contracted}) :
    (contractDatum data hc hab hOne).sourceEdgeIndex (sourceEdgeMap data hc hab hOne e)
      = data.sourceEdgeIndex e.1 := by
  show ((contractDatum data hc hab hOne).edgePartition
      (foldEdge hc hab hOne ⟨e.1.1.1, e.2⟩)).blockCard e.1.1.2
    = (data.edgePartition e.1.1.1).blockCard e.1.1.2
  rw [contractDatum_edgePartition_foldEdge data hc hab hOne ⟨e.1.1.1, e.2⟩]

/-- The index form of `sourceEdgeIndex_sourceEdgeMap` read through
`sourceEdgeEquiv`. -/
theorem sourceEdgeIndex_sourceEdgeEquiv (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1)
    (e : {e : data.SourceEdge // e.1.1 ≠ contracted}) :
    (contractDatum data hc hab hOne).sourceEdgeIndex (sourceEdgeEquiv data hc hab hOne e)
      = data.sourceEdgeIndex e.1 :=
  sourceEdgeIndex_sourceEdgeMap data hc hab hOne e

/-- The inverse form: every source edge occurrence downstairs has the index of
the occurrence upstairs it comes from. -/
theorem sourceEdgeIndex_symm_sourceEdgeEquiv (data : GluingDatum target degree)
    {contracted : target.edges} (hc : (contracted : target.V × target.V) = (a, b))
    (hab : a ≠ b) (hOne : num_edges target a b = 1)
    (f : (contractDatum data hc hab hOne).SourceEdge) :
    data.sourceEdgeIndex ((sourceEdgeEquiv data hc hab hOne).symm f).1
      = (contractDatum data hc hab hOne).sourceEdgeIndex f := by
  rw [← sourceEdgeIndex_sourceEdgeEquiv data hc hab hOne
    ((sourceEdgeEquiv data hc hab hOne).symm f),
    Equiv.apply_symm_apply]

end SurvivingEdges

end ContractionFibre

end DraismaVargas.Infrastructure
