import Bananas.Jacobian.BananaJacobianReducedInjectivity
import Bananas.Jacobian.BananaJacobianDiagonal

/-!
# Integer-lattice reduction for banana coordinates

This file formalizes two elementary moves in the reduction algorithm used in
Proposition 2.14.  Subtracting the least coordinate times the diagonal makes
all coordinates nonnegative and leaves a zero coordinate.  Once coordinates
lie in their strand intervals, an out-of-order terminal/zero pair can be
swapped by a difference of two displayed strand-length relations.

The remaining existence step is the terminating iteration which alternates
diagonal normalization with reducing coordinates larger than their strand
length.  The lemmas here record the algebraic invariants needed by that
iteration without hiding them in the full kernel of the class map.
-/

namespace Bananas

open Utilities
open scoped BigOperators

/-- The relation lattice displayed in Proposition 2.14: it is generated by
the diagonal vector and the strand-length relations based at strand zero. -/
def bananaDisplayedRelations {g : ℕ} (B : Banana g) :
    AddSubgroup (Fin (g + 1) → ℤ) :=
  AddSubgroup.closure
    ({bananaDiagonalRelation (g := g)} ∪
      Set.range (bananaStrandLengthRelation B))

theorem bananaDiagonalRelation_mem_displayedRelations {g : ℕ}
    (B : Banana g) :
    bananaDiagonalRelation (g := g) ∈ bananaDisplayedRelations B := by
  apply AddSubgroup.subset_closure
  exact Set.mem_union_left _ (Set.mem_singleton _)

theorem bananaStrandLengthRelation_mem_displayedRelations {g : ℕ}
    (B : Banana g) (beta : Fin (g + 1)) :
    bananaStrandLengthRelation B beta ∈ bananaDisplayedRelations B := by
  apply AddSubgroup.subset_closure
  exact Set.mem_union_right _ ⟨beta, rfl⟩

/-- Every displayed relation is an actual relation of the graph-level class
map. -/
theorem bananaDisplayedRelations_le_coordinateRelations {g : ℕ}
    (B : Banana g) :
    bananaDisplayedRelations B ≤ bananaCoordinateRelations B := by
  rw [bananaDisplayedRelations, AddSubgroup.closure_le]
  intro relation hRelation
  rcases hRelation with hDiagonal | hLength
  · rw [Set.mem_singleton_iff.mp hDiagonal]
    exact bananaDiagonalRelation_mem_relations B
  · obtain ⟨beta, rfl⟩ := hLength
    exact bananaStrandLengthRelation_mem_relations B beta

/-- Subtract the coordinate at `pivot` from every coordinate. -/
def bananaDiagonalNormalize {g : ℕ} (a : Fin (g + 1) → ℤ)
    (pivot : Fin (g + 1)) : Fin (g + 1) → ℤ :=
  a - a pivot • bananaDiagonalRelation

@[simp] theorem bananaDiagonalNormalize_apply {g : ℕ}
    (a : Fin (g + 1) → ℤ) (pivot alpha : Fin (g + 1)) :
    bananaDiagonalNormalize a pivot alpha = a alpha - a pivot := by
  simp [bananaDiagonalNormalize, bananaDiagonalRelation]

@[simp] theorem bananaDiagonalNormalize_pivot {g : ℕ}
    (a : Fin (g + 1) → ℤ) (pivot : Fin (g + 1)) :
    bananaDiagonalNormalize a pivot pivot = 0 := by
  simp

/-- Diagonal normalization changes a vector by an explicit multiple of the
paper's diagonal generator. -/
theorem sub_bananaDiagonalNormalize {g : ℕ}
    (a : Fin (g + 1) → ℤ) (pivot : Fin (g + 1)) :
    a - bananaDiagonalNormalize a pivot =
      a pivot • bananaDiagonalRelation := by
  unfold bananaDiagonalNormalize
  abel

/-- Hence diagonal normalization preserves the presented divisor class. -/
theorem sub_bananaDiagonalNormalize_mem_relations {g : ℕ} (B : Banana g)
    (a : Fin (g + 1) → ℤ) (pivot : Fin (g + 1)) :
    a - bananaDiagonalNormalize a pivot ∈ bananaCoordinateRelations B := by
  rw [sub_bananaDiagonalNormalize]
  exact (bananaCoordinateRelations B).zsmul_mem
    (bananaDiagonalRelation_mem_relations B) (a pivot)

theorem sub_bananaDiagonalNormalize_mem_displayedRelations {g : ℕ}
    (B : Banana g) (a : Fin (g + 1) → ℤ) (pivot : Fin (g + 1)) :
    a - bananaDiagonalNormalize a pivot ∈ bananaDisplayedRelations B := by
  rw [sub_bananaDiagonalNormalize]
  exact (bananaDisplayedRelations B).zsmul_mem
    (bananaDiagonalRelation_mem_displayedRelations B) (a pivot)

/-- Every integer coordinate vector can be made nonnegative with a zero
coordinate using only the diagonal relation.  This is the first normalization
step in the paper's reduction algorithm. -/
theorem exists_nonnegative_zero_diagonalNormalize {g : ℕ} (B : Banana g)
    (a : Fin (g + 1) → ℤ) :
    ∃ b : Fin (g + 1) → ℤ,
      (∃ pivot, b pivot = 0) ∧
      (∀ alpha, 0 ≤ b alpha) ∧
      a - b ∈ bananaCoordinateRelations B := by
  classical
  obtain ⟨pivot, _hpivotMem, hMinimal⟩ :=
    Finset.exists_min_image (Finset.univ : Finset (Fin (g + 1))) a
      Finset.univ_nonempty
  refine ⟨bananaDiagonalNormalize a pivot, ⟨pivot,
    bananaDiagonalNormalize_pivot a pivot⟩, ?_,
    sub_bananaDiagonalNormalize_mem_relations B a pivot⟩
  intro alpha
  rw [bananaDiagonalNormalize_apply]
  exact sub_nonneg.mpr
    (hMinimal alpha (Finset.mem_univ alpha))

/-- The same first normalization step, now stated in the exact displayed
relation lattice rather than the full kernel. -/
theorem exists_nonnegative_zero_mod_displayedRelations {g : ℕ}
    (B : Banana g) (a : Fin (g + 1) → ℤ) :
    ∃ b : Fin (g + 1) → ℤ,
      (∃ pivot, b pivot = 0) ∧
      (∀ alpha, 0 ≤ b alpha) ∧
      a - b ∈ bananaDisplayedRelations B := by
  classical
  obtain ⟨pivot, _hpivotMem, hMinimal⟩ :=
    Finset.exists_min_image (Finset.univ : Finset (Fin (g + 1))) a
      Finset.univ_nonempty
  refine ⟨bananaDiagonalNormalize a pivot, ⟨pivot,
    bananaDiagonalNormalize_pivot a pivot⟩, ?_,
    sub_bananaDiagonalNormalize_mem_displayedRelations B a pivot⟩
  intro alpha
  rw [bananaDiagonalNormalize_apply]
  exact sub_nonneg.mpr (hMinimal alpha (Finset.mem_univ alpha))

/-- The displayed relation comparing arbitrary strands `alpha` and `beta`.
It is the difference of the paper's two generators based at strand zero. -/
def bananaPairwiseLengthRelation {g : ℕ} (B : Banana g)
    (alpha beta : Fin (g + 1)) : Fin (g + 1) → ℤ :=
  (B.length alpha : ℤ) • bananaCoordinateBasis alpha -
    (B.length beta : ℤ) • bananaCoordinateBasis beta

theorem bananaPairwiseLengthRelation_eq {g : ℕ} (B : Banana g)
    (alpha beta : Fin (g + 1)) :
    bananaPairwiseLengthRelation B alpha beta =
      bananaStrandLengthRelation B beta -
        bananaStrandLengthRelation B alpha := by
  unfold bananaPairwiseLengthRelation bananaStrandLengthRelation
  abel

theorem bananaPairwiseLengthRelation_mem_relations {g : ℕ} (B : Banana g)
    (alpha beta : Fin (g + 1)) :
    bananaPairwiseLengthRelation B alpha beta ∈
      bananaCoordinateRelations B := by
  rw [bananaPairwiseLengthRelation_eq]
  exact (bananaCoordinateRelations B).sub_mem
    (bananaStrandLengthRelation_mem_relations B beta)
    (bananaStrandLengthRelation_mem_relations B alpha)

theorem bananaPairwiseLengthRelation_mem_displayedRelations {g : ℕ}
    (B : Banana g) (alpha beta : Fin (g + 1)) :
    bananaPairwiseLengthRelation B alpha beta ∈
      bananaDisplayedRelations B := by
  rw [bananaPairwiseLengthRelation_eq]
  exact (bananaDisplayedRelations B).sub_mem
    (bananaStrandLengthRelation_mem_displayedRelations B beta)
    (bananaStrandLengthRelation_mem_displayedRelations B alpha)

/-- Exchange a zero at `beta` with a terminal coordinate at `alpha`.
Every output is a valid position because zero and the strand length are both
endpoints of `PathPosition`. -/
def bananaLeftJustifySwap {g : ℕ} (B : Banana g)
    (p : ∀ gamma : Fin (g + 1), B.PathPosition gamma)
    (alpha beta : Fin (g + 1)) :
    ∀ gamma : Fin (g + 1), B.PathPosition gamma :=
  fun gamma =>
    if gamma = alpha then ⟨0, by have := B.length_pos gamma; omega⟩
    else if gamma = beta then ⟨B.length gamma, by omega⟩
    else p gamma

@[simp] theorem bananaLeftJustifySwap_at_full {g : ℕ} (B : Banana g)
    (p : ∀ gamma : Fin (g + 1), B.PathPosition gamma)
    (alpha beta : Fin (g + 1)) :
    (bananaLeftJustifySwap B p alpha beta alpha).val = 0 := by
  simp [bananaLeftJustifySwap]

@[simp] theorem bananaLeftJustifySwap_at_zero {g : ℕ} (B : Banana g)
    (p : ∀ gamma : Fin (g + 1), B.PathPosition gamma)
    (alpha beta : Fin (g + 1)) (h : beta ≠ alpha) :
    (bananaLeftJustifySwap B p alpha beta beta).val = B.length beta := by
  simp [bananaLeftJustifySwap, h]

theorem bananaLeftJustifySwap_at_other {g : ℕ} (B : Banana g)
    (p : ∀ gamma : Fin (g + 1), B.PathPosition gamma)
    (alpha beta gamma : Fin (g + 1)) (hAlpha : gamma ≠ alpha)
    (hBeta : gamma ≠ beta) :
    bananaLeftJustifySwap B p alpha beta gamma = p gamma := by
  simp [bananaLeftJustifySwap, hAlpha, hBeta]

/-- A left-justification swap differs from the original coordinate vector by
exactly one pairwise length relation. -/
theorem positionCoordinates_sub_leftJustifySwap {g : ℕ} (B : Banana g)
    (p : ∀ gamma : Fin (g + 1), B.PathPosition gamma)
    (alpha beta : Fin (g + 1))
    (hFull : (p alpha).val = B.length alpha)
    (hZero : (p beta).val = 0) :
    bananaPositionCoordinates B p -
        bananaPositionCoordinates B (bananaLeftJustifySwap B p alpha beta) =
      bananaPairwiseLengthRelation B alpha beta := by
  have hNe : alpha ≠ beta := by
    intro h
    subst beta
    have := B.length_pos alpha
    omega
  funext gamma
  by_cases hGammaAlpha : gamma = alpha
  · subst gamma
    simp [bananaPositionCoordinates, bananaLeftJustifySwap,
      bananaPairwiseLengthRelation, bananaCoordinateBasis, hFull, hNe]
  · by_cases hGammaBeta : gamma = beta
    · subst gamma
      simp [bananaPositionCoordinates, bananaLeftJustifySwap,
        bananaPairwiseLengthRelation, bananaCoordinateBasis, hZero, hNe.symm]
    · simp [bananaPositionCoordinates, bananaLeftJustifySwap,
        bananaPairwiseLengthRelation, bananaCoordinateBasis,
        hGammaAlpha, hGammaBeta]

/-- The local ``move a terminal coordinate left and a zero right'' operation
used in the paper preserves the presented class and retains a zero
coordinate.  The order hypothesis identifies precisely an out-of-order pair;
it is not needed for the lattice identity itself. -/
theorem leftJustifySwap_normalization_step {g : ℕ} (B : Banana g)
    (p : ∀ gamma : Fin (g + 1), B.PathPosition gamma)
    (alpha beta : Fin (g + 1)) (_hOrder : beta < alpha)
    (hFull : (p alpha).val = B.length alpha)
    (hZero : (p beta).val = 0) :
    (∃ gamma, (bananaLeftJustifySwap B p alpha beta gamma).val = 0) ∧
      bananaPositionCoordinates B p -
          bananaPositionCoordinates B (bananaLeftJustifySwap B p alpha beta) ∈
        bananaCoordinateRelations B := by
  refine ⟨⟨alpha, bananaLeftJustifySwap_at_full B p alpha beta⟩, ?_⟩
  rw [positionCoordinates_sub_leftJustifySwap B p alpha beta hFull hZero]
  exact bananaPairwiseLengthRelation_mem_relations B alpha beta

/-- The same left-justification move in the exact displayed lattice. -/
theorem leftJustifySwap_mod_displayedRelations {g : ℕ} (B : Banana g)
    (p : ∀ gamma : Fin (g + 1), B.PathPosition gamma)
    (alpha beta : Fin (g + 1))
    (hFull : (p alpha).val = B.length alpha)
    (hZero : (p beta).val = 0) :
    bananaPositionCoordinates B p -
        bananaPositionCoordinates B (bananaLeftJustifySwap B p alpha beta) ∈
      bananaDisplayedRelations B := by
  rw [positionCoordinates_sub_leftJustifySwap B p alpha beta hFull hZero]
  exact bananaPairwiseLengthRelation_mem_displayedRelations B alpha beta

/-- The ordering clause in `IsPaperReducedPositionCoordinates` says exactly
that no zero occurs to the left of a terminal coordinate. -/
theorem isPaperReduced_iff_no_leftJustify_pair {g : ℕ} (B : Banana g)
    (p : ∀ gamma : Fin (g + 1), B.PathPosition gamma) :
    IsPaperReducedPositionCoordinates B p ↔
      (∃ gamma, (p gamma).val = 0) ∧
        ¬ ∃ alpha beta, beta < alpha ∧
          (p alpha).val = B.length alpha ∧ (p beta).val = 0 := by
  constructor
  · intro hPaper
    refine ⟨hPaper.1, ?_⟩
    rintro ⟨alpha, beta, hBetaAlpha, hFull, hZero⟩
    exact (not_lt_of_ge (hPaper.2 alpha beta hFull hZero).le) hBetaAlpha
  · rintro ⟨hZeroExists, hNoPair⟩
    refine ⟨hZeroExists, ?_⟩
    intro alpha beta hFull hZero
    have hNe : alpha ≠ beta := by
      intro h
      subst beta
      have := B.length_pos alpha
      omega
    exact lt_of_not_ge fun hNot =>
      hNoPair ⟨alpha, beta, lt_of_le_of_ne hNot hNe.symm, hFull, hZero⟩

end Bananas
