import Utilities.Subdivision.ContractionForestCensusGeneral

/-!
# Spanning forests for the contraction census

`Utilities.Subdivision.ContractionForestCensusGeneral` supplies the
union-find census of an arbitrary `ExplicitPotential.Core n p`: `compFold`, its
reachability characterization `compFold_iff`, the graphic-matroid rank
inequality `card_le_card_image_compFold_add_card`, and `IsForest` as its
equality case.  What it does not supply is the *existence* of a maximal forest.

This file supplies it.  `exists_spanning_forest` produces a slot set `F` that is
a census forest and whose reachability relation is already the full one, so that
`F.card + (number of components) = n`.  When the core is connected -- one
component -- that reads `F.card = n - 1`: a spanning tree.

## The argument

Take `F` a forest of maximal cardinality; forests exist, since `∅` is one.  If
some pair of vertices is reachable through all slots but not through `F`, then
some *single* slot `e` has its two ends `F`-unreachable, because the
`F`-reachability relation is an equivalence and, if it contained every slot's
end pair, it would contain the reflexive-transitive closure of all of them.
Adjoining that slot keeps the forest property:

* `card_le_card_image_compFold_add_card` gives `n ≤ |image(compFold (insert e F))| + F.card + 1`;
* `card_image_compFold_insert_lt` gives `|image(compFold (insert e F))| < |image(compFold F)|`,
  because `compFold (insert e F)` is constant on `compFold F`-classes and glues
  the two distinct classes of `e`'s ends;
* `IsForest core F` reads `|image(compFold F)| + F.card = n`.

The three together force equality, hence `IsForest core (insert e F)`, which
contradicts maximality.  So the maximal forest already realizes full
reachability.

Nothing here is specific to any application: it is generic census theory.

## What is proved

* `isForest_empty` -- the empty slot set is a forest.
* `reachIn_mono` -- reachability is monotone in the slot set.
* `reachIn_of_forall_slot_reachIn` -- a relation containing every slot's end
  pair contains all reachability.
* `card_image_compFold_insert_lt` -- adjoining a slot whose ends are
  unreachable strictly drops the class count.
* `isForest_insert` -- and keeps the forest property.
* `exists_spanning_forest` -- the headline.
* `exists_spanning_forest_card` -- its numerical form,
  `F.card + |image (compFold core univ)| = n`.
* `exists_spanning_tree_card` -- the connected case, `F.card + 1 = n`.

## What is NOT proved

* Nothing here says the core is connected; `exists_spanning_tree_card` takes
  connectedness as the explicit hypothesis
  `(Finset.image (compFold core Finset.univ) Finset.univ).card = 1`, in the
  census's own language.  Translating `graph_connected` into that hypothesis is
  a separate statement and is not attempted here.
-/

namespace DraismaVargas.Infrastructure.CensusSpanningForest

open Utilities.Certificate.ContractionForestCensusGeneral
open Utilities.Certificate.ExplicitPotential (Core)

variable {n p : ℕ} (core : Core n p)

/-! ## 1.  Forests exist -/

/-- The additive reading of `IsForest`, which is the one every count below
uses. -/
theorem isForest_iff_add {F : Finset (Fin p)} :
    IsForest core F ↔
      (Finset.image (compFold core F) Finset.univ).card + F.card = n := by
  have hle := card_image_compFold_le core F
  have hge := card_le_card_image_compFold_add_card core F
  unfold IsForest
  omega

/-- The empty slot set is a census forest: it contracts nothing. -/
theorem isForest_empty : IsForest core (∅ : Finset (Fin p)) := by
  rw [isForest_iff_add]
  simp

/-! ## 2.  Reachability is monotone, and generated by the slots -/

theorem adjInList_mono {F G : Finset (Fin p)} (h : F ⊆ G) {u v : Fin n}
    (huv : AdjInList core (edgeList F) u v) :
    AdjInList core (edgeList G) u v := by
  obtain ⟨e, he, hends⟩ := huv
  exact ⟨e, (mem_edgeList G e).mpr (h ((mem_edgeList F e).mp he)), hends⟩

/-- Reachability only grows when the contracted slot set does. -/
theorem reachIn_mono {F G : Finset (Fin p)} (h : F ⊆ G) {x y : Fin n}
    (hxy : ReachIn core F x y) : ReachIn core G x y := by
  induction hxy with
  | refl => exact Relation.ReflTransGen.refl
  | tail _ hstep ih => exact ih.tail (adjInList_mono core h hstep)

/-- A relation that is an equivalence and contains every slot's pair of ends
contains all of reachability. -/
theorem reachIn_of_forall_slot_reachIn {F : Finset (Fin p)}
    (hslot : ∀ e : Fin p, ReachIn core F (core.tail e) (core.head e))
    {x y : Fin n} (hxy : ReachIn core Finset.univ x y) : ReachIn core F x y := by
  induction hxy with
  | refl => exact (reachIn_equivalence core F).refl x
  | @tail b c _ hstep ih =>
      obtain ⟨e, -, hends⟩ := hstep
      rcases hends with ⟨htail, hhead⟩ | ⟨hhead, htail⟩
      · exact (reachIn_equivalence core F).trans ih (htail ▸ hhead ▸ hslot e)
      · exact (reachIn_equivalence core F).trans ih
          (htail ▸ hhead ▸ (reachIn_equivalence core F).symm (hslot e))

/-! ## 3.  Adjoining a crossing slot -/

/-- `compFold` of a larger slot set is constant on the classes of a smaller
one. -/
theorem compFold_compFold_of_subset {F G : Finset (Fin p)} (h : F ⊆ G)
    (x : Fin n) :
    compFold core G (compFold core F x) = compFold core G x :=
  (compFold_iff core G _ _).mpr
    (reachIn_mono core h
      ((reachIn_equivalence core F).symm (reachIn_self_compFold core F x)))

/-- **The strict drop.**  Adjoining a slot whose two ends are not yet
`F`-reachable strictly reduces the number of classes: the two ends' classes are
distinct elements of the old image with the same new representative. -/
theorem card_image_compFold_insert_lt {F : Finset (Fin p)} {e : Fin p}
    (hne : ¬ ReachIn core F (core.tail e) (core.head e)) :
    (Finset.image (compFold core (insert e F)) Finset.univ).card
      < (Finset.image (compFold core F) Finset.univ).card := by
  classical
  set A : Finset (Fin n) := Finset.image (compFold core F) Finset.univ with hA
  set u : Fin n := compFold core F (core.tail e) with hu
  set v : Fin n := compFold core F (core.head e) with hv
  have hsub : F ⊆ insert e F := Finset.subset_insert e F
  have huv : u ≠ v := fun hEq ↦ hne ((compFold_iff core F _ _).mp hEq)
  have humem : u ∈ A := Finset.mem_image_of_mem _ (Finset.mem_univ _)
  have hvmem : v ∈ A.erase u := Finset.mem_erase.mpr
    ⟨fun hEq ↦ huv hEq.symm, Finset.mem_image_of_mem _ (Finset.mem_univ _)⟩
  -- the new fold agrees at `u` and `v`
  have hglue : compFold core (insert e F) u = compFold core (insert e F) v := by
    rw [hu, hv, compFold_compFold_of_subset core hsub,
      compFold_compFold_of_subset core hsub]
    exact compFold_tail_eq_head_of_mem core (Finset.mem_insert_self e F)
  -- the new image is the old image pushed forward
  have himage : Finset.image (compFold core (insert e F)) Finset.univ
      = A.image (compFold core (insert e F)) := by
    refine Finset.Subset.antisymm ?_ (Finset.image_subset_iff.mpr
      fun _ _ ↦ Finset.mem_image_of_mem _ (Finset.mem_univ _))
    intro z hz
    obtain ⟨x, -, rfl⟩ := Finset.mem_image.mp hz
    exact Finset.mem_image.mpr ⟨compFold core F x,
      Finset.mem_image_of_mem _ (Finset.mem_univ _),
      compFold_compFold_of_subset core hsub x⟩
  -- and `u` may be dropped, because `v` already carries its value
  have herase : A.image (compFold core (insert e F))
      = (A.erase u).image (compFold core (insert e F)) := by
    refine Finset.Subset.antisymm ?_
      (Finset.image_subset_image (Finset.erase_subset u A))
    intro z hz
    obtain ⟨w, hw, rfl⟩ := Finset.mem_image.mp hz
    by_cases hwu : w = u
    · exact Finset.mem_image.mpr ⟨v, hvmem, by rw [← hglue, hwu]⟩
    · exact Finset.mem_image.mpr ⟨w, Finset.mem_erase.mpr ⟨hwu, hw⟩, rfl⟩
  have hcard : (A.erase u).card + 1 = A.card := Finset.card_erase_add_one humem
  calc (Finset.image (compFold core (insert e F)) Finset.univ).card
      = ((A.erase u).image (compFold core (insert e F))).card := by
        rw [himage, herase]
    _ ≤ (A.erase u).card := Finset.card_image_le
    _ < A.card := by omega

/-- Adjoining a crossing slot keeps the forest property. -/
theorem isForest_insert {F : Finset (Fin p)} {e : Fin p} (hF : IsForest core F)
    (hne : ¬ ReachIn core F (core.tail e) (core.head e)) :
    IsForest core (insert e F) := by
  classical
  have hmem : e ∉ F := fun he ↦ hne
    ((compFold_iff core F _ _).mp (compFold_tail_eq_head_of_mem core he))
  have hcardins : (insert e F).card = F.card + 1 := Finset.card_insert_of_notMem hmem
  have hlt := card_image_compFold_insert_lt core hne
  have hge := card_le_card_image_compFold_add_card core (insert e F)
  rw [isForest_iff_add] at hF ⊢
  omega

/-! ## 4.  The spanning forest -/

/-- **Every core has a spanning forest.**  A census forest whose reachability
relation is already the full one. -/
theorem exists_spanning_forest :
    ∃ F : Finset (Fin p), IsForest core F ∧
      ∀ x y : Fin n, ReachIn core Finset.univ x y → ReachIn core F x y := by
  classical
  obtain ⟨F, hFmem, hFmax⟩ :=
    Finset.exists_max_image
      ((Finset.univ : Finset (Finset (Fin p))).filter fun G ↦ IsForest core G)
      Finset.card ⟨∅, Finset.mem_filter.mpr ⟨Finset.mem_univ _, isForest_empty core⟩⟩
  have hF : IsForest core F := (Finset.mem_filter.mp hFmem).2
  refine ⟨F, hF, ?_⟩
  intro x y hxy
  by_contra hnot
  have hslot : ¬ ∀ e : Fin p, ReachIn core F (core.tail e) (core.head e) := by
    intro hall
    exact hnot (reachIn_of_forall_slot_reachIn core hall hxy)
  obtain ⟨e, hne⟩ := not_forall.mp hslot
  have hmem : e ∉ F := fun he ↦ hne
    ((compFold_iff core F _ _).mp (compFold_tail_eq_head_of_mem core he))
  have hins : IsForest core (insert e F) := isForest_insert core hF hne
  have hle := hFmax (insert e F)
    (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hins⟩)
  rw [Finset.card_insert_of_notMem hmem] at hle
  omega

/-- The spanning forest's cardinality: slots plus classes make up the vertices,
with the classes counted by the *full* fold. -/
theorem exists_spanning_forest_card :
    ∃ F : Finset (Fin p), IsForest core F ∧
      F.card + (Finset.image (compFold core Finset.univ) Finset.univ).card = n := by
  classical
  obtain ⟨F, hF, hspan⟩ := exists_spanning_forest core
  refine ⟨F, hF, ?_⟩
  have hiff : ∀ x y : Fin n,
      compFold core F x = compFold core F y ↔
        compFold core Finset.univ x = compFold core Finset.univ y := by
    intro x y
    rw [compFold_iff, compFold_iff]
    exact ⟨reachIn_mono core (Finset.subset_univ F), hspan x y⟩
  have hle₁ := card_image_le_of_rep_iff (compFold_idem core F) hiff
  have hle₂ := card_image_le_of_rep_iff (compFold_idem core Finset.univ)
    (fun x y ↦ (hiff x y).symm)
  rw [isForest_iff_add] at hF
  omega

/-- **The connected case: a spanning tree.**  Stated with connectedness in the
census's own language, one class for the full fold. -/
theorem exists_spanning_tree_card
    (hConnected :
      (Finset.image (compFold core Finset.univ) Finset.univ).card = 1) :
    ∃ F : Finset (Fin p), IsForest core F ∧ F.card + 1 = n := by
  obtain ⟨F, hF, hcard⟩ := exists_spanning_forest_card core
  exact ⟨F, hF, by omega⟩

end DraismaVargas.Infrastructure.CensusSpanningForest
