import Utilities.Subdivision.ContractionForestCensusGeneral
import Utilities.Subdivision.DegenerateSeparator

/-!
# Canonical closed-face subdivision data

This is the row-independent adapter from a nonnegative slot-length vector and
its forest census to a `DegSpec`.  The representative map is the canonical
union-find map generated by the zero slots.
-/

namespace Utilities.Certificate.ClosedFaceCensus

open Utilities
open Utilities.Certificate
open Utilities.Certificate.ContractionForestCensusGeneral

variable {n p : ℕ}

/-- The vanishing slots of a nonnegative length assignment. -/
def zeroSet (length : Fin p → ℕ) : Finset (Fin p) :=
  Finset.univ.filter (fun edge => length edge = 0)

@[simp] theorem mem_zeroSet (length : Fin p → ℕ) (edge : Fin p) :
    edge ∈ zeroSet length ↔ length edge = 0 := by
  simp [zeroSet]

/-- The canonical degenerate subdivision attached to a forest face. -/
def censusSpec (core : ExplicitPotential.Core n p) (hn : 0 < n)
    (length : Fin p → ℕ)
    (hForest : IsForest core (zeroSet length))
    (hNotLoopy : ¬ IsLoopy core (zeroSet length)) :
    Utilities.Certificate.DegenerateSpec.DegSpec n p where
  core := core
  length := length
  core_nonempty := hn
  rep := compFold core (zeroSet length)
  rep_idem := compFold_idem core (zeroSet length)
  rep_zero := fun edge hzero =>
    compFold_tail_eq_head_of_mem core ((mem_zeroSet length edge).2 hzero)
  rep_loopless := fun edge hpos =>
    rep_loopless_of_not_isLoopy core hNotLoopy edge (by
      rw [mem_zeroSet]
      omega)
  forest := forest_image_add_card_eq core hForest

/-- Extensionality for degenerate specifications; all other fields are proofs. -/
theorem degSpec_ext
    {d d' : Utilities.Certificate.DegenerateSpec.DegSpec n p}
    (hCore : d.core = d'.core) (hLength : d.length = d'.length)
    (hRep : d.rep = d'.rep) : d = d' := by
  obtain ⟨core, length, _, rep, _, _, _, _⟩ := d
  obtain ⟨core', length', _, rep', _, _, _, _⟩ := d'
  simp only at hCore hLength hRep
  subst hCore
  subst hLength
  subst hRep
  rfl

end Utilities.Certificate.ClosedFaceCensus
