import Utilities.Subdivision.CoreExpansion
import Utilities.Subdivision.ContractionForestCensusGeneral

/-!
# Closed faces carried by a core expansion

The positive expansion certificate in `CoreExpansion` assigns length one to
slots internal to a fibre and then contracts them topologically.  A closed
row construction instead assigns those slots length zero.  The bridge between
the two descriptions is the following fibre theorem: the equivalence relation
generated by the slots tagged `contracted` is exactly equality under the
expansion's fibre map.

This statement is genus-independent and contains no finite atlas data.  It is
the combinatorial heart of lowering a closed construction on a trivalent
expansion back to the smaller core.
-/

set_option autoImplicit false

namespace Utilities.Subdivision.CoreExpansion

open Utilities
open Utilities.Certificate
open Utilities.Certificate.ExplicitPotential
open Utilities.Certificate.ContractionForestCensusGeneral

namespace ExpansionData

variable {n p N Q : ℕ} (D : ExpansionData n p N Q) (C : Core n p)

/-- Slots which disappear in the closed face associated to an expansion. -/
def contractedSlots : Finset (Fin Q) :=
  Finset.univ.filter fun e => D.kind e = .contracted

@[simp] theorem mem_contractedSlots (e : Fin Q) :
    e ∈ D.contractedSlots ↔ D.kind e = .contracted := by
  simp [contractedSlots]

variable {D C}

/-- Direct adjacency through a contracted slot stays in one fibre. -/
theorem fib_eq_of_adjInContracted
    (hCond : D.Conditions C) {a b : Fin N}
    (hab : AdjInList D.bigCore (edgeList D.contractedSlots) a b) :
    D.fib a = D.fib b := by
  obtain ⟨e, he, hab⟩ := hab
  have hk : D.kind e = .contracted :=
    (D.mem_contractedSlots e).mp ((mem_edgeList D.contractedSlots e).mp he)
  have hFib := (compatible_of_conditions hCond e).1 hk
  rcases hab with ⟨hTail, hHead⟩ | ⟨hHead, hTail⟩
  · simpa [hTail, hHead] using hFib
  · simpa [hTail, hHead] using hFib.symm

/-- A chain of contracted slots stays in one fibre. -/
theorem fib_eq_of_reachInContracted
    (hCond : D.Conditions C) {a b : Fin N}
    (hab : ReachIn D.bigCore D.contractedSlots a b) :
    D.fib a = D.fib b := by
  induction hab with
  | refl => rfl
  | tail _ hlast ih =>
      exact ih.trans (fib_eq_of_adjInContracted hCond hlast)

/-- Conversely, the finite-cut fibre condition in `ExpansionData.Conditions`
forces every two vertices of one fibre to be joined by contracted slots. -/
theorem reachInContracted_of_fib_eq
    (hCond : D.Conditions C) {a b : Fin N} (hab : D.fib a = D.fib b) :
    ReachIn D.bigCore D.contractedSlots a b := by
  classical
  let T : Finset (Fin N) :=
    Finset.univ.filter fun v => ReachIn D.bigCore D.contractedSlots a v
  have haT : a ∈ T := by
    exact Finset.mem_filter.mpr ⟨Finset.mem_univ _, Relation.ReflTransGen.refl⟩
  by_contra hReach
  have hbT : b ∉ T := by
    simpa [T] using hReach
  obtain ⟨e, hk, _hOwner, hCross⟩ :=
    fibre_of_conditions hCond (D.fib a) T
      ⟨a, haT, rfl⟩ ⟨b, hbT, hab.symm⟩
  have he : e ∈ D.contractedSlots := (D.mem_contractedSlots e).mpr hk
  have hAdj : AdjInList D.bigCore (edgeList D.contractedSlots)
      (D.bigCore.tail e) (D.bigCore.head e) :=
    ⟨e, (mem_edgeList D.contractedSlots e).mpr he, Or.inl ⟨rfl, rfl⟩⟩
  have hStep : ReachIn D.bigCore D.contractedSlots
      (D.bigCore.tail e) (D.bigCore.head e) :=
    Relation.ReflTransGen.single hAdj
  rcases hCross with ⟨hTailIn, hHeadOut⟩ | ⟨hHeadIn, hTailOut⟩
  · have hToTail : ReachIn D.bigCore D.contractedSlots a (D.bigCore.tail e) :=
      (Finset.mem_filter.mp hTailIn).2
    exact hHeadOut (Finset.mem_filter.mpr
      ⟨Finset.mem_univ _, hToTail.trans hStep⟩)
  · have hToHead : ReachIn D.bigCore D.contractedSlots a (D.bigCore.head e) :=
      (Finset.mem_filter.mp hHeadIn).2
    have hBack : ReachIn D.bigCore D.contractedSlots
        (D.bigCore.head e) (D.bigCore.tail e) :=
      reachInList_symmetric D.bigCore (edgeList D.contractedSlots) hStep
    exact hTailOut (Finset.mem_filter.mpr
      ⟨Finset.mem_univ _, hToHead.trans hBack⟩)

/-- **Expansion fibre theorem.**  The union-find quotient generated by the
contracted expansion slots has exactly the fibres prescribed by `D.fib`. -/
theorem compFold_eq_iff_fib_eq
    (hCond : D.Conditions C) (a b : Fin N) :
    compFold D.bigCore D.contractedSlots a =
        compFold D.bigCore D.contractedSlots b ↔
      D.fib a = D.fib b := by
  rw [compFold_iff]
  exact ⟨fib_eq_of_reachInContracted hCond,
    reachInContracted_of_fib_eq hCond⟩

end ExpansionData

end Utilities.Subdivision.CoreExpansion
