import Utilities.Subdivision.SubdivisionIso

/-!
# Subdivision specifications on the CLOSED length orthant

`SubdivisionGraph.Spec` carries `length_pos : ∀ edge, 0 < length edge`, so a
certificate written against it is valid only on the *interior* of the length
orthant.  Every equal-genus contraction of the core therefore has to be
treated as a separate certificate target.  This module introduces the
degenerate variant, whose lengths may vanish, so that a contraction target is
a **face** of a cone a certificate already covers rather than a new case.

## The one thing that is not just "drop the field"

Dropping `length_pos` from `Spec` and keeping `Spec.graph` verbatim gives the
**wrong** graph.  A slot of length `0` emits no unit steps and no interior
vertices, so `Spec.graph` would *delete* it and leave its two endpoints as
distinct vertices.  Metric degeneration **contracts**: a segment of length
zero identifies its endpoints.  Deletion drops the genus by one per deleted
slot; contraction preserves it.  A degenerate spec must therefore carry the
vertex identification explicitly, as an idempotent representative map `rep`.

## Why no vertex weights are needed

Write `z` for the number of zero slots.  The graph below has
`∑ length` edges and `#(image rep) + ∑ (length - 1)` vertices, so

    genus = #positiveSlots - #(image rep) + 1 .

Genus equals the core's `p - n + 1` exactly when `#(image rep) + z = n`,
which is the field `forest` below.  For the canonical representative map
generated by the zero slots, this is precisely the graphic-matroid statement
that the zero set is a forest.  For an arbitrary bare `DegSpec`, however, the
cardinality equation alone does not prevent an unrelated extra
identification from balancing a redundant zero edge.  Consumer interfaces
that mean an honest contraction must therefore require exact generation by
the zero slots or use a canonical union-find representative.  Genus
preservation itself still follows from the displayed cardinality equation,
so no vertex weight is needed.

## What is *not* defined here

No rank, no `winnable`, no Riemann--Roch on a degenerate object.  A `DegSpec`
has a `graph : CFGraph` and nothing else; all semantics remain on `CFGraph`.
The two bridges are

* `Contraction`, the face-equals-contraction-target correspondence: a
  `DegSpec` whose zero set is a forest is `LaplacianEquiv` to the strictly
  positive `Spec` on the contracted core; and
* `toSpec`, the translation lemma: at a strictly positive length vector a
  `DegSpec` *is* an ordinary `Spec`, with `rep = id`.
-/

namespace Utilities.Certificate.DegenerateSpec
open Utilities.Certificate

open Utilities

open Finset ExplicitPotential SubdivisionGraph

/-- Subdivision data on the **closed** length orthant.

`length` may vanish.  `rep` names the vertex identification produced by
collapsing the zero slots; `forest` is the genus-preserving cardinality
condition.  Honest closed-face authoring interfaces use the canonical
union-find representative rather than treating an arbitrary `rep` as a
contraction. -/
structure DegSpec (n p : ℕ) where
  core : ExplicitPotential.Core n p
  length : Fin p → ℕ
  core_nonempty : 0 < n
  /-- Canonical representative of a core vertex after collapsing zero slots. -/
  rep : Fin n → Fin n
  rep_idem : ∀ v : Fin n, rep (rep v) = rep v
  /-- A vanishing slot identifies its two endpoints: this is contraction, not
  deletion. -/
  rep_zero : ∀ e : Fin p, length e = 0 → rep (core.tail e) = rep (core.head e)
  /-- A surviving slot is not a loop after the contraction. -/
  rep_loopless : ∀ e : Fin p, 0 < length e → rep (core.tail e) ≠ rep (core.head e)
  /-- The Euler-characteristic equation for genus preservation.  When `rep`
  is the canonical quotient generated by the zero slots, this is exactly the
  assertion that those slots form a forest; see `genus_graph`. -/
  forest : (Finset.univ.image rep).card
      + (Finset.univ.filter (fun e : Fin p => length e = 0)).card = n

namespace DegSpec

variable {n p : ℕ} (d : DegSpec n p)

/-! ## The vertex and step types -/

/-- Surviving core vertices: the `rep`-fixed points, i.e. one per class. -/
abbrev Class := {v : Fin n // d.rep v = v}

/-- Interior vertices of the surviving slots.  A slot of length `0` or `1`
contributes none, because `Fin (0 - 1) = Fin (1 - 1) = Fin 0`. -/
abbrev Interior := Σ e : Fin p, Fin (d.length e - 1)

abbrev Vertex := d.Class ⊕ d.Interior

/-- A unit step exists only on a slot of positive length. -/
abbrev Step := Σ e : Fin p, Fin (d.length e)

/-- The class of a core vertex, as a vertex of the degenerate subdivision. -/
def coreVertex (v : Fin n) : d.Vertex := Sum.inl ⟨d.rep v, d.rep_idem v⟩

def interiorVertex (e : Fin p) (o : Fin (d.length e - 1)) : d.Vertex :=
  Sum.inr ⟨e, o⟩

theorem coreVertex_eq_iff (u v : Fin n) :
    d.coreVertex u = d.coreVertex v ↔ d.rep u = d.rep v := by
  unfold coreVertex
  constructor
  · intro h; exact congrArg Subtype.val (Sum.inl.inj h)
  · intro h; rw [Sum.inl.injEq]; exact Subtype.ext h

def stepLeft (e : Fin p) (o : Fin (d.length e)) : d.Vertex :=
  if hzero : o.val = 0 then d.coreVertex (d.core.tail e)
  else d.interiorVertex e ⟨o.val - 1, by have := o.isLt; omega⟩

def stepRight (e : Fin p) (o : Fin (d.length e)) : d.Vertex :=
  if hlast : o.val + 1 = d.length e then d.coreVertex (d.core.head e)
  else d.interiorVertex e ⟨o.val, by have := o.isLt; omega⟩

def unitEdge (s : d.Step) : d.Vertex × d.Vertex :=
  (d.stepLeft s.1 s.2, d.stepRight s.1 s.2)

theorem stepLeft_ne_stepRight (e : Fin p) (o : Fin (d.length e)) :
    d.stepLeft e o ≠ d.stepRight e o := by
  have hpos : 0 < d.length e := lt_of_le_of_lt (Nat.zero_le _) o.isLt
  unfold stepLeft stepRight
  split_ifs with h0 h1
  · intro h
    exact d.rep_loopless e hpos (congrArg Subtype.val (Sum.inl.inj h))
  · simp [coreVertex, interiorVertex]
  · simp [coreVertex, interiorVertex]
  · intro h
    have hs : (⟨e, ⟨o.val - 1, by have := o.isLt; omega⟩⟩ : d.Interior)
        = ⟨e, ⟨o.val, by have := o.isLt; omega⟩⟩ := Sum.inr.inj h
    have : o.val - 1 = o.val :=
      congrArg (fun x : d.Interior => x.2.val) hs
    omega

/-- The degenerate subdivision graph.  Zero slots emit nothing; their
endpoints have already been identified by `rep`. -/
abbrev graph (d : DegSpec n p) : CFGraph where
  V := d.Vertex
  instNonempty := ⟨d.coreVertex ⟨0, d.core_nonempty⟩⟩
  edges := (Finset.univ : Finset d.Step).val.map d.unitEdge
  loopless := by
    intro v hmem
    simp only [Multiset.mem_map, Finset.mem_val, Finset.mem_univ, true_and]
      at hmem
    obtain ⟨s, hs⟩ := hmem
    rcases s with ⟨e, o⟩
    simp only [unitEdge, Prod.mk.injEq] at hs
    exact d.stepLeft_ne_stepRight e o (hs.1.trans hs.2.symm)

@[simp] theorem graph_edges :
    d.graph.edges = (Finset.univ : Finset d.Step).val.map d.unitEdge := rfl

/-! ## Path positions

The chip-position trichotomy.  On a `Spec` a certificate may get away with a
two-case split (`offset = 0` versus `offset > 0`, the latter always interior)
whenever the offset is *strictly* below the slot length — a bound that
usually comes from `length_pos`.  On the closed orthant the third case,
`offset = length`, is reachable and must be present. -/

abbrev PathPosition (e : Fin p) := Fin (d.length e + 1)

def pathVertex (e : Fin p) (k : d.PathPosition e) : d.Vertex :=
  if hzero : k.val = 0 then d.coreVertex (d.core.tail e)
  else if hlast : k.val = d.length e then d.coreVertex (d.core.head e)
  else d.interiorVertex e ⟨k.val - 1, by have := k.isLt; omega⟩

theorem pathVertex_zero (e : Fin p) :
    d.pathVertex e ⟨0, by omega⟩ = d.coreVertex (d.core.tail e) := dif_pos rfl

theorem pathVertex_length (e : Fin p) :
    d.pathVertex e ⟨d.length e, by omega⟩ = d.coreVertex (d.core.head e) := by
  unfold pathVertex
  by_cases h : d.length e = 0
  · rw [dif_pos (by simpa using h)]
    exact (d.coreVertex_eq_iff _ _).mpr (d.rep_zero e h)
  · rw [dif_neg (by simpa using h), dif_pos rfl]

theorem pathVertex_interior (e : Fin p) (k : d.PathPosition e)
    (h0 : k.val ≠ 0) (hL : k.val ≠ d.length e) :
    d.pathVertex e k = d.interiorVertex e ⟨k.val - 1, by have := k.isLt; omega⟩ := by
  unfold pathVertex
  rw [dif_neg h0, dif_neg hL]

theorem pathVertex_eq_of_val_eq (e : Fin p) {j k : d.PathPosition e}
    (h : j.val = k.val) : d.pathVertex e j = d.pathVertex e k :=
  congrArg (d.pathVertex e) (Fin.ext h)

/-- A path position clamped into range.  On a slot the certificate actually
uses this is the identity; it exists so that a *generic* statement can name a
position on every slot without carrying a bound for the slots it ignores. -/
def clampPos (d : DegSpec n p) (e : Fin p) (k : ℕ) : d.PathPosition e :=
  ⟨min k (d.length e), by omega⟩

@[simp] theorem clampPos_val_of_le {e : Fin p} {k : ℕ} (hk : k ≤ d.length e) :
    (d.clampPos e k).val = k := by
  simp only [clampPos]
  omega

/-- **The path vertex at a clamped position**, total in the natural number `k`.

This is the form a row proof should use throughout.  `pathVertex` is indexed by
`Fin (length e + 1)`, so naming a position costs a bound proof at every
occurrence; on the closed orthant those bounds are exactly the ones that stop
being free.  `pathAt` carries none: positions beyond the end of the slot are
clamped to the head, which is where a chip pushed off the end belongs.

It lives here rather than beside its first consumer because the two consumers
sit on independent branches of the tower: ramp scripts read chips off it, and
`Certificate/ScaleQReduced.lean` walks along it. -/
def pathAt (d : DegSpec n p) (e : Fin p) (k : ℕ) : d.Vertex :=
  d.pathVertex e (d.clampPos e k)

theorem pathAt_congr (e : Fin p) {j k : ℕ}
    (h : min j (d.length e) = min k (d.length e)) : d.pathAt e j = d.pathAt e k :=
  d.pathVertex_eq_of_val_eq e h

theorem pathAt_of_eq (e : Fin p) {j k : ℕ} (h : j = k) :
    d.pathAt e j = d.pathAt e k := by rw [h]

@[simp] theorem pathAt_zero (e : Fin p) :
    d.pathAt e 0 = d.coreVertex (d.core.tail e) := by
  unfold pathAt
  rw [d.pathVertex_eq_of_val_eq e (j := d.clampPos e 0) (k := ⟨0, by omega⟩)
    (by simp [clampPos]), d.pathVertex_zero]

theorem pathAt_length {e : Fin p} {k : ℕ} (hk : d.length e ≤ k) :
    d.pathAt e k = d.coreVertex (d.core.head e) := by
  unfold pathAt
  rw [d.pathVertex_eq_of_val_eq e (j := d.clampPos e k)
    (k := ⟨d.length e, by omega⟩) (by simp only [clampPos]; omega),
    d.pathVertex_length]

theorem pathAt_interior {e : Fin p} {k : ℕ} (h0 : k ≠ 0) (hk : k < d.length e) :
    d.pathAt e k = d.interiorVertex e ⟨k - 1, by omega⟩ := by
  unfold pathAt
  rw [d.pathVertex_interior e (d.clampPos e k)
      (by simp only [clampPos]; omega) (by simp only [clampPos]; omega)]
  exact congrArg (d.interiorVertex e)
    (Fin.ext (by show min k (d.length e) - 1 = k - 1; omega))

/-! ## Genus: the whole point of the `forest` field -/

/-- The `rep`-fixed points are exactly the image of `rep`. -/
theorem image_rep_eq_filter :
    (Finset.univ.image d.rep) = Finset.univ.filter (fun v : Fin n => d.rep v = v) := by
  ext v
  constructor
  · intro hv
    obtain ⟨u, -, hu⟩ := Finset.mem_image.mp hv
    exact Finset.mem_filter.mpr ⟨Finset.mem_univ _, by rw [← hu, d.rep_idem u]⟩
  · intro hv
    exact Finset.mem_image.mpr ⟨v, Finset.mem_univ v, (Finset.mem_filter.mp hv).2⟩

theorem card_class :
    Fintype.card d.Class = (Finset.univ.image d.rep).card := by
  rw [d.image_rep_eq_filter, Fintype.card_subtype]

@[simp] theorem card_edges :
    d.graph.edges.card = ∑ e : Fin p, d.length e := by
  simp [graph, Fintype.card_sigma]

@[simp] theorem card_vertices :
    Fintype.card d.graph.V
      = (Finset.univ.image d.rep).card + ∑ e : Fin p, (d.length e - 1) := by
  simp [graph, Vertex, Interior, Fintype.card_sigma, d.card_class]

/-- Splitting the edge count into interior vertices plus one per surviving
slot. -/
theorem sum_length_eq :
    (∑ e : Fin p, d.length e)
      = (∑ e : Fin p, (d.length e - 1))
        + (Finset.univ.filter (fun e : Fin p => 0 < d.length e)).card := by
  rw [Finset.card_filter, ← Finset.sum_add_distrib]
  exact Finset.sum_congr rfl fun e _ => by
    by_cases h : 0 < d.length e <;> simp [h] <;> omega

theorem card_pos_add_card_zero :
    (Finset.univ.filter (fun e : Fin p => 0 < d.length e)).card
      + (Finset.univ.filter (fun e : Fin p => d.length e = 0)).card = p := by
  have h : (Finset.univ.filter (fun e : Fin p => d.length e = 0))
      = (Finset.univ.filter (fun e : Fin p => ¬ (0 < d.length e))) := by
    apply Finset.filter_congr
    intro e _
    constructor
    · intro h; omega
    · intro h; omega
  rw [h, Finset.card_filter_add_card_filter_not]
  simp

/-- **Genus is preserved on every forest face.**  No vertex weight appears:
the `forest` field is exactly what makes the two `z`'s cancel. -/
@[simp] theorem genus_graph : genus d.graph = (p : ℤ) - (n : ℤ) + 1 := by
  have hE := d.card_edges
  have hV := d.card_vertices
  have hSum := d.sum_length_eq
  have hCard := d.card_pos_add_card_zero
  have hForest := d.forest
  unfold genus
  rw [hE, hV]
  have hSumZ : ((∑ e : Fin p, d.length e : ℕ) : ℤ)
      = ((∑ e : Fin p, (d.length e - 1) : ℕ) : ℤ)
        + ((Finset.univ.filter (fun e : Fin p => 0 < d.length e)).card : ℤ) := by
    exact_mod_cast hSum
  have hCardZ : ((Finset.univ.filter (fun e : Fin p => 0 < d.length e)).card : ℤ)
      + ((Finset.univ.filter (fun e : Fin p => d.length e = 0)).card : ℤ)
      = (p : ℤ) := by exact_mod_cast hCard
  have hForestZ : ((Finset.univ.image d.rep).card : ℤ)
      + ((Finset.univ.filter (fun e : Fin p => d.length e = 0)).card : ℤ)
      = (n : ℤ) := by exact_mod_cast hForest
  push_cast
  push_cast at hSumZ hCardZ hForestZ
  omega

/-! ## Multiplicities -/

theorem num_edges_eq_card_filter_steps (x y : d.Vertex) :
    num_edges d.graph x y =
      ((Finset.univ : Finset d.Step).filter fun s =>
        d.unitEdge s = (x, y) ∨ d.unitEdge s = (y, x)).card := by
  unfold num_edges
  change Multiset.card
      (((Finset.univ : Finset d.Step).val.map d.unitEdge).filter
        (fun e => e = (x, y) ∨ e = (y, x))) = _
  rw [Multiset.filter_map, Multiset.card_map]
  rfl

/-! ## Fibre regrouping

The transferable half of a symbolic certificate.  Every quantity a
`SlopeScript`-style certificate computes at a core vertex is an
endpoint-indicator sum over slots.  On the contracted core such a sum is the
sum, over the members of one collapsed class, of the *uncontracted* sums —
so a row's per-core-vertex lemmas are reusable at every face by addition
instead of being reproved per face. -/

theorem sum_tail_class (r : Fin n) (F : Fin p → ℤ) :
    ∑ e : Fin p, (if d.rep (d.core.tail e) = r then F e else 0)
      = ∑ v ∈ Finset.univ.filter (fun v : Fin n => d.rep v = r),
          ∑ e : Fin p, (if d.core.tail e = v then F e else 0) := by
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun e _ => ?_
  by_cases h : d.rep (d.core.tail e) = r
  · rw [if_pos h, Finset.sum_eq_single_of_mem (d.core.tail e)
      (Finset.mem_filter.mpr ⟨Finset.mem_univ _, h⟩)
      (fun b _ hb => if_neg (fun hEq => hb hEq.symm))]
    exact (if_pos rfl).symm
  · rw [if_neg h]
    symm
    refine Finset.sum_eq_zero fun v hv => ?_
    refine if_neg ?_
    rintro rfl
    exact h (Finset.mem_filter.mp hv).2

theorem sum_head_class (r : Fin n) (G : Fin p → ℤ) :
    ∑ e : Fin p, (if d.rep (d.core.head e) = r then G e else 0)
      = ∑ v ∈ Finset.univ.filter (fun v : Fin n => d.rep v = r),
          ∑ e : Fin p, (if d.core.head e = v then G e else 0) := by
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun e _ => ?_
  by_cases h : d.rep (d.core.head e) = r
  · rw [if_pos h, Finset.sum_eq_single_of_mem (d.core.head e)
      (Finset.mem_filter.mpr ⟨Finset.mem_univ _, h⟩)
      (fun b _ hb => if_neg (fun hEq => hb hEq.symm))]
    exact (if_pos rfl).symm
  · rw [if_neg h]
    symm
    refine Finset.sum_eq_zero fun v hv => ?_
    refine if_neg ?_
    rintro rfl
    exact h (Finset.mem_filter.mp hv).2

/-- A vanishing slot contributes nothing to a contracted endpoint sum, because
its two endpoints lie in the same class and its two endpoint contributions are
equal and opposite.  This is why a certificate's per-slot data may be summed
over *all* slots of the uncontracted core, zero ones included. -/
theorem zero_slot_cancels (r : Fin n) (F G : Fin p → ℤ) (e : Fin p)
    (hzero : d.length e = 0) (hFG : F e = G e) :
    (if d.rep (d.core.tail e) = r then F e else 0)
      + (if d.rep (d.core.head e) = r then -G e else 0) = 0 := by
  rw [d.rep_zero e hzero, hFG]
  split_ifs <;> ring

/-! ## The face-equals-contraction-target correspondence -/

/-- Matching data identifying a `DegSpec` with the strictly positive `Spec`
on its contracted core.  All four maps are pure index bookkeeping; no lengths
change.  Slot reorientation is deliberately *not* included: it is already
supplied by `SubdivisionGraph.Spec.Relabeling`, which composes with the
`LaplacianEquiv` produced here. -/
structure Contraction {n' p' : ℕ} (d : DegSpec n p)
    (target : SubdivisionGraph.Spec n' p') where
  /-- Which uncontracted core vertex represents each target vertex. -/
  vtx : Fin n' → Fin n
  vtx_rep : ∀ v' : Fin n', d.rep (vtx v') = vtx v'
  vtx_inj : Function.Injective vtx
  vtx_surj : ∀ v : Fin n, ∃ v' : Fin n', vtx v' = d.rep v
  /-- Which uncontracted slot each target slot is. -/
  slot : Fin p' → Fin p
  slot_inj : Function.Injective slot
  slot_surj : ∀ e : Fin p, 0 < d.length e → ∃ e' : Fin p', slot e' = e
  length_eq : ∀ e' : Fin p', target.length e' = d.length (slot e')
  tail_eq : ∀ e' : Fin p', vtx (target.core.tail e') = d.rep (d.core.tail (slot e'))
  head_eq : ∀ e' : Fin p', vtx (target.core.head e') = d.rep (d.core.head (slot e'))

namespace Contraction

variable {n' p' : ℕ} {d : DegSpec n p} {target : SubdivisionGraph.Spec n' p'}
  (c : Contraction d target)

theorem slot_pos (e' : Fin p') : 0 < d.length (c.slot e') := by
  rw [← c.length_eq]; exact target.length_pos e'

/-- Core-vertex half of the vertex bijection. -/
def classMap : Fin n' → d.Class := fun v' => ⟨c.vtx v', c.vtx_rep v'⟩

theorem classMap_bijective : Function.Bijective c.classMap := by
  constructor
  · intro a b h
    exact c.vtx_inj (congrArg Subtype.val h)
  · rintro ⟨v, hv⟩
    obtain ⟨v', hv'⟩ := c.vtx_surj v
    exact ⟨v', Subtype.ext (hv'.trans hv)⟩

/-- Interior half of the vertex bijection. -/
def interiorMap : (Σ e' : Fin p', Fin (target.length e' - 1)) → d.Interior :=
  fun s => ⟨c.slot s.1, ⟨s.2.val, by
    have := s.2.isLt
    have := c.length_eq s.1
    omega⟩⟩

theorem interiorMap_bijective : Function.Bijective c.interiorMap := by
  constructor
  · rintro ⟨e₁, o₁⟩ ⟨e₂, o₂⟩ h
    have he : c.slot e₁ = c.slot e₂ := congrArg Sigma.fst h
    have he' : e₁ = e₂ := c.slot_inj he
    subst he'
    have ho : (o₁ : ℕ) = (o₂ : ℕ) := congrArg (fun x : d.Interior => (x.2 : ℕ)) h
    have ho' : o₁ = o₂ := Fin.ext ho
    rw [ho']
  · rintro ⟨e, o⟩
    have hpos : 0 < d.length e := by have := o.isLt; omega
    obtain ⟨e', he'⟩ := c.slot_surj e hpos
    subst he'
    have hlen := c.length_eq e'
    refine ⟨⟨e', ⟨o.val, by have := o.isLt; omega⟩⟩, ?_⟩
    exact congrArg (Sigma.mk (c.slot e')) (Fin.ext rfl)

/-- Unit-step bijection. -/
def stepMap : target.Step → d.Step :=
  fun s => ⟨c.slot s.1, ⟨s.2.val, by
    have := s.2.isLt
    have := c.length_eq s.1
    omega⟩⟩

theorem stepMap_bijective : Function.Bijective c.stepMap := by
  constructor
  · rintro ⟨e₁, o₁⟩ ⟨e₂, o₂⟩ h
    have he : c.slot e₁ = c.slot e₂ := congrArg Sigma.fst h
    have he' : e₁ = e₂ := c.slot_inj he
    subst he'
    have ho : (o₁ : ℕ) = (o₂ : ℕ) := congrArg (fun x : d.Step => (x.2 : ℕ)) h
    have ho' : o₁ = o₂ := Fin.ext ho
    rw [ho']
  · rintro ⟨e, o⟩
    have hpos : 0 < d.length e := lt_of_le_of_lt (Nat.zero_le _) o.isLt
    obtain ⟨e', he'⟩ := c.slot_surj e hpos
    subst he'
    have hlen := c.length_eq e'
    refine ⟨⟨e', ⟨o.val, by have := o.isLt; omega⟩⟩, ?_⟩
    exact congrArg (Sigma.mk (c.slot e')) (Fin.ext rfl)

/-- Vertex bijection of the correspondence. -/
noncomputable def vertexEquiv : target.Vertex ≃ d.Vertex :=
  Equiv.sumCongr (Equiv.ofBijective _ c.classMap_bijective)
    (Equiv.ofBijective _ c.interiorMap_bijective)

noncomputable def stepEquiv : target.Step ≃ d.Step :=
  Equiv.ofBijective _ c.stepMap_bijective

@[simp] theorem vertexEquiv_coreVertex (v' : Fin n') :
    c.vertexEquiv (target.coreVertex v') = d.coreVertex (c.vtx v') := by
  show Sum.inl (c.classMap v') = d.coreVertex (c.vtx v')
  unfold coreVertex classMap
  exact congrArg Sum.inl (Subtype.ext (c.vtx_rep v').symm)

@[simp] theorem vertexEquiv_interiorVertex (e' : Fin p')
    (o : Fin (target.length e' - 1)) :
    c.vertexEquiv (target.interiorVertex e' o) =
      d.interiorVertex (c.slot e') ⟨o.val, by
        have := o.isLt; have := c.length_eq e'; omega⟩ := rfl

@[simp] theorem stepEquiv_apply (e' : Fin p') (o : Fin (target.length e')) :
    c.stepEquiv ⟨e', o⟩ = (⟨c.slot e', ⟨o.val, by
      have := o.isLt; have := c.length_eq e'; omega⟩⟩ : d.Step) := rfl

theorem unitEdge_stepEquiv (s : target.Step) :
    d.unitEdge (c.stepEquiv s)
      = (c.vertexEquiv (target.unitEdge s).1, c.vertexEquiv (target.unitEdge s).2) := by
  rcases s with ⟨e', o⟩
  have hlen := c.length_eq e'
  have hLeft : d.stepLeft (c.slot e') ⟨o.val, by omega⟩
      = c.vertexEquiv (target.stepLeft e' o) := by
    by_cases h0 : o.val = 0
    · rw [show d.stepLeft (c.slot e') ⟨o.val, by omega⟩
            = d.coreVertex (d.core.tail (c.slot e')) from dif_pos h0,
        show target.stepLeft e' o
            = target.coreVertex (target.core.tail e') from dif_pos h0,
        c.vertexEquiv_coreVertex, c.tail_eq e', d.coreVertex_eq_iff]
      exact (d.rep_idem _).symm
    · rw [show d.stepLeft (c.slot e') ⟨o.val, by omega⟩
            = d.interiorVertex (c.slot e') ⟨o.val - 1, by omega⟩ from dif_neg h0,
        show target.stepLeft e' o
            = target.interiorVertex e' ⟨o.val - 1, by omega⟩ from dif_neg h0,
        c.vertexEquiv_interiorVertex]
  have hRight : d.stepRight (c.slot e') ⟨o.val, by omega⟩
      = c.vertexEquiv (target.stepRight e' o) := by
    by_cases h1 : o.val + 1 = target.length e'
    · rw [show d.stepRight (c.slot e') ⟨o.val, by omega⟩
            = d.coreVertex (d.core.head (c.slot e')) from
            dif_pos (by change o.val + 1 = d.length (c.slot e'); omega),
        show target.stepRight e' o
            = target.coreVertex (target.core.head e') from dif_pos h1,
        c.vertexEquiv_coreVertex, c.head_eq e', d.coreVertex_eq_iff]
      exact (d.rep_idem _).symm
    · rw [show d.stepRight (c.slot e') ⟨o.val, by omega⟩
            = d.interiorVertex (c.slot e') ⟨o.val, by omega⟩ from
            dif_neg (by change ¬ (o.val + 1 = d.length (c.slot e')); omega),
        show target.stepRight e' o
            = target.interiorVertex e' ⟨o.val, by omega⟩ from dif_neg h1,
        c.vertexEquiv_interiorVertex]
  exact Prod.ext hLeft hRight

/-- **The correspondence.**  A face of the closed orthant whose zero set is a
forest carries the same Laplacian as the strictly positive subdivision of the
contracted core. -/
noncomputable def laplacianEquiv : LaplacianEquiv target.graph d.graph where
  toEquiv := c.vertexEquiv
  num_edges_eq := by
    intro x y
    rw [d.num_edges_eq_card_filter_steps,
      target.num_edges_eq_card_filter_steps]
    have hIff (s : target.Step) :
        (d.unitEdge (c.stepEquiv s) = (c.vertexEquiv x, c.vertexEquiv y) ∨
          d.unitEdge (c.stepEquiv s) = (c.vertexEquiv y, c.vertexEquiv x)) ↔
        (target.unitEdge s = (x, y) ∨ target.unitEdge s = (y, x)) := by
      rw [c.unitEdge_stepEquiv s]
      simp only [Prod.ext_iff, c.vertexEquiv.injective.eq_iff]
    have hFilter :
        (Finset.univ.filter fun s : d.Step =>
            d.unitEdge s = (c.vertexEquiv x, c.vertexEquiv y) ∨
            d.unitEdge s = (c.vertexEquiv y, c.vertexEquiv x))
          = (Finset.univ.filter fun s : target.Step =>
              target.unitEdge s = (x, y) ∨ target.unitEdge s = (y, x)).map
                c.stepEquiv.toEmbedding := by
      ext s
      simp only [Finset.mem_filter, Finset.mem_univ, true_and, Finset.mem_map,
        Equiv.coe_toEmbedding]
      constructor
      · intro h
        exact ⟨c.stepEquiv.symm s, by
          simpa using (hIff (c.stepEquiv.symm s)).1 (by simpa using h), by simp⟩
      · rintro ⟨t, ht, rfl⟩
        exact (hIff t).2 ht
    rw [hFilter, Finset.card_map]

noncomputable def graphIso : CFGraphIso target.graph d.graph where
  vertexEquiv := c.vertexEquiv
  map_num_edges := c.laplacianEquiv.num_edges_eq

end Contraction

/-! ## The translation lemma: strictly positive lengths -/

/-- At a strictly positive length vector the `forest` field forces `rep` to be
the identity: there are no zero slots, so `rep` has `n` values, hence is
surjective, hence bijective, hence — being idempotent — the identity. -/
theorem rep_eq_self_of_pos (hpos : ∀ e : Fin p, 0 < d.length e) (v : Fin n) :
    d.rep v = v := by
  have hzero : (Finset.univ.filter (fun e : Fin p => d.length e = 0)) = ∅ := by
    apply Finset.filter_false_of_mem
    intro e _
    have := hpos e
    omega
  have hcard : (Finset.univ.image d.rep).card = n := by
    have := d.forest
    rw [hzero] at this
    simpa using this
  have huniv : (Finset.univ.image d.rep) = (Finset.univ : Finset (Fin n)) :=
    Finset.eq_univ_of_card _ (by simpa using hcard)
  have hmem : v ∈ Finset.univ.image d.rep := by rw [huniv]; exact Finset.mem_univ v
  obtain ⟨u, -, hu⟩ := Finset.mem_image.mp hmem
  rw [← hu, d.rep_idem u]

/-- A degenerate spec with strictly positive lengths *is* an ordinary
subdivision spec on the same core and lengths. -/
def toSpec (hpos : ∀ e : Fin p, 0 < d.length e) : SubdivisionGraph.Spec n p where
  core := d.core
  length := d.length
  core_nonempty := d.core_nonempty
  core_loopless := by
    intro e h
    exact d.rep_loopless e (hpos e) (congrArg d.rep h)
  length_pos := hpos

/-- The identity matching, exhibiting a strictly positive `DegSpec` as its own
`Spec`. -/
def toSpecContraction (hpos : ∀ e : Fin p, 0 < d.length e) :
    Contraction d (d.toSpec hpos) where
  vtx := id
  vtx_rep := fun v => d.rep_eq_self_of_pos hpos v
  vtx_inj := fun _ _ h => h
  vtx_surj := fun v => ⟨v, (d.rep_eq_self_of_pos hpos v).symm⟩
  slot := id
  slot_inj := fun _ _ h => h
  slot_surj := fun e _ => ⟨e, rfl⟩
  length_eq := fun _ => rfl
  tail_eq := fun _e => (d.rep_eq_self_of_pos hpos _).symm
  head_eq := fun _e => (d.rep_eq_self_of_pos hpos _).symm

/-- **Translation lemma.**  Whatever a certificate proves about the degenerate
graph at a strictly positive length vector, it proves about the genuine
`SubdivisionGraph.Spec` subdivision there. -/
noncomputable def laplacianEquivToSpec (hpos : ∀ e : Fin p, 0 < d.length e) :
    LaplacianEquiv (d.toSpec hpos).graph d.graph :=
  (d.toSpecContraction hpos).laplacianEquiv

theorem bnExists_toSpec_iff (hpos : ∀ e : Fin p, 0 < d.length e) (r deg : ℤ) :
    BNExists (d.toSpec hpos).graph r deg ↔ BNExists d.graph r deg :=
  (d.laplacianEquivToSpec hpos).bnExists_iff r deg

/-! ## Core-supported divisors on a face -/

/-- Push arbitrary core weights to contracted core classes.  A class carries
the sum of its members' weights and subdivision-interior vertices carry zero. -/
def coreClassDivisor (weight : Fin n → ℤ) : CFDiv d.graph
  | Sum.inl c => ∑ v ∈ Finset.univ.filter (fun v : Fin n => d.rep v = c.val),
      weight v
  | Sum.inr _interior => 0

@[simp] theorem coreClassDivisor_coreVertex (weight : Fin n → ℤ) (r : Fin n) :
    d.coreClassDivisor weight (d.coreVertex r) =
      ∑ v ∈ Finset.univ.filter (fun v : Fin n => d.rep v = d.rep r),
        weight v := rfl

@[simp] theorem coreClassDivisor_interiorVertex (weight : Fin n → ℤ)
    (e : Fin p) (o : Fin (d.length e - 1)) :
    d.coreClassDivisor weight (d.interiorVertex e o) = 0 := rfl

/-- Nonnegative source weights remain effective after classes are merged. -/
theorem coreClassDivisor_effective (weight : Fin n → ℤ)
    (hWeight : ∀ v, 0 ≤ weight v) : effective (d.coreClassDivisor weight) := by
  intro vertex
  rcases vertex with c | interior
  · exact Finset.sum_nonneg fun v _ => hWeight v
  · rfl

/-- **A chip survives contraction.**  If the weights are nonnegative and `c`
carries one, then the sum over `c`'s contracted class is at least one: the
other members of the class can only add.

This is the one fact every guarding row needs about its own chip vertices, and
it was written out by hand — the same `Finset.single_le_sum` argument — in each
of them.  It is stated at the class sum rather than at `coreClassDivisor`
because a row whose divisor carries interior chips as well (`GenusFiveRow05`,
`GenusFiveRow08`, `GenusFiveRow10`) reduces to a class sum of a *combined*
weight, not to a bare `coreClassDivisor`. -/
theorem one_le_classSum_of_chip (weight : Fin n → ℤ)
    (hWeight : ∀ v, 0 ≤ weight v) {c : Fin n} (hChip : 1 ≤ weight c) :
    1 ≤ ∑ v ∈ Finset.univ.filter (fun v : Fin n => d.rep v = d.rep c),
      weight v := by
  classical
  refine le_trans hChip (Finset.single_le_sum (f := weight) ?_ ?_)
  · exact fun v _ => hWeight v
  · simp

/-- The `coreClassDivisor` reading of `one_le_classSum_of_chip`.  This is the
form `Guarding.GuardingSet.one_le_divisor_of_chip` is a corollary of. -/
theorem one_le_coreClassDivisor_of_chip (weight : Fin n → ℤ)
    (hWeight : ∀ v, 0 ≤ weight v) {c : Fin n} (hChip : 1 ≤ weight c) :
    1 ≤ d.coreClassDivisor weight (d.coreVertex c) := by
  rw [d.coreClassDivisor_coreVertex]
  exact d.one_le_classSum_of_chip weight hWeight hChip

/-- Contracting core classes preserves the total core weight. -/
theorem deg_coreClassDivisor (weight : Fin n → ℤ) :
    deg (d.coreClassDivisor weight) = ∑ v : Fin n, weight v := by
  classical
  have hFiber : ∀ c : d.Class,
      (Finset.univ.filter (fun v : Fin n => d.rep v = c.val)) =
        Finset.univ.filter
          (fun v : Fin n => (⟨d.rep v, d.rep_idem v⟩ : d.Class) = c) := by
    intro c
    ext v
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    exact ⟨fun h => Subtype.ext h, fun h => congrArg Subtype.val h⟩
  have hsplit : deg (d.coreClassDivisor weight) =
      ∑ c : d.Class, ∑ v ∈ Finset.univ.filter
        (fun v : Fin n => d.rep v = c.val), weight v := by
    simp [deg, coreClassDivisor, Fintype.sum_sum_type]
  rw [hsplit, Finset.sum_congr rfl (fun c _ => by rw [hFiber c])]
  exact Finset.sum_fiberwise Finset.univ
    (fun v : Fin n => (⟨d.rep v, d.rep_idem v⟩ : d.Class)) weight

end DegSpec

end Utilities.Certificate.DegenerateSpec
