import Utilities.Subdivision.DegenerateSlopeScript
import Utilities.Subdivision.ContractionForestCensusGeneral

/-!
# Ramp (cut-march) scripts on the CLOSED length orthant

This is the `DegSpec` counterpart of the `Ramp` section of
`MarkedGraphs/GenusFourCore100.lean`, which is stated over
`SubdivisionGraph.Spec` and is therefore available only on the interior of the
length orthant.  Nothing in `GenusFourCore100` is touched; these are separate
statements about `DegSpec.graph`, so the strictly positive path keeps working
verbatim.

## What a ramp is

A *ramp* moves a chip across a cut of the core.  It is the firing script whose
value at path position `k` of slot `e` is

    pot (tail e) + sgn e * min (k - lo e) t ,

i.e. the script is flat until path position `lo e`, then rises with slope
`sgn e ∈ {-1, 0, 1}` for `t` unit steps, then is flat again.  `RampData`
records the two consistency conditions: the core potential must actually
change by `sgn e * t` across each slot, and the rising window must fit inside
the slot (unless the slot is flat).

## The one new field: `repInv`

On the open orthant a ramp needs only `potential` and `window`.  On the closed
orthant the script is a function on the *contracted* graph, where a vanishing
slot has already identified its two endpoints, so the core potential must be
constant on each `rep`-class.  That is the third field `repInv`.

It is not an extra assumption in practice.  `potential` and `window` together
already force `pot (head e) = pot (tail e)` on every **vanishing** slot: a
vanishing slot has `lo e + t ≤ 0` or `sgn e = 0`, and either way `sgn e * t = 0`
(`RampData.pot_head_eq_tail_of_zero`).  So as soon as `rep` is *generated* by
the vanishing slots — which is exactly `DegenerateCoreVertexCut.DegSpec
.RepIsContraction`, and is true by construction for `RowProof.censusSpec`,
whose `rep` is a `compFold` — `repInv` follows; see `RampData.of_reachIn`.

## Why this is stated generically

Both catalog row 100 and catalog row 097 march across cuts of a six-vertex,
nine-slot core, and row 097's open proof imports row 100's solely to reuse the
open `RampData`.  Stating the closed analogue here, on an arbitrary
`DegSpec n p`, means the two closed ports share it rather than each growing a
copy.
-/

namespace Utilities.Certificate.DegenerateSpec
open Utilities.Certificate

open Utilities

open Finset ExplicitPotential

namespace DegSpec

variable {n p : ℕ}

/-! ## The data -/

/-- Path values of a ramp script: flat, then rising with slope `sgn e` across
the `t` unit steps starting at path position `lo e`, then flat again. -/
def rampValue (d : DegSpec n p) (pot : Fin n → ℤ) (sgn : Fin p → ℤ)
    (lo : Fin p → ℕ) (t : ℕ) : Fin p → ℕ → ℤ := fun e k =>
  pot (d.core.tail e) + sgn e * ((min (k - lo e) t : ℕ) : ℤ)

/-- Unit-step slopes of a ramp script. -/
def rampSlope (sgn : Fin p → ℤ) (lo : Fin p → ℕ) (t : ℕ) : Fin p → ℕ → ℤ :=
  fun e k => if lo e ≤ k ∧ k < lo e + t then sgn e else 0

/-- Consistency of the ramp data with the core potential, on the closed
orthant.  The first two fields are the open-orthant conditions verbatim; see
the module docstring for `repInv`. -/
structure RampData (d : DegSpec n p) (pot : Fin n → ℤ) (sgn : Fin p → ℤ)
    (lo : Fin p → ℕ) (t : ℕ) : Prop where
  potential : ∀ e : Fin p,
    pot (d.core.head e) = pot (d.core.tail e) + sgn e * (t : ℤ)
  window : ∀ e : Fin p, lo e + t ≤ d.length e ∨ sgn e = 0
  /-- The core potential is constant on each contracted class. -/
  repInv : ∀ v : Fin n, pot (d.rep v) = pot v

/-- The ramp firing script. -/
def rampScript (d : DegSpec n p) (pot : Fin n → ℤ) (sgn : Fin p → ℤ)
    (lo : Fin p → ℕ) (t : ℕ) : firing_script d.graph :=
  d.slotValueScript pot (d.rampValue pot sgn lo t)

variable {d : DegSpec n p} {pot : Fin n → ℤ} {sgn : Fin p → ℤ}
  {lo : Fin p → ℕ} {t : ℕ}

/-! ## `repInv` is free once `rep` is generated by the vanishing slots -/

/-- A vanishing slot carries no potential difference: its window has collapsed
(`lo + t ≤ 0`) or its slope is zero, and either way `sgn e * t = 0`. -/
theorem RampData.pot_head_eq_tail_of_zero
    (hpot : ∀ e : Fin p, pot (d.core.head e) = pot (d.core.tail e) + sgn e * (t : ℤ))
    (hwin : ∀ e : Fin p, lo e + t ≤ d.length e ∨ sgn e = 0)
    (e : Fin p) (hzero : d.length e = 0) :
    pot (d.core.head e) = pot (d.core.tail e) := by
  rw [hpot e]
  rcases hwin e with hw | hw
  · have ht : t = 0 := by omega
    rw [ht]
    simp
  · rw [hw]
    ring

/-- The potential is constant along any chain of vanishing slots. -/
theorem RampData.pot_eq_of_reachIn
    (hpot : ∀ e : Fin p, pot (d.core.head e) = pot (d.core.tail e) + sgn e * (t : ℤ))
    (hwin : ∀ e : Fin p, lo e + t ≤ d.length e ∨ sgn e = 0)
    {u v : Fin n}
    (h : Utilities.Certificate.ContractionForestCensusGeneral.ReachIn d.core
      (Finset.univ.filter fun e : Fin p => d.length e = 0) u v) :
    pot u = pot v := by
  induction h with
  | refl => rfl
  | @tail b c _ hbc ih =>
      obtain ⟨e, he, hcase⟩ := hbc
      have hzero : d.length e = 0 := by
        have := (Utilities.Certificate.ContractionForestCensusGeneral.mem_edgeList _ e).mp he
        simpa using this
      have hstep := RampData.pot_head_eq_tail_of_zero hpot hwin e hzero
      rcases hcase with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
      · exact ih.trans hstep.symm
      · exact ih.trans hstep

/-- **`repInv` for free.**  If `rep`-equality is witnessed by a chain of
vanishing slots — `DegenerateCoreVertexCut.DegSpec.RepIsContraction`, which
holds definitionally whenever `rep` is a `compFold` of the vanishing set, as
it is for `RowProof.censusSpec` — then the two open-orthant conditions already
build a closed-orthant `RampData`. -/
theorem RampData.of_reachIn
    (hpot : ∀ e : Fin p, pot (d.core.head e) = pot (d.core.tail e) + sgn e * (t : ℤ))
    (hwin : ∀ e : Fin p, lo e + t ≤ d.length e ∨ sgn e = 0)
    (hrep : ∀ u v : Fin n, d.rep u = d.rep v →
      Utilities.Certificate.ContractionForestCensusGeneral.ReachIn d.core
        (Finset.univ.filter fun e : Fin p => d.length e = 0) u v) :
    RampData d pot sgn lo t where
  potential := hpot
  window := hwin
  repInv := fun v =>
    RampData.pot_eq_of_reachIn hpot hwin (hrep (d.rep v) v (d.rep_idem v))

/-! ## Compatibility and the step slopes -/

theorem rampCompatible (h : RampData d pot sgn lo t) :
    d.SlotValueCompatible pot (d.rampValue pot sgn lo t) := by
  constructor
  · intro e
    simp only [rampValue, h.repInv]
    simp
  · intro e
    have hp := h.potential e
    rw [h.repInv]
    rcases h.window e with hw | hw
    · have hmin : min (d.length e - lo e) t = t := by omega
      simp only [rampValue, hmin, hp]
    · simp only [rampValue, hp, hw]
      ring

@[simp] theorem rampScript_coreVertex (h : RampData d pot sgn lo t) (v : Fin n) :
    d.rampScript pot sgn lo t (d.coreVertex v) = pot v := by
  rw [rampScript, d.slotValueScript_core, h.repInv]

@[simp] theorem rampScript_interiorVertex (e : Fin p)
    (o : Fin (d.length e - 1)) :
    d.rampScript pot sgn lo t (d.interiorVertex e o) =
      d.rampValue pot sgn lo t e (o.val + 1) := rfl

theorem isStepSlope_ramp (h : RampData d pot sgn lo t) :
    d.IsStepSlope (d.rampScript pot sgn lo t) (rampSlope sgn lo t) := by
  intro e o
  rw [rampScript, d.slotValueScript_stepRight (rampCompatible h),
    d.slotValueScript_stepLeft (rampCompatible h)]
  simp only [rampValue, rampSlope]
  by_cases hw : lo e ≤ o.val ∧ o.val < lo e + t
  · rw [if_pos hw]
    obtain ⟨hw1, hw2⟩ := hw
    have h1 : min (o.val + 1 - lo e) t = (o.val - lo e) + 1 := by omega
    have h2 : min (o.val - lo e) t = o.val - lo e := by omega
    rw [h1, h2]
    push_cast
    ring
  · rw [if_neg hw]
    have h1 : min (o.val + 1 - lo e) t = min (o.val - lo e) t := by
      simp only [not_and_or, not_le, not_lt] at hw
      omega
    rw [h1]
    ring

/-! ## The Laplacian of a ramp -/

/-- At a contracted core class the Laplacian of a ramp is the endpoint sum over
**all** slots of the uncontracted core, vanishing slots included; this is
`DegSpec.prin_coreVertex_eq_endpointSum` specialised to a ramp. -/
theorem prin_ramp_coreVertex (h : RampData d pot sgn lo t) (r : Fin n) :
    prin d.graph (d.rampScript pot sgn lo t) (d.coreVertex r) =
      ∑ e : Fin p,
        ((if d.rep (d.core.tail e) = d.rep r then rampSlope sgn lo t e 0 else 0) +
          (if d.rep (d.core.head e) = d.rep r then
            -rampSlope sgn lo t e (d.length e - 1) else 0)) :=
  d.prin_coreVertex_eq_endpointSum (isStepSlope_ramp h) r

/-- **The form a row proof reads.**  The Laplacian of a ramp at a contracted
class is the sum, over the members of the class, of the *uncontracted*
per-core-vertex endpoint formula — the same expression the open-orthant
`prin_ramp_coreVertex` produces on a `SubdivisionGraph.Spec`.  A row therefore
proves its per-core-vertex value lemmas once and reads every face off by
summing. -/
theorem prin_ramp_coreVertex_classSum (h : RampData d pot sgn lo t) (r : Fin n) :
    prin d.graph (d.rampScript pot sgn lo t) (d.coreVertex r) =
      ∑ v ∈ Finset.univ.filter (fun v : Fin n => d.rep v = d.rep r),
        ∑ e : Fin p,
          ((if d.core.tail e = v then rampSlope sgn lo t e 0 else 0) +
            (if d.core.head e = v then
              -rampSlope sgn lo t e (d.length e - 1) else 0)) :=
  d.prin_coreVertex_eq_classSum (isStepSlope_ramp h) r

theorem prin_ramp_interiorVertex (h : RampData d pot sgn lo t) (e : Fin p)
    (o : Fin (d.length e - 1)) :
    prin d.graph (d.rampScript pot sgn lo t) (d.interiorVertex e o) =
      rampSlope sgn lo t e (o.val + 1) - rampSlope sgn lo t e o.val :=
  d.prin_interiorVertex_eq_slopeDifference (isStepSlope_ramp h) e o

/-! ## Endpoint slopes

The two lemmas that read the slope at the two ends of a slot.  Unlike the open
orthant these must survive `length e = 0`, where `length e - 1` is `0` rather
than the last step; both statements are still true there, and the proofs no
longer need `length_pos`. -/

theorem rampSlope_zero (sgn : Fin p → ℤ) (lo : Fin p → ℕ) (t : ℕ) (e : Fin p) :
    rampSlope sgn lo t e 0 = if lo e = 0 ∧ 0 < t then sgn e else 0 := by
  simp only [rampSlope]
  split_ifs <;> first | rfl | (exfalso; omega)

theorem rampSlope_last (h : RampData d pot sgn lo t) (e : Fin p) :
    rampSlope sgn lo t e (d.length e - 1) =
      if lo e + t = d.length e ∧ 0 < t then sgn e else 0 := by
  rcases h.window e with hw | hw
  · simp only [rampSlope]
    split_ifs <;> first | rfl | (exfalso; omega)
  · simp only [rampSlope, hw]
    split_ifs <;> rfl

theorem rampSlope_zero_t (sgn : Fin p → ℤ) (lo : Fin p → ℕ) (e : Fin p)
    (k : ℕ) : rampSlope sgn lo 0 e k = 0 := by
  simp only [rampSlope]
  rw [if_neg (show ¬ (lo e ≤ k ∧ k < lo e + 0) by omega)]

/-- Divergence of a ramp along one slot: a chip is created at path position
`lo` and destroyed at `lo + t`, up to the sign. -/
theorem rampSlope_diff (sgn : Fin p → ℤ) (lo : Fin p → ℕ) (t : ℕ)
    (e : Fin p) (k : ℕ) (hk : 0 < k) :
    rampSlope sgn lo t e k - rampSlope sgn lo t e (k - 1) =
      (if k = lo e ∧ 0 < t then sgn e else 0) -
        (if k = lo e + t ∧ 0 < t then sgn e else 0) := by
  rcases Nat.eq_zero_or_pos t with ht | ht
  · subst ht
    rw [rampSlope_zero_t, rampSlope_zero_t,
      if_neg (show ¬ (k = lo e ∧ 0 < 0) by omega),
      if_neg (show ¬ (k = lo e + 0 ∧ 0 < 0) by omega)]
    try ring
  · simp only [rampSlope]
    by_cases h1 : lo e ≤ k ∧ k < lo e + t
    · rw [if_pos h1]
      by_cases h2 : lo e ≤ k - 1 ∧ k - 1 < lo e + t
      · rw [if_pos h2, if_neg (show ¬ (k = lo e ∧ 0 < t) by omega),
          if_neg (show ¬ (k = lo e + t ∧ 0 < t) by omega)]
        try ring
      · rw [if_neg h2, if_pos (show k = lo e ∧ 0 < t by omega),
          if_neg (show ¬ (k = lo e + t ∧ 0 < t) by omega)]
        try ring
    · rw [if_neg h1]
      by_cases h2 : lo e ≤ k - 1 ∧ k - 1 < lo e + t
      · rw [if_pos h2, if_neg (show ¬ (k = lo e ∧ 0 < t) by omega),
          if_pos (show k = lo e + t ∧ 0 < t by omega)]
        try ring
      · rw [if_neg h2, if_neg (show ¬ (k = lo e ∧ 0 < t) by omega),
          if_neg (show ¬ (k = lo e + t ∧ 0 < t) by omega)]
        try ring

/-! ## Agreement with the open orthant

At a strictly positive length vector `rep` is the identity, so `repInv` is
vacuous and `RampData` is exactly the open-orthant structure of
`GenusFourCore100.RampData` read on `DegSpec.toSpec`. -/

theorem RampData.of_pos (hpos : ∀ e : Fin p, 0 < d.length e)
    (hpot : ∀ e : Fin p, pot (d.core.head e) = pot (d.core.tail e) + sgn e * (t : ℤ))
    (hwin : ∀ e : Fin p, lo e + t ≤ d.length e ∨ sgn e = 0) :
    RampData d pot sgn lo t where
  potential := hpot
  window := hwin
  repInv := fun v => by rw [d.rep_eq_self_of_pos hpos v]

/-- On the interior the class sum of `prin_ramp_coreVertex_classSum` collapses
to a single term, giving literally the open-orthant formula. -/
theorem prin_ramp_coreVertex_of_pos (h : RampData d pot sgn lo t)
    (hpos : ∀ e : Fin p, 0 < d.length e) (r : Fin n) :
    prin d.graph (d.rampScript pot sgn lo t) (d.coreVertex r) =
      ∑ e : Fin p,
        ((if d.core.tail e = r then rampSlope sgn lo t e 0 else 0) +
          (if d.core.head e = r then
            -rampSlope sgn lo t e (d.length e - 1) else 0)) :=
  d.prin_coreVertex_eq_endpointSum_of_pos (isStepSlope_ramp h) hpos r

/-! ## Pointwise bookkeeping on the degenerate subdivision

Everything below is the closed-orthant replacement for the "`divisor_ext` plus
`one_chip` at a path position" bookkeeping of `GenusFourCore100.lean`.  The one
structural change is that a value at a **core class** is the class sum of the
uncontracted per-core-vertex value; that is stated once here, and a row then
never has to mention classes again. -/

theorem divisor_ext {D E : CFDiv d.graph}
    (hcore : ∀ v : Fin n, D (d.coreVertex v) = E (d.coreVertex v))
    (hint : ∀ (e : Fin p) (o : Fin (d.length e - 1)),
      D (d.interiorVertex e o) = E (d.interiorVertex e o)) :
    D = E := by
  funext x
  rcases x with c | ⟨e, o⟩
  · have hc : d.coreVertex c.val = Sum.inl c :=
      congrArg Sum.inl (Subtype.ext c.2)
    rw [← hc]
    exact hcore c.val
  · exact hint e o

theorem coreVertex_ne_interiorVertex (v : Fin n) (e : Fin p)
    (o : Fin (d.length e - 1)) :
    d.coreVertex v ≠ d.interiorVertex e o := by
  simp [coreVertex, interiorVertex]

/-! ### One chip, read at a class and at an interior vertex -/

/-- The per-core-vertex indicator of a chip at path position `k` of slot `e`.
The **uncontracted** formula: the value at a contracted class is its class sum,
by `one_chip_pathVertex_coreVertex`.  Written as a nested `if` rather than a
sum of two indicators because on the closed orthant `k = 0` and
`k = length e` can coincide. -/
def chipCore (d : DegSpec n p) (e : Fin p) (k : ℕ) (v : Fin n) : ℤ :=
  if k = 0 then (if d.core.tail e = v then 1 else 0)
  else if k = d.length e then (if d.core.head e = v then 1 else 0)
  else 0

/-- The value of a chip at path position `k` of slot `e` at the interior vertex
`(e', o)`. -/
def chipInt (_d : DegSpec n p) (e : Fin p) (k : ℕ) (e' : Fin p) (o : ℕ) : ℤ :=
  if e = e' then (if k = o + 1 then 1 else 0) else 0

/-- Distinct interior vertices are distinguished by their slot and offset. -/
theorem interiorVertex_eq_iff (e e' : Fin p) (o : Fin (d.length e - 1))
    (o' : Fin (d.length e' - 1)) :
    d.interiorVertex e o = d.interiorVertex e' o' ↔ e = e' ∧ o.val = o'.val := by
  constructor
  · intro h
    have hs : (⟨e, o⟩ : d.Interior) = ⟨e', o'⟩ := Sum.inr.inj h
    exact ⟨congrArg Sigma.fst hs,
      congrArg (fun s : d.Interior => (s.2 : ℕ)) hs⟩
  · rintro ⟨rfl, hv⟩
    exact congrArg (d.interiorVertex e) (Fin.ext hv)

/-- Summing a single-vertex indicator over a contracted class. -/
theorem sum_class_indicator (r u : Fin n) (c : ℤ) :
    (∑ v ∈ Finset.univ.filter (fun v : Fin n => d.rep v = d.rep r),
      if u = v then c else 0) = if d.rep u = d.rep r then c else 0 := by
  classical
  by_cases hu : d.rep u = d.rep r
  · rw [if_pos hu, Finset.sum_eq_single_of_mem u
      (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hu⟩)
      (fun b _ hb => if_neg fun hEq => hb hEq.symm)]
    exact if_pos rfl
  · rw [if_neg hu]
    refine Finset.sum_eq_zero fun v hv => if_neg ?_
    rintro rfl
    exact hu (Finset.mem_filter.mp hv).2

theorem one_chip_pathVertex_coreVertex (e : Fin p) (k : d.PathPosition e)
    (r : Fin n) :
    one_chip (G := d.graph) (d.pathVertex e k) (d.coreVertex r) =
      ∑ v ∈ Finset.univ.filter (fun v : Fin n => d.rep v = d.rep r),
        d.chipCore e k.val v := by
  classical
  by_cases hz : k.val = 0
  · have hk : d.pathVertex e k = d.coreVertex (d.core.tail e) := by
      rw [d.pathVertex_eq_of_val_eq e (j := k) (k := ⟨0, by omega⟩) hz,
        d.pathVertex_zero]
    have hchip : ∀ v : Fin n,
        d.chipCore e k.val v = if d.core.tail e = v then 1 else 0 := fun v => by
      simp only [chipCore]; rw [if_pos hz]
    rw [hk]
    simp only [hchip]
    rw [d.sum_class_indicator r (d.core.tail e) 1]
    simp only [one_chip, d.coreVertex_eq_iff]
    by_cases h : d.rep (d.core.tail e) = d.rep r
    · rw [if_pos h.symm, if_pos h]
    · rw [if_neg fun hh => h hh.symm, if_neg h]
  · by_cases hl : k.val = d.length e
    · have hk : d.pathVertex e k = d.coreVertex (d.core.head e) := by
        rw [d.pathVertex_eq_of_val_eq e (j := k) (k := ⟨d.length e, by omega⟩) hl,
          d.pathVertex_length]
      have hchip : ∀ v : Fin n,
          d.chipCore e k.val v = if d.core.head e = v then 1 else 0 := fun v => by
        simp only [chipCore]; rw [if_neg hz, if_pos hl]
      rw [hk]
      simp only [hchip]
      rw [d.sum_class_indicator r (d.core.head e) 1]
      simp only [one_chip, d.coreVertex_eq_iff]
      by_cases h : d.rep (d.core.head e) = d.rep r
      · rw [if_pos h.symm, if_pos h]
      · rw [if_neg fun hh => h hh.symm, if_neg h]
    · have hchip : ∀ v : Fin n, d.chipCore e k.val v = 0 := fun v => by
        simp only [chipCore]; rw [if_neg hz, if_neg hl]
      rw [d.pathVertex_interior e k hz hl]
      simp only [hchip, Finset.sum_const_zero]
      simp only [one_chip]
      exact if_neg (d.coreVertex_ne_interiorVertex r e _)

theorem one_chip_pathVertex_interiorVertex (e : Fin p) (k : d.PathPosition e)
    (e' : Fin p) (o : Fin (d.length e' - 1)) :
    one_chip (G := d.graph) (d.pathVertex e k) (d.interiorVertex e' o) =
      d.chipInt e k.val e' o.val := by
  classical
  have ho := o.isLt
  have hk1 := k.isLt
  simp only [one_chip, chipInt]
  by_cases hz : k.val = 0
  · have hk : d.pathVertex e k = d.coreVertex (d.core.tail e) := by
      rw [d.pathVertex_eq_of_val_eq e (j := k) (k := ⟨0, by omega⟩) hz,
        d.pathVertex_zero]
    rw [hk, if_neg fun hh =>
      (d.coreVertex_ne_interiorVertex (d.core.tail e) e' o) hh.symm,
      if_neg (show ¬ (k.val = o.val + 1) by omega)]
    exact (ite_self _).symm
  · by_cases hl : k.val = d.length e
    · have hk : d.pathVertex e k = d.coreVertex (d.core.head e) := by
        rw [d.pathVertex_eq_of_val_eq e (j := k) (k := ⟨d.length e, by omega⟩) hl,
          d.pathVertex_length]
      rw [hk, if_neg fun hh =>
        (d.coreVertex_ne_interiorVertex (d.core.head e) e' o) hh.symm]
      symm
      by_cases he : e = e'
      · subst he
        rw [if_pos rfl, if_neg (show ¬ (k.val = o.val + 1) by omega)]
      · rw [if_neg he]
    · rw [d.pathVertex_interior e k hz hl]
      by_cases he : e = e'
      · subst he
        rw [if_pos rfl]
        by_cases hoff : k.val = o.val + 1
        · rw [if_pos hoff, if_pos]
          exact congrArg (d.interiorVertex e)
            (Fin.ext (by show (o : ℕ) = k.val - 1; omega))
        · rw [if_neg hoff, if_neg]
          intro hEq
          have hs : (⟨e, o⟩ : d.Interior)
              = ⟨e, ⟨k.val - 1, by omega⟩⟩ := Sum.inr.inj hEq
          have hv : (o : ℕ) = k.val - 1 :=
            congrArg (fun x : d.Interior => (x.2 : ℕ)) hs
          omega
      · rw [if_neg he, if_neg]
        intro hEq
        have hs : (⟨e', o⟩ : d.Interior)
            = ⟨e, ⟨k.val - 1, by omega⟩⟩ := Sum.inr.inj hEq
        exact he (congrArg Sigma.fst hs).symm

/-! ### The divisor of a ramp

`prin_ramp_eq` is the closed-orthant replacement for the per-march
`prin_*_eq` divisor identities a row proves on the open orthant.  It is stated
once, generically, and in the *slot-indexed* form: a ramp lifts one chip from
path position `lo e + t` back to `lo e` on every slot, weighted by `sgn e`.  A
row instantiates it and expands the nine-term sum, rather than reproving the
identity per march. -/

/-- The per-slot core identity behind `prin_ramp_eq`. -/
theorem ramp_slot_core (h : RampData d pot sgn lo t) (e : Fin p) (v : Fin n) :
    ((if d.core.tail e = v then rampSlope sgn lo t e 0 else 0) +
      (if d.core.head e = v then
        -rampSlope sgn lo t e (d.length e - 1) else 0)) =
      sgn e * (d.chipCore e (min (lo e) (d.length e)) v -
        d.chipCore e (min (lo e + t) (d.length e)) v) := by
  rcases h.window e with hw | hw
  · rw [rampSlope_zero, rampSlope_last h]
    have h1 : min (lo e) (d.length e) = lo e := by omega
    have h2 : min (lo e + t) (d.length e) = lo e + t := by omega
    simp only [chipCore, h1, h2]
    split_ifs <;> first | ring1 | (exfalso; omega)
  · simp only [rampSlope, hw, ite_self]
    simp

/-- The per-slot interior identity behind `prin_ramp_eq`. -/
theorem ramp_slot_interior (h : RampData d pot sgn lo t) (e' : Fin p)
    (o : Fin (d.length e' - 1)) :
    rampSlope sgn lo t e' (o.val + 1) - rampSlope sgn lo t e' o.val =
      ∑ e : Fin p, sgn e *
        (d.chipInt e (min (lo e) (d.length e)) e' o.val -
          d.chipInt e (min (lo e + t) (d.length e)) e' o.val) := by
  classical
  have ho := o.isLt
  have hcollapse :
      (∑ e : Fin p, sgn e *
        (d.chipInt e (min (lo e) (d.length e)) e' o.val -
          d.chipInt e (min (lo e + t) (d.length e)) e' o.val)) =
      sgn e' * (d.chipInt e' (min (lo e') (d.length e')) e' o.val -
        d.chipInt e' (min (lo e' + t) (d.length e')) e' o.val) := by
    refine Fintype.sum_eq_single e' fun e hne => ?_
    simp only [chipInt, if_neg hne, sub_zero, mul_zero]
  rw [hcollapse]
  have hdiff := rampSlope_diff sgn lo t e' (o.val + 1) (by omega)
  simp only [Nat.add_sub_cancel] at hdiff
  rw [hdiff]
  rcases h.window e' with hw | hw
  · have h1 : min (lo e') (d.length e') = lo e' := by omega
    have h2 : min (lo e' + t) (d.length e') = lo e' + t := by omega
    simp only [chipInt, h1, h2]
    split_ifs <;> first | ring1 | (exfalso; omega)
  · rw [hw]
    simp

/-- **The divisor of a ramp, on the closed orthant.**  Every slot contributes
`sgn e` chips moved from path position `lo e + t` back to `lo e`; slots with
`sgn e = 0` contribute nothing, which is why the clamped positions are
harmless. -/
theorem prin_ramp_eq (h : RampData d pot sgn lo t) :
    prin d.graph (d.rampScript pot sgn lo t) =
      ∑ e : Fin p, sgn e •
        (one_chip (G := d.graph) (d.pathAt e (lo e)) -
          one_chip (G := d.graph) (d.pathAt e (lo e + t))) := by
  classical
  refine d.divisor_ext ?_ ?_
  · intro r
    rw [d.prin_ramp_coreVertex_classSum h r, Finset.sum_apply]
    simp only [Pi.smul_apply, Pi.sub_apply, smul_eq_mul, pathAt,
      one_chip_pathVertex_coreVertex, clampPos]
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl fun e _ => ?_
    rw [← Finset.sum_sub_distrib, Finset.mul_sum]
    exact Finset.sum_congr rfl fun v _ => d.ramp_slot_core h e v
  · intro e' o
    rw [d.prin_ramp_interiorVertex h e' o, Finset.sum_apply]
    simp only [Pi.smul_apply, Pi.sub_apply, smul_eq_mul, pathAt,
      one_chip_pathVertex_interiorVertex, clampPos]
    exact d.ramp_slot_interior h e' o

/-! ### Chips at a clamped position, read at the two kinds of vertex -/

theorem one_chip_pathAt_coreVertex (e : Fin p) (k : ℕ) (r : Fin n) :
    one_chip (G := d.graph) (d.pathAt e k) (d.coreVertex r) =
      ∑ v ∈ Finset.univ.filter (fun v : Fin n => d.rep v = d.rep r),
        d.chipCore e (min k (d.length e)) v :=
  d.one_chip_pathVertex_coreVertex e (d.clampPos e k) r

theorem one_chip_pathAt_interiorVertex (e : Fin p) (k : ℕ) (e' : Fin p)
    (o : Fin (d.length e' - 1)) :
    one_chip (G := d.graph) (d.pathAt e k) (d.interiorVertex e' o) =
      d.chipInt e (min k (d.length e)) e' o.val :=
  d.one_chip_pathVertex_interiorVertex e (d.clampPos e k) e' o

end DegSpec

end Utilities.Certificate.DegenerateSpec
