import Mathlib

/-!
# A rank-one divisor of degree `⌈g/2⌉ + 1` on a subdivision (Draisma--Vargas)

This is the Mathlib-only Challenge surface for the discrete form of the
Draisma--Vargas bound on the gonality of metric graphs (J. Draisma and
A. Vargas, *Catalan-many tropical morphisms to trees; Part I: Constructions*,
arXiv:1909.12924, Theorem 1; A. Vargas, *Part II: A space and a count*,
arXiv:2609.09109).  It contains the advertised theorem statements and the
complete local vocabulary needed to read them.  The advertised declarations
deliberately end in `sorry`.

Both theorems are stated in witness form: they assert that some subdivision
carries a divisor of degree exactly `⌈g/2⌉ + 1` and rank at least one, rather
than bounding an infimum.  Metric graphs are not formalized.  A metric graph
with positive integer edge lengths is presented by a finite graph together
with the lengths, and the conclusion is read on the finite graph obtained by
cutting each edge into unit pieces.
-/

namespace DraismaVargasChallenge

universe u

open Multiset Finset

/-! ## Self-contained statement vocabulary -/

/-- A finite, nonempty, loopless undirected multigraph.  An undirected edge is
stored by either ordering of its endpoints; `num_edges` below forgets that
ordering. -/
structure CFGraph where
  /-- The finite, nonempty type of vertices. -/
  V : Type u
  [instDecidableEq : DecidableEq V]
  [instFintype : Fintype V]
  [instNonempty : Nonempty V]
  /-- Edge occurrences, each stored once using either endpoint ordering. -/
  edges : Multiset (V × V)
  /-- No edge occurrence has equal endpoints. -/
  loopless : ∀ v, (v, v) ∉ edges

attribute [instance] CFGraph.instDecidableEq CFGraph.instFintype CFGraph.instNonempty

/-- The number of edges between two vertices, counted with multiplicity. -/
def num_edges (G : CFGraph) (v w : G.V) : ℕ :=
  Multiset.card (G.edges.filter (fun e => e = (v, w) ∨ e = (w, v)))

/-- A graph is connected when every nontrivial vertex cut has a crossing
edge. -/
def graph_connected (G : CFGraph) : Prop :=
  ∀ S : Finset G.V, (∃ v w : G.V, v ∈ S ∧ w ∉ S) →
    ∃ v ∈ S, ∃ w ∉ S, num_edges G v w > 0

/-- The genus (cyclomatic number) `|E| - |V| + 1`. -/
def genus (G : CFGraph) : ℤ :=
  Multiset.card G.edges - Fintype.card G.V + 1

/-- The degree (valence) of a vertex. -/
def vertex_degree (G : CFGraph) (v : G.V) : ℤ :=
  ∑ u : G.V, (num_edges G v u : ℤ)

/-- A divisor is an integer-valued function on the vertices. -/
abbrev CFDiv (G : CFGraph) := G.V → ℤ

/-- The principal divisor obtained by firing one vertex once. -/
def firing_vector (G : CFGraph) (v : G.V) : CFDiv G :=
  fun w => if w = v then -vertex_degree G v else num_edges G v w

/-- The subgroup generated by all vertex firings. -/
def principal_divisors (G : CFGraph) : AddSubgroup (CFDiv G) :=
  AddSubgroup.closure (Set.range (firing_vector G))

/-- Two divisors are linearly equivalent when their difference is principal. -/
def linear_equiv (G : CFGraph) (D D' : CFDiv G) : Prop :=
  D' - D ∈ principal_divisors G

/-- A divisor is effective when it has no negative coefficient. -/
def effective {G : CFGraph} (D : CFDiv G) : Prop :=
  ∀ v : G.V, D v ≥ 0

/-- The additive monoid of effective divisors. -/
def Eff (G : CFGraph) : AddSubmonoid (CFDiv G) :=
  { carrier := {D : CFDiv G | effective D}
    zero_mem' := by
      simp only [effective, ge_iff_le, Set.mem_ofPred_eq, Pi.zero_apply,
        Std.le_refl, implies_true]
    add_mem' := by
      intro D₁ D₂ h₁ h₂ v
      exact add_nonneg (h₁ v) (h₂ v) }

/-- A divisor is winnable when it is linearly equivalent to an effective
divisor. -/
def winnable (G : CFGraph) (D : CFDiv G) : Prop :=
  ∃ D' ∈ Eff G, linear_equiv G D D'

/-- The degree of a divisor, i.e. its total number of chips. -/
def deg {G : CFGraph} : CFDiv G →+ ℤ :=
  { toFun := fun D => ∑ v, D v
    map_zero' := by simp only [Pi.zero_apply, sum_const_zero]
    map_add' := by
      intro D₁ D₂
      simp only [Pi.add_apply, sum_add_distrib] }

/-- The effective divisors of a prescribed degree. -/
def eff_of_degree (G : CFGraph) (k : ℤ) : Set (CFDiv G) :=
  {E | effective E ∧ deg E = k}

/-- `rank_geq G D k` means that removing any effective divisor of degree `k`
from `D` leaves a winnable divisor. -/
def rank_geq (G : CFGraph) (D : CFDiv G) (k : ℤ) : Prop :=
  ∀ E ∈ eff_of_degree G k, winnable G (D - E)

/-- `gonality_leq G k` means that `G` has a degree-`k` divisor of rank at
least one.  This deliberately states the witness property directly, without
introducing a minimum or an infimum. -/
def gonality_leq (G : CFGraph) (k : ℤ) : Prop :=
  ∃ D : CFDiv G, deg D = k ∧ rank_geq G D 1

/-! ### Subdivisions with prescribed edge lengths

Every occurrence of an edge gets its own slot, so parallel edges remain
distinct and may receive different lengths.  An edge occurrence of length `L`
is replaced by a path of `L` unit edges.  The `L - 1` new vertices of that
path remember the edge occurrence and their position along it.  The regular
subdivisions are the constant-length case.  The statements below use only
positive lengths.  A zero length is a junk value: that edge occurrence is
simply deleted.
-/

/-- A canonical enumeration of the occurrences in the edge multiset.  The
subtype `G.edges` distinguishes repeated copies of the same endpoint pair. -/
noncomputable def subdivisionEdgeEquiv (G : CFGraph) :
    G.edges ≃ Fin G.edges.card := by
  simpa using Fintype.equivFin G.edges

/-- The endpoint pair occupying a canonical edge-occurrence slot. -/
noncomputable def subdivisionEdgeAt (G : CFGraph)
    (edge : Fin G.edges.card) : G.V × G.V :=
  (((subdivisionEdgeEquiv G).symm edge : G.edges) : G.V × G.V)

/-- The length of the edge occurrence in a canonical slot. -/
noncomputable abbrev subdivisionSlotLength (G : CFGraph)
    (length : G.edges → ℕ) (edge : Fin G.edges.card) : ℕ :=
  length ((subdivisionEdgeEquiv G).symm edge)

/-- Vertices of the subdivision with edge lengths `length`: relabelled
original vertices, together with an edge slot and an interior position
`0, ..., L - 2` along it, where `L` is the length of that slot. -/
abbrev SubdivisionVertex (G : CFGraph) (length : G.edges → ℕ) :=
  Fin (Fintype.card G.V) ⊕
    (Σ edge : Fin G.edges.card, Fin (subdivisionSlotLength G length edge - 1))

/-- Unit steps in the subdivided paths. -/
abbrev SubdivisionStep (G : CFGraph) (length : G.edges → ℕ) :=
  Σ edge : Fin G.edges.card, Fin (subdivisionSlotLength G length edge)

/-- The left endpoint of one unit step in a subdivided edge. -/
noncomputable def subdivisionStepLeft (G : CFGraph) (length : G.edges → ℕ)
    (edge : Fin G.edges.card) (offset : Fin (subdivisionSlotLength G length edge)) :
    SubdivisionVertex G length :=
  if hzero : offset.val = 0 then
    Sum.inl (Fintype.equivFin G.V (subdivisionEdgeAt G edge).1)
  else
    Sum.inr ⟨edge, ⟨offset.val - 1, by
      have hoffset := offset.isLt
      omega⟩⟩

/-- The right endpoint of one unit step in a subdivided edge. -/
noncomputable def subdivisionStepRight (G : CFGraph) (length : G.edges → ℕ)
    (edge : Fin G.edges.card) (offset : Fin (subdivisionSlotLength G length edge)) :
    SubdivisionVertex G length :=
  if hlast : offset.val + 1 = subdivisionSlotLength G length edge then
    Sum.inl (Fintype.equivFin G.V (subdivisionEdgeAt G edge).2)
  else
    Sum.inr ⟨edge, ⟨offset.val, by
      have hoffset := offset.isLt
      omega⟩⟩

/-- The subdivision of `G` in which every edge occurrence `e` is replaced by a
path of exactly `length e` edges. -/
noncomputable def subdivision (G : CFGraph) (length : G.edges → ℕ) :
    CFGraph where
  V := SubdivisionVertex G length
  instNonempty := ⟨Sum.inl ⟨0, Fintype.card_pos⟩⟩
  edges := (Finset.univ : Finset (SubdivisionStep G length)).val.map fun step =>
    (subdivisionStepLeft G length step.1 step.2,
      subdivisionStepRight G length step.1 step.2)
  loopless := by
    intro vertex hmem
    simp only [Multiset.mem_map, Finset.mem_val, Finset.mem_univ, true_and]
      at hmem
    obtain ⟨⟨edge, offset⟩, hstep⟩ := hmem
    simp only [Prod.mk.injEq] at hstep
    have hne : subdivisionStepLeft G length edge offset ≠
        subdivisionStepRight G length edge offset := by
      unfold subdivisionStepLeft subdivisionStepRight
      split_ifs with hzero hlast
      · intro heq
        have hEnds : (subdivisionEdgeAt G edge).1 =
            (subdivisionEdgeAt G edge).2 :=
          (Fintype.equivFin G.V).injective (Sum.inl.inj heq)
        have hMember : subdivisionEdgeAt G edge ∈ G.edges := Multiset.coe_mem
        rcases hEdge : subdivisionEdgeAt G edge with ⟨tail, head⟩
        simp only [hEdge] at hEnds hMember
        subst head
        exact G.loopless tail hMember
      · simp
      · simp
      · intro heq
        have hSigma := Sum.inr.inj heq
        have hOffsets : offset.val - 1 = offset.val := by
          exact congrArg (fun x => x.2.val) hSigma
        omega
    exact hne (hstep.1.trans hstep.2.symm)

/-- The `n`th regular subdivision of `G`: every edge occurrence is replaced by
a path of exactly `n` edges.  The length is written `n * 1` (propositionally,
not definitionally, equal to `n`): it is `n` times the unit length, which
makes the construction agree definitionally with the implementation library,
where regular subdivision scales unit edge lengths by `n`. -/
noncomputable def regularSubdivision (G : CFGraph) (n : ℕ) (_hn : 0 < n) :
    CFGraph :=
  subdivision G fun _ => n * 1

/-! ## The Draisma--Vargas bound -/

/-- **Draisma--Vargas, discrete form.**  Every connected finite loopless
multigraph of genus `g` has a regular subdivision carrying a divisor of degree
`⌈g/2⌉ + 1` and rank at least one.

Adding chips cannot lower the rank, so this is equivalent to the bound
`min_{n ≥ 1} gon(σ_n G) ≤ ⌈g/2⌉ + 1` on the divisorial gonalities of the
regular subdivisions `σ_n G`. -/
theorem regular_subdivision_gonality_le_ceil_half_genus_add_one
    (G : CFGraph.{u}) (h_connected : graph_connected G) :
    ∃ (n : ℕ) (hn : 0 < n),
      gonality_leq (regularSubdivision G n hn) (⌈(genus G : ℚ) / 2⌉ + 1) := by
  sorry

/-- **Draisma--Vargas, for positive integer edge lengths.**  Give every edge
occurrence of a connected finite loopless multigraph `G` of genus `g` a
positive integer length (a metric graph with rational edge lengths, up to
scale).  Then for some `n ≥ 1`, cutting every edge `e` into `n * length e`
unit edges produces a graph carrying a divisor of degree `⌈g/2⌉ + 1` and rank
at least one.

The constant length `1` recovers
`regular_subdivision_gonality_le_ceil_half_genus_add_one`.  A metric graph
with a loop is covered after placing a vertex in the interior of the loop. -/
theorem common_refinement_gonality_le_ceil_half_genus_add_one
    (G : CFGraph.{u}) (h_connected : graph_connected G)
    (length : G.edges → ℕ) (h_length : ∀ e, 0 < length e) :
    ∃ n : ℕ, 0 < n ∧
      gonality_leq (subdivision G fun e => n * length e)
        (⌈(genus G : ℚ) / 2⌉ + 1) := by
  sorry

end DraismaVargasChallenge
